---
permalink: sm-storage/actions-you-can-perform-on-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes 
summary: 您可以在磁碟區上執行許多不同的動作：增加容量、刪除、複製、初始化、重新分配、 變更擁有權、變更快取設定、以及變更媒體掃描設定。 
---
= 您可以在磁碟區上執行的動作
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在磁碟區上執行許多不同的動作：增加容量、刪除、複製、初始化、重新分配、 變更擁有權、變更快取設定、以及變更媒體掃描設定。



== 增加容量

您可以透過兩種方式擴充磁碟區的容量：

* 使用資源池或Volume群組中可用的可用容量。
+
您可以選取功能表：「Storage[資源池和Volume Groups（資源池和Volume群組）」>「Add Capacity（新增容量）」、將容量新增至磁碟區。

* 將未指派的容量（以未使用磁碟機的形式）新增至磁碟區的集區或磁碟區群組。當資源池或磁碟區群組中不存在可用容量時、請使用此選項。
+
您可以選取功能表：「Storage[資源池和Volume群組>新增容量]、將未指派的容量新增至資源池或Volume群組。

+
如果資源池或磁碟區群組中沒有可用的可用容量、您就無法增加磁碟區的容量。您必須先增加資源池或磁碟區群組的大小、或刪除未使用的磁碟區。



擴充磁碟區容量之後、您必須手動增加檔案系統大小以符合需求。您的做法取決於所使用的檔案系統。如需詳細資料、請參閱主機作業系統文件。



== 刪除

一般而言、如果磁碟區是以錯誤的參數或容量建立、不再符合儲存組態需求、或是不再需要用於備份或應用程式測試的快照映像、就會刪除磁碟區。刪除磁碟區會增加資源池或磁碟區群組中的可用容量。

刪除磁碟區會導致這些磁碟區上的所有資料遺失。刪除磁碟區也會刪除任何相關的快照映像、排程和快照磁碟區、並移除任何鏡射關係。



== 複本

複製磁碟區時、您會在同一個儲存陣列上建立兩個獨立磁碟區（來源磁碟區和目標磁碟區）的時間點複本。您可以選取功能表：「Storage[磁碟區>複製服務>複製磁碟區]來複製磁碟區。



== 初始化

初始化磁碟區會清除磁碟區中的所有資料。第一次建立磁碟區時、就會自動初始化該磁碟區。不過、Recovery Guru可能會建議您手動初始化磁碟區、以便從某些故障情況中恢復。初始化磁碟區時、磁碟區會保留其WWN、主機指派、已分配容量及保留容量設定。它也會保留相同的資料保證（DA）設定和安全性設定。

您可以選取功能表：Storage[ Volume > More > Initialize Volumes（儲存設備[磁碟區>更多>初始化磁碟區）]來初始化



== 重新分配

您可以重新分配磁碟區、將磁碟區移回其偏好的控制器擁有者。通常、當主機與儲存陣列之間的資料路徑發生問題時、多重路徑驅動程式會將磁碟區從其偏好的控制器擁有者移出。

大多數主機多重路徑驅動程式會嘗試存取其慣用控制器擁有者路徑上的每個磁碟區。但是、如果此偏好的路徑無法使用、主機上的多重路徑驅動程式就會容錯移轉到替代路徑。此容錯移轉可能會導致磁碟區擁有權變更為替代控制器。解決造成容錯移轉的情況之後、有些主機可能會自動將磁碟區擁有權移回偏好的控制器擁有者、但在某些情況下、您可能需要手動重新分配磁碟區。

您可以選取功能表：「Storage[磁碟區>更多>重新分配磁碟區]來重新分配磁碟區。



== 變更Volume擁有權

變更磁碟區的擁有權會變更磁碟區的慣用控制器擁有權。Volume的慣用控制器擁有者列在功能表：Storage（儲存）[Volumes（磁碟區）> View（檢視）/Edit Settings（編輯設定）> Advanced（進階）索引標籤]下。

您可以選取功能表：「Storage[ Volume > More > Change所有權」（儲存設備[磁碟區>更多>變更擁有權）來變更磁碟區的擁有權。



=== 鏡射與Volume擁有權

如果鏡射配對的主要磁碟區是由控制器A擁有、則次要磁碟區也將由遠端儲存陣列的控制器A擁有。變更主要磁碟區的擁有者將自動變更次要磁碟區的擁有者、以確保這兩個磁碟區都屬於同一個控制器。主端的目前擁有權變更會自動傳播至次要端的對應目前擁有權變更。

如果鏡射一致性群組包含本機次要磁碟區、且控制器擁有權已變更、則在第一次寫入作業時、次要磁碟區會自動傳輸回其原始控制器擁有者。您無法使用*變更所有權*選項來變更次要Volume的控制器所有權。



=== 複製Volume與Volume所有權

在複製磁碟區作業期間、相同的控制器必須同時擁有來源磁碟區和目標磁碟區。有時當複本磁碟區作業開始時、兩個磁碟區都沒有相同的慣用控制器。因此、目標磁碟區的擁有權會自動傳輸至來源磁碟區的慣用控制器。當磁碟區複本完成或停止時、目標磁碟區的擁有權會還原至其偏好的控制器。

如果在複製磁碟區作業期間變更來源磁碟區的擁有權、則目標磁碟區的擁有權也會變更。在某些作業系統環境下、可能需要重新設定多重路徑主機驅動程式、才能使用I/O路徑。（某些多重路徑驅動程式需要編輯才能辨識I/O路徑。如需詳細資訊、請參閱您的驅動程式文件。）



== 變更快取設定

快取記憶體是控制器上暫用揮發性儲存設備（RAM）的區域、存取時間比磁碟機媒體快。如果使用快取記憶體、您可以提高整體I/O效能、因為以下原因：

* 從主機要求讀取的資料可能已經在先前作業的快取中、因此不需要存取磁碟機。
* 寫入資料一開始會寫入快取、如此可釋出應用程式以繼續執行、而不需等待資料寫入磁碟機。


選取功能表：Storage[磁碟區>更多>變更快取設定]以變更下列快取設定：

* *讀寫快取*：讀取快取是儲存已從磁碟機讀取之資料的緩衝區。讀取作業的資料可能已經在先前作業的快取中、因此不需要存取磁碟機。資料會保留在讀取快取中、直到資料被清除為止。
+
寫入快取是一種緩衝區、用於儲存來自主機的資料、但尚未寫入磁碟機。資料會保留在寫入快取中、直到寫入磁碟機為止。寫入快取可提高I/O效能。

* *使用鏡射寫入快取*-寫入快取搭配鏡射會在寫入某個控制器快取記憶體的資料同時寫入另一個控制器的快取記憶體時發生。因此、如果一個控制器故障、另一個控制器就能完成所有未完成的寫入作業。只有啟用寫入快取且存在兩個控制器時、才能使用寫入快取鏡射。使用鏡射進行寫入快取是建立磁碟區的預設設定。
* *無電池寫入快取*-無電池寫入快取設定可讓寫入快取繼續、即使電池遺失、故障、電力完全耗盡或未充滿電也沒問題。通常不建議選擇不含電池的寫入快取、因為如果電力中斷、資料可能會遺失。一般而言、寫入快取會由控制器暫時關閉、直到電池充電或更換故障電池為止。
+
此設定僅適用於啟用寫入快取的情況。此設定不適用於精簡磁碟區。

* *動態讀取快取預先擷取*-動態快取讀取預先擷取可讓控制器在讀取磁碟機至快取的資料區塊時、將其他循序資料區塊複製到快取中。此快取可增加日後從快取中填入資料要求的機會。對於使用連續I/O的多媒體應用程式而言、動態快取讀取預先擷取非常重要預先擷取至快取的資料速率和數量、是根據主機讀取的速率和要求大小而自行調整。隨機存取不會將資料預先擷取至快取。停用讀取快取時、此功能不適用。
+
對於精簡磁碟區、動態快取讀取預先擷取一律停用、無法變更。





== 變更媒體掃描設定

媒體掃描會偵測並修復應用程式不常讀取的磁碟區塊上的媒體錯誤。如果集區或磁碟區群組中的其他磁碟機因使用備援資訊重建故障磁碟機的資料、以及使用集區或磁碟區群組中其他磁碟機的資料、此掃描可防止資料遺失。

媒體掃描會根據要掃描的容量和掃描持續時間、以固定的速度持續執行。背景掃描可能會由較高優先順序的背景工作（例如重建）暫停、但會以相同的固定速率繼續。

您可以選取功能表：「Storage[ Volume > More（磁碟區>更多）> Change media scan settings（變更媒體掃描設定）」來啟用及設定媒體掃描的執行時間。

只有在儲存陣列和該磁碟區啟用媒體掃描選項時、才會掃描磁碟區。如果該磁碟區也啟用備援檢查、則會檢查磁碟區中的備援資訊是否與資料一致、前提是磁碟區具有備援。建立每個磁碟區時、預設會啟用具有備援檢查的媒體掃描。

如果掃描期間發生無法恢復的媒體錯誤、資料將會使用備援資訊（如果有）進行修復。例如、最佳RAID 5磁碟區或最佳或僅有一個磁碟機故障的RAID 6磁碟區中都有備援資訊。如果無法使用備援資訊修復不可恢復的錯誤、資料區塊將會新增至無法讀取的區段記錄。可修正和不可修正的媒體錯誤都會報告到事件記錄中。

如果備援檢查發現資料與備援資訊不一致、則會將其報告至事件記錄。
