---
permalink: sm-storage/assign-hot-spares-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, assign hot spares 
summary: 您可以將熱備援磁碟指派為待命磁碟機、以便在RAID 1、RAID 5或RAID 6 Volume群組中提供額外的資料保護。如果其中一個磁碟機故障、控制器會將故障磁碟機的資料重新建構至熱備援磁碟機。 
---
= 指派熱備援磁碟機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將熱備援磁碟指派為待命磁碟機、以便在RAID 1、RAID 5或RAID 6 Volume群組中提供額外的資料保護。如果其中一個磁碟機故障、控制器會將故障磁碟機的資料重新建構至熱備援磁碟機。

.開始之前
* 必須建立RAID 1、RAID 5或RAID 6 Volume群組。（熱備援磁碟區無法用於資源池。而是使用每個磁碟機內的備用容量來保護資料。）
* 必須具備符合下列條件的磁碟機：
+
** 未指派、具有最佳狀態。
** 與Volume群組中的磁碟機相同的媒體類型（例如SSD）。
** 與Volume群組中的磁碟機相同的介面類型（例如SAS）。
** 容量等於或大於Volume群組中磁碟機的已用容量。




.關於這項工作
本工作說明如何從「硬體」頁面手動指派熱備援磁碟機。建議的涵蓋範圍為每個磁碟機集兩個熱備援磁碟機。

[CAUTION]
====
也可以從初始設定精靈指派熱備援磁碟機。您可以在「硬體」頁面上尋找以粉色顯示的磁碟機支架、以判斷是否已指派熱備援磁碟機。

====
.步驟
. 選取*硬體*。
. 如果圖形顯示控制器、請按一下*顯示機櫃正面*。
+
圖形會變更、以顯示磁碟機而非控制器。

. 選取您要作為熱備援的未指派磁碟機（以灰色顯示）。
+
隨即開啟磁碟機的內容功能表。

. 選取*指派熱備援*。
+
如果磁碟機已啟用安全功能、則會開啟「*安全清除磁碟機*」對話方塊。若要將啟用安全功能的磁碟機作為熱備援磁碟機、您必須先執行「安全清除」作業、以移除其所有資料並重設其安全屬性。

+
[CAUTION]
====
*可能會遺失資料*-請確定您已選取正確的磁碟機。完成「安全清除」作業之後、您將無法恢復任何資料。

====
+
如果磁碟機*未*啟用安全功能、則會開啟「確認指派熱備援磁碟機」對話方塊。

. 檢閱對話方塊中的文字、然後確認操作。
+
磁碟機在「Hardware（硬體）」頁面上以粉色顯示、表示它現在是熱備援磁碟機。





== 結果

如果RAID 1、RAID 5或RAID 6磁碟區群組內的磁碟機故障、控制器會自動使用備援資料、將故障磁碟機的資料重建為熱備援磁碟機。
