---
permalink: sm-storage/automatic-versus-manual-pool-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, pool 
summary: 您可以自動或手動建立資源池、以便將實體儲存設備分組、然後視需要動態配置。建立集區時、您可以新增實體磁碟機。 
---
= 自動與手動建立資源池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以自動或手動建立資源池、以便將實體儲存設備分組、然後視需要動態配置。建立集區時、您可以新增實體磁碟機。



== 自動建立

當System Manager偵測到儲存陣列中的未指派容量時、就會啟動自動建立集區。偵測到未指派的容量時、System Manager會自動提示您建立一個或多個資源池、或將未指派的容量新增至現有資源池、或同時新增至兩者。

當下列其中一項條件成立時、就會自動建立集區：

* 儲存陣列中不存在集區、而且有足夠的類似磁碟機可建立新的集區。
* 新磁碟機會新增至至少有一個集區的儲存陣列。


集區中的每個磁碟機必須為相同的磁碟機類型（HDD或SSD）、而且容量必須相似。System Manager會提示您完成下列工作：

* 如果有足夠數量的磁碟機屬於這些類型、請建立單一集區。
* 如果未指派的容量包含不同的磁碟機類型、請建立多個資源池。
* 如果儲存陣列中已定義集區、請將磁碟機新增至現有集區、然後將相同磁碟機類型的新磁碟機新增至集區。
* 將相同磁碟機類型的磁碟機新增至現有的集區、如果新磁碟機類型不同、請使用其他磁碟機類型來建立不同的集區。




== 手動建立

當自動建立無法判斷最佳組態時、您可能需要手動建立集區。發生這種情況的原因如下：

* 新磁碟機可能會新增至多個集區。
* 一或多個新的資源池候選對象可以使用機櫃損失保護或藥櫃損失保護。
* 一或多位目前的資源池候選對象無法維持其機櫃遺失保護或藥櫃遺失保護狀態。


如果您的儲存陣列上有多個應用程式、但不想讓它們競用相同的磁碟機資源、您可能也想要手動建立集區。在這種情況下、您可以考慮手動為一或多個應用程式建立較小的資源池。您只能指派一或兩個磁碟區、而不需將工作負載指派給有許多磁碟區的大型集區、以便在其中發佈資料。手動建立專屬特定應用程式工作負載的獨立資源池、可讓儲存陣列作業更快速地執行、同時減少爭用。
