---
permalink: sm-storage/capacity-for-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity, volumes, 
summary: 儲存陣列中的磁碟機可為您的資料提供實體儲存容量。在開始儲存資料之前、您必須先將分配的容量設定為稱為資源池或磁碟區群組的邏輯元件。您可以使用這些儲存物件來設定、儲存、維護及保留儲存陣列上的資料。 
---
= 如何在 SANtricity System Manager 中指派磁碟區容量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存陣列中的磁碟機可為您的資料提供實體儲存容量。在開始儲存資料之前、您必須先將分配的容量設定為稱為資源池或磁碟區群組的邏輯元件。您可以使用這些儲存物件來設定、儲存、維護及保留儲存陣列上的資料。



== 使用容量來建立及擴充磁碟區

您可以從資源池或磁碟區群組中未指派的容量或可用容量建立磁碟區。

* 當您從未指派的容量建立磁碟區時、可以同時建立集區或磁碟區群組和磁碟區。
* 當您從可用容量建立磁碟區時、會在現有的資源池或磁碟區群組上建立額外的磁碟區。


擴充磁碟區容量之後、您必須手動增加檔案系統大小以符合需求。您的做法取決於所使用的檔案系統。如需詳細資料、請參閱主機作業系統文件。



== 適用於厚磁碟區和精簡磁碟區的容量類型

您可以建立厚磁碟區或精簡磁碟區。報告的容量和已分配的容量對於大型磁碟區而言相同、但對於精簡磁碟區則不同。

* 對於較厚的Volume、該磁碟區的報告容量等於已配置的實體儲存容量。實體儲存容量必須全部存在。實體配置的空間等於報告給主機的空間。
+
您通常會將厚磁碟區的報告容量設定為您認為該磁碟區將會增加的最大容量。大型磁碟區可為您的應用程式提供高且可預測的效能、主要是因為所有的使用者容量都是在建立時保留和配置的。

* 對於精簡磁碟區、回報容量是報告給主機的容量、而分配的容量則是目前分配給寫入資料的磁碟機空間量。
+
報告的容量可以大於儲存陣列上的已分配容量。精簡磁碟區的規模可因應成長需求、而不需考慮目前可用的資產。



[NOTE]
====
不提供建立精簡磁碟區的選項。SANtricity如果要建立精簡磁碟區、請使用命令列介面（CLI）。

====


== 大型磁碟區的容量限制

大型磁碟區的最小容量為1個mib、最大容量則取決於集區或Volume群組中磁碟機的數量和容量。

增加報告的厚磁碟區容量時、請謹記下列準則：

* 您最多可以指定三個小數位數（例如、65.375 GiB）。
* 容量必須小於（或等於）Volume群組中可用的最大容量。
+
當您建立磁碟區時、會預先配置部分額外容量以進行動態區段大小（DSS）移轉。DSS移轉是軟體的一項功能、可讓您變更磁碟區的區段大小。

* 部分主機作業系統支援大於2 TiB的磁碟區（報告容量上限由主機作業系統決定）。事實上、某些主機作業系統最多可支援128個TiB磁碟區。如需其他詳細資料、請參閱主機作業系統文件。




== 精簡磁碟區的容量限制

您可以建立報告容量較大且分配容量相對較小的精簡磁碟區、這對儲存使用率和效率有助益。精簡磁碟區有助於簡化儲存管理、因為分配的容量可以隨著應用程式需求的改變而增加、而不會中斷應用程式、進而提高儲存使用率。

除了回報的容量和已分配的容量、精簡磁碟區也包含寫入的容量。寫入容量是指從分配給精簡磁碟區的保留容量中寫入的容量量。

下表列出精簡磁碟區的容量限制。

[cols="3*"]
|===
| 容量類型 | 最小尺寸 | 最大尺寸 


 a| 
已報告
 a| 
32個MIB
 a| 
256 TiB



 a| 
已分配
 a| 
4個MIB
 a| 
64 TiB

|===
對於精簡磁碟區、如果已達到256 TiB的最大報告容量、您就無法增加容量。請確定精簡磁碟區的保留容量設定為大於最大報告容量的大小。

系統會根據已分配的容量上限、自動擴充已分配的容量。分配的容量上限可讓您將精簡磁碟區的自動成長限制在報告容量以下。當寫入的資料量接近分配的容量時、您可以變更分配的容量上限。

若要變更已分配的容量上限、請選取功能表：「Storage[ Volume > Thin Volume Monitoring（磁碟區監控）」索引標籤>「Change Limit（變更限制）」。

由於System Manager在建立精簡磁碟區時並未配置完整容量、因此資源池中可能存在可用容量不足的情況。空間不足可能會封鎖對集區的寫入、不只是對精簡磁碟區、也會對需要來自集區容量的其他作業（例如、快照映像或快照磁碟區）。不過、您仍可從集區執行讀取作業。如果發生這種情況、您會收到警示臨界值警告。
