---
permalink: sm-storage/capacity-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity terms 
summary: 瞭解容量術語如何適用於您的儲存陣列。 
---
= 容量術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解容量術語如何適用於您的儲存陣列。



== 儲存物件

下列術語說明可與儲存陣列互動的不同儲存物件類型。

[cols="25h,~"]
|===
| 儲存物件 | 說明 


 a| 
主機
 a| 
主機是一種伺服器、可將I/O傳送至儲存陣列上的磁碟區。



 a| 
LUN
 a| 
邏輯單元編號（LUN）是指派給主機用來存取磁碟區之位址空間的編號。磁碟區會以LUN的形式、以容量形式呈現給主機。

每個主機都有自己的LUN位址空間。因此、不同主機可以使用相同的LUN來存取不同的磁碟區。



 a| 
鏡射一致性群組
 a| 
鏡射一致性群組是一個或多個鏡射配對的容器。對於非同步鏡射作業、您必須建立鏡射一致性群組。



 a| 
鏡射Volume配對
 a| 
鏡射配對由兩個磁碟區組成、一是主要磁碟區、另一是次要磁碟區。



 a| 
資源池
 a| 
資源池是邏輯分組的一組磁碟機。您可以使用集區來建立一個或多個可供主機存取的磁碟區。（您可以從集區或磁碟區群組建立磁碟區。）



 a| 
Snapshot一致性群組
 a| 
Snapshot一致性群組是建立快照映像時、將其視為單一實體的磁碟區集合。每個磁碟區都有自己的快照映像、但所有映像都會在同一時間點建立。



 a| 
Snapshot群組
 a| 
Snapshot群組是來自單一基礎Volume的快照映像集合。



 a| 
Snapshot Volume
 a| 
Snapshot Volume可讓主機存取快照映像中的資料。快照磁碟區包含自己的保留容量、可儲存對基礎磁碟區所做的任何修改、而不會影響原始的快照映像。



 a| 
Volume
 a| 
Volume是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機所建立的邏輯元件、可用來存取儲存陣列上的儲存設備。



 a| 
Volume群組
 a| 
Volume群組是具有共享特性之磁碟區的容器。Volume群組具有已定義的容量和RAID層級。您可以使用Volume群組來建立一個或多個可讓主機存取的磁碟區。（您可以從磁碟區群組或集區建立磁碟區。）

|===


== 儲存容量

下列術語說明儲存陣列上使用的不同容量類型。

[cols="25h,~"]
|===
| 容量類型 | 說明 


 a| 
已分配容量
 a| 
已分配容量是指從集區或磁碟區群組中的磁碟機所配置的實體容量。

您可以使用已分配的容量來建立磁碟區和複製服務作業。



 a| 
可用容量
 a| 
可用容量是指尚未分配給磁碟區建立或複製服務作業和儲存物件的資源池或磁碟區群組中可用的容量。



 a| 
集區或Volume群組容量
 a| 
資源池、Volume或Volume群組容量是儲存陣列中已指派給資源池或Volume群組的容量。此容量可用來建立磁碟區、並滿足複製服務作業和儲存物件的各種容量需求。



 a| 
集區無法使用的容量
 a| 
集區無法使用的容量是集區中的空間、因為磁碟機大小不相符而無法使用。



 a| 
保留容量
 a| 
保留容量是指為支援潛在磁碟機故障而保留在集區中的容量（磁碟機數量）。



 a| 
報告容量
 a| 
回報容量是指報告給主機的容量、可由主機存取。



 a| 
保留容量
 a| 
保留容量是指用於任何複製服務作業和儲存物件的實體配置容量。主機無法直接讀取。



 a| 
SSD快取
 a| 
[NOTE]
====
EF600或EF300儲存系統無法使用此功能。

====
SSD快取是一組固態磁碟（SSD）磁碟機、您可以在儲存陣列中以邏輯方式將其分組。SSD快取功能可將最常存取的資料（「熱」資料）快取到較低延遲的SSD磁碟機、以動態加速應用程式工作負載。



 a| 
未指派的容量
 a| 
未指派的容量是儲存陣列中*尚未*指派給資源池或磁碟區群組的空間。



 a| 
寫入容量
 a| 
寫入容量是指從分配給精簡磁碟區的保留容量中寫入的容量量。

|===