---
permalink: sm-storage/change-cache-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache settings 
summary: 您可以變更讀取快取和寫入快取設定、以影響磁碟區的整體I/O效能。 
---
= 變更磁碟區的快取設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更讀取快取和寫入快取設定、以影響磁碟區的整體I/O效能。

.關於這項工作
變更磁碟區的快取設定時、請謹記以下準則：

* 開啟「變更快取設定」對話方塊之後、您可能會看到所選快取內容旁顯示的圖示。此圖示表示控制器已暫停快取作業。
+
當新電池正在充電、控制器已移除、或控制器偵測到快取大小不相符時、可能會發生此動作。清除條件之後、對話方塊中選取的快取內容就會變成作用中。如果所選的快取內容未啟用、請聯絡技術支援部門。

* 您可以變更單一磁碟區或儲存陣列上多個磁碟區的快取設定。您可以同時變更所有標準磁碟區或所有精簡磁碟區的快取設定。


.步驟
. 選取功能表：Storage[磁碟區]。
. 選取任何Volume、然後選取功能表：More（更多）[變更快取設定]。
+
「變更快取設定」對話方塊隨即出現。儲存陣列上的所有磁碟區都會顯示在此對話方塊中。

. 選取*基礎*索引標籤、以變更讀取快取和寫入快取的設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 快取設定 | 說明 


 a| 
讀取快取
 a| 
讀取快取是儲存已從磁碟機讀取之資料的緩衝區。讀取作業的資料可能已經在先前作業的快取中、因此不需要存取磁碟機。資料會保留在讀取快取中、直到資料被清除為止。



 a| 
寫入快取
 a| 
寫入快取是一種緩衝區、用於儲存來自主機的資料、但尚未寫入磁碟機。資料會保留在寫入快取中、直到寫入磁碟機為止。寫入快取可提高I/O效能。


NOTE: 快取會在停用磁碟區的*寫入快取*之後自動排清。

|===
====
. 選取*進階*索引標籤以變更大型磁碟區的進階設定。進階快取設定僅適用於厚磁碟區。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 快取設定 | 說明 


 a| 
動態讀取快取預先擷取
 a| 
動態快取讀取預先擷取可讓控制器在從磁碟機讀取資料區塊到快取時、將其他循序資料區塊複製到快取。此快取可增加日後從快取中填入資料要求的機會。對於使用連續I/O的多媒體應用程式而言、動態快取讀取預先擷取非常重要預先擷取至快取的資料速率和數量、是根據主機讀取的速率和要求大小而自行調整。隨機存取不會將資料預先擷取至快取。停用讀取快取時、此功能不適用。

對於精簡磁碟區、動態快取讀取預先擷取一律停用、無法變更。



 a| 
寫入快取、不含電池
 a| 
寫入快取（無電池）設定可讓寫入快取繼續、即使電池遺失、故障、電力完全耗盡或未充滿電也沒問題。通常不建議選擇不含電池的寫入快取、因為如果電力中斷、資料可能會遺失。一般而言、寫入快取會由控制器暫時關閉、直到電池充電或更換故障電池為止。


CAUTION: *可能的資料遺失*-如果您選取此選項、但沒有通用電源供應器來提供保護、您可能會遺失資料。此外、如果您沒有控制器電池、並且啟用*無電池寫入快取*選項、則可能會遺失資料。

此設定僅適用於啟用寫入快取的情況。此設定不適用於精簡磁碟區。



 a| 
使用鏡射寫入快取
 a| 
寫入快取搭配鏡射時、寫入某個控制器快取記憶體的資料也會寫入另一個控制器的快取記憶體。因此、如果一個控制器故障、另一個控制器就能完成所有未完成的寫入作業。只有啟用寫入快取且存在兩個控制器時、才能使用寫入快取鏡射。使用鏡射進行寫入快取是建立磁碟區的預設設定。

此設定僅適用於啟用寫入快取的情況。此設定不適用於精簡磁碟區。

|===
====
. 按一下「*儲存*」以變更快取設定。

