---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: 您可以變更磁碟區的設定、例如名稱、主機指派、區段大小、修改優先順序、快取、 等等。 
---
= 變更 SANtricity System Manager 中的磁碟區設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更磁碟區的設定、例如名稱、主機指派、區段大小、修改優先順序、快取、 等等。

.開始之前
您要變更的Volume處於最佳狀態。


NOTE: 在變更磁碟區設定時、部分作業可能無法使用

.步驟
. 從左側面板中，選擇功能表：Storage[Volumes]。
. 選擇要變更的磁碟區，然後按一下功能表：省略符號圖示 [編輯設定]。
+
「編輯 Volume 設定」視窗隨即出現，顯示所選 volume 的組態設定。

. 依需求配置磁碟區設定：
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
名稱
 a| 
顯示磁碟區名稱。當目前名稱不再有意義或適用時、請變更Volume名稱。



 a| 
主機
 a| 
顯示Volume指派。您可以將磁碟區指派給主機或主機叢集、以便存取該磁碟區進行I/O作業。這項指派可讓主機或主機叢集存取儲存陣列中的特定磁碟區或多個磁碟區。

** *指派給*-識別可存取所選磁碟區的主機或主機叢集。
** * LUN*-邏輯單元號碼（LUN）是指派給主機用來存取磁碟區之位址空間的號碼。磁碟區會以LUN的形式、以容量形式呈現給主機。每個主機都有自己的LUN位址空間。因此、不同主機可以使用相同的LUN來存取不同的磁碟區。
+

NOTE: 對於NVMe介面、此欄會顯示命名空間ID。命名空間是NVM儲存設備、其格式化為區塊存取。它類似於SCSI中的邏輯單元、與儲存陣列中的磁碟區相關。命名空間ID是NVMe控制器的命名空間唯一識別碼、可設定為1到255之間的值。它類似於SCSI中的邏輯單元號碼（LUN）。





 a| 
區段規模調整
 a| 
顯示區段大小調整的設定、僅適用於Volume群組中的磁碟區。您可以變更區段大小以最佳化效能。

*允許的區段大小轉換*- System Manager會決定允許的區段大小轉換。無法在下拉式清單中使用不適當的從目前區段大小轉換的區段大小。允許的轉換通常是目前區段大小的兩倍或一半。例如、如果目前的Volume區段大小為32 KiB、則允許新的Volume區段大小為16 KiB或64 KiB。

*啟用SSD快取的磁碟區*-您可以為啟用SSD快取的磁碟區指定4-KiB區段大小。請務必針對啟用SSD快取的磁碟區選取4-KiB區段大小、以便處理小區塊I/O作業（例如、16個KiB I/O區塊大小或更小）。如果您選取4 KiB做為啟用SSD快取的磁碟區的區段大小、以處理大量區塊循序作業、效能可能會受到影響。

*變更區段大小的時間*-變更磁碟區區區段大小的時間長短取決於下列變數：

** 主機的I/O負載
** 磁碟區的修改優先順序
** Volume群組中的磁碟機數量
** 磁碟機通道數
** 儲存陣列控制器的處理能力當您變更磁碟區的區段大小時、I/O效能會受到影響、但您的資料仍然可用。




 a| 
修改優先順序
 a| 
顯示修改優先順序的設定、僅適用於Volume群組中的磁碟區。

修改優先順序會定義相對於系統效能、為磁碟區修改作業分配多少處理時間。您可以提高磁碟區修改優先順序、但這可能會影響系統效能。

移動滑桿以選取優先順序層級。

*修改優先率*：最低優先率有利於系統效能、但修改作業需要較長時間。最高優先順序率有利於修改作業、但系統效能可能會受損。

|===
====
. 按一下「 * 儲存 * 」。
+
System Manager會根據您的選擇來變更Volume的設定。



.完成後
選擇選單：Storage[Operations in Progress]，查看目前正在對所選磁碟區執行的變更操作的進度。
