---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, group 
summary: 您可以變更快照群組的設定、以變更其名稱、自動刪除設定、允許的最大快照映像數、系統管理員傳送保留容量警示通知的百分比點、或是保留容量達到其定義的最大百分比時所使用的原則。 
---
= 變更快照群組的保留容量設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更快照群組的設定，以變更其名稱，自動刪除設定，允許的最大快照映像數， SANtricity 系統管理員傳送保留容量警示通知的百分比，或保留容量達到其最大定義百分比時使用的原則。

在建立快照群組期間、系統會建立保留容量、以儲存群組中所有快照映像的資料。

.步驟
. 選取功能表：Storage[集區與Volume群組]。
. 按一下*保留容量*索引標籤。
. 選取您要編輯的快照群組、然後按一下「*檢視/編輯設定*」。
+
此時將出現Snapshot Group Settings（快照組設置）對話框。

. 視需要變更快照群組的設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
* Snapshot群組設定*



 a| 
名稱
 a| 
快照群組的名稱。必須指定快照群組的名稱。



 a| 
自動刪除
 a| 
此設定可將群組中的快照映像總數維持在或低於使用者定義的最大值。啟用此選項時、系統管理員會在建立新快照時、自動刪除群組中最舊的快照映像、以符合群組允許的最大快照映像數。



 a| 
Snapshot映像限制
 a| 
可設定的值、指定快照群組允許的最大快照映像數。



 a| 
Snapshot排程
 a| 
如果為「是」、則會設定自動建立快照的排程。



 a| 
*保留容量設定*



 a| 
提醒我...
 a| 
當快照群組的保留容量即將滿時、使用微調方塊來調整系統管理員傳送警示通知的百分比點。

當快照群組的保留容量超過指定臨界值時、System Manager會傳送警示、讓您有時間增加保留容量或刪除不必要的物件。



 a| 
完整保留容量的原則
 a| 
您可以選擇下列其中一項原則：

** *清除最舊的快照映像*：System Manager會自動清除快照群組中最舊的快照映像、以釋放快照映像保留容量、供群組內重複使用。
** *拒絕寫入基本磁碟區*-當保留容量達到其定義的最大百分比時、System Manager會拒絕任何I/O寫入要求、以觸發保留容量存取。




 a| 
*相關物件*



 a| 
基礎Volume
 a| 
用於群組的基礎磁碟區名稱。基礎Volume是建立快照映像的來源。它可以是厚磁碟區或精簡磁碟區、通常會指派給主機。基礎磁碟區可位於磁碟區群組或磁碟集區中。



 a| 
Snapshot映像
 a| 
由此群組建立的映像數。Snapshot映像是在特定時間點擷取的Volume資料邏輯複本。如同還原點、Snapshot映像可讓您回復至已知良好的資料集。雖然主機可以存取快照映像、但無法直接讀取或寫入。

|===
====
. 按一下「*儲存*」、將您的變更套用至快照群組設定。

