---
permalink: sm-storage/change-the-settings-for-a-snapshot-schedule.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, snapshot, schedule 
summary: 對於快照排程、您可以變更自動收集時間或收集頻率。 
---
= 變更快照排程的設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於快照排程、您可以變更自動收集時間或收集頻率。

.關於這項工作
您可以從現有的快照排程匯入設定、也可以視需要修改設定。

由於快照排程與快照群組或快照一致性群組相關聯、因此保留容量可能會受到排程設定變更的影響。

.步驟
. 選取功能表：Storage[快照]。
. 按一下*排程*索引標籤。
. 選取您要變更的快照排程、然後按一下*編輯*。
+
此時將顯示Edit Snapshot Schedule（編輯快照排程）對話方塊。

. 執行下列其中一項：
+
** *使用其他快照物件中先前定義的排程*-按一下*匯入排程*、選取含有您要匯入排程的物件、然後按一下*匯入*。
** *編輯排程設定*-請參閱下方欄位詳細資料。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
日/月
 a| 
請選擇下列其中一個選項：

*** *每日/每週*-選擇同步快照的個別日期。如果您想要每日排程、也可以選取右上角的*全日*核取方塊。
*** *每月/每年*-選擇同步快照的個別月份。在「*於日*」欄位中、輸入每月進行同步的天數。有效輸入項目為* 1 *至* 31 *、*最後*。您可以使用分號或分號分隔多天。使用連字號表示包含日期。例如：1、3、4、10-15、Last。如果您想要每月排程、也可以選取右上角的*全月*核取方塊。




 a| 
開始時間
 a| 
從下拉式清單中、選取每日快照的新開始時間。選擇以每小時為單位提供。開始時間預設為比目前時間早一個半小時。



 a| 
時區
 a| 
從下拉式清單中、選取儲存陣列的時區。



 a| 
每天快照

快照之間的時間
 a| 
選取每天要建立的快照映像數目。

如果您選取多個還原點、請同時選取還原點之間的時間。對於多個還原點、請確定您擁有足夠的保留容量。



 a| 
開始日期

結束日期

無結束日期
 a| 
輸入開始同步的開始日期。同時輸入結束日期或選擇*無結束日期*。

|===
====


. 按一下「 * 儲存 * 」。

