---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: 若要變更主機連接埠識別碼上的使用者標籤、新增主機連接埠識別碼至主機、或從主機刪除主機連接埠識別碼、請變更主機連接埠識別碼。 
---
= 在 SANtricity System Manager 中變更主機的主機連接埠標識符
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要變更主機連接埠識別碼上的使用者標籤、新增主機連接埠識別碼至主機、或從主機刪除主機連接埠識別碼、請變更主機連接埠識別碼。

.關於這項工作
變更主機連接埠識別碼時、請謹記下列準則：

* *新增*-新增主機連接埠時、您要將主機連接埠識別碼與您建立的主機建立關聯、以便連線至儲存陣列。您可以使用主機匯流排介面卡（HBA）公用程式手動輸入連接埠資訊。
* *編輯*：您可以編輯主機連接埠、以便將主機連接埠移至（關聯）其他主機。您可能已將主機匯流排介面卡或iSCSI啟動器移至其他主機、因此必須將主機連接埠（建立關聯）移至新主機。
* *刪除*：您可以刪除主機連接埠、以便從主機移除（取消關聯）主機連接埠。


.步驟
. 從左側面板中，選擇功能表：Storage [Hosts]。
. 選擇要關聯連接埠的主機，然後按一下 menu:ellipsis icon[Edit Settings]。
+
如果要向主機叢集中的某個主機新增連接埠，請選擇所需的主機。無法在主機叢集層級新增連接埠。

+
此時會顯示「編輯主機設定」畫面，其中顯示目前的主機設定。

. 視需要變更主機連接埠識別碼設定。
+
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
主機連接埠
 a| 
您可以選擇下列其中一個選項：

** *Add host port* -- 按一下 *Add host port*，將新的主機連接埠識別碼關聯到主機。主機連接埠識別碼名稱的長度取決於主機介面技術。Fibre Channel 和 Infiniband 主機連接埠識別碼名稱必須為 16 個字元。iSCSI 主機連接埠識別碼名稱最多為 223 個字元。連接埠必須是唯一的。不允許使用已設定的連接埠號碼。
** *刪除（X 圖示）* -- 按一下 *X* 圖示可移除（取消關聯）主機連接埠識別碼。刪除選項不會實際移除主機連接埠。此選項會移除主機連接埠與主機之間的關聯。除非您移除主機匯流排適配器或 iSCSI 啟動器，否則控制器仍會識別該主機連接埠。
+
[NOTE]
====
如果刪除主機連接埠識別碼、則該識別碼不再與此主機相關聯。此外、主機也無法透過此主機連接埠識別碼存取任何已指派的磁碟區。

====




 a| 
名稱
 a| 
如有需要，您可以變更連接埠標籤名稱。連接埠標籤名稱必須是唯一的。不允許使用已配置的標籤名稱。



 a| 
CHAP機密
 a| 
僅適用於iSCSI主機。您可以設定或變更啟動器（iSCSI主機）的CHAP機密。

System Manager使用Challenge Handshake驗證傳輸協定（CHAP）方法、在初始連結期間驗證目標和啟動器的身分。驗證是以稱為CHAP機密的共用安全金鑰為基礎。

|===
. 按一下「 * 儲存 * 」。

