---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-consistency-group-member-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, consistency group, member volume 
summary: 您可以變更一致性群組成員磁碟區的設定、以調整系統管理員在成員磁碟區的保留容量即將滿時傳送警示通知的百分比點、並變更保留容量達到其定義上限時所使用的原則 百分比。 
---
= 變更一致性群組成員磁碟區的保留容量設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更一致性群組成員磁碟區的設定、以調整系統管理員在成員磁碟區的保留容量即將滿時傳送警示通知的百分比點、並變更保留容量達到其定義上限時所使用的原則 百分比。

.關於這項工作
變更個別成員磁碟區的保留容量設定、也會變更與一致性群組相關聯之所有成員磁碟區的保留容量設定。

.步驟
. 選取功能表：Storage[集區與Volume群組]。
. 按一下*保留容量*索引標籤。
. 選取您要編輯的一致性群組成員磁碟區、然後按一下「*檢視/編輯設定*」。
+
「成員Volume保留容量設定」對話方塊隨即出現。

. 視需要變更成員磁碟區的保留容量設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
提醒我...
 a| 
當成員Volume的保留容量即將滿時、使用微調方塊來調整系統管理員傳送警示通知的百分比點。

當成員磁碟區的保留容量超過指定臨界值時、System Manager會傳送警示、讓您有時間增加保留容量或刪除不必要的物件。


NOTE: 變更單一成員磁碟區的警示設定、將會針對屬於同一個一致性群組的_all_成員磁碟區進行變更。



 a| 
完整保留容量的原則
 a| 
您可以選擇下列其中一項原則：

** *清除最舊的快照映像*：System Manager會自動清除一致性群組中最舊的快照映像、以釋放成員的保留容量、以便在群組內重複使用。
** *拒絕寫入基本磁碟區*-當保留容量達到其定義的最大百分比時、System Manager會拒絕任何I/O寫入要求、以觸發保留容量存取。


|===
====
. 按一下「*儲存*」以套用您的變更。


.結果
System Manager會變更成員磁碟區的保留容量設定、以及一致性群組中所有成員磁碟區的保留容量設定。
