---
permalink: sm-storage/comparison-between-thick-volumes-and-thin-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, comparison, thick volumes, thin volumes 
summary: 完整的磁碟區一律是完整配置的、這表示在建立磁碟區時、會配置所有的容量。精簡磁碟區一律精簡配置、這表示在資料寫入磁碟區時、會分配容量。 
---
= 比較厚磁碟區與精簡磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
完整的磁碟區一律是完整配置的、這表示在建立磁碟區時、會配置所有的容量。精簡磁碟區一律精簡配置、這表示在資料寫入磁碟區時、會分配容量。

[NOTE]
====
System Manager不提供建立精簡磁碟區的選項。如果要建立精簡磁碟區、請使用命令列介面（CLI）。

====
[cols="25h,~"]
|===
| Volume類型 | 說明 


 a| 
大型磁碟區
 a| 
* 大型磁碟區是從集區或磁碟區群組建立。
* 在使用大型磁碟區的情況下、系統會預先提供大量的儲存空間、以因應未來的儲存需求。
* 在建立磁碟區時、會以實體儲存設備上預先配置的整個磁碟區大小來建立厚磁碟區。這項預先配置意味著建立100 GiB磁碟區實際上會耗用100 GiB的磁碟機分配容量。不過、空間可能仍未使用、導致儲存容量使用率過低。
* 建立大型磁碟區時、請確定不要過度配置單一磁碟區的容量。單一磁碟區的過度配置容量、可快速消耗系統中的所有實體儲存設備。
* 請記住、複製服務（快照映像、快照磁碟區、磁碟區複本和非同步鏡射）也需要儲存容量、因此請勿將所有容量分配給大型磁碟區。空間不足可能會區塊寫入集區或Volume群組。如果發生這種情況、您會收到可用容量警示臨界值警告。




 a| 
精簡磁碟區
 a| 
* 只能從集區建立精簡磁碟區、而非從磁碟區群組建立。
* 精簡磁碟區必須是RAID 6。
* EF600或EF300儲存系統無法使用精簡磁碟區。
* 您必須使用CLI來建立精簡磁碟區。
* 與厚磁碟區不同的是、精簡磁碟區所需的空間不會在建立期間分配、而是在稍後隨需提供。
* 精簡磁碟區可讓您過度配置其大小。也就是、您可以指派大於Volume大小的LUN大小。然後您可以視需要擴充磁碟區（如有必要、可在程序中新增磁碟機）、而不需擴充LUN的大小、因此無需中斷使用者的連線。
* 您可以使用精簡配置區塊空間回收（取消對應）、透過主機發行的SCSI unmap命令、在儲存陣列上回收精簡配置的磁碟區區塊。支援精簡配置的儲存陣列可重新規劃回收空間的用途、以滿足同一個儲存陣列中其他精簡配置磁碟區的配置要求、進而更有效地報告磁碟空間使用量及資源使用效率。


|===


== 精簡磁碟區限制

精簡磁碟區支援所有複雜磁碟區的作業、但有下列例外：

* 您無法變更精簡磁碟區的區段大小。
* 您無法啟用精簡磁碟區的預先讀取備援檢查。
* 您無法在複製Volume作業中使用精簡磁碟區作為目標磁碟區。
* 您只能在非同步鏡射配對的主要端變更精簡磁碟區的已分配容量限制和警告臨界值。對主要端的這些參數所做的任何變更、都會自動傳播到次要端。

