---
permalink: sm-storage/consolidate-volume-group-free-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, consolidate, free capacity, volume group 
summary: 使用「整合可用容量」選項、將現有的可用範圍整合到選取的Volume群組中。執行此動作、即可從Volume群組中的可用容量上限建立額外的Volume。 
---
= 整合Volume群組的可用容量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「整合可用容量」選項、將現有的可用範圍整合到選取的Volume群組中。執行此動作、即可從Volume群組中的可用容量上限建立額外的Volume。

.開始之前
* Volume群組必須包含至少一個可用容量區域。
* Volume群組中的所有磁碟區都必須處於線上狀態且處於最佳狀態。
* 不得進行Volume修改作業、例如變更Volume的區段大小。


.關於這項工作
您無法在作業開始後取消。在整合作業期間、您的資料仍可存取。

您可以使用下列任一方法啟動「整合可用容量」對話方塊：

* 當至少偵測到一個Volume群組的一個可用容量區域時、「通知」區域的首頁會顯示「整合可用容量」建議。按一下「*整合可用容量*」連結以啟動對話方塊。
* 您也可以從「資源池與磁碟區群組」頁面啟動「整合可用容量」對話方塊、如下列工作所述。


.深入瞭解可用容量領域
[%collapsible]
====
可用容量區域是指在建立磁碟區期間、刪除磁碟區或未使用所有可用容量所產生的可用容量。當您在具有一或多個可用容量區域的Volume群組中建立Volume時、該Volume的容量僅限於該Volume群組中最大的可用容量區域。例如、如果某個Volume群組的可用容量總計為15 GiB、而最大的可用容量區域則為10 GiB、則您可以建立的最大磁碟區為10 GiB。

您可以整合Volume群組的可用容量、以提升寫入效能。隨著主機寫入、修改及刪除檔案、您的Volume群組可用容量會隨著時間而變得零碎。最後、可用容量不會位於單一鄰近區塊中、而是分散在整個Volume群組的小區段中。這會導致進一步的檔案分散、因為主機必須將新檔案以片段形式寫入、以符合可用叢集範圍。

藉由整合所選Volume群組的可用容量、每當主機寫入新檔案時、您都會發現檔案系統效能有所提升。整合程序也有助於防止新檔案在未來被分割。

====
.步驟
. 選取功能表：Storage[集區與Volume群組]。
. 選取您要整合的可用容量Volume群組、然後選取功能表：Unic尋常 工作[整合Volume群組可用容量]。
+
此時會出現「整合可用容量」對話方塊。

. 輸入「整合」以確認您要執行此作業。
. 按一下*整合*。
+
System Manager會開始將磁碟區群組的可用容量區域整合（重組）為一個鄰近的容量、以供後續的儲存組態工作使用。



.完成後
選取功能表：首頁[檢視進行中的作業]以檢視整合可用容量作業的進度。這項作業可能會耗費大量時間、並可能影響系統效能。
