---
permalink: sm-storage/convert-a-snapshot-volume-to-read-write-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, convert, snapshot, volume, read-write mode 
summary: 您可以視需要將唯讀快照磁碟區或快照一致性群組快照磁碟區轉換為讀寫模式。 
---
= 在 SANtricity System Manager 中將快照磁碟區轉換為讀寫模式
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以視需要將唯讀快照磁碟區或快照一致性群組快照磁碟區轉換為讀寫模式。

轉換為可讀寫存取的快照磁碟區包含自己的保留容量。此容量用於將主機應用程式後續所做的任何修改儲存至基礎磁碟區、而不會影響參考的快照映像。

.步驟
. 選取功能表：Storage[快照]。
. 選擇* Snapshot Volumes（快照卷）*選項卡。
+
此時將出現Snapshot Volumes（快照卷）表並顯示與儲存陣列相關的所有快照卷。

. 選取您要轉換的唯讀快照磁碟區、然後按一下*「Convert to read/Write*（轉換成讀取/寫入*）」。
+
此時會出現「轉換為讀取/寫入」對話方塊、並啟動*保留容量*步驟。Volume候選人表格僅顯示支援指定保留容量的候選對象。

. 若要為讀寫快照磁碟區分配保留容量、請執行下列其中一項動作：
+
** *接受預設設定*-使用此建議選項、以預設設定分配快照磁碟區的保留容量。
** *配置您自己的保留容量設定以滿足您的資料儲存需求*-依照下列準則來配置保留容量。
+
*** 保留容量的預設設定為基礎磁碟區容量的40%、通常此容量已足夠。
*** 所需的容量視磁碟區I/O寫入的頻率和大小而異。




. 選擇*下一步*以檢閱或編輯設定。
+
「編輯設定」對話方塊隨即出現。

. 接受或指定快照磁碟區的適當設定、然後選取*完成*以轉換快照磁碟區。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*保留容量設定*



 a| 
提醒我...
 a| 
當快照群組的保留容量即將滿時、使用微調方塊來調整系統傳送警示通知的百分比點。

當快照磁碟區的保留容量超過指定臨界值時、系統會傳送警示、讓您有時間增加保留容量或刪除不必要的物件。

|===
====

