---
permalink: sm-storage/copy-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy volume 
summary: 您可以將資料從一個磁碟區複製到同一個儲存陣列中的另一個磁碟區、然後建立來源磁碟區的實體時間點複製（複製）。 
---
= 複製Volume
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將資料從一個磁碟區複製到同一個儲存陣列中的另一個磁碟區、然後建立來源磁碟區的實體時間點複製（複製）。

.開始之前
* 必須停止來源Volume和目標Volume的所有I/O活動。
* 必須卸載來源Volume和目標Volume上的任何檔案系統。
* 如果您之前曾在複製Volume作業中使用過目標Volume、則不再需要該資料或已備份資料。


.關於這項工作
來源Volume是接受主機I/O並儲存應用程式資料的磁碟區。當複製Volume啟動時、來源Volume的資料會完整複製到目標Volume。

目標Volume是標準Volume、可維護來源Volume中資料的複本。複製Volume作業完成後、目標Volume與來源Volume相同。目標磁碟區的容量必須與來源磁碟區相同或更大、但它可以有不同的RAID層級。

.深入瞭解線上和離線複本
[%collapsible]
====
*線上複本*

線上複本會建立儲存陣列內任何磁碟區的時間點複本、但仍可在複本進行中寫入磁碟區。此功能是透過建立磁碟區快照、並將快照作為複本的實際來源磁碟區來實現。建立時間點映像的磁碟區稱為基礎磁碟區、可以是儲存陣列中的標準磁碟區或精簡磁碟區。

*離線複本*

離線複本會從來源磁碟區讀取資料、並將其複製到目標磁碟區、同時在複本進行期間暫停所有對來源磁碟區的更新。來源Volume的所有更新都會暫停、以避免在目標Volume上建立時間不一致的情況。離線Volume複製關係是指來源Volume與目標Volume之間的關係。

====
[NOTE]
====
複製Volume作業會覆寫目標磁碟區上的資料、並使與目標磁碟區相關的所有快照磁碟區（如果有）失效。

====
.步驟
. 選取功能表：Storage[磁碟區]。
. 選取您要作為複製Volume作業來源的Volume、然後選取功能表：複製服務[複製Volume ]。
+
此時會出現Copy Volume Select Target（複製Volume選取目標）對話方塊。

. 選取您要複製資料的目標Volume。
+
此對話方塊中顯示的表格會列出所有符合資格的目標Volume。

. 使用滑桿來設定複製Volume作業的複本優先順序。
+
複本優先順序會決定與服務I/O要求相比、用於完成複製Volume作業的系統資源數量。

+
.深入瞭解複本優先順序率
[%collapsible]
====
複本優先順序有五種：

** 最低
** 低
** 中
** 高
** 最高


如果將複本優先順序設定為最低速度、則會優先處理I/O活動、而且複製Volume作業所需的時間較長。如果複本優先順序設定為最高速度、則複本磁碟區作業會優先處理、但儲存陣列的I/O活動可能會受到影響。

====
. 選取要建立線上複本或離線複本。若要建立線上複本、請選取「在複製作業期間*保持來源磁碟區上線」核取方塊。
. 執行下列其中一項：
+
** 若要執行_onle_複製作業、請按一下*「下一步*」以繼續「*保留容量*」對話方塊。
** 若要執行_offline複製作業、請按一下* Finish（完成）*以啟動離線複本。


. 如果您選擇建立線上複本、請設定儲存線上複本資料及其他資訊所需的保留容量、然後按一下*完成*開始線上複本。
+
Volume候選資料表僅顯示支援指定保留容量的候選資料。保留容量是指用於任何複製服務作業和儲存物件的實體配置容量。主機無法直接讀取。

+
使用下列準則來分配保留容量：

+
** 保留容量的預設設定為基礎磁碟區容量的40%、通常此容量已足夠。
** 不過、保留容量會因原始資料的變更次數而有所不同。儲存物件作用時間越長、保留容量就越大。




.結果
System Manager會將所有資料從來源磁碟區複製到目標磁碟區。複製Volume作業完成後、目標Volume會自動成為主機的唯讀磁碟區。

.完成後
選取功能表：首頁[檢視進行中的作業]以檢視複製Volume作業的進度。這項作業可能會耗費大量時間、並可能影響系統效能。
