---
permalink: sm-storage/create-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, consistency group 
summary: 為了確保複本一致、您可以建立一組多個磁碟區、稱為快照一致性群組。 
---
= 建立Snapshot一致性群組
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了確保複本一致、您可以建立一組稱為「_snapshot consistency group」的多個磁碟區。

此群組可讓您同時建立所有磁碟區的快照映像、以確保一致性。屬於快照一致性群組的每個磁碟區都稱為_member Volume _。當您將磁碟區新增至快照一致性群組時、系統會自動建立與此成員磁碟區相對應的新快照群組。

.關於這項工作
快照一致性群組建立順序可讓您為群組選取成員磁碟區、並將容量分配給成員磁碟區。

建立快照一致性群組的程序是多步驟程序。



== 步驟1：新增成員至Snapshot一致性群組

選取成員以指定組成快照一致性群組的磁碟區集合。您在快照一致性群組上執行的任何動作、都會統一延伸至所選的成員磁碟區。

.開始之前
成員磁碟區必須處於最佳狀態。

.步驟
. 選取功能表：Storage[快照]。
. 單擊* Snapshot Consistency Group*（*快照一致性組*）選
. 選取功能表：Create [Snapshot Consistency group（建立[ Snapshot一致性群組]）
+
此時將出現Create Snapshot Consistency Group（創建Snapshot一致性組）對話框。

. 選取要新增為成員磁碟區的磁碟區至快照一致性群組。
. 按一下*下一步*、然後前往 <<步驟2：保留快照一致性群組的容量>>。




== 步驟2：保留快照一致性群組的容量

將保留容量與快照一致性群組建立關聯。System Manager會根據快照一致性群組的內容來建議磁碟區和容量。您可以接受建議的保留容量組態、或自訂已配置的儲存設備。

.關於這項工作
在「保留容量」對話方塊中、Volume候選資料表僅顯示支援指定保留容量的候選資料。保留容量是指用於任何複製服務作業和儲存物件的實體配置容量。主機無法直接讀取。

.步驟
. 使用spinner方塊來分配快照一致性群組的保留容量。請執行下列其中一項動作：
+
** *接受預設設定*。
+
使用此建議選項、以預設設定為每個成員磁碟區分配保留容量。

** *配置您自己的保留容量設定、以滿足您的資料儲存需求。*
+
使用下列準則來分配保留容量。

+
*** 保留容量的預設設定為基礎Volume容量的40%。通常這種容量是足夠的。
*** 所需容量會因磁碟區I/O寫入的頻率和大小、以及快照映像集合的數量和持續時間而有所不同。




. *選用：*如果您變更預設的保留容量設定、請按一下*重新整理候選項目*、以重新整理您所指定保留容量的候選清單。
. 按一下*下一步*、然後前往 <<步驟3：編輯快照一致性群組的設定>>。




== 步驟3：編輯快照一致性群組的設定

接受或選擇快照一致性群組的自動刪除設定和保留容量警示臨界值。

.關於這項工作
快照一致性群組建立順序可讓您為群組選取成員磁碟區、並將容量分配給成員磁碟區。

.步驟
. 視需要接受或變更快照一致性群組的預設設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
* Snapshot一致性群組設定*



 a| 
名稱
 a| 
指定快照一致性群組的名稱。



 a| 
在下列情況下啟用自動刪除快照映像：
 a| 
如果您想要在指定限制之後自動刪除快照影像、請保持核取方塊的選取狀態；請使用「微調」方塊來變更限制。如果清除此核取方塊、快照映像建立會在32個映像之後停止。



 a| 
*保留容量設定*



 a| 
提醒我...
 a| 
當快照一致性群組的保留容量即將滿時、請使用微調方塊來調整系統傳送警示通知的百分比點。

當快照一致性群組的保留容量超過指定臨界值時、請使用預先通知來增加保留容量、或在剩餘空間用盡之前刪除不必要的物件。



 a| 
完整保留容量的原則
 a| 
請選擇下列其中一項原則：

** *清除最舊的快照映像*：系統會自動清除快照一致性群組中最舊的快照映像、以釋放快照映像保留容量供群組內重複使用。
** *拒絕寫入基本磁碟區*-當保留容量達到其定義的最大百分比時、系統會拒絕任何I/O寫入要求、以觸發保留容量存取。


|===
====
. 對快照一致性群組組組態感到滿意之後、請按一下*完成*。

