---
permalink: sm-storage/create-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volume, group 
summary: 您可以使用Volume群組來建立一或多個可供主機存取的磁碟區。Volume群組是一個容器、用於具有RAID層級和容量等共享特性的磁碟區。 
---
= 建立Volume群組
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Volume群組來建立一或多個可供主機存取的磁碟區。Volume群組是一個容器、用於具有RAID層級和容量等共享特性的磁碟區。

由於磁碟容量較大、而且能夠跨控制器分散磁碟區、因此每個磁碟區群組建立一個以上的磁碟區、是充分利用儲存容量及保護資料的好方法。

在建立Volume群組之前、請先檢閱以下準則：

* 您至少需要一個未指派的磁碟機。
* 單一磁碟區群組中的磁碟機數量有限制。這些限制會因RAID層級而異。
* 若要啟用機櫃/藥櫃遺失保護、您必須建立一個磁碟區群組、使用位於至少三個磁碟櫃或藥櫃中的磁碟機、除非您使用的是RAID 1、其中兩個磁碟櫃/藥櫃為最小值。
* 如果您有EF600或EF300儲存陣列、而且打算手動建立磁碟區群組、請確定每個控制器都能存取前12個插槽中的相同磁碟機數量、以及最後12個插槽中的相同磁碟機數量。此組態可協助控制器更有效地使用兩個磁碟機端PCIe匯流排。目前系統管理員可在建立磁碟區群組時、在「進階」功能下選取磁碟機。
* 檢閱您選擇的RAID層級如何影響Volume群組的最終容量：
+
** 如果您選取RAID 1、則必須一次新增兩個磁碟機、以確保已選取鏡射配對。選取四個以上的磁碟機時、即可實現鏡射和分段（稱為RAID 10或RAID 1+0）。
** 如果您選取RAID 5、則必須至少新增三個磁碟機才能建立Volume群組。
** 如果您選取RAID 6、則必須至少新增五個磁碟機才能建立Volume群組。




.步驟
. 選取功能表：Storage[集區與Volume群組]。
. 按一下功能表：「Create [Volume group（建立[ Volume群組]）
+
此時將出現Create Volume Group（創建Volume組）對話框。

. 輸入Volume群組的名稱。
. 選擇最符合您資料儲存與保護需求的RAID層級。
+
Volume群組候選資料表隨即出現、並僅顯示支援所選RAID層級的候選資料。

. *選用：*如果您的儲存陣列中有多種磁碟機類型、請選取您要使用的磁碟機類型。
+
Volume群組候選資料表隨即出現、並僅顯示支援所選磁碟機類型和RAID層級的候選資料。

. *選用：*您可以選擇自動方法或手動方法、以定義要在Volume群組中使用的磁碟機。自動方法為預設選項。
+
若要手動選取磁碟機、請按一下*手動選取磁碟機（進階）*連結。按一下時、它會變更為*自動選取磁碟機（進階）*。

+
「手動」方法可讓您選取組成磁碟區群組的特定磁碟機。您可以選取特定的未指派磁碟機、以取得所需的容量。如果儲存陣列包含具有不同媒體類型或不同介面類型的磁碟機、您只能選擇單一磁碟機類型的未設定容量、以建立新的Volume群組。

+
[NOTE]
====
只有瞭解磁碟機備援和最佳磁碟機組態的專家、才應使用手動方法。

====
. 根據顯示的磁碟機特性、選取您要在磁碟區群組中使用的磁碟機、然後按一下*「Create」（建立）*。
+
顯示的磁碟機特性取決於您選擇的是自動方法或手動方法。

+
.自動方法磁碟機特性
====
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
可用容量
 a| 
顯示GiB的可用容量。選擇容量符合應用程式儲存需求的Volume群組候選對象。



 a| 
磁碟機總數
 a| 
顯示此磁碟區群組可用的磁碟機數量。選取一個磁碟區群組候選磁碟機數量。



 a| 
磁碟區塊大小（僅限EF300和EF600）
 a| 
顯示群組中磁碟機可以寫入的區塊大小（磁區大小）。價值可能包括：

** 512 - 512位元組區段大小。
** 4K - 4、096位元組區大小。




 a| 
安全功能
 a| 
指出此磁碟區群組候選磁碟機是否完全由具備安全功能的磁碟機組成、磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。

** 您可以使用磁碟機安全性來保護磁碟區群組、但所有磁碟機都必須具備安全功能才能使用此功能。
** 如果您要建立僅FDE磁碟區群組、請在「Secure Capable（安全功能）」欄中尋找* Yes - FDE*。如果您要建立僅限FIPS的Volume群組、請在「Secure Capable（安全功能）」欄中尋找* Yes - FIPS-*。
** 您可以建立由磁碟機組成的磁碟區群組、這些磁碟機可能具有安全功能、也可能不具備安全功能、或是混合了安全性層級。如果磁碟區群組中的磁碟機包含不安全的磁碟機、則無法保護磁碟區群組的安全。




 a| 
啟用安全性？
 a| 
提供選項、讓磁碟機安全功能可與安全的磁碟機搭配使用。如果磁碟區群組具備安全功能、而且您已設定安全金鑰、則可選取核取方塊來啟用磁碟機安全性。


NOTE: 啟用磁碟機安全性之後、唯一的方法是刪除磁碟區群組並清除磁碟機。



 a| 
DA能力
 a| 
表示此群組是否可使用資料保證（DA）。資料保證（DA）會檢查並修正資料經由控制器向下傳輸至磁碟機時可能發生的錯誤。

如果您要使用DA、請選取具有DA功能的Volume群組。（對於具有DA功能的磁碟機、系統會自動在集區中建立的磁碟區上啟用DA。）

磁碟區群組可包含具有DA功能或不具備DA功能的磁碟機、但所有磁碟機都必須具備DA功能、才能使用此功能。



 a| 
資源資源配置功能（僅限EF300和EF600）
 a| 
顯示資源資源配置是否可供此群組使用。資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。



 a| 
機櫃損失保護
 a| 
顯示機櫃遺失保護是否可用。機櫃遺失保護功能可確保在磁碟區群組中的磁碟區資料能夠在發生與機櫃通訊完全中斷時存取。



 a| 
藥櫃遺失保護
 a| 
顯示藥櫃遺失保護功能是否可用、僅當您使用含有藥櫃的磁碟機櫃時才會提供此功能。如果磁碟櫃中的單一藥櫃發生通訊完全中斷、藥櫃遺失保護可確保磁碟區群組中磁碟區上的資料可存取。



 a| 
支援的Volume區塊大小（僅限EF300和EF600）
 a| 
顯示可為群組中的磁碟區建立的區塊大小：

** 512n -原生512位元組。
** 512e -模擬512位元組。
** 4K - 4、096位元組。


|===
====
+
.手動方法磁碟機特性
====
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
媒體類型
 a| 
表示媒體類型。支援下列媒體類型：

** 硬碟機
** 固態磁碟（SSD）


磁碟區群組中的所有磁碟機必須為相同的媒體類型（所有SSD或所有硬碟機）。Volume群組不能混用各種媒體類型或介面類型。



 a| 
磁碟區塊大小（僅限EF300和EF600）
 a| 
顯示群組中磁碟機可以寫入的區塊大小（磁區大小）。價值可能包括：

** 512 - 512位元組區段大小。
** 4K - 4、096位元組區大小。




 a| 
磁碟機容量
 a| 
表示磁碟機容量。

** 如果可能、請選取容量等於Volume群組中目前磁碟機容量的磁碟機。
** 如果您必須新增容量較小的未指派磁碟機、請注意、Volume群組中目前每個磁碟機的可用容量都會減少。因此、磁碟機容量在整個磁碟區群組中是相同的。
** 如果您必須新增容量較大的未指派磁碟機、請注意、您新增的未指派磁碟機的可用容量會減少、以便符合磁碟區群組中磁碟機的目前容量。




 a| 
匣
 a| 
表示磁碟機的匣位置。



 a| 
插槽
 a| 
表示磁碟機的插槽位置。



 a| 
速度（rpm）
 a| 
表示磁碟機的速度。



 a| 
邏輯區段大小
 a| 
指出區段大小和格式。



 a| 
安全功能
 a| 
指出此磁碟區群組候選磁碟機是否完全由具備安全功能的磁碟機組成、磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。

** 您可以使用磁碟機安全性來保護磁碟區群組、但所有磁碟機都必須具備安全功能才能使用此功能。
** 如果您要建立僅FDE磁碟區群組、請在「Secure Capable（安全功能）」欄中尋找* Yes - FDE*。如果您要建立僅限FIPS的Volume群組、請在「Secure Capable（安全功能）」欄中尋找* Yes - FIPS-*。
** 您可以建立由磁碟機組成的磁碟區群組、這些磁碟機可能具有安全功能、也可能不具備安全功能、或是混合了安全性層級。如果磁碟區群組中的磁碟機包含不安全的磁碟機、則無法保護磁碟區群組的安全。




 a| 
DA能力
 a| 
表示此群組是否可使用資料保證（DA）。資料保證（DA）會檢查並修正資料經由控制器向下傳輸至磁碟機時可能發生的錯誤。

如果您要使用DA、請選取具有DA功能的Volume群組。（對於具有DA功能的磁碟機、系統會自動在集區中建立的磁碟區上啟用DA。）

磁碟區群組可包含具有DA功能或不具備DA功能的磁碟機、但所有磁碟機都必須具備DA功能、才能使用此功能。



 a| 
支援的Volume區塊大小（僅限EF300和EF600）
 a| 
顯示可為群組中的磁碟區建立的區塊大小：

** 512n -原生512位元組。
** 512e -模擬512位元組。
** 4K - 4、096位元組。




 a| 
資源資源配置功能（僅限EF300和EF600）
 a| 
顯示資源資源配置是否可供此群組使用。資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。

|===
====

