---
permalink: sm-storage/create-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, volume 
summary: 您可以建立快照磁碟區、讓主機存取磁碟區或快照一致性群組的快照映像。您可以將快照磁碟區指定為唯讀或讀寫。 
---
= 建立Snapshot Volume
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立快照磁碟區、讓主機存取磁碟區或快照一致性群組的快照映像。您可以將快照磁碟區指定為唯讀或讀寫。

.關於這項工作
快照磁碟區建立順序可讓您從快照映像建立快照磁碟區、並在磁碟區為讀取/寫入時提供分配保留容量的選項。快照磁碟區可指定為下列其中一項：

* 唯讀快照磁碟區可讓主機應用程式讀取快照映像所含資料的複本、但無法修改快照映像。唯讀快照磁碟區沒有相關的保留容量。
* 讀寫快照磁碟區可讓主機應用程式對快照映像中所含資料的複本擁有寫入存取權。它有自己的保留容量、可用來將主機應用程式後續所做的任何修改儲存到基礎磁碟區、而不會影響參考的快照映像。


建立快照磁碟區的程序有多個步驟。



== 步驟1：檢視快照磁碟區的成員

選取基礎磁碟區的快照映像或快照一致性群組。如果您選取快照一致性群組快照映像、快照一致性群組的成員磁碟區就會出現以供檢閱。

.步驟
. 選取功能表：Storage[快照]。
. 選擇* Snapshot Volumes（快照卷）*選項卡。
. 選擇* Create *（建立*）。
+
此時將出現Create Snapshot Volume（創建Snapshot Volume）對話框。

. 選取您要轉換成快照磁碟區的快照映像（磁碟區或快照一致性群組）、然後按一下*「Next*（下一步*）」。使用*篩選*欄位中的文字項目來縮小清單範圍。
+
如果選取的是快照一致性群組快照映像、則會出現「Review Members（檢視成員）」對話方塊。

+
在「Review Members（檢閱成員）」對話方塊中、檢閱已選取要轉換為快照磁碟區的磁碟區清單、然後按一下「* Next*（*下一步*）」。

. 前往 <<步驟2：將Snapshot Volume指派給主機>>。




== 步驟2：將Snapshot Volume指派給主機

選取特定的主機或主機叢集、將其指派給快照磁碟區。這項指派可讓主機或主機叢集存取快照Volume。如果需要、您可以選擇稍後指派主機。

.開始之前
* 有效的主機或主機叢集存在於「hosts」頁面下方。
* 必須已為主機定義主機連接埠識別碼。
* 在建立啟用DA的磁碟區之前、請確認您規劃的主機連線是否支援Data Assurance（DA）功能。如果儲存陣列中控制器上的任何主機連線不支援DA、則相關主機無法存取啟用DA的磁碟區上的資料。


.關於這項工作
指派磁碟區時、請謹記以下準則：

* 主機的作業系統可以對主機可存取的磁碟區數量有特定限制。
* 您可以為儲存陣列中的每個快照磁碟區定義一個主機指派。
* 指派的磁碟區會在儲存陣列的控制器之間共用。
* 主機或主機叢集無法使用相同的邏輯單元編號（LUN）兩次來存取快照Volume。您必須使用唯一的LUN。


[NOTE]
====
如果您嘗試將磁碟區指派給主機叢集、而該磁碟區與已建立的主機叢集指派衝突、則將磁碟區指派給主機時、將會失敗。

====
.步驟
. 在*指派給主機*對話方塊中、選取您要指派給新磁碟區的主機或主機叢集。如果您想在不指派主機的情況下建立磁碟區、請從下拉式清單中選取*稍後指派*。
. 選取存取模式。請選擇下列其中一項：
+
** *讀取/寫入*-此選項可讓主機存取快照磁碟區的讀取/寫入權限、並需要保留容量。
** *唯讀*-此選項可讓主機以唯讀方式存取快照磁碟區、而且不需要保留容量。


. 按一下「*下一步*」、然後執行下列其中一項：
+
** 如果您的快照磁碟區是讀取/寫入、則會出現「Review Capacity（檢閱容量）」對話方塊。前往 <<步驟3：保留快照磁碟區的容量>>。
** 如果您的快照Volume為唯讀、則會出現「編輯優先順序」對話方塊。前往 <<步驟4：編輯快照磁碟區的設定>>。






== 步驟3：保留快照磁碟區的容量

將保留容量與讀寫快照磁碟區建立關聯。System Manager會根據基礎磁碟區或快照一致性群組的內容、建議磁碟區和容量。您可以接受建議的保留容量組態、或自訂已配置的儲存設備。

.關於這項工作
您可以視需要增加或減少快照磁碟區的保留容量。如果您發現快照保留容量大於您所需的容量、您可以減少快照的大小、以釋放其他邏輯磁碟區所需的空間。

.步驟
. 使用spinner方塊來分配快照磁碟區的保留容量。
+
Volume候選人表格僅顯示支援指定保留容量的候選對象。

+
請執行下列其中一項動作：

+
** *接受預設設定*。
+
使用此建議選項、以預設設定分配快照磁碟區的保留容量。

** *配置您自己的保留容量設定、以滿足您的資料儲存需求*。
+
如果您變更預設的保留容量設定、請按一下*重新整理候選項目*、針對您指定的保留容量重新整理候選清單。

+
使用下列準則來分配保留容量。

+
*** 保留容量的預設設定為基礎磁碟區容量的40%、通常此容量已足夠。
*** 所需容量會因磁碟區I/O寫入的頻率和大小、以及快照映像集合的數量和持續時間而有所不同。




. *選用：*如果您要為快照一致性群組建立快照磁碟區、「Change候選人」選項會出現在「保留容量候選」表格中。按一下*變更候選對象*以選取備用的保留容量候選對象。
. 按一下*下一步*、然後前往 <<步驟4：編輯快照磁碟區的設定>>。




== 步驟4：編輯快照磁碟區的設定

變更快照磁碟區的設定、例如其名稱、快取、保留容量警示臨界值等。

.關於這項工作
您可以將磁碟區新增至固態磁碟（SSD）快取、以提升唯讀效能。SSD快取由一組SSD磁碟機組成、您可以在儲存陣列中以邏輯方式將這些磁碟機組成群組。

.步驟
. 視需要接受或變更快照磁碟區的設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
* Snapshot Volume設定*



 a| 
名稱
 a| 
指定快照磁碟區的名稱。



 a| 
啟用SSD快取
 a| 
選擇此選項可在SSD上啟用唯讀快取。



 a| 
*保留容量設定*



 a| 
提醒我...
 a| 
*僅在讀寫快照磁碟區*中顯示。

當快照群組的保留容量即將滿時、使用微調方塊來調整系統傳送警示通知的百分比點。

當快照群組的保留容量超過指定臨界值時、請使用預先通知來增加保留容量、或在剩餘空間用盡之前刪除不必要的物件。

|===
====
. 檢閱Snapshot Volume組態。按一下*上一步*進行任何變更。
. 當您對快照磁碟區組態感到滿意時、請按一下*完成*。

