---
permalink: sm-storage/create-workloads.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, workloads 
summary: 您可以為任何類型的應用程式建立工作負載。 
---
= 建立工作負載
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以為任何類型的應用程式建立工作負載。

.關於這項工作
工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

System Manager僅針對下列應用程式類型建議最佳化Volume組態：

* Microsoft®SQL Server™
* Microsoft®Exchange Server™
* 視訊監控
* VMware ESXi™（適用於與虛擬機器檔案系統搭配使用的磁碟區）


請謹記以下準則：

* _使用應用程式專屬的工作負載_時、系統建議使用最佳化的Volume組態、以將應用程式工作負載I/O與應用程式執行個體的其他流量之間的爭用降至最低。您可以檢閱建議的磁碟區組態、然後使用「新增/編輯磁碟區」對話方塊來編輯、新增或刪除系統建議的磁碟區和特性。
* _使用其他應用程式類型_時、您可以使用「新增/編輯磁碟區」對話方塊手動指定磁碟區組態。


.步驟
. 選取功能表：Storage[磁碟區]。
. 選取功能表：Create [Workload。
+
此時會出現Create Application Workload對話方塊。

. 使用下拉式清單選取您要建立工作負載的應用程式類型、然後輸入工作負載名稱。
. 按一下「 * 建立 * 」。


.完成後
您已準備好將儲存容量新增至所建立的工作負載。使用* Create Volume*（建立磁碟區）選項可為應用程式建立一或多個磁碟區、並將特定容量分配給每個磁碟區。
