---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: 您可以在現有的資源池或Volume群組上啟用或停用資源資源配置。 
---
= 在 SANtricity System Manager 中啟用或停用現有磁碟區組和池的資源配置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於任何具有DULBE功能的磁碟機、您可以在資源池或磁碟區群組中的現有磁碟區上啟用或停用資源資源配置。

資源預置是 EF80、EF50、EF300/EF300C 和 EF600/EF600C 儲存陣列的功能，它允許磁碟區立即投入使用，無需後台初始化過程。分配給該磁碟區的所有磁碟機區塊都將被釋放（取消映射），這可以延長 SSD 的使用壽命並提高最大寫入效能。

根據預設、磁碟機支援DULBE的系統會啟用資源配置。除非您先前已停用資源資源配置、否則不需要啟用資源配置。

.開始之前
* 您必須擁有 EF80 、 EF50 、 EF300 或 EF600 儲存陣列。
* 您必須擁有SSD磁碟區群組或集區、其中所有磁碟機都支援NVMe取消分配或未寫入的邏輯區塊錯誤啟用（DULBE）錯誤恢復功能。否則、資源資源配置選項將無法使用。


.關於這項工作
當您為現有的Volume群組和集區啟用資源資源配置時、所選Volume群組或集區中的所有Volume都會變更、以允許取消分配區塊。此程序可能需要背景作業、以確保以不對應的精細度進行一致的分配。此作業不會取消對應任何空間。背景作業完成後、作業系統必須取消對應任何未使用的區塊、才能建立可用空間。

當您停用現有磁碟區群組或集區的資源配置時、背景作業會重新寫入每個磁碟區中的所有邏輯區塊。現有資料保持不變。寫入作業會對應或配置磁碟區群組或集區相關磁碟機上的區塊。


NOTE: 對於新的Volume群組和資源池、您可以從功能表：設定[系統>其他設定>啟用/停用資源資源配置的磁碟區]啟用或停用資源配置。

.步驟
. 從左側面板中選擇功能表：Storage[Pools and volume groups]。
. 按一下 *ellipsis* 圖示，然後針對所選的資源池或磁碟區群組選取 *Enable resource provisioning* 或 *Disable resource provisioning* 。
. 在對話方塊中、確認操作。



NOTE: *如果您重新啟用DULBE*-在背景作業完成之後、您可能需要重新啟動主機、使其偵測DULBE組態變更、然後重新掛載所有檔案系統。
