---
permalink: sm-storage/faq-storage-drives.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 儲存磁碟機常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 什麼是熱備援磁碟機？

熱備援磁碟機在RAID 1、RAID 5或RAID 6磁碟區群組中扮演待命磁碟機的角色。它們是功能完整的磁碟機、不含任何資料。如果磁碟機在Volume群組中故障、控制器會自動將故障磁碟機的資料重新建構至熱備援磁碟機。

如果儲存陣列中的磁碟機故障、則熱備援磁碟機將自動取代故障磁碟機、而不需要實體交換。如果熱備援磁碟機在磁碟機故障時可用、則控制器會使用備援資料、將故障磁碟機的資料重新建構至熱備援磁碟機。

熱備援磁碟機並非專供特定磁碟區群組使用。相反地、您可以使用熱備援磁碟機來處理儲存陣列中任何容量相同或容量較小的故障磁碟機。熱備援磁碟機的媒體類型（HDD或SSD）必須與其保護的磁碟機相同。

[NOTE]
====
集區不支援熱備援磁碟機。集區不使用熱備援磁碟機、而是使用組成集區的每個磁碟機內的保留容量。

====


== 什麼是保留容量？

保留容量是指為支援潛在磁碟機故障而保留在集區中的容量（磁碟機數量）。

建立集區時、系統會根據集區中的磁碟機數量、自動保留預設的保留容量。

資源池會在重建期間使用保留容量、而磁碟區群組則會將熱備援磁碟機用於相同用途。保留容量方法是比熱備援磁碟機更好的方法、因為它可讓重建作業更快完成。保留容量會分散在集區中的多個磁碟機上、而非熱備援磁碟機上的一個磁碟機、因此您不會受限於單一磁碟機的速度或可用度。



== 為什麼我要邏輯地更換磁碟機？

如果某個磁碟機故障、或是您因為其他原因而想要更換它、而且您的儲存陣列中有未指派的磁碟機、您可以邏輯地將故障磁碟機更換為未指派的磁碟機。如果您沒有未指派的磁碟機、您可以更換磁碟機。

原始磁碟機的資料會複製或重建到替換磁碟機。



== 何處可以檢視正在進行重建的磁碟機狀態？

您可以從「作業進行中」儀表板檢視磁碟機重建狀態。

在首頁中、按一下右上角的*「View Operations in progress*（檢視進行中的作業*）」連結。

視磁碟機而定、完整重建可能需要相當長的時間。如果磁碟區擁有權有所變更、可能會進行完整重建、而非快速重建。
