---
permalink: sm-storage/faq-snapshots.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 快照常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 為什麼我看不到所有磁碟區、主機或主機叢集？

具有啟用DA基礎磁碟區的Snapshot Volume不符合指派給不具備Data Assurance（DA）功能的主機的資格。您必須先停用基礎磁碟區上的DA、才能將快照磁碟區指派給不具備DA功能的主機。

請針對您要指派快照磁碟區的主機、考慮下列準則：

* 如果主機透過不支援DA的I/O介面連接至儲存陣列、則該主機將無法執行DA功能。
* 如果主機叢集至少有一個主機成員不具備DA功能、則該主機叢集無法執行DA功能。


[NOTE]
====
您無法在與快照（一致性群組、快照群組、快照映像和快照磁碟區）、磁碟區複本、 和鏡射。必須先刪除所有相關的保留容量和快照物件、才能在基礎磁碟區上停用DA。

====


== 什麼是快照映像？

Snapshot映像是在特定時間點擷取的Volume內容邏輯複本。Snapshot映像使用最小的儲存空間。

Snapshot映像資料儲存方式如下：

* 建立快照映像時、會完全符合基礎磁碟區。快照完成後、當基礎磁碟區上的任何區塊或區塊集發生第一次寫入要求時、原始資料會複製到快照保留容量、然後再將新資料寫入基礎磁碟區。
* 後續的快照僅包含自建立第一個快照映像以來已變更的資料區塊。後續的寫入時複製作業會將基礎磁碟區上即將覆寫的原始資料、儲存至快照保留容量、然後再將新資料寫入基礎磁碟區。




== 為何要使用快照映像？

您可以使用快照來保護資料、避免意外或惡意遺失或毀損。

選取稱為Snapshot一致性群組的基礎磁碟區或一組基礎磁碟區、然後以下列一種或多種方式擷取快照映像：

* 您可以建立單一基礎磁碟區的快照映像、或是由多個基礎磁碟區所組成的快照一致性群組。
* 您可以手動拍攝快照、或為基礎磁碟區或快照一致性群組建立排程、以自動擷取定期快照映像。
* 您可以建立快照映像的主機存取快照磁碟區。
* 您可以執行復原作業來還原快照映像。


系統會將多個快照映像保留為還原點、您可以在特定時間點將其復原至已知的良好資料集。回溯功能可防止資料意外刪除及資料毀損。



== 快照可使用哪些類型的磁碟區？

標準磁碟區和精簡磁碟區是唯一可用於儲存快照映像的磁碟區類型。無法使用非標準磁碟區。基礎磁碟區可位於集區或磁碟區群組上。



== 為什麼要建立Snapshot一致性群組？

您可以建立快照一致性群組、以確保快照映像同時在多個磁碟區上擷取。

例如、由多個磁碟區所組成的資料庫、如果需要維持一致的恢復目的、則需要快照一致性群組來收集所有磁碟區的協調快照、並使用它們來還原整個資料庫。

快照一致性群組中包含的磁碟區稱為「成員磁碟區」。

您可以在快照一致性群組上執行下列快照作業：

* 建立快照一致性群組的快照映像、以取得成員磁碟區的同步映像。
* 建立快照一致性群組的排程、以自動擷取成員磁碟區的定期同步映像。
* 建立快照一致性群組映像的主機存取快照磁碟區。
* 針對快照一致性群組執行復原作業。




== 什麼是Snapshot Volume？何時需要保留容量？

Snapshot Volume可讓主機存取快照映像中的資料。快照磁碟區包含自己的保留容量、可儲存對基礎磁碟區所做的任何修改、而不會影響原始的快照映像。主機無法讀取或寫入Snapshot映像。如果您要讀取或寫入快照資料、請建立快照磁碟區並將其指派給主機。

您可以建立兩種類型的快照磁碟區。快照磁碟區的類型會決定它是否使用保留容量。

* *唯讀*：以唯讀方式建立的快照磁碟區、可讓主機應用程式讀取快照映像中所含資料的複本。唯讀快照磁碟區不會使用保留容量。
* *讀寫*：以讀寫方式建立的快照磁碟區、可讓您變更快照磁碟區、而不會影響參考的快照映像。讀寫快照磁碟區會使用保留容量來儲存這些變更。您可以隨時將唯讀快照磁碟區轉換為讀寫。




== 什麼是快照群組？

Snapshot群組是單一關聯基礎Volume的時間點快照映像集合。

System Manager會將快照映像整理成_snapshot Groups_。Snapshot群組不需要使用者動作、但您可以隨時調整快照群組的保留容量。此外、當符合下列條件時、系統可能會提示您建立保留容量：

* 只要您對尚未建立快照群組的基礎磁碟區建立快照、System Manager就會自動建立快照群組。這會為用於儲存後續快照映像的基礎磁碟區建立保留容量。
* 每當您為基礎磁碟區建立快照排程時、System Manager都會自動建立快照群組。




== 為什麼要停用快照磁碟區？

當您想要將不同的快照磁碟區指派給快照映像時、請停用快照磁碟區。您可以保留停用的快照磁碟區供日後使用。

如果您不再需要快照磁碟區或一致性群組快照磁碟區、而不打算稍後重新建立、則應刪除該磁碟區、而非停用該磁碟區。



== 「停用」狀態為何？

處於「已停用」狀態的快照磁碟區目前未指派給快照映像。若要啟用快照磁碟區、您必須使用重新建立作業、將新的快照映像指派給停用的快照磁碟區。

快照磁碟區特性是由指派給它的快照映像所定義。在處於「已停用」狀態的快照磁碟區上、讀寫活動會暫停。



== 為什麼要暫停快照排程？

當排程暫停時、不會建立排程的快照映像。您可以暫停快照排程以節省儲存空間、然後稍後再繼續排程的快照。

如果您不需要快照排程、則應刪除排程、而非暫停排程。
