---
permalink: sm-storage/faq-storage-array-settings.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 的儲存陣列設定常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 什麼是自動負載平衡？

「自動負載平衡」功能可提供自動化I/O平衡、確保來自主機的傳入I/O流量能在兩個控制器之間動態管理和平衡。

「自動負載平衡」功能可動態回應一段時間內的負載變更、並自動調整Volume控制器擁有權、以修正工作負載在控制器之間移轉時發生的任何負載不平衡問題、進而改善I/O資源管理。

每個控制器的工作負載都會持續受到監控、並可在主機上安裝多重路徑驅動程式的協助下、在必要時自動取得平衡。當工作負載在各個控制器之間自動重新平衡時、儲存管理員可免除手動調整Volume控制器所有權以因應儲存陣列負載變更的負擔。

啟用「自動負載平衡」時、會執行下列功能：

* 自動監控及平衡控制器資源使用率。
* 視需要自動調整Volume控制器擁有權、藉此最佳化主機與儲存陣列之間的I/O頻寬。


[NOTE]
====
指派使用控制器SSD快取的任何Volume均不符合自動負載平衡傳輸的資格。

====


== 什麼是控制器快取？

控制器快取是一種實體記憶體空間、可簡化兩種類型的I/O（輸入/輸出）作業：控制器與主機之間、控制器與磁碟之間。

對於讀寫資料傳輸、主機和控制器會透過高速連線進行通訊。但是、從控制器後端到磁碟的通訊速度較慢、因為磁碟是相對較慢的裝置。

當控制器快取接收資料時、控制器會向主機應用程式確認它目前正在保留資料。如此一來、主機應用程式就不需要等待I/O寫入磁碟。而是應用程式可以繼續作業。伺服器應用程式也能輕鬆存取快取的資料、不需要額外的磁碟讀取來存取資料。

控制器快取會以多種方式影響儲存陣列的整體效能：

* 快取會做為緩衝區、因此不需要同步處理主機和磁碟資料傳輸。
* 從主機進行讀取或寫入作業的資料可能位於先前作業的快取中、因此不需要存取磁碟。
* 如果使用寫入快取、則主機可以在將先前寫入作業的資料寫入磁碟之前、先傳送後續的寫入命令。
* 如果啟用快取預先擷取、則會最佳化循序讀取存取。快取預先擷取可讓讀取作業更容易在快取中找到資料、而非從磁碟讀取資料。


[CAUTION]
====
*可能的資料遺失*-如果您啟用*無電池寫入快取*選項、而且沒有通用電源供應器來保護資料、您可能會遺失資料。此外、如果您沒有控制器電池、並且啟用*無電池寫入快取*選項、則可能會遺失資料。

====


== 什麼是快取排清？

當快取中的未寫入資料量達到特定層級時、控制器會定期將快取資料寫入磁碟機。此寫入程序稱為「排清」。

控制器使用兩種演算法來排清快取：需求型與年齡型。控制器使用需求型演算法、直到快取資料量降至快取清除臨界值以下為止。根據預設、當80%的快取正在使用時、就會開始排清。

在System Manager中、您可以設定「開始需求快取排清」臨界值、以最佳方式支援環境中使用的I/O類型。在主要是寫入作業的環境中、您應該將「開始需求快取排清」百分比設定為高、以增加快取處理任何新寫入要求的可能性、而不需要移至磁碟。高百分比的設定會限制快取的清除次數、使快取中保留更多資料、進而增加快取命中次數的機率。

在I/O不穩定的環境中（使用資料突發）、您可以使用低快取排清功能、讓系統在資料突發之間頻繁排清快取。在處理各種負載的多元I/O環境中、或是當負載類型不明時、將臨界值設為良好的中間接地、設定為50%。請注意、如果您選擇低於80%的開始百分比、可能會看到效能降低、因為讀取主機所需的資料可能無法使用。選擇較低的百分比也會增加維護快取層級所需的磁碟寫入次數、進而增加系統負荷。

根據年齡的演算法會指定寫入資料在符合排清至磁碟資格之前、保留在快取中的時間段。控制器會使用根據年齡的演算法、直到快取齊面臨界值達到為止。預設值為10秒、但此時間段僅會在閒置期間計算。您無法在System Manager中修改排清時間、而是必須在命令列介面（CLI）中使用*設定儲存陣列*命令。

[CAUTION]
====
*可能的資料遺失*-如果您啟用*無電池寫入快取*選項、而且沒有通用電源供應器來保護資料、您可能會遺失資料。此外、如果您沒有控制器電池、並且啟用*無電池寫入快取*選項、則可能會遺失資料。

====


== 什麼是快取區塊大小？

儲存陣列的控制器將其快取組織成「區塊」、這是大小可為8、16、32 KiB的記憶體區塊。儲存系統上的所有磁碟區都共用相同的快取空間、因此磁碟區只能有一個快取區塊大小。

應用程式使用不同的區塊大小、可能會影響儲存效能。根據預設、System Manager中的區塊大小為32 KiB、但您可以將值設為8、16、32 KiB。較小的尺寸是檔案系統或資料庫應用程式的理想選擇。對於需要大量資料傳輸、連續I/O或高頻寬（例如多媒體）的應用程式而言、較大的規模是理想的選擇。



== 何時應該同步儲存陣列時鐘？

如果您注意到 SANtricity 系統管理員中顯示的時間戳記與管理用戶端（透過瀏覽器存取 SANtricity 系統管理員的電腦）中顯示的時間戳記不一致，則應手動同步儲存陣列中的控制器時鐘。只有在 SANtricity 系統管理員中未啟用 NTP （網路時間傳輸協定）時，才需要執行此工作。

[NOTE]
====
我們強烈建議您使用NTP伺服器、而非手動同步時鐘。NTP會使用SNTP（簡易網路時間傳輸協定）、自動將時鐘與外部伺服器同步。

====
您可以從「系統」頁面上的「同步儲存陣列時鐘」對話方塊中、檢查同步狀態。如果對話方塊中顯示的時間不相符、請執行同步處理。您可以定期檢視此對話方塊、以指出控制器時鐘的時間顯示是否已偏離並不再同步。
