---
permalink: sm-storage/faq-systems-clusters.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 的主機系統和主機叢集常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 什麼是主機和主機叢集？

主機是一種伺服器、可將I/O傳送至儲存陣列上的磁碟區。主機叢集是一組主機。您可以建立主機叢集、以便輕鬆將相同的磁碟區指派給多個主機。

您可以分別定義主機。它可以是獨立實體、也可以新增至主機叢集。您可以將磁碟區指派給個別主機、或是主機叢集的一部或多部主機、與主機叢集中的其他主機共用一個或多個磁碟區的存取權。

主機叢集是SANtricity 您在《支援系統》中建立的邏輯實體。您必須先將主機新增至主機叢集、才能指派磁碟區。



== 為什麼我需要建立主機叢集？

如果您想要讓兩個以上的主機共用同一組磁碟區的存取權、則需要建立主機叢集。一般而言、個別主機上安裝了叢集軟體、以協調磁碟區存取。



== 如何知道哪種主機作業系統類型正確？

主機作業系統類型欄位包含主機的作業系統。您可以從下拉式清單中選取建議的主機類型。

下拉式清單中顯示的主機類型取決於儲存陣列機型和韌體版本。最新版本會先顯示最常見的選項、最可能是適當的選項。此清單上的外觀並不表示完全支援此選項。

[NOTE]
====
如需主機支援的詳細資訊、請參閱 https://imt.netapp.com/matrix/#welcome["NetApp 互通性對照表工具"^]。

====
清單中可能會出現下列部分主機類型：

[cols="35h,~"]
|===
| 主機作業系統類型 | 作業系統（OS）和多重路徑驅動程式 


 a| 
Linux DM-MP（核心3.10或更新版本）
 a| 
支援使用Device Mapper多重路徑容錯移轉解決方案搭配3.10或更新版本核心的Linux作業系統。



 a| 
VMware ESXi
 a| 
使用VMware內建的儲存陣列類型原則模組SATP_ALUA、支援執行原生多路徑外掛程式（NMP）架構的VMware ESXi作業系統。



 a| 
Windows（叢集式或非叢集式）
 a| 
支援未執行Atto多重路徑驅動程式的Windows叢集式或非叢集式組態。



 a| 
Atto叢集（所有作業系統）
 a| 
支援所有使用Atto Technology、Inc.、多重路徑驅動程式的叢集組態。



 a| 
Linux（Veritas DMP）
 a| 
使用Veritas DMP多重路徑解決方案支援Linux作業系統。



 a| 
Linux（Atto）
 a| 
支援使用Atto Technology、Inc.、多重路徑驅動程式的Linux作業系統。



 a| 
Mac OS（Atto）
 a| 
支援使用Atto Technology、Inc.、多重路徑驅動程式的Mac OS版本。



 a| 
Windows（Atto）
 a| 
支援使用Atto Technology、Inc.、多重路徑驅動程式的Windows作業系統。



 a| 
IBM服務
 a| 
支援IBM SAN Volume Controller組態。



 a| 
原廠預設值
 a| 
保留用於儲存陣列的初始啟動。如果您的主機作業系統類型設為出廠預設值、請將其變更為符合主機作業系統和連接主機上執行的多重路徑驅動程式。



 a| 
Linux DM-MP（核心3.9或更早版本）
 a| 
支援使用具備3.9或更早核心的Device Mapper多重路徑容錯移轉解決方案的Linux作業系統。



 a| 
叢集式視窗（已過時）
 a| 
如果您的主機作業系統類型設定為此值、請改用Windows（叢集式或非叢集式）設定。

|===


== 什麼是HBA和介面卡連接埠？

主機匯流排介面卡（HBA）是一種主機板、位於主機中、包含一或多個主機連接埠。主機連接埠是主機匯流排介面卡（HBA）上的連接埠、可提供與控制器的實體連線、並用於I/O作業。

HBA上的介面卡連接埠稱為主機連接埠。大多數HBA都有一個或兩個主機連接埠。HBA具有唯一的全球識別碼（WWID）、而且每個HBA主機連接埠都有唯一的WWID。當您透過 SANtricity 系統管理員手動建立主機時、主機連接埠識別碼可用來將適當的 HBA 與實體主機建立關聯。



== 如何將主機連接埠與主機配對？

如果您是手動建立主機、則必須先使用主機上可用的適當主機匯流排介面卡（HBA）公用程式、來判斷與主機中安裝的每個HBA相關聯的主機連接埠識別碼。

取得此資訊後、請從「Create Host（建立主機）」對話方塊中提供的清單中、選取已登入儲存陣列的主機連接埠識別碼。

[NOTE]
====
請務必為您要建立的主機選取適當的主機連接埠識別碼。如果您將錯誤的主機連接埠識別碼關聯起來、可能會導致無法預期地從其他主機存取此資料。

====


== 如何建立CHAP機密？

如果您在連接至儲存陣列的任何iSCSI主機上設定Challenge Handshake驗證傳輸協定（CHAP）驗證、則必須為每個iSCSI主機重新輸入該啟動器CHAP密碼。

若要這麼做、您可以將System Manager做為「建立主機」作業的一部分、或是透過「檢視/編輯設定」選項來使用。

如果您使用CHAP相互驗證、也必須在「設定」頁面中定義儲存陣列的目標CHAP機密、然後在每個iSCSI主機上重新輸入該目標CHAP機密。



== 什麼是預設叢集？

預設叢集是系統定義的實體、可讓登入儲存陣列的任何未關聯主機連接埠識別碼、存取指派給預設叢集的磁碟區。未關聯的主機連接埠識別碼是與特定主機邏輯上並未關聯的主機連接埠、而是實際安裝在主機上並登入儲存陣列。

[NOTE]
====
如果您想讓主機對儲存陣列中的特定磁碟區擁有特定存取權、則必須使用預設叢集。您必須將主機連接埠識別碼與其對應的主機建立關聯。此工作可在「建立主機」作業期間手動完成。然後、您可以將磁碟區指派給個別主機或主機叢集。

====
在外部儲存環境有助於允許所有主機和所有登入主機連接埠識別碼連線至儲存陣列的特殊情況下、您應該僅使用預設叢集（All存取模式）存取所有磁碟區。 而不讓儲存陣列或使用者介面知道主機。

一開始、您只能透過命令列介面（CLI）將磁碟區指派給預設叢集。不過、在您將至少一個Volume指派給預設叢集之後、此實體（稱為預設叢集）會顯示在使用者介面中、您可以在其中管理此實體。



== 什麼是主機連線報告？

啟用主機連線報告時、儲存陣列會持續監控控制器與已設定主機之間的連線、然後在連線中斷時發出警示。

如果纜線鬆脫、毀損或遺失、或主機發生其他問題、可能會中斷連線。在這些情況下、系統可能會開啟Recovery Guru訊息：

* *主機備援遺失*-如果任一控制器無法與主機通訊、就會開啟。
* *主機類型不正確*-如果儲存陣列上未正確指定主機類型、就會開啟、這可能會導致容錯移轉問題。


在重新啟動控制器所需時間可能超過連線逾時時間的情況下、您可能會想要停用主機連線報告功能。停用此功能會抑制「Recovery Gurus」訊息。

[NOTE]
====
停用主機連線報告也會停用自動負載平衡、以監控及平衡控制器資源使用量。不過、如果您重新啟用主機連線報告、則自動負載平衡功能不會自動重新啟用。

====