---
permalink: sm-storage/faq-volumes-workloads.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 捲和工作負載常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 什麼是Volume？

Volume是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機所建立的邏輯元件、可用來存取儲存陣列上的儲存設備。

磁碟區是從集區或磁碟區群組中可用的容量所建立。磁碟區具有已定義的容量。雖然磁碟區可能包含多個磁碟機、但磁碟區會顯示為主機的一個邏輯元件。



== 當磁碟區群組中有足夠的可用容量來建立磁碟區時、為什麼我看到容量過度配置錯誤？

選取的Volume群組可能有一個或多個可用容量區域。可用容量區域是指在建立磁碟區期間、刪除磁碟區或未使用所有可用容量所產生的可用容量。

當您在具有一或多個可用容量區域的Volume群組中建立Volume時、該Volume的容量僅限於該Volume群組中最大的可用容量區域。例如、如果某個Volume群組的可用容量總計為15 GiB、而最大的可用容量區域則為10 GiB、則您可以建立的最大磁碟區為10 GiB。

如果Volume群組有可用容量區域、則Volume群組圖表會包含一個連結、指出現有可用容量區域的數量。選取連結以顯示快顯視窗、指出每個區域的容量。

透過整合可用容量、您可以從Volume群組中的可用容量上限建立額外的Volume。您可以使用下列其中一種方法、將現有的可用容量整合到選取的Volume群組：

* 當至少偵測到一個Volume群組的一個可用容量區域時、「通知」區域的首頁會顯示「整合可用容量」建議。按一下「*整合可用容量*」連結以啟動對話方塊。
* 您也可以選取功能表：資源池和Volume群組[不尋常的工作>整合Volume群組可用容量]以啟動對話方塊。


如果您要使用特定的可用容量區域、而非最大的可用容量區域、請使用命令列介面（CLI）。



== 我所選的工作負載如何影響磁碟區建立？

在磁碟區建立期間、系統會提示您提供工作負載使用的相關資訊。系統會使用此資訊為您建立最佳Volume組態、並可視需要加以編輯。您也可以在磁碟區建立順序中跳過此步驟。

工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

* *應用程式專屬*-當您使用應用程式專屬的工作負載來建立磁碟區時、系統可能會建議最佳化的磁碟區組態、以將應用程式工作負載I/O與應用程式執行個體的其他流量之間的爭用降至最低。對於針對下列應用程式類型所建立的工作負載、會自動建議並最佳化I/O類型、區段大小、控制器擁有權、讀寫快取等Volume特性。
+
** Microsoft®SQL Server™
** Microsoft®Exchange Server™
** 視訊監控應用程式
** VMware ESXi™（適用於與虛擬機器檔案系統搭配使用的磁碟區）
+
您可以使用「新增/編輯磁碟區」對話方塊來檢閱建議的磁碟區組態、以及編輯、新增或刪除系統建議的磁碟區和特性。



* *其他*（或不支援特定磁碟區建立的應用程式）- 其他工作負載則使用Volume組態、您必須手動指定何時要建立與特定應用程式無關的工作負載、或是儲存陣列上未針對您要使用的應用程式進行內建最佳化。您必須使用「新增/編輯磁碟區」對話方塊手動指定磁碟區組態。




== 為什麼這些磁碟區與工作負載沒有關聯？

如果磁碟區是使用命令列介面（CLI）建立、或是已從不同的儲存陣列移轉（匯入/匯出）、則不會與工作負載建立關聯。



== 為什麼我無法刪除選取的工作負載？

此工作負載由一組使用命令列介面（CLI）建立的磁碟區、或是從不同儲存陣列移轉（匯入/匯出）的磁碟區組成。因此、此工作負載中的磁碟區不會與應用程式專屬的工作負載相關聯、因此無法刪除工作負載。



== 應用程式專屬的工作負載如何協助我管理儲存陣列？

應用程式專屬工作負載的Volume特性決定了工作負載與儲存陣列元件的互動方式、並有助於在特定組態下判斷環境的效能。

應用程式是SQL Server或Exchange等軟體。您可以定義一或多個工作負載來支援每個應用程式。



== 提供此資訊如何協助建立儲存設備？

工作負載資訊是用來最佳化所選工作負載的磁碟區特性、例如I/O類型、區段大小、讀取/寫入快取。這些最佳化特性決定了工作負載與儲存陣列元件的互動方式。

System Manager會根據您提供的工作負載資訊、建立適當的磁碟區、並將其放在系統上目前存在的可用集區或磁碟區群組中。系統會根據您所選工作負載的目前最佳實務做法、建立磁碟區並最佳化其特性。

在您完成為特定工作負載建立磁碟區之前、您可以使用「新增/編輯磁碟區」對話方塊來檢閱建議的磁碟區組態、以及編輯、新增或刪除系統建議的磁碟區和特性。

如需最佳實務做法資訊、請參閱應用程式專屬的文件。



== 我需要如何辨識擴充的容量？

如果您增加磁碟區的容量、主機可能無法立即辨識磁碟區容量的增加。

大多數作業系統都會辨識擴充的Volume容量、並在啟動Volume擴充之後自動擴充。不過、有些可能沒有。如果作業系統無法自動辨識擴充的Volume容量、您可能需要執行磁碟重新掃描或重新開機。

擴充磁碟區容量之後、您必須手動增加檔案系統大小以符合需求。您的做法取決於所使用的檔案系統。

如需其他詳細資料、請參閱主機作業系統文件。



== 為什麼我看不到所有池和/或磁碟區組？

您無法將磁碟區移至的任何集區或磁碟區群組不會顯示在清單中。

集區或Volume群組不符合下列任何理由的資格：

* 集區或Volume群組集區的資料保證（DA）功能不相符。
* 集區或磁碟區群組處於非最佳狀態。
* 集區或Volume群組的容量太小。




== 什麼是區段大小？

區段是儲存陣列移至等量磁碟區（RAID群組）中的下一個磁碟機之前、儲存在磁碟機上的資料量（千位元組）。區段大小僅適用於磁碟區群組、而非資源池。

區段大小是根據其所包含的資料區塊數目來定義。在判斷區段大小時、您必須知道要儲存在磁碟區中的資料類型。如果應用程式通常使用小型隨機讀取與寫入（IOPS）、則較小的區段大小通常會更好。或者、如果應用程式具有大量的循序讀取和寫入（處理量）、則較大的區段大小通常會較佳。

無論應用程式使用小型隨機讀取與寫入、或是大量循序讀取與寫入、如果區段大小大於一般資料區塊區塊大小、儲存陣列的效能都會更好。這通常可讓磁碟機更輕鬆、更快速地存取資料、這對於提高儲存陣列效能來說非常重要。



=== IOPS效能非常重要的環境

在每秒I/O作業次數（IOPS）環境中、如果您使用的區段大小大於磁碟機讀取/寫入的一般資料區塊大小（「chunk」）、則儲存陣列的效能會更好。如此可確保每個區塊都寫入單一磁碟機。



=== 處理量非常重要的環境

在處理量環境中、區段大小應該是資料磁碟機總數的一小部分、以及一般資料區塊大小（I/O大小）。如此一來、資料就會以單一等量磁碟區的形式分散在磁碟區群組中的磁碟機上、進而加快讀取和寫入速度。



== 什麼是偏好的控制器擁有權？

偏好的控制器擁有權定義指定為磁碟區擁有或主要控制器的控制器。

控制器擁有權非常重要、因此應謹慎規劃。控制器應盡量平衡整體I/O。

例如、如果某個控制器主要讀取大型連續資料區塊、而另一個控制器則有較小的資料區塊、而且經常讀取和寫入、則負載會截然不同。瞭解哪些磁碟區包含哪種資料類型、可讓您在兩個控制器上平均平衡I/O傳輸。



== 我想在何時使用「稍後指派主機」選項？

如果您想加速建立磁碟區的程序、可以跳過主機指派步驟、以便離線初始化新建立的磁碟區。

必須初始化新建立的磁碟區。系統可以使用兩種模式之一來初始化它們：立即可用的格式（IAF）背景初始化程序或離線程序。

將磁碟區對應到主機時、會強制該群組中任何初始化的磁碟區轉換成背景初始化。此背景初始化程序可同時執行主機I/O、有時可能會耗費大量時間。

如果未對應磁碟區群組中的任何磁碟區、則會執行離線初始化。離線程序比背景程序快得多。



== 我需要知道哪些關於主機區塊大小需求的資訊？

對於EF300和EF600系統、可以設定一個磁碟區來支援512位元組或4KiB區塊大小（也稱為「磁碟區大小」）。您必須在建立磁碟區期間設定正確的值。如果可能、系統會建議適當的預設值。

設定Volume區塊大小之前、請先閱讀下列限制與準則。

* 某些作業系統和虛擬機器（尤其是VMware目前）需要512位元組的區塊大小、而且不支援4KiB、因此請務必在建立磁碟區之前先瞭解主機需求。一般而言、您可以設定一個Volume來呈現4KiB區塊大小、以達到最佳效能；不過、請確定您的主機允許使用4KiB（或「4Kn」）區塊。
* 您為集區或磁碟區群組選取的磁碟機類型、也會決定支援哪些磁碟區塊大小、如下所示：
+
** 如果您使用寫入512位元組區塊的磁碟機來建立磁碟區群組、則只能建立含有512位元組區塊的磁碟區。
** 如果您使用寫入4KiB區塊的磁碟機來建立磁碟區群組、則可以使用512位元組或4KiB區塊來建立磁碟區。


* 如果陣列有iSCSI主機介面卡、則所有磁碟區都限制為512位元組區塊（無論磁碟區群組區塊大小）。這是因為特定的硬體實作。
* 一旦設定區塊大小、您就無法變更區塊大小。如果您需要變更區塊大小、則必須刪除磁碟區並重新建立。

