---
permalink: sm-storage/faq-pools-volume-groups.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 的池和磁碟區組常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 什麼是Volume群組？

Volume群組是具有共享特性之磁碟區的容器。Volume群組具有已定義的容量和RAID層級。您可以使用Volume群組來建立一個或多個可讓主機存取的磁碟區。（您可以從磁碟區群組或集區建立磁碟區。）



== 什麼是資源池？

資源池是邏輯分組的一組磁碟機。您可以使用集區來建立一個或多個可供主機存取的磁碟區。（您可以從集區或磁碟區群組建立磁碟區。）

集區可免除系統管理員監控每個主機使用量的需求、以判斷何時可能耗盡儲存空間、並避免傳統的磁碟調整大小停機。當集區即將耗盡時、可在不中斷營運的情況下將額外的磁碟機新增至集區、而且容量成長對主機而言是透明的。

有了資源池、資料會自動重新分散、以維持平衡。透過將同位元檢查資訊和備用容量分散到整個集區、集區中的每個磁碟機都可用來重建故障磁碟機。此方法不使用專用的熱備援磁碟機、而是保留（備用）整個資源池的容量。磁碟機故障時、會讀取其他磁碟機上的區段以重新建立資料。然後選擇新的磁碟機來寫入故障磁碟機上的每個區段、以便維持磁碟機之間的資料發佈。



== 什麼是保留容量？

保留容量是指實體配置的容量、用於儲存複製服務物件的資料、例如快照映像、一致性群組成員磁碟區和鏡射配對磁碟區。

與複製服務作業相關聯的保留容量Volume位於集區或Volume群組中。您可以從集區或Volume群組建立保留容量。



== 什麼是FDE/FIPS安全性？

FDE/FIPS安全性是指可在讀取期間使用獨特加密金鑰加密資料的安全磁碟機。這些具有安全功能的磁碟機可防止未獲授權存取實體從儲存陣列移除的磁碟機上的資料。

安全的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。FIPS磁碟機已通過認證測試。

[NOTE]
====
對於需要FIPS支援的磁碟區、請僅使用FIPS磁碟機。在磁碟區群組或集區中混合使用FIPS和FDE磁碟機、將會將所有磁碟機視為FDE磁碟機。此外、FDE磁碟機無法新增至All FIPS Volume群組或Pool、也無法作為備援磁碟機使用。

====


== 什麼是備援檢查？

備援檢查可決定集區或磁碟區群組中磁碟區上的資料是否一致。如果資源池或磁碟區群組中的某個磁碟機故障、備援資料可用於快速重建替換磁碟機上的資訊。

您一次只能在一個集區或磁碟區群組上執行此檢查。磁碟區備援檢查會執行下列動作：

* 掃描RAID 3 Volume、RAID 5 Volume或RAID 6 Volume中的資料區塊、然後檢查每個區塊的備援資訊。（RAID 3只能使用命令列介面指派給Volume群組。）
* 比較RAID 1鏡射磁碟機上的資料區塊。
* 如果控制器韌體判定資料不一致、則傳回備援錯誤。


[NOTE]
====
在相同的集區或磁碟區群組上立即執行備援檢查可能會導致錯誤。若要避免此問題、請先等待一到兩分鐘、再在同一個集區或磁碟區群組上執行另一個備援檢查。

====


== 集區與Volume群組之間有何差異？

集區類似於磁碟區群組、但有下列差異。

* 集區中的資料會隨機儲存在集區中的所有磁碟機上、這與儲存在同一組磁碟機上的Volume群組資料不同。
* 當磁碟機故障時、集區的效能降級較少、重建所需時間也較短。
* 集區具有內建的保留容量、因此不需要專用的熱備援磁碟機。
* 集區可將大量磁碟機進行分組。
* 集區不需要指定的RAID層級。




== 為什麼要手動設定集區？

下列範例說明您想要手動設定集區的原因。

* 如果您的儲存陣列上有多個應用程式、但不想讓它們競用相同的磁碟機資源、您可以考慮手動為一或多個應用程式建立較小的資源池。
+
您只能指派一或兩個磁碟區、而不需將工作負載指派給有許多磁碟區的大型集區、以便在其中發佈資料。手動建立專屬特定應用程式工作負載的獨立資源池、可讓儲存陣列作業更快速地執行、同時減少爭用。

+
若要手動建立集區：選取* Storage*、然後選取* Pools & Volume Groups*。從「All Capacity（所有容量）」索引標籤、按一下功能表：「Create[Pool]（建立資源池

* 如果有多個相同磁碟機類型的集區、則會出現一則訊息、指出System Manager無法自動建議集區的磁碟機。不過、您可以手動將磁碟機新增至現有的集區。
+
若要手動將磁碟機新增至現有的集區：從「集區與磁碟區群組」頁面選取集區、然後按一下「*新增容量*」。





== 容量警示為何重要？

容量警示會指出何時要將磁碟機新增至資源池。集區需要足夠的可用容量、才能成功執行儲存陣列作業。您可以將 SANtricity 系統管理員設定為在集區的可用容量達到或超過指定百分比時傳送警示，以防止這些作業中斷。

使用* Pool自動組態*選項或*建立集區*選項建立集區時、您可以設定此百分比。如果您選擇自動選項、預設設定會自動決定何時收到警示通知。如果您選擇手動建立集區、可以決定警示通知設定；如果您願意、也可以接受預設設定。您稍後可以在功能表：設定[警示]中調整這些設定。

[NOTE]
====
當集區中的可用容量達到指定百分比時、系統會使用您在警示組態中指定的方法傳送警示通知。

====


== 為什麼我無法提升我的保存能力？

如果您已在所有可用容量上建立磁碟區、則可能無法增加保留容量。

保留容量是指為支援潛在磁碟機故障而保留在集區上的容量（磁碟機數量）。建立集區時、系統會根據集區中的磁碟機數量、自動保留預設的保留容量。如果您已在所有可用容量上建立磁碟區、則無法透過新增磁碟機或刪除磁碟區、來增加保留容量、而不將容量新增至資源池。

您可以從*資源池和Volume群組*變更保留容量。選取您要編輯的資源池。按一下「*檢視/編輯設定*」、然後選取「*設定*」索引標籤。

[NOTE]
====
保留容量會指定為多個磁碟機、即使實際保留容量會分散在集區中的磁碟機上。

====


== 我可以從集區移除的磁碟機數量是否有限制？

SANtricity 系統管理員會針對您可以從集區移除多少磁碟機，設定限制。

* 您無法將集區中的磁碟機數量減少至少於11個磁碟機。
* 如果資源池中沒有足夠的可用容量來容納移除磁碟機中的資料、則當該資料重新分配到資源池中的其餘磁碟機時、您就無法移除磁碟機。
* 一次最多可移除60個磁碟機。如果您選取超過60個磁碟機、「移除磁碟機」選項會停用。如果您需要移除超過60個磁碟機、請重複「移除磁碟機」作業。




== 磁碟機支援哪些媒體類型？

支援下列媒體類型：硬碟機（HDD）和固態磁碟（SSD）。



== 為什麼有些磁碟機沒有顯示？

在「Add Capacity」（新增容量）對話方塊中、並非所有磁碟機都能新增容量至現有的資源池或磁碟區群組。

磁碟機不符合下列任何理由：

* 磁碟機必須未指派、且未啟用安全功能。磁碟機已經是另一個集區、另一個磁碟區群組的一部分、或是設定為熱備援磁碟機、則不符合資格。如果磁碟機未指派、但已啟用安全功能、您必須手動清除該磁碟機、才能符合資格。
* 處於非最佳狀態的磁碟機不符合資格。
* 如果磁碟機的容量太小、就不符合資格。
* 磁碟機媒體類型必須與集區或磁碟區群組相符。您無法混用下列項目：
+
** 硬碟機（HDD）搭配固態磁碟（SSD）
** NVMe與SAS磁碟機
** 具有512位元組和4KiB磁碟區區塊大小的磁碟機


* 如果集區或磁碟區群組包含所有具有安全功能的磁碟機、則不會列出不安全功能的磁碟機。
* 如果集區或磁碟區群組包含所有聯邦資訊處理標準（FIPS）磁碟機、則不會列出非FIPS磁碟機。
* 如果集區或磁碟區群組包含所有資料保證（DA）功能的磁碟機、且集區或磁碟區群組中至少有一個啟用DA的磁碟區、則不符合不具備DA功能的磁碟機資格、因此無法將其新增至該集區或磁碟區群組。不過、如果集區或Volume群組中沒有啟用DA的磁碟區、則無法將無法使用DA的磁碟機新增至該集區或Volume群組。如果您決定混合使用這些磁碟機、請記住、您無法建立任何啟用DA的磁碟區。


[NOTE]
====
您可以新增磁碟機、或刪除資源池或磁碟區群組、來增加儲存陣列的容量。

====


== 如何維護機櫃/藥櫃遺失保護？

若要維護資源池或磁碟區群組的機櫃/藥櫃遺失保護、請使用下表中指定的條件。

[cols="1a,1a,1a"]
|===
| 層級 | 機櫃/藥櫃損失保護條件 | 所需的磁碟櫃/藥櫃數量下限 


 a| 
資源池
 a| 
如果是磁碟櫃、該資源池必須在單一磁碟櫃中包含兩個以上的磁碟機。

對於藥櫃、該資源池必須包含每個藥櫃的相同磁碟機數量。
 a| 
6適用於磁碟櫃

5個用於抽屜



 a| 
RAID 6
 a| 
磁碟區群組在單一磁碟櫃或磁碟櫃中不含兩個以上的磁碟機。
 a| 
3.



 a| 
RAID 3或RAID 5
 a| 
Volume群組中的每個磁碟機都位於獨立的磁碟櫃或抽屜中。
 a| 
3.



 a| 
RAID 1
 a| 
鏡射配對中的每個磁碟機必須位於獨立的磁碟櫃或磁碟櫃中。
 a| 
2.



 a| 
RAID 0
 a| 
無法達到機櫃/藥櫃遺失保護。
 a| 
不適用

|===
[NOTE]
====
如果磁碟機已在集區或磁碟區群組中故障、則無法維護機櫃/藥櫃遺失保護。在這種情況下、失去磁碟機櫃或抽屜的存取權、進而導致集區或磁碟區群組中的另一個磁碟機遺失資料。

====


== 集區和磁碟區群組的最佳磁碟機定位為何？

建立集區和磁碟區群組時、請務必在上方和下方磁碟機插槽之間平衡磁碟機的選擇。

對於EF600和EF300控制器、磁碟機插槽0-11連接至一個PCI橋接器、而插槽12-23則連接至不同的PCI橋接器。為獲得最佳效能、您應該在磁碟機選擇之間取得平衡、以納入與上方和下方插槽大致相同的磁碟機數量。此定位可確保您的磁碟區不會在必要時達到頻寬限制。



== 哪種RAID層級最適合我的應用程式？

若要將磁碟區群組的效能最大化、您必須選取適當的RAID層級。您可以知道存取磁碟區群組的應用程式讀取和寫入百分比、藉此判斷適當的RAID層級。請使用「效能」頁面取得這些百分比。



=== RAID層級與應用程式效能

RAID仰賴一系列的組態（稱為_Levels）來判斷如何從磁碟機寫入和擷取使用者和備援資料。每個RAID層級都提供不同的效能功能。由於RAID 5和RAID 6組態的優異讀取效能、高讀取百分比的應用程式在使用RAID 5磁碟區或RAID 6磁碟區時效能將會很好。

讀取百分比較低（寫入密集）的應用程式在RAID 5磁碟區或RAID 6磁碟區上的效能不佳。效能降級是控制器將資料和備援資料寫入RAID 5 Volume群組或RAID 6 Volume群組中的磁碟機的方式所致。

根據下列資訊選取RAID層級。

* RAID 0*

* *說明*
+
** 非備援的分段模式。


* *運作方式*
+
** RAID 0會在Volume群組中的所有磁碟機之間條帶化資料。


* *資料保護功能*
+
** RAID 0不建議用於高可用度需求。RAID 0更適合非關鍵資料。
** 如果磁碟區群組中的單一磁碟機故障、所有相關的磁碟區都會故障、而且所有資料都會遺失。


* *磁碟機編號需求*
+
** RAID層級0至少需要一個磁碟機。
** RAID 0磁碟區群組可有30個以上的磁碟機。
** 您可以建立包含儲存陣列中所有磁碟機的磁碟區群組。




* RAID 1或RAID 10*

* *說明*
+
** 分段/鏡射模式。


* *運作方式*
+
** RAID 1使用磁碟鏡射、將資料同時寫入兩個重複的磁碟。
** RAID 10使用磁碟機等量分段來在一組鏡射磁碟機配對之間分段資料。


* *資料保護功能*
+
** RAID 1和RAID 10提供高效能和最佳資料可用度。
** RAID 1和RAID 10使用磁碟機鏡射功能、從一個磁碟機精確複製到另一個磁碟機。
** 如果磁碟機配對中的其中一個磁碟機故障、儲存陣列就能立即切換至另一個磁碟機、而不會遺失任何資料或服務。
** 單一磁碟機故障會導致相關磁碟區降級。鏡射磁碟機可存取資料。
** 磁碟區群組中的磁碟機配對故障會導致所有相關的磁碟區故障、並可能導致資料遺失。


* *磁碟機編號需求*
+
** RAID 1至少需要兩個磁碟機：一個磁碟機用於使用者資料、一個磁碟機用於鏡射資料。
** 如果您選取四個或更多磁碟機、RAID 10會在整個磁碟區群組中自動設定：兩個磁碟機用於使用者資料、兩個磁碟機用於鏡射資料。
** 磁碟區群組中必須有偶數個磁碟機。如果您沒有偶數個磁碟機、但仍有一些未指派的磁碟機、請前往*資源池與磁碟區群組*、將其他磁碟機新增至磁碟區群組、然後重試此作業。
** RAID 1和RAID 10磁碟區群組可擁有30個以上的磁碟機。您可以建立包含儲存陣列中所有磁碟機的Volume群組。




* RAID 5*

* *說明*
+
** 高I/O模式。


* *運作方式*
+
** 使用者資料和備援資訊（同位元檢查）會在磁碟機之間進行等量分佈。
** 一個磁碟機的容量相當於備援資訊。


* *資料保護功能*
+
** 如果RAID 5 Volume群組中的單一磁碟機故障、所有相關的磁碟區都會降級。備援資訊可讓您繼續存取資料。
** 如果RAID 5磁碟區群組中有兩個或多個磁碟機故障、所有相關的磁碟區都會故障、而且所有資料都會遺失。


* *磁碟機編號需求*
+
** 磁碟區群組中至少必須有三個磁碟機。
** 一般而言、磁碟區群組中最多只能有30個磁碟機。




* RAID 6*

* *說明*
+
** 高I/O模式。


* *運作方式*
+
** 使用者資料和備援資訊（雙同位元檢查）會在磁碟機之間分佈。
** 兩個磁碟機的容量相當於備援資訊。


* *資料保護功能*
+
** 如果RAID 6磁碟區群組中有一或兩個磁碟機故障、則所有相關的磁碟區都會降級、但冗餘資訊仍可存取資料。
** 如果在RAID 6 Volume群組中有三個以上的磁碟機故障、則所有相關的磁碟區都會故障、而且所有資料都會遺失。


* *磁碟機編號需求*
+
** 磁碟區群組中至少必須有五個磁碟機。
** 一般而言、磁碟區群組中最多只能有30個磁碟機。




[NOTE]
====
您無法變更集區的RAID層級。使用者介面會自動將集區設定為RAID 6。

====


=== RAID層級與資料保護

RAID 1、RAID 5和RAID 6會將備援資料寫入磁碟機媒體、以利容錯。備援資料可能是資料（鏡射）的複本、或是從資料衍生的錯誤修正程式碼。如果磁碟機故障、您可以使用備援資料快速重建替換磁碟機上的資訊。

您可以在單一磁碟區群組中設定單一RAID層級。該磁碟區群組的所有備援資料都儲存在磁碟區群組中。磁碟區群組的容量是成員磁碟機的集合容量減去為備援資料保留的容量。備援所需的容量取決於所使用的RAID層級。



== 什麼是資料保證？

資料保證（DA）實作T10保護資訊（PI）標準、藉由檢查及修正在I/O路徑傳輸資料時可能發生的錯誤、來提升資料完整性。

「資料保證」功能的一般用途是檢查控制器與磁碟機之間I/O路徑的部分。在資源池和Volume群組層級提供DA功能。

啟用此功能時、儲存陣列會將錯誤檢查代碼（也稱為循環備援檢查或CRC）附加到磁碟區中的每個資料區塊。資料區塊移動之後、儲存陣列會使用這些CRC代碼來判斷傳輸期間是否發生任何錯誤。可能毀損的資料既不會寫入磁碟、也不會傳回主機。如果您要使用DA功能、請在建立新的Volume時選取具有DA功能的集區或Volume群組（請在Pool and Volume Group候選人表格中尋找「DA」旁邊的「Yes」（是））。

請務必使用能夠執行DA的I/O介面、將這些啟用DA的磁碟區指派給主機。具備DA功能的I/O介面包括光纖通道、SAS、TCP/IP iSCSI、NVMe / FC、NVMe / IB、 適用於InfiniBand的NVMe/RoCE和iSER（適用於RDMA/IB的iSCSI擴充功能）。SRP不支援DA over InfiniBand。



== 什麼是安全功能（磁碟機安全性）？

磁碟機安全功能可防止在從儲存陣列移除時、未獲授權存取啟用安全功能之磁碟機上的資料。這些磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。



== 增加保留容量需要知道什麼？

一般而言、當您收到預留容量可能會變滿的警告時、您應該增加容量。您只能以8 GiB的增量來增加保留容量。

* 您必須在資源池或磁碟區群組中擁有足夠的可用容量、才能在必要時加以擴充。
+
如果任何集區或Volume群組上不存在可用容量、您可以將未使用磁碟機的未指派容量新增至集區或Volume群組。

* 集區或磁碟區群組中的磁碟區必須處於最佳狀態、且不得處於任何修改狀態。
* 可用容量必須存在於您要用來增加容量的資源池或磁碟區群組中。
* 您無法為唯讀的快照磁碟區增加保留容量。只有讀寫快照磁碟區需要保留容量。


對於快照作業、保留容量通常是基礎磁碟區的40%。對於非同步鏡射作業、保留容量通常為基礎磁碟區的20%。如果您認為基礎磁碟區會經歷許多變更、或儲存物件複製服務作業的預估使用壽命將會很長、請使用較高的百分比。



== 為什麼我不能選擇其他要減少的金額？

您只能減少保留容量、以增加容量的金額為準。成員磁碟區的保留容量只能以新增的相反順序移除。

如果存在下列任一情況、您就無法減少儲存物件的保留容量：

* 如果儲存物件是鏡射的配對磁碟區。
* 如果儲存物件僅包含一個保留容量的磁碟區。儲存物件必須包含至少兩個保留容量的磁碟區。
* 如果儲存物件是停用的快照磁碟區。
* 如果儲存物件包含一或多個相關的快照映像、


您只能以新增磁碟區的相反順序、移除保留容量的磁碟區。

您無法減少快照磁碟區的保留容量、因為該快照磁碟區沒有任何關聯的保留容量。只有讀寫快照磁碟區需要保留容量。



== 為什麼我需要每個成員磁碟區的保留容量？

Snapshot一致性群組中的每個成員磁碟區都必須擁有自己的保留容量、才能將主機應用程式所做的任何修改儲存到基礎磁碟區、而不會影響參考的一致性群組快照映像。保留容量可讓主機應用程式寫入指派為讀寫的成員磁碟區中所含資料複本。

一致性群組快照映像無法直接讀取或寫入主機。而是使用快照映像來儲存從基礎磁碟區擷取的資料。

在建立指定為讀寫的一致性群組快照磁碟區期間、System Manager會為一致性群組中的每個成員磁碟區建立保留容量。此保留容量可讓主機應用程式寫入一致性群組快照映像中所含資料的複本。



== 如何檢視及解讀所有SSD快取統計資料？

您可以檢視SSD快取的名義統計資料和詳細統計資料。名義統計資料是詳細統計資料的子集。

只有當您將所有SSD統計資料匯出至「.csv'」檔案時、才能檢視詳細的統計資料。當您檢閱及解讀統計資料時、請記住、有些解讀是由統計資料的組合所衍生而來。



=== 名義統計資料

若要檢視SSD快取統計資料、請選取功能表：「Storage[資源池與磁碟區群組]」。選取您要檢視統計資料的SSD快取、然後選取功能表：More（更多）[View Statistics（檢視統計資料）]。名義統計資料會顯示在「檢視SSD快取統計資料」對話方塊中。

下列清單包含名義統計資料、這是詳細統計資料的子集。

[cols="25h,~"]
|===
| 名義統計 | 說明 


 a| 
讀取/寫入
 a| 
從啟用SSD快取的磁碟區讀取或主機寫入的主機總數。比較讀取與寫入的關係。讀取必須大於寫入、才能有效執行SSD快取作業。讀取與寫入的比率越高、快取的操作就越好。



 a| 
快取命中次數
 a| 
快取命中數的計數。



 a| 
快取命中數（%）
 a| 
衍生自快取命中/（讀取+寫入）。若要有效執行SSD快取作業、快取命中率應大於50%。少數人可能會指出以下幾點：

* 讀取與寫入的比率太小
* 不會重複讀取
* 快取容量太小




 a| 
快取分配（%）
 a| 
分配的SSD快取儲存容量、以此控制器可用SSD快取儲存空間的百分比表示。衍生自已分配位元組/可用位元組。快取分配百分比通常顯示為100%。如果這個數字低於100%、表示快取尚未暖機、或SSD快取容量大於所有存取的資料。在後一種情況下、較小的SSD快取容量可提供相同等級的效能。請注意、這並不表示快取資料已置於SSD快取中、只是準備步驟、資料才可置於SSD快取中。



 a| 
快取使用率（%）
 a| 
包含已啟用磁碟區資料的SSD快取儲存容量、以已配置SSD快取儲存設備的百分比表示。此值代表從使用者資料位元組/配置位元組衍生出來的SSD快取使用率或密度。快取使用率百分比通常低於100%、可能低得多。此數字顯示填滿快取資料的SSD快取容量百分比。這個數字低於100%、因為SSD快取區塊的每個分配單元（SSD快取區塊）被分成較小的單元、稱為子區塊、因此會稍微獨立地填滿。較高的數字通常較好、但效能增益可能很大、即使數量較少。

|===


=== 詳細統計資料

詳細統計資料包括名義統計資料、以及其他統計資料。這些額外的統計資料會連同名義統計資料一起儲存、但與名義統計資料不同的是、它們不會顯示在「檢視SSD快取統計資料」對話方塊中。您只能在將統計資料匯出至「.csv'」檔案之後、才能檢視詳細的統計資料。

檢視「.csv'」檔案時、請注意、詳細統計資料會列在名義統計資料之後：

[cols="25h,~"]
|===
| 詳細統計資料 | 說明 


 a| 
讀取區塊
 a| 
主機讀取區塊數。



 a| 
寫入區塊
 a| 
主機寫入區塊數。



 a| 
完整熱門區塊
 a| 
快取命中的區塊數。完整的命中率區塊表示已從SSD快取中完全讀取的區塊數。SSD快取只有對完整快取點擊的作業有助於提升效能。



 a| 
部分命中數
 a| 
至少有一個區塊（但不是所有區塊）位於SSD快取中的主機讀取數量。部分命中率是SSD快取* Miss *、從基礎磁碟區讀取內容時會感到滿意。



 a| 
部分命中-區塊
 a| 
部分命中的區塊數。部分快取命中率和部分快取命中率區塊是由在SSD快取中只有部分資料的作業所造成。在此情況下、作業必須從快取的硬碟機（HDD）磁碟區取得資料。SSD快取對這類命中率沒有任何效能優勢。如果部分快取命中率區塊數高於完整的快取命中率區塊、則不同的I/O特性類型（檔案系統、資料庫或Web伺服器）可能會改善效能。相較於SSD快取變暖時的快取命中、預期「部分命中」和「未命中」數量會較多。



 a| 
未命中
 a| 
SSD快取中沒有任何區塊的主機讀取數量。當從基礎磁碟區滿足讀取要求時、就會發生SSD快取遺漏。相較於SSD快取變暖時的快取命中、預期「部分命中」和「未命中」數量會較多。



 a| 
未命中-區塊
 a| 
未命中的區塊數。



 a| 
填入動作（主機讀取）
 a| 
從基礎磁碟區複製資料到SSD快取的主機讀取數量。



 a| 
讀取行動（主機讀取）-區塊
 a| 
「讀取資料」動作（主機讀取）中的區塊數。



 a| 
填入動作（主機寫入）
 a| 
從基礎磁碟區複製資料到SSD快取的主機寫入次數。由於寫入I/O作業、未填滿快取組態設定的「讀取動作（主機寫入）」計數可能為零。



 a| 
讀取動作（主機寫入）-區塊
 a| 
「讀取動作（主機寫入）」中的區塊數。



 a| 
讓動作無效
 a| 
資料失效或從SSD快取移除的次數。每個主機寫入要求、每個具有強制單位存取（FUA）的主機讀取要求、每個驗證要求、以及其他情況下、都會執行快取無效作業。



 a| 
回收行動
 a| 
將SSD快取區塊重新用於其他基礎磁碟區和/或不同邏輯區塊定址（LBA）範圍的次數。若要有效執行快取作業、可回收的數量必須少於合併的讀取和寫入作業數。如果回收動作數量接近讀取和寫入的合併數量、SSD快取就會發生衝突。快取容量需要增加、或工作負載不適合搭配SSD快取使用。



 a| 
可用位元組
 a| 
SSD快取中可供此控制器使用的位元組數。



 a| 
已分配位元組
 a| 
此控制器從SSD快取配置的位元組數。從SSD快取配置的位元組可能是空的、或可能包含來自基礎磁碟區的資料。



 a| 
使用者資料位元組
 a| 
SSD快取中包含基礎磁碟區資料的已分配位元組數。可用位元組、已分配位元組和使用者資料位元組、用於計算快取分配百分比和快取使用率百分比。

|===


== 集區的最佳化容量為何？

當SSD磁碟機的一部分容量未配置時、其壽命將更長、寫入效能將更高。

對於與集區相關聯的磁碟機、未分配的容量由集區的保留容量、可用容量（磁碟區未使用的容量）以及保留為額外最佳化容量的可用容量所組成。額外的最佳化容量可藉由減少可用容量來確保最小程度的最佳化容量、因此無法建立磁碟區。

建立集區時、會產生建議的最佳化容量、以平衡效能、磁碟機耗損壽命和可用容量。「資源池設定」對話方塊中的「其他最佳化容量」滑桿可調整資源池的最佳化容量。調整滑桿可提高效能、延長使用壽命、同時犧牲可用容量或額外可用容量、同時犧牲效能和磁碟機使用壽命。

[NOTE]
====
額外最佳化容量滑桿僅適用於EF600和EF300儲存系統。

====


== 什麼是Volume群組的最佳化容量？

當SSD磁碟機的一部分容量未配置時、其壽命將更長、寫入效能將更高。

對於與磁碟區群組相關聯的磁碟機、未分配的容量由磁碟區群組的可用容量（磁碟區未使用的容量）和保留為最佳化容量的部分可用容量組成。額外的最佳化容量可藉由減少可用容量來確保最小程度的最佳化容量、因此無法建立磁碟區。

建立Volume群組時、會產生建議的最佳化容量、以平衡效能、磁碟機耗損壽命和可用容量。Volume Group Settings（Volume群組設定）對話方塊中的其他Optimization Capacity（最佳化容量）滑桿可調整Volume群組的最佳化容量。調整滑桿可提高效能、延長使用壽命、同時犧牲可用容量或額外可用容量、同時犧牲效能和磁碟機使用壽命。

[NOTE]
====
額外最佳化容量滑桿僅適用於EF600和EF300儲存系統。

====


== 什麼是資源資源配置功能？

資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。

資源配置的磁碟區是SSD磁碟區群組或集區中的一個完整磁碟區、在建立磁碟區時、會將磁碟機容量分配給該磁碟區（指派給該磁碟區）、但磁碟區塊會被取消分配（未對應）。相較之下、在傳統的厚磁碟區中、所有磁碟區區塊都會在背景磁碟區初始化作業期間對應或配置、以便初始化Data Assurance保護資訊欄位、並使每個RAID等量磁碟區的資料和RAID同位元保持一致。使用資源配置的Volume、就不會進行時間限制的背景初始化。相反地、每個RAID等量磁碟區都會在第一次寫入等量磁碟區塊時初始化。

資源配置的磁碟區僅支援SSD磁碟區群組和集區、群組或集區中的所有磁碟機都支援NVMe取消分配或未寫入的邏輯區塊錯誤啟用（DULBE）錯誤恢復功能。建立資源配置的Volume時、會取消分配指派給該磁碟區的所有磁碟區塊（未對應）。此外、主機可以使用NVMe資料集管理命令或SCSI取消對應命令、取消分配磁碟區中的邏輯區塊。取消分配區塊可改善SSD的耗損壽命、並提高最大寫入效能。每個磁碟機機型和容量的改善程度各不相同。


NOTE: EF300C 或 EF600C 儲存陣列目前不支援 DULBE 。



== 關於資源配置的Volume功能、我需要知道什麼？

資源資源配置是EF300和EF600儲存陣列的一項功能、可讓磁碟區立即投入使用、而無需背景初始化程序。

資源配置的磁碟區是SSD磁碟區群組或集區中的一個完整磁碟區、在建立磁碟區時、會將磁碟機容量分配給該磁碟區（指派給該磁碟區）、但磁碟區塊會被取消分配（未對應）。相較之下、在傳統的厚磁碟區中、所有磁碟區區塊都會在背景磁碟區初始化作業期間對應或配置、以便初始化Data Assurance保護資訊欄位、並使每個RAID等量磁碟區的資料和RAID同位元保持一致。使用資源配置的Volume、就不會進行時間限制的背景初始化。相反地、每個RAID等量磁碟區都會在第一次寫入等量磁碟區塊時初始化。

資源配置的磁碟區僅支援SSD磁碟區群組和集區、群組或集區中的所有磁碟機都支援NVMe取消分配或未寫入的邏輯區塊錯誤啟用（DULBE）錯誤恢復功能。建立資源配置的Volume時、會取消分配指派給該磁碟區的所有磁碟區塊（未對應）。此外、主機可以使用NVMe資料集管理命令或SCSI取消對應命令、取消分配磁碟區中的邏輯區塊。取消分配區塊可改善SSD的耗損壽命、並提高最大寫入效能。每個磁碟機機型和容量的改善程度各不相同。

預設會在磁碟機支援DULBE的系統上啟用資源配置。您可以從*資源池與磁碟區群組*停用該預設設定。


NOTE: EF300C 或 EF600C 儲存陣列目前不支援 DULBE 。
