---
permalink: sm-storage/host-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host, terms 
summary: 瞭解主機條款如何適用於您的儲存陣列。 
---
= 主機術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解主機條款如何適用於您的儲存陣列。

[cols="25h,~"]
|===
| 元件 | 定義 


 a| 
主機
 a| 
主機是一種伺服器、可將I/O傳送至儲存陣列上的磁碟區。



 a| 
主機名稱
 a| 
主機名稱應等於主機的系統名稱。



 a| 
主機叢集
 a| 
主機叢集是一組主機。您可以建立主機叢集、以便輕鬆將相同的磁碟區指派給多個主機。



 a| 
主機介面傳輸協定
 a| 
主機介面傳輸協定是指控制器與主機之間的連線（例如光纖通道、iSCSI等）。



 a| 
HBA或網路介面卡（NIC）
 a| 
主機匯流排介面卡（HBA）是一種主機板、位於主機中、包含一或多個主機連接埠。



 a| 
主機連接埠
 a| 
主機連接埠是主機匯流排介面卡（HBA）上的連接埠、可提供與控制器的實體連線、並用於I/O作業。



 a| 
主機連接埠識別碼
 a| 
主機連接埠識別碼是與主機匯流排介面卡（HBA）上的每個主機連接埠相關聯的唯一全世界名稱。

* 網際網路小型電腦系統介面（iSCSI）主機連接埠識別碼必須介於1到233個字元之間。iSCSI主機連接埠識別碼會以標準IQN格式顯示（例如、「iqn.xxx.com.xxx:8b3ad`」）。
* 非iSCSI主機連接埠識別碼（例如Fibre Channel和Serial Attached SCSI（SAS））會在每兩個字元（例如「xx:yy:zz」）後以分號分隔顯示。Fibre Channel主機連接埠識別碼必須有16個字元。




 a| 
主機作業系統類型
 a| 
主機作業系統類型是一種組態設定、可定義儲存陣列中的控制器對I/O的反應、視主機的作業系統（或變體）而定。這也稱為_host類型_。



 a| 
控制器主機連接埠
 a| 
控制器主機連接埠是控制器上的連接埠、可提供實體連線至主機、並用於I/O作業。



 a| 
LUN
 a| 
邏輯單元編號（LUN）是指派給主機用來存取磁碟區之位址空間的編號。磁碟區會以LUN的形式、以容量形式呈現給主機。

每個主機都有自己的LUN位址空間。因此、不同主機可以使用相同的LUN來存取不同的磁碟區。

|===