---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: 建立磁碟區時、您可以選取工作負載來自訂特定應用程式的儲存陣列組態。 
---
= 工作負載的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立磁碟區時、您可以選取工作負載來自訂特定應用程式的儲存陣列組態。

工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

在Volume建立期間、系統會提示您回答有關工作負載使用的問題。例如、如果您要為Microsoft Exchange建立磁碟區、系統會詢問您需要多少信箱、平均信箱容量需求為何、以及您想要的資料庫複本數量。系統會使用此資訊為您建立最佳Volume組態、並可視需要加以編輯。您也可以在磁碟區建立順序中跳過此步驟。



== 工作負載類型

您可以建立兩種類型的工作負載：應用程式專屬和其他。

* *特定應用程式*。當您使用應用程式專屬的工作負載來建立磁碟區時、系統可能會建議最佳化的磁碟區組態、以盡量減少應用程式工作負載I/O與應用程式執行個體的其他流量之間的爭用。對於針對下列應用程式類型所建立的工作負載、會自動建議並最佳化I/O類型、區段大小、控制器擁有權、讀寫快取等Volume特性。
+
** Microsoft®SQL Server™
** Microsoft®Exchange Server™
** 視訊監控應用程式
** VMware ESXi™（適用於與虛擬機器檔案系統搭配使用的磁碟區）
+
您可以使用「新增/編輯磁碟區」對話方塊來檢閱建議的磁碟區組態、以及編輯、新增或刪除系統建議的磁碟區和特性。



* *其他*（或不支援特定磁碟區建立的應用程式）。其他工作負載則使用Volume組態、您必須手動指定何時要建立與特定應用程式無關的工作負載、或是系統沒有內建的最佳化功能、無法在儲存陣列上使用應用程式。您必須使用「新增/編輯磁碟區」對話方塊手動指定磁碟區組態。




== 應用程式與工作負載檢視

若要檢視應用程式和工作負載、請啟動SANtricity 《系統管理程式》。從該介面、您可以使用幾種不同的方式來檢視與應用程式特定工作負載相關的資訊：

* 您可以在「Volumes」（磁碟區）並排顯示區中選取「* Applications & Workload *」（*應用程式與工作負載*）索引標籤、以檢視儲存陣列的磁碟區、並依工作負載和工作負載相關的應用程式類型進行分組。
* 您可以在「效能」方塊中選取*應用程式與工作負載*索引標籤、以檢視邏輯物件的效能指標（延遲、IOPS和MB）。物件會依應用程式和相關工作負載進行分組。藉由定期收集此效能資料、您可以建立基準測量並分析趨勢、協助您調查與I/O效能相關的問題。

