---
permalink: sm-storage/how-reserved-capacity-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, 
summary: 當為磁碟區提供快照或非同步鏡射作業等複本服務作業時、系統會自動建立保留容量。 
---
= 保留容量的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當為磁碟區提供快照或非同步鏡射作業等複本服務作業時、系統會自動建立保留容量。

保留容量的目的是在發生錯誤時、將資料變更儲存在這些磁碟區上。與磁碟區一樣、保留容量是從集區或磁碟區群組建立。



== 複製使用保留容量的服務物件

保留容量是這些複製服務物件所使用的基礎儲存機制：

* Snapshot群組
* 讀寫快照磁碟區
* 一致性群組成員磁碟區
* 鏡射配對磁碟區


建立或擴充這些複製服務物件時、您必須從集區或Volume群組建立新的保留容量。保留容量通常是基礎磁碟區的40%、用於快照作業、20%的基礎磁碟區用於非同步鏡射作業。不過、保留容量會因原始資料的變更次數而有所不同。



== 精簡磁碟區與保留容量

對於精簡磁碟區、如果已達到256 TiB的最大報告容量、您就無法增加容量。請確定精簡磁碟區的保留容量設定為大於最大報告容量的大小。（精簡磁碟區一律精簡配置、這表示在資料寫入磁碟區時、會分配容量。）

如果您使用集區中的精簡磁碟區來建立保留容量、請檢閱下列有關保留容量的動作和結果：

* 如果精簡磁碟區的保留容量失敗、精簡磁碟區本身就不會自動轉換至「故障」狀態。不過、由於精簡磁碟區上的所有I/O作業都需要存取保留容量磁碟區、因此I/O作業一律會將檢查條件傳回要求的主機。如果保留容量磁碟區的基本問題可以解決、保留容量磁碟區會恢復至最佳狀態、精簡磁碟區將會再次運作。
* 如果您使用現有的精簡磁碟區來完成非同步鏡射配對、則該精簡磁碟區會以新的保留容量Volume重新初始化。在初始同步處理程序期間、只會傳輸主要端上已配置的區塊。




== 容量警示

複製服務物件具有可設定的容量警告和警示臨界值、以及當保留容量已滿時可設定的回應。

當複製服務物件磁碟區的保留容量接近填滿點時、會向使用者發出警示。根據預設、此警示會在保留容量為75%滿時發出；不過、您可以視需要上下調整此警示點。如果您收到此警示、可以增加當時保留容量磁碟區的容量。在這方面、每個複製服務物件都可以獨立設定。



== 孤立的保留容量磁碟區

孤立保留容量Volume是一種磁碟區、因為其關聯的複製服務物件已刪除、所以不再儲存複製服務作業的資料。刪除複製服務物件時、其保留的容量Volume也應該被刪除。但是、保留容量磁碟區無法刪除。

由於任何主機都無法存取孤立的保留容量磁碟區、因此它們是可供回收的候選磁碟區。手動刪除孤立的保留容量磁碟區、以便將其容量用於其他作業。

System Manager會在首頁的通知區域中、以「回收未使用的容量」訊息提醒您孤立的保留容量磁碟區。您可以按一下*回收未使用的容量*來顯示「回收未使用的容量」對話方塊、您可以在其中刪除孤立的保留容量磁碟區。



== 保留容量的特性

* 在建立磁碟區期間、必須考量分配給保留容量的容量、以保留足夠的可用容量。
* 保留容量可以小於基本磁碟區（最小大小為8個mib）。
* 有些空間會被中繼資料佔用、但空間極少（192 KiB）、因此在判斷保留容量Volume的大小時、不需要將其納入考量。
* 保留容量無法從主機直接讀取或寫入。
* 每個讀寫快照磁碟區、快照群組、一致性群組成員磁碟區和鏡射配對磁碟區都有保留容量。

