---
permalink: sm-storage/how-volumes-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, copy, 
summary: Volume是資料容器、可管理及組織儲存陣列上的儲存空間。 
---
= 磁碟區的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volume是資料容器、可管理及組織儲存陣列上的儲存空間。

您可以從儲存陣列上可用的儲存容量建立磁碟區、並讓您輕鬆組織及使用系統資源。此概念類似於使用電腦上的資料夾/目錄來組織檔案、以便輕鬆快速地存取。

Volume是唯一可讓主機看到的資料層。在SAN環境中、磁碟區會對應至主機可見的邏輯單元編號（LUN）。LUN可容納使用儲存陣列支援的一或多個主機存取傳輸協定（包括FC、iSCSI和SAS）存取的使用者資料。



== 您可以從集區和Volume群組建立的Volume類型

Volume會從資源池或磁碟區群組中抽取容量。您可以從儲存陣列上的集區或磁碟區群組建立下列類型的磁碟區。

* *從資源池*-您可以從資源池建立磁碟區、做為完全資源配置（完整）磁碟區_或精簡資源配置（精簡）磁碟區。_
+
[NOTE]
====
System Manager介面不提供建立精簡磁碟區的選項。如果要建立精簡磁碟區、請使用命令列介面（CLI）。

====
* *從Volume Groups *（磁碟區群組）-您只能從Volume群組建立磁碟區、做為完全資源配置（完整）磁碟區_。


厚磁碟區和精簡磁碟區會以不同方式從儲存陣列抽取容量：

* 建立磁碟區時、會配置厚磁碟區的容量。
* 精簡磁碟區的容量會在寫入磁碟區時、以資料形式分配。


資源隨需配置有助於避免浪費分配的容量、並可節省企業前期儲存成本。不過、完整資源配置的優點是延遲較短、因為在建立大型磁碟區時、所有儲存設備都會一次分配。

[NOTE]
====
EF600和EF300儲存系統不支援精簡配置。

====


== 磁碟區的特性

集區或磁碟區群組中的每個磁碟區都可以根據儲存在其中的資料類型、擁有各自的特性。這些特性包括：

* *區段大小*-區段是儲存陣列移至磁碟區（RAID群組）中下一個磁碟機之前、儲存在磁碟機上的資料量（千位元組）、以千位元組（KiB）為單位。區段大小等於或小於Volume群組的容量。區段大小是固定的、無法變更集區的區段大小。
* * Capacity *：您可以從資源池或磁碟區群組中可用的可用容量建立磁碟區。在建立磁碟區之前、集區或磁碟區群組必須已經存在、而且必須有足夠的可用容量來建立磁碟區。
* *控制器所有權*-所有儲存陣列都可以有一或兩個控制器。在單一控制器陣列上、磁碟區的工作負載是由單一控制器管理。在雙控制器陣列上、磁碟區將會有一個偏好的控制器（A或B）「擁有」該磁碟區。在雙控制器組態中、磁碟區擁有權會使用自動負載平衡功能自動調整、以修正工作負載在控制器之間移動時的任何負載平衡問題。自動負載平衡功能可自動進行I/O工作負載平衡、確保來自主機的傳入I/O流量能在兩個控制器之間動態管理及平衡。
* * Volume assign*（Volume assign*）-您可以在建立Volume時或稍後、讓主機存取Volume。所有主機存取都是透過邏輯單元號碼（LUN）來管理。主機會偵測LUN、然後再將其指派給磁碟區。如果您要將磁碟區指派給多個主機、請使用叢集軟體來確保該磁碟區可供所有主機使用。
+
主機類型可針對主機可存取的磁碟區數量設定特定限制。當您建立要供特定主機使用的磁碟區時、請謹記此限制。

* *描述性名稱*：您可以任意命名Volume、但我們建議您將名稱描述成描述性名稱。


在磁碟區建立期間、每個磁碟區都會被分配容量、並指派名稱、區段大小（僅限磁碟區群組）、控制器擁有權、以及磁碟區對主機指派。磁碟區資料會視需要在不同的控制器之間自動進行負載平衡。
