---
permalink: sm-storage/how-ssd-cache-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, 
summary: SSD快取功能是以控制器為基礎的解決方案、可將最常存取的資料（「熱」資料）快取到較低延遲的固態磁碟機（SSD）、以動態加速系統效能。SSD快取僅用於主機讀取。 
---
= SSD快取的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSD快取功能是以控制器為基礎的解決方案、可將最常存取的資料（「熱」資料）快取到較低延遲的固態磁碟機（SSD）、以動態加速系統效能。SSD快取僅用於主機讀取。

[NOTE]
====
EF600或EF300儲存系統無法使用此功能。

====


== SSD快取與主要快取的比較

SSD快取是次快取、可搭配控制器動態隨機存取記憶體（DRAM）中的主快取一起使用。

SSD快取的運作方式與主要快取不同：

* 對於主快取、每個I/O作業都必須透過快取來登入資料、才能執行作業。
+
在主快取中、資料會在主機讀取後儲存在DRAM中。

* SSD快取僅用於將資料放入快取中、以改善整體系統效能。
+
在SSD快取中、資料會從磁碟區複製、並儲存在兩個內部RAID磁碟區（每個控制器一個）上、當您建立SSD快取時會自動建立這些磁碟區。



內部RAID磁碟區用於內部快取處理。這些磁碟區無法存取或顯示在使用者介面中。不過、這兩個磁碟區確實會根據儲存陣列中允許的磁碟區總數來計算。



== 如何使用SSD快取

智慧型快取會將資料放在較低延遲的磁碟機中、以便更快回應未來對該資料的要求。如果程式要求快取中的資料（稱為「快取命中率」）、則低延遲磁碟機可以為該交易提供服務。否則、會發生「快取記憶體遺漏」、而且必須從原始、較慢的磁碟機存取資料。隨著快取命中次數增加、整體效能也會提升。

當主機程式存取儲存陣列的磁碟機時、資料會儲存在SSD快取中。當主機程式再次存取相同的資料時、會從SSD快取讀取、而非從硬碟機讀取。一般存取的資料會儲存在SSD快取中。只有在無法從SSD快取讀取資料時、才能存取硬碟機。

SSD快取只有在有助於將資料放入快取中以改善整體系統效能時才會使用。

當CPU需要處理讀取資料時、請遵循下列步驟：

. 檢查DRAM快取。
. 如果在DRAM快取中找不到、請檢查SSD快取。
. 如果在SSD快取中找不到、請從硬碟機取得。如果資料被視為值得快取、請複製到SSD快取。




== 提升效能

將存取最多的資料（熱點）複製到SSD快取、可提高硬碟作業效率、縮短延遲、並加速讀寫速度。使用高效能SSD快取HDD磁碟區的資料、可改善I/O效能和回應時間。

簡單的磁碟區I/O機制可用於將資料移入或移出SSD快取。資料快取並儲存在SSD上之後、會在SSD快取上執行資料的後續讀取、因此不需要存取HDD磁碟區。



== SSD快取和磁碟機安全功能

若要在同時使用磁碟機安全性（已啟用安全功能）的磁碟區上使用SSD快取、則磁碟區的磁碟機安全功能和SSD快取必須相符。如果不相符、磁碟區將無法安全啟用。



== 實作SSD快取

若要實作SSD快取、請執行下列步驟：

. 建立SSD快取。
. 將SSD快取與要實作SSD讀取快取的磁碟區建立關聯。


[NOTE]
====
指派使用控制器SSD快取的任何Volume均不符合自動負載平衡傳輸的資格。

====