---
permalink: sm-storage/how-do-i-view-and-interpret-all-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, statistics 
summary: 您可以檢視SSD快取的名義統計資料和詳細統計資料。名義統計資料是詳細統計資料的子集。 
---
= 如何檢視及解讀所有SSD快取統計資料？
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視SSD快取的名義統計資料和詳細統計資料。名義統計資料是詳細統計資料的子集。

只有當您將所有SSD統計資料匯出至「.csv'」檔案時、才能檢視詳細的統計資料。當您檢閱及解讀統計資料時、請記住、有些解讀是由統計資料的組合所衍生而來。



== 名義統計資料

若要檢視SSD快取統計資料、請選取功能表：「Storage[資源池與磁碟區群組]」。選取您要檢視統計資料的SSD快取、然後選取功能表：More（更多）[View Statistics（檢視統計資料）]。名義統計資料會顯示在「檢視SSD快取統計資料」對話方塊中。

下列清單包含名義統計資料、這是詳細統計資料的子集。

[cols="25h,~"]
|===
| 名義統計 | 說明 


 a| 
讀取/寫入
 a| 
從啟用SSD快取的磁碟區讀取或主機寫入的主機總數。比較讀取與寫入的關係。讀取必須大於寫入、才能有效執行SSD快取作業。讀取與寫入的比率越高、快取的操作就越好。



 a| 
快取命中次數
 a| 
快取命中數的計數。



 a| 
快取命中數（%）
 a| 
衍生自快取命中/（讀取+寫入）。若要有效執行SSD快取作業、快取命中率應大於50%。少數人可能會指出以下幾點：

* 讀取與寫入的比率太小
* 不會重複讀取
* 快取容量太小




 a| 
快取分配（%）
 a| 
分配的SSD快取儲存容量、以此控制器可用SSD快取儲存空間的百分比表示。衍生自已分配位元組/可用位元組。快取分配百分比通常顯示為100%。如果這個數字低於100%、表示快取尚未暖機、或SSD快取容量大於所有存取的資料。在後一種情況下、較小的SSD快取容量可提供相同等級的效能。請注意、這並不表示快取資料已置於SSD快取中、只是準備步驟、資料才可置於SSD快取中。



 a| 
快取使用率（%）
 a| 
包含已啟用磁碟區資料的SSD快取儲存容量、以已配置SSD快取儲存設備的百分比表示。此值代表從使用者資料位元組/配置位元組衍生出來的SSD快取使用率或密度。快取使用率百分比通常低於100%、可能低得多。此數字顯示填滿快取資料的SSD快取容量百分比。這個數字低於100%、因為SSD快取區塊的每個分配單元（SSD快取區塊）被分成較小的單元、稱為子區塊、因此會稍微獨立地填滿。較高的數字通常較好、但效能增益可能很大、即使數量較少。

|===


== 詳細統計資料

詳細統計資料包括名義統計資料、以及其他統計資料。這些額外的統計資料會連同名義統計資料一起儲存、但與名義統計資料不同的是、它們不會顯示在「檢視SSD快取統計資料」對話方塊中。您只能在將統計資料匯出至「.csv'」檔案之後、才能檢視詳細的統計資料。

檢視「.csv'」檔案時、請注意、詳細統計資料會列在名義統計資料之後：

[cols="25h,~"]
|===
| 詳細統計資料 | 說明 


 a| 
讀取區塊
 a| 
主機讀取區塊數。



 a| 
寫入區塊
 a| 
主機寫入區塊數。



 a| 
完整熱門區塊
 a| 
快取命中的區塊數。完整的命中率區塊表示已從SSD快取中完全讀取的區塊數。SSD快取只有對完整快取點擊的作業有助於提升效能。



 a| 
部分命中數
 a| 
至少有一個區塊（但不是所有區塊）位於SSD快取中的主機讀取數量。部分命中率是SSD快取* Miss *、從基礎磁碟區讀取內容時會感到滿意。



 a| 
部分命中-區塊
 a| 
部分命中的區塊數。部分快取命中率和部分快取命中率區塊是由在SSD快取中只有部分資料的作業所造成。在此情況下、作業必須從快取的硬碟機（HDD）磁碟區取得資料。SSD快取對這類命中率沒有任何效能優勢。如果部分快取命中率區塊數高於完整的快取命中率區塊、則不同的I/O特性類型（檔案系統、資料庫或Web伺服器）可能會改善效能。相較於SSD快取變暖時的快取命中、預期「部分命中」和「未命中」數量會較多。



 a| 
未命中
 a| 
SSD快取中沒有任何區塊的主機讀取數量。當從基礎磁碟區滿足讀取要求時、就會發生SSD快取遺漏。相較於SSD快取變暖時的快取命中、預期「部分命中」和「未命中」數量會較多。



 a| 
未命中-區塊
 a| 
未命中的區塊數。



 a| 
填入動作（主機讀取）
 a| 
從基礎磁碟區複製資料到SSD快取的主機讀取數量。



 a| 
讀取行動（主機讀取）-區塊
 a| 
「讀取資料」動作（主機讀取）中的區塊數。



 a| 
填入動作（主機寫入）
 a| 
從基礎磁碟區複製資料到SSD快取的主機寫入次數。由於寫入I/O作業、未填滿快取組態設定的「讀取動作（主機寫入）」計數可能為零。



 a| 
讀取動作（主機寫入）-區塊
 a| 
「讀取動作（主機寫入）」中的區塊數。



 a| 
讓動作無效
 a| 
資料失效或從SSD快取移除的次數。每個主機寫入要求、每個具有強制單位存取（FUA）的主機讀取要求、每個驗證要求、以及其他情況下、都會執行快取無效作業。



 a| 
回收行動
 a| 
將SSD快取區塊重新用於其他基礎磁碟區和/或不同邏輯區塊定址（LBA）範圍的次數。若要有效執行快取作業、可回收的數量必須少於合併的讀取和寫入作業數。如果回收動作數量接近讀取和寫入的合併數量、SSD快取就會發生衝突。快取容量需要增加、或工作負載不適合搭配SSD快取使用。



 a| 
可用位元組
 a| 
SSD快取中可供此控制器使用的位元組數。



 a| 
已分配位元組
 a| 
此控制器從SSD快取配置的位元組數。從SSD快取配置的位元組可能是空的、或可能包含來自基礎磁碟區的資料。



 a| 
使用者資料位元組
 a| 
SSD快取中包含基礎磁碟區資料的已分配位元組數。可用位元組、已分配位元組和使用者資料位元組、用於計算快取分配百分比和快取使用率百分比。

|===