---
permalink: sm-storage/increase-capacity-of-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, capacity, volume 
summary: 您可以使用資源池或磁碟區群組中可用的可用容量、來增加磁碟區的報告容量（報告給主機的容量）。 
---
= 增加 SANtricity System Manager 中捲的容量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用資源池或磁碟區群組中可用的可用容量、來增加磁碟區的報告容量（報告給主機的容量）。

.開始之前
* 磁碟區相關聯的資源池或磁碟區群組中有足夠的可用容量可用。
* 磁碟區是最佳的、不會處於任何修改狀態。
* 精簡磁碟區的報告容量上限為256 TiB。
* 磁碟區中沒有使用熱備援磁碟機。（僅適用於Volume群組中的Volume。）



NOTE: 您一次只能將磁碟區容量擴充至 128 TiB 。

.關於這項工作
請記住、您未來可能會對此集區或Volume群組中的其他磁碟區有任何容量需求。請確定您允許足夠的可用容量來建立快照映像、快照磁碟區或遠端鏡像。

[NOTE]
====
增加磁碟區容量僅在某些作業系統上受支援。如果您在不受支援的主機作業系統上增加磁碟區容量、擴充的容量將無法使用、而且您無法還原原始磁碟區容量。

====
.步驟
. 從左側面板中，選擇功能表：Storage[Volumes]。
. 選擇要增加容量的磁碟區，然後按一下功能表：省略符號圖示 [增加容量]。
+
「確認增加容量」頁面隨即顯示。

. 選擇* Yes*繼續。
+
顯示 Increase Reported Capacity 頁面。

+
此頁面顯示磁碟區目前報告的容量、以及磁碟區相關資源池或磁碟區群組中的可用容量。

. 使用 *Increase reported capacity by adding...* 方塊將容量新增至目前可用的報告容量。您可以變更容量值，以 mebibytes（MiB）、gibibytes（GiB）或 tebibytes（TiB）顯示。
. 按一下*「增加*」。


.結果
* System Manager會根據您的選擇來增加磁碟區的容量。
* 選擇選單：Storage[Operations in Progress]，查看目前正在為所選磁碟區執行的容量擴容作業的進度。此操作可能耗時較長，並可能影響系統效能。


.完成後
擴充磁碟區容量之後、您必須手動增加檔案系統大小以符合需求。您的做法取決於所使用的檔案系統。如需詳細資料、請參閱主機作業系統文件。
