---
permalink: sm-storage/interpret-performance-data.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, interpret, performance data 
summary: 效能資料可引導您調整儲存陣列的效能。 
---
= 解讀效能資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
效能資料可引導您調整儲存陣列的效能。

解讀效能資料時、請記住、有幾個因素會影響儲存陣列的效能。下表說明要考量的主要領域。

[cols="25h,~"]
|===
| 效能資料 | 效能調校的影響 


 a| 
延遲（毫秒或毫秒）
 a| 
監控特定物件的I/O活動。

可能識別瓶頸物件：

* 如果在多個磁碟區之間共用一個磁碟區群組、則個別磁碟區可能需要自己的磁碟區群組、以改善磁碟機的連續效能並減少延遲。
* 有了資源池、磁碟機之間可能會出現較大的延遲、而工作負載可能不平均、因此延遲值較不具意義、而且一般而言較高。
* 磁碟機類型和速度會影響延遲。透過隨機I/O、更快的旋轉磁碟機可減少往返磁碟上不同位置的時間。
* 磁碟機太少、導致佇列命令越多、磁碟機處理命令的時間越長、系統的一般延遲也就越高。
* 較大的I/O延遲較大、因為傳輸資料所需的時間較多。
* 較高的延遲可能表示I/O模式是隨機的。具有隨機I/O的磁碟機延遲時間會比具有連續串流的磁碟機長。
* 通用磁碟區群組磁碟機或磁碟區之間的延遲差異、可能表示磁碟機速度緩慢。




 a| 
IOPS
 a| 
影響每秒輸入/輸出作業（IOPS或IOS/sec）的因素包括：

* 存取模式（隨機或連續）
* I/O大小
* RAID層級
* 快取區塊大小
* 是否啟用讀取快取
* 是否啟用寫入快取
* 動態快取讀取預先擷取
* 區段大小
* Volume群組或儲存陣列中的磁碟機數量


快取命中率越高、I/O速率就越高。啟用寫入快取的寫入I/O速率比停用的高。在決定是否為個別磁碟區啟用寫入快取時、請查看目前的IOPS和最大IOPS。循序I/O模式的速率應高於隨機I/O模式。無論您的I/O模式為何、都要啟用寫入快取、以最大化I/O速率並縮短應用程式回應時間。

您可以在磁碟區的IOPS統計資料中看到變更區段大小所導致的效能提升。嘗試判斷最佳區段大小、或使用檔案系統大小或資料庫區塊大小。



 a| 
MIB/s
 a| 
傳輸率或處理量率取決於應用程式I/O大小和I/O速率。一般而言、小型應用程式I/O要求可降低傳輸率、但可提供更快的I/O速率和更短的回應時間。應用程式I/O要求越大、傳輸率就越高。

瞭解典型的應用程式I/O模式、有助於判斷特定儲存陣列的最大I/O傳輸率。



 a| 
CPU
 a| 
此值是使用中處理容量的百分比。

您可能會注意到相同類型物件的CPU使用量差異。例如、某個控制器的CPU使用率很高、或隨著時間而增加、而另一個控制器的CPU使用量則較輕或較穩定。在此情況下、您可能想要將一個或多個磁碟區的控制器擁有權變更為CPU百分比較低的控制器。

您可能想要監控整個儲存陣列的CPU。如果隨著時間推移CPU持續增加、而應用程式效能降低、您可能需要新增儲存陣列。將儲存陣列新增至企業、就能以可接受的效能層級持續滿足應用程式需求。



 a| 
保留空間
 a| 
保留空間是指控制器、控制器主機通道和控制器磁碟機通道的剩餘效能。此值以百分比表示、代表這些物件可提供的最大效能與目前效能等級之間的落差。

* 對於控制器而言、保留空間是最大可能IOPS的百分比。
* 對於通道、保留空間是最大處理量（即MIB/s）的百分比讀取處理量、寫入處理量及雙向處理量均包含在計算中。


|===