---
permalink: sm-storage/performance-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, performance, terms 
summary: 瞭解效能術語如何適用於您的儲存陣列。 
---
= 效能術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解效能術語如何適用於您的儲存陣列。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
應用程式
 a| 
應用程式是一種軟體程式、例如SQL或Exchange。



 a| 
CPU
 a| 
CPU對於「中央處理器」來說很短。 CPU表示正在使用的儲存陣列處理容量百分比。



 a| 
主機
 a| 
主機是一種伺服器、可將I/O傳送至儲存陣列上的磁碟區。



 a| 
IOPS
 a| 
IOPS代表每秒輸入/輸出作業。



 a| 
延遲
 a| 
延遲是指要求（例如讀取或寫入命令）與主機或儲存陣列回應之間的時間間隔。



 a| 
LUN
 a| 
邏輯單元編號（LUN）是指派給主機用來存取磁碟區之位址空間的編號。磁碟區會以LUN的形式、以容量形式呈現給主機。

每個主機都有自己的LUN位址空間。因此、不同主機可以使用相同的LUN來存取不同的磁碟區。



 a| 
MIB
 a| 
mibibibyte（mega二進位位元組）的縮寫。一個mib是220、或1、048、576位元組。請比較MB、表示10個基本值。1 MB等於1、024位元組。



 a| 
物件
 a| 
物件是任何邏輯或實體儲存元件。

邏輯物件包括磁碟區群組、集區和磁碟區。實體物件包括儲存陣列、陣列控制器、主機和磁碟機。



 a| 
資源池
 a| 
資源池是邏輯分組的一組磁碟機。您可以使用集區來建立一個或多個可供主機存取的磁碟區。（您可以從集區或磁碟區群組建立磁碟區。）



 a| 
讀取
 a| 
讀取是「讀取作業」的簡短說明、當主機從儲存陣列要求資料時、就會發生這種情況。



 a| 
Volume
 a| 
Volume是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機所建立的邏輯元件、可用來存取儲存陣列上的儲存設備。

磁碟區是從集區或磁碟區群組中可用的容量所建立。磁碟區具有已定義的容量。雖然磁碟區可能包含多個磁碟機、但磁碟區會顯示為主機的一個邏輯元件。



 a| 
Volume名稱
 a| 
Volume名稱是在建立磁碟區時指派給該磁碟區的字元字串。您可以接受預設名稱、或提供更具說明性的名稱、以指示儲存在磁碟區中的資料類型。



 a| 
Volume群組
 a| 
Volume群組是具有共享特性之磁碟區的容器。Volume群組具有已定義的容量和RAID層級。您可以使用Volume群組來建立一個或多個可讓主機存取的磁碟區。（您可以從磁碟區群組或集區建立磁碟區。）



 a| 
工作負載
 a| 
工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。



 a| 
寫入
 a| 
從主機傳送資料至陣列以供儲存時、寫入是「寫入作業」的簡稱。

|===