---
permalink: sm-storage/replace-drive-logically-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, replace, drive, logically 
summary: 如果某個磁碟機故障、或是您因為其他原因而想要更換它、而且您的儲存陣列中有未指派的磁碟機、您可以邏輯地將故障磁碟機更換為未指派的磁碟機。如果您沒有未指派的磁碟機、您可以更換磁碟機。 
---
= 以邏輯方式更換磁碟機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果某個磁碟機故障、或是您因為其他原因而想要更換它、而且您的儲存陣列中有未指派的磁碟機、您可以邏輯地將故障磁碟機更換為未指派的磁碟機。如果您沒有未指派的磁碟機、您可以更換磁碟機。

.關於這項工作
當您以未指派的磁碟機邏輯取代磁碟機時、未指派的磁碟機便會被指派、然後成為相關聯的集區或磁碟區群組的永久成員。您可以使用「邏輯置換」選項來取代下列類型的磁碟機：

* 故障磁碟機
* 遺失磁碟機
* Recovery Guru已通知您SSD磁碟機即將停產
* Recovery Guru已通知您即將發生磁碟機故障的硬碟機
* 指派的磁碟機（僅適用於磁碟區群組中的磁碟機、而非資源池中的磁碟機）


更換磁碟機必須具備下列特性：

* 處於最佳狀態
* 處於「未指派」狀態
* 與要更換的磁碟機相同的屬性（媒體類型、介面類型等）
* 相同的FDE功能（建議使用、但不需要）
* 相同的DA功能（建議使用、但不需要）


.步驟
. 選取*硬體*。
. 如果圖形顯示控制器、請按一下*顯示機櫃正面*。
+
圖形會變更、以顯示磁碟機而非控制器。

. 按一下您要邏輯置換的磁碟機。
+
此時會出現磁碟機的內容功能表。

. 按一下*邏輯置換*。
. *選用：*選取「*更換後故障磁碟機*」核取方塊、即可在更換原始磁碟機後故障。
+
此核取方塊只有在原始指派的磁碟機未故障或遺失時才會啟用。

. 從*選取更換磁碟機*表格中、選取您要使用的更換磁碟機。
+
下表僅列出與您要更換之磁碟機相容的磁碟機。如有可能、請選取一個磁碟機、以維持磁碟櫃遺失保護和藥櫃遺失保護。

. 按一下*取代*。
+
如果原始磁碟機故障或遺失、則會使用同位元檢查資訊、在替換磁碟機上重建資料。此重建作業會自動開始。磁碟機的故障指示燈會熄滅、且集區或磁碟區群組中磁碟機的活動指示燈會開始閃亮。

+
如果原始磁碟機沒有故障或遺失、其資料會複製到更換磁碟機。此複製作業會自動開始。複製作業完成後、系統會將原始磁碟機切換至「Unassigned（未指派）」狀態、或者如果核取方塊已選取、則會切換至「故障」狀態。


