---
permalink: sm-storage/rtv-what-do-i-need-to-know-before-starting-a-remote-storage-import.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, import 
summary: 遠端儲存功能可讓您將遠端儲存系統的資料複製到本機E系列儲存系統上的磁碟區。使用此功能之前、請先檢閱下列準則。 
---
= 在開始遠端儲存匯入之前、我需要知道什麼？
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
遠端儲存功能可讓您將遠端儲存系統的資料複製到本機E系列儲存系統上的磁碟區。使用此功能之前、請先檢閱下列準則。



== 組態

在建立遠端儲存匯入之前、您必須先完成下列動作並確認下列條件：

* 確保本機E系列儲存系統的每個控制器都能與遠端儲存系統建立iSCSI連線。
* 在本機E系列儲存系統上、建立匯入作業的目標磁碟區。請確定磁碟區的容量等於或大於來源磁碟區、區塊大小與來源磁碟區相符、且未對應。請參閱 link:create-volumes.html["建立磁碟區"]。
* 使用iSCSI合格名稱（IQN）、將本機E系列儲存系統設定為遠端系統上的主機。您可以從功能表：設定[系統> iSCSI設定>目標IQN]檢視IQN。此外、請務必根據所使用的系統設定適當的主機類型。
* 停止所有I/O、卸載任何檔案系統、並移除遠端儲存系統上所選磁碟區的所有主機或應用程式指派。
* 將磁碟區指派給新建立的本機E系列儲存系統主機、以供遠端儲存系統使用。
* 從遠端儲存系統收集下列資訊、以便建立匯入：
+
** iSCSI合格名稱（IQN）
** iSCSI IP位址
** 來源資料來源的遠端儲存設備LUN編號


* 匯入程序開始後、整個本機目的地磁碟區會被複製的資料覆寫。任何寫入本機目的地磁碟區的新資料、都會在建立匯入之後、傳播到遠端儲存設備上的磁碟區。因此、建議您在開始匯入程序之前、先備份遠端儲存系統上的磁碟區。




== 匯入程序

下列步驟概述匯入程序。

. 存取System Manager介面、然後前往*遠端儲存*頁面。選取*匯入*以開始建立新的匯入。如需詳細指示、請參閱 link:rtv-import-remote-storage.html["匯入遠端儲存設備"]。
+
如果要執行離線匯入、請勿在匯入完成之前對應目的地Volume。

. 監控匯入進度。
+
匯入開始後、即可對應目標磁碟區。完成匯入作業所需的時間取決於遠端儲存設備（來源Volume）的大小、匯入的優先順序設定、以及儲存系統及其相關磁碟區的I/O負載量。

+
匯入完成後、目標磁碟區即為來源的複本。

. 當您準備中斷對應關係時、請從「*作業進行中*」面板對匯入物件執行*中斷連線*。


一旦匯入中斷連線、本機目的地的效能就會恢復正常、不再受到遠端連線的影響。



== 限制

遠端儲存功能有下列限制：

* 鏡射必須停用。
* E系列系統上的目的地Volume不得有快照。
* 在開始匯入之前、不得將E系列系統上的目的地Volume對應至任何主機。
* E系列系統上的目的地Volume必須停用資源資源配置。
* 不支援將遠端儲存磁碟區直接對應至主機或多個主機。
* 不支援Web服務Proxy。
* 不支援iSCSI CHAP機密。
* 不支援SMcli。
* 不支援VMware資料存放區。
* 當存在匯入配對時、一次只能升級關係/匯入配對中的一個儲存系統。




== 其他資訊

如需遠端儲存功能的詳細資訊、請參閱 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["遠端儲存技術報告"^]。
