---
permalink: sm-storage/rtv-remote-storage-volume-requirements.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, volume, requirements 
summary: 用於匯入的磁碟區必須符合大小、狀態及其他條件的要求。 
---
= 遠端儲存Volume需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
用於匯入的磁碟區必須符合大小、狀態及其他條件的要求。



== 遠端儲存Volume

匯入的來源Volume稱為「遠端儲存Volume」。 此Volume必須符合下列條件：

* 無法成為另一個匯入的一部分
* 必須具有線上狀態


匯入開始後、控制器韌體會在背景中建立遠端儲存磁碟區。由於背景程序、遠端儲存磁碟區在System Manager中無法管理、只能用於匯入作業。

建立後、遠端儲存Volume會與E系列系統上的任何其他標準Volume一樣處理、但下列例外情況除外：

* 可作為遠端儲存設備的Proxy。
* 無法做為其他Volume複本或快照的候選對象。
* 匯入進行中時、無法變更「資料保證」設定。
* 無法對應至任何主機、因為這些主機是專為匯入作業保留的。


每個遠端儲存磁碟區只會與一個遠端儲存物件相關聯、但是一個遠端儲存物件可以與多個遠端儲存磁碟區相關聯。遠端儲存磁碟區使用下列組合加以唯一識別：

* 遠端儲存物件識別碼
* 遠端儲存設備LUN編號




== 目標Volume候選對象

目標Volume是本機E系列系統上的目的地Volume。目的地Volume必須符合下列條件：

* 必須是RAID/DDP Volume。
* 容量必須等於或大於遠端儲存Volume。
* 區塊大小必須與遠端儲存磁碟區相同。
* 必須具有有效狀態（最佳）。
* 無法建立下列任何關係：磁碟區複本、快照複本、非同步或同步鏡射。
* 無法進行任何重新設定作業：動態Volume擴充、動態容量擴充、動態區段大小、動態RAID移轉、動態容量減量、 或重組。
* 無法在匯入開始之前將其對應至主機（不過、匯入完成後即可將其對應）。
* 無法啟用Flash讀取快取（FRC）。


System Manager會在匯入遠端儲存精靈中自動檢查這些需求。只有符合所有需求的磁碟區才會顯示以供選擇目的地磁碟區。
