---
permalink: sm-storage/rtv-import-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, import, remote, storage 
summary: 若要從遠端系統將儲存設備匯入本機E系列儲存系統、請使用匯入遠端儲存精靈。 
---
= 在 SANtricity System Manager 中導入遠端存儲
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要從遠端系統將儲存設備匯入本機E系列儲存系統、請使用匯入遠端儲存精靈。

.開始之前
* E系列儲存系統必須設定為與遠端儲存系統通訊。
+
[NOTE]
====
遠端儲存功能的使用者指南中說明硬體組態、您可從E系列與SANtricity 版次文件中心取得、網址為 https://docs.netapp.com/us-en/e-series/remote-storage-volumes/setup-remote-volumes-concept.html["設定硬體"^]和中的 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["遠端儲存技術報告"^]。

====
* 對於遠端儲存系統、請收集下列資訊：
+
** iSCSI IQN
** iSCSI IP位址
** 遠端儲存設備（來源Volume）的LUN編號


* 對於本機E系列儲存系統、請建立或選取要用於資料匯入的磁碟區。請參閱 link:create-volumes.html["建立磁碟區"]。目標Volume必須符合下列需求：
+
** 符合遠端儲存設備（來源Volume）的區塊大小。
** 容量等於或大於遠端儲存設備。
** 狀態為Optimal（最佳）且可供使用。




如需完整的需求清單、請參閱 link:rtv-remote-storage-volume-requirements.html["遠端儲存Volume需求"]。

* *建議：*在開始匯入程序之前、先備份遠端儲存系統上的磁碟區。


.關於這項工作
在此工作中、您可以在遠端儲存設備和本機E系列儲存系統上的磁碟區之間建立對應。完成組態之後、就會開始匯入。

[NOTE]
====
由於許多變數會影響匯入作業及其完成時間、因此建議您先執行較小的「測試」匯入。使用這些測試可確保所有連線都能正常運作、並確保匯入作業在適當的時間內完成。

====
.步驟
. 選取功能表：Storage[遠端儲存設備]。
. 按一下*匯入遠端儲存設備*。
+
隨即顯示匯入遠端儲存設備的精靈。

. 在「設定來源」面板的*步驟1A*中、輸入連線資訊。如果您要新增另一個iSCSI連線、請按一下*「新增其他IP位址」*、以加入遠端儲存設備的其他IP位址。完成後、按一下*下一步*。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
名稱
 a| 
在System Manager介面中輸入遠端儲存設備的名稱、以加以識別。

名稱最多可包含30個字元、而且只能包含字母、數字和下列特殊字元：底線（_）、破折號（-）和雜湊符號（#）。名稱不得包含空格。



 a| 
iSCSI連線內容
 a| 
輸入遠端儲存設備的連線內容：

** * iSCSI合格名稱（IQN）*：輸入iSCSI IQN。
** * IP位址*：輸入IPV4位址。
** *連接埠*：輸入用於來源與目標裝置之間通訊的連接埠號碼。依預設、連接埠號碼為3260。


|===
====
+
按「*下一步*」之後、「組態來源」面板的*步驟1b*就會顯示出來。

. 在「* LUN*」欄位中、選取要作為來源的遠端儲存設備LUN編號、然後按「*下一步*」。
+
「設定目標」面板隨即開啟、並顯示要做為匯入目標的Volume候選項目。由於區塊大小、容量或磁碟區可用度的關係、部分磁碟區不會顯示在候選清單中。

. 從表中選取E系列儲存系統上的目標Volume。如有需要、請使用滑桿變更匯入優先順序。單擊 * 下一步 * 。在下一個對話方塊中輸入「Continue」（繼續）、然後按一下「* Continue *（繼續*）」以確認作業。
+
如果目標磁碟區的容量大於來源磁碟區、則不會向連接至E系列系統的主機報告額外容量。若要使用新容量、您必須在匯入作業完成並中斷連線之後、在主機上執行檔案系統擴充作業。

+
在對話方塊中確認組態之後、將會顯示「檢閱」面板。

. 在「檢閱」面板中、確認設定正確無誤、然後按一下「*完成*」以啟動匯入。
+
另一個對話方塊隨即開啟、詢問您是否要啟動另一個匯入。

. 如有需要、請按一下* Yes（是）*以建立另一個遠端儲存匯入。按一下「組態來源」面板的*是*返回*步驟1A*、您可以在其中選取現有組態或新增組態。如果您不想建立其他匯入項目、請按一下「*否*」結束對話方塊。
+
匯入程序開始後、整個目標磁碟區會被複製的資料覆寫。如果主機在此程序期間將任何新資料寫入目標磁碟區、則新資料會傳回遠端裝置（來源磁碟區）。

. 在「遠端儲存」面板下的「檢視作業」對話方塊中、檢視作業進度。


.結果
完成匯入作業所需的時間取決於遠端儲存系統的大小、匯入的優先順序設定、以及儲存系統及其相關磁碟區的I/O負載量。

匯入完成後、本機磁碟區即為遠端儲存設備的複本。

.完成後
當您準備好中斷兩個磁碟區之間的關係時、請從「作業進行中」檢視中選取匯入物件上的*中斷連線*。一旦關係中斷連線、本機磁碟區的效能就會恢復正常、不再受到遠端連線的影響。
