---
permalink: sm-storage/schedule-snapshot-images.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, schedule, snapshot, images 
summary: 您可以建立快照排程、以便在基礎磁碟區發生問題時進行還原、並執行排程備份。您可以在每日、每週或每月的排程中、隨時建立基礎磁碟區或快照一致性群組的快照。 
---
= 排程快照映像
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立快照排程、以便在基礎磁碟區發生問題時進行還原、並執行排程備份。您可以在每日、每週或每月的排程中、隨時建立基礎磁碟區或快照一致性群組的快照。

.開始之前
基本Volume必須處於最佳狀態。

.關於這項工作
此工作說明如何為現有的快照一致性群組或基礎磁碟區建立快照排程。

[NOTE]
====
您也可以在建立基礎磁碟區或快照一致性群組的快照映像的同時、建立快照排程。

====
.步驟
. 請執行下列其中一項動作來建立快照排程：
+
** 選取功能表：Storage[磁碟區]。
+
選取此快照排程的物件（Volume或Snapshot一致性群組）、然後選取功能表：複製服務[建立快照排程]。

** 選取功能表：Storage[快照]。
+
選取*排程*索引標籤、然後按一下*建立*。



. 選取此快照排程的物件（Volume或Snapshot一致性群組）、然後按一下*「Next（下一步）」*。
+
此時會出現Create Snapshot Schedule（建立Snapshot排程）對話方塊。

. 請執行下列其中一項動作：
+
** *使用其他快照物件中先前定義的排程*。
+
確定顯示進階選項。按一下*顯示更多選項*。按一下*匯入排程*、選取含有您要匯入排程的物件、然後按一下*匯入*。

** *修改基本或進階選項*。
+
在對話方塊的右上角、按一下*顯示更多選項*以顯示所有選項、然後參閱下表。



+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
*基本設定*



 a| 
選取天
 a| 
選取每週的個別日期以取得快照映像。



 a| 
開始時間
 a| 
從下拉式清單中、為每日快照選取新的開始時間（選項以每小時為單位提供）。開始時間預設為比目前時間早一個半小時。



 a| 
時區
 a| 
從下拉式清單中、選取陣列的時區。



 a| 
*進階設定*



 a| 
日/月
 a| 
請選擇下列其中一個選項：

** *每日/每週*-選擇同步快照的個別日期。如果您想要每日排程、也可以選取右上角的*全日*核取方塊。
** *每月/每年*-選擇同步快照的個別月份。在「*於日*」欄位中、輸入每月進行同步的天數。有效輸入項目為* 1 *至* 31 *、*最後*。您可以使用分號或分號分隔多天。使用連字號表示包含日期。例如：1、3、4、10-15、Last。如果您想要每月排程、也可以選取右上角的*全月*核取方塊。




 a| 
開始時間
 a| 
從下拉式清單中、為每日快照選取新的開始時間（選項以每小時為單位提供）。開始時間預設為比目前時間早一個半小時。



 a| 
時區
 a| 
從下拉式清單中、選取陣列的時區。



 a| 
每天快照數/快照之間的時間
 a| 
選取每天要建立的快照映像數目。如果您選取多個、也可以選取快照映像之間的時間。對於多個快照映像、請確定您擁有足夠的保留容量。



 a| 
立即建立Snapshot映像？
 a| 
選取此核取方塊可建立即時映像、以及您正在排程的自動映像。



 a| 
開始/結束日期或無結束日期
 a| 
輸入開始同步的開始日期。同時輸入結束日期或選擇*無結束日期*。

|===
====
. 請執行下列其中一項動作：
+
** 如果物件是快照一致性群組、請按一下「*建立*」以接受設定並建立排程。
** 如果物件是磁碟區、請按一下*「下一步」*、為快照映像分配保留容量。
+
Volume候選資料表僅顯示支援指定保留容量的候選資料。保留容量是指用於任何複製服務作業和儲存物件的實體配置容量。主機無法直接讀取。



. 使用微調方塊來分配快照映像的保留容量。請執行下列其中一項動作：
+
** *接受預設設定。*
+
使用此建議選項、以預設設定分配快照映像的保留容量。

** *配置您自己的保留容量設定、以滿足您的資料儲存需求。*
+
如果您變更預設的保留容量設定、請按一下*重新整理候選項目*、針對您指定的保留容量重新整理候選清單。

+
使用下列準則來分配保留容量：

+
*** 保留容量的預設設定為基礎Volume容量的40%。通常這種容量是足夠的。
*** 所需容量會因磁碟區I/O寫入的頻率和大小、以及快照映像集合的數量和持續時間而有所不同。




. 單擊 * 下一步 * 。
+
「編輯設定」對話方塊隨即出現。

. 視需要編輯快照排程的設定、然後按一下*完成*。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
* Snapshot映像限制*



 a| 
在下列情況下啟用自動刪除快照映像：
 a| 
如果您想要在指定限制之後自動刪除快照影像、請保持核取方塊的選取狀態；請使用「微調」方塊來變更限制。如果清除此核取方塊、快照映像建立會在32個映像之後停止。



 a| 
*保留容量設定*



 a| 
提醒我...
 a| 
使用微調方塊來調整當排程的保留容量即將滿時、系統傳送警示通知的百分比點。

當排程的保留容量超過指定臨界值時、請使用預先通知來增加保留容量、或在剩餘空間用盡之前刪除不必要的物件。



 a| 
完整保留容量的原則
 a| 
請選擇下列其中一項原則：

** *清除最舊的快照映像*：系統會自動清除最舊的快照映像、釋放快照映像保留容量、以便在快照群組中重複使用。
** *拒絕寫入基本磁碟區*-當保留容量達到其定義的最大百分比時、系統會拒絕任何I/O寫入要求、以觸發保留容量存取。


|===
====

