---
permalink: sm-storage/start-snapshot-image-rollback-for-consistency-group-member-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, snapshot, consistency, group, member, volumes 
summary: 您可以執行復原作業來變更快照一致性群組成員磁碟區的內容、以符合儲存在快照映像中的內容。 
---
= 針對Snapshot一致性群組成員磁碟區、開始Snapshot映像復原
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行復原作業來變更快照一致性群組成員磁碟區的內容、以符合儲存在快照映像中的內容。

復原作業不會變更與快照一致性群組相關聯的快照映像內容。

.開始之前
* 有足夠的保留容量可供開始復原作業。
* 選取的快照映像是最佳的、選取的磁碟區是最佳的。
* 選取的磁碟區尚未執行復原作業。


.關於這項工作
復原開始順序可讓您在快照一致性群組的快照映像上開始復原、同時提供新增儲存容量的選項。您一次無法為快照一致性群組啟動多個復原作業。

[NOTE]
====
主機可立即存取新的回溯磁碟區、但現有的成員磁碟區在復原開始後、不再允許主機讀寫存取。您可以在開始復原之前、先建立成員磁碟區的快照映像、以保留預先復原的基礎磁碟區以供還原之用。

====
開始復原快照一致性群組的快照映像的程序是多步驟程序。



== 步驟1：選取成員

您必須選取要回溯的成員磁碟區。

.步驟
. 選取功能表：Storage[快照]。
. 選擇* Snapshot imags*（快照映像*）選項卡。
. 選取快照一致性群組快照映像、然後選取功能表：「Rollback [Start]（回溯[開始]）」。
+
此時會出現「開始復原」對話方塊。

. 選取成員磁碟區或磁碟區。
. 按一下「*下一步*」、然後執行下列其中一項：
+
** 如果任何選取的成員磁碟區與儲存快照映像的多個保留容量物件相關聯、則會出現「Review Capacity（檢閱容量）」對話方塊。前往 <<步驟2：審查容量>>。
** 如果所選的成員磁碟區都沒有與儲存快照映像的多個保留容量物件相關聯、則會出現「編輯優先順序」對話方塊。前往 <<步驟3：編輯優先順序>>。






== 步驟2：審查容量

如果您選取了與多個保留容量物件相關聯的成員磁碟區、例如快照群組和保留容量磁碟區、您可以檢閱並增加回溯磁碟區的保留容量。

.步驟
. 在保留容量極低（或零）的任何成員磁碟區旁、按一下「*編輯*」欄中的「*增加容量*」連結。
+
此時會出現「增加保留容量」對話方塊。

. 使用微調方塊來調整容量百分比、然後按一下*增加*。
+
如果包含所選儲存物件的集區或Volume群組中不存在可用容量、且儲存陣列具有未指派的容量、您可以新增容量。您可以建立新的資源池或磁碟區群組、然後使用該資源池或磁碟區群組上的新可用容量重試此作業。

. 按一下*下一步*、然後前往 <<步驟3：編輯優先順序>>。
+
「編輯優先順序」對話方塊隨即出現。





== 步驟3：編輯優先順序

您可以視需要編輯復原作業的優先順序。

.關於這項工作
復原優先順序會決定有多少系統資源專用於復原作業、而犧牲系統效能。

.步驟
. 使用滑桿視需要調整復原優先順序。
. 確認您要執行此作業、然後按一下「*完成*」。


.結果
System Manager會執行下列動作：

* 使用儲存在所選快照映像上的內容、還原快照一致性群組成員磁碟區。
* 使回溯磁碟區立即可供主機存取。您不需要等待復原作業完成。


.完成後
選取功能表：首頁[檢視進行中的作業]以檢視復原作業的進度。

如果復原作業不成功、則會暫停作業。您可以繼續暫停的作業、如果仍不成功、請依照Recovery Guru程序修正問題、或聯絡技術支援部門。
