---
permalink: sm-storage/start-snapshot-image-rollback-for-base-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, base, volume 
summary: 您可以執行復原作業來變更基礎磁碟區的內容、以符合儲存在快照映像中的內容。復原作業不會變更與基礎磁碟區相關聯的快照映像內容。 
---
= 為基礎磁碟區開始Snapshot映像復原
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行復原作業來變更基礎磁碟區的內容、以符合儲存在快照映像中的內容。

復原作業不會變更與基礎磁碟區相關聯的快照映像內容。

.開始之前
* 有足夠的保留容量可供開始復原作業。
* 選取的快照映像是最佳的、選取的磁碟區是最佳的。
* 選取的磁碟區尚未執行復原作業。


.關於這項工作
復原開始順序可讓您在基礎磁碟區的快照映像上開始復原、同時提供新增儲存容量的選項。您一次無法為基礎磁碟區啟動多個復原作業。

[NOTE]
====
主機可以立即存取新的回溯式基礎Volume、但現有的基礎Volume不允許主機在回溯開始後進行讀寫存取。您可以在開始復原之前、先建立基礎磁碟區的快照、以保留復原前的基礎磁碟區以供還原。

====
.步驟
. 選取功能表：Storage[快照]。
. 選擇* Snapshot imags*（快照映像*）選項卡。
. 選取快照映像、然後選取功能表：「Rollback [Start]（回溯[開始]）」。
+
出現「Confirm Start Rollback（確認開始回溯）」對話方塊。

. *可選：*如果需要，請選擇選項*增加容量*。
+
此時會出現「增加保留容量」對話方塊。

+
.. 使用微調方塊來調整容量百分比。
+
如果包含所選儲存物件的集區或Volume群組中不存在可用容量、且儲存陣列具有未指派的容量、您可以新增容量。您可以建立新的資源池或磁碟區群組、然後使用該資源池或磁碟區群組上的新可用容量重試此作業。

.. 按一下*「增加*」。


. 確認您要執行此作業、然後按一下「*回復*」。


.結果
System Manager會執行下列動作：

* 使用儲存在所選快照映像上的內容來還原磁碟區。
* 使回溯磁碟區立即可供主機存取。您不需要等待復原作業完成。


.完成後
選取功能表：首頁[檢視進行中的作業]以檢視復原作業的進度。

如果復原作業不成功、則會暫停作業。您可以繼續暫停的作業、如果仍不成功、請依照Recovery Guru程序修正問題、或聯絡技術支援部門。
