---
permalink: sm-storage/types-of-copy-volume-operations.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: 您可以執行離線複製磁碟區作業或線上複製磁碟區作業。離線作業會從來源磁碟區讀取資料、然後將其複製到目標磁碟區。線上作業使用快照磁碟區做為來源、並將其資料複製到目標磁碟區。 
---
= 複製Volume作業的類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以執行「離線複製磁碟區」作業或「線上複製磁碟區」作業。離線作業會從來源磁碟區讀取資料、然後將其複製到目標磁碟區。線上作業使用快照磁碟區做為來源、並將其資料複製到目標磁碟區。

為確保資料完整性、在任一類型的複製Volume作業期間、所有至目標Volume的I/O活動都會暫停。此暫停的原因是、在程序完成之前、目標Volume上的資料狀態不一致。

離線和線上複製Volume作業如下所述。



== 離線複製Volume作業

離線複製Volume關係是指來源Volume與目標Volume之間的關係。離線複本會從來源磁碟區讀取資料、並將其複製到目標磁碟區、同時在複本進行期間暫停所有對來源磁碟區的更新。來源Volume的所有更新都會暫停、以避免在目標Volume上建立時間不一致的情況。

[cols="25h,~"]
|===
2+| 離線複製作業的相關資訊 


 a| 
讀寫要求
 a| 
* 參與離線複本的來源磁碟區可用於唯讀I/O活動、而複製磁碟區作業的狀態為「進行中」或「待處理」。
* 離線複本完成後、允許寫入要求。
* 若要防止寫入保護的錯誤訊息、請勿存取參與「複製Volume」作業且狀態為「進行中」的來源Volume。




 a| 
日誌記錄檔案系統
 a| 
* 如果來源磁碟區已格式化為日誌記錄檔案系統、則儲存陣列控制器可能會拒絕向來源磁碟區發出讀取要求的任何嘗試、並可能出現錯誤訊息。
* 日誌記錄檔案系統驅動程式會在嘗試發出讀取要求之前發出寫入要求。控制器會拒絕寫入要求、而且由於遭拒的寫入要求、可能不會發出讀取要求。這種情況可能會導致出現錯誤訊息、表示來源磁碟區受到寫入保護。
* 若要避免此問題發生、請勿嘗試在「複製Volume」作業狀態為「進行中」時、存取參與離線複本的來源Volume。


|===


== 線上複製Volume作業

線上複製磁碟區關係是快照磁碟區與目標磁碟區之間的關係。您可以在來源磁碟區上線時啟動複製磁碟區作業、以便寫入資料。此功能是透過建立磁碟區快照、並將快照作為複本的實際來源磁碟區來實現。

當您針對來源Volume啟動複製Volume作業時、System Manager會建立基礎Volume的快照映像、並在基礎Volume的快照映像與目標Volume之間建立複本關係。使用快照映像作為來源磁碟區、可讓儲存陣列在複本進行期間繼續寫入來源磁碟區。

在線上複製作業期間、由於寫入時複製程序、效能會受到影響。線上複本完成後、基礎Volume效能就會恢復。

[cols="25h,~"]
|===
2+| 線上複製作業須知 


 a| 
可以使用哪種磁碟區？
 a| 
* 建立時間點映像的磁碟區稱為基礎磁碟區、必須是儲存陣列上的標準磁碟區或精簡磁碟區。
* 目標Volume可以是Volume群組中的標準Volume、也可以是集區中的標準Volume。目標Volume不能是快照群組中的精簡磁碟區或基礎磁碟區。
* 您可以使用線上複製Volume功能、將資料從精簡磁碟區複製到位於相同儲存陣列之集區中的標準磁碟區。但您無法使用複製Volume功能、將資料從標準Volume複製到精簡Volume。




 a| 
基礎Volume效能
 a| 
* 如果使用作為複本來源的快照磁碟區為作用中、則基礎磁碟區效能會因為寫入時複製作業而降級。複本完成後、快照會停用、並還原基本磁碟區效能。雖然快照已停用、但保留容量磁碟區和複本關係仍維持不變。




 a| 
建立的磁碟區類型
 a| 
* 快照磁碟區和保留容量磁碟區會在線上複製作業期間建立。
* 快照磁碟區並非實際含有資料的磁碟區、而是特定時間內包含在磁碟區上的資料參考。
* 針對所擷取的每個快照、系統會建立保留容量磁碟區、以保留快照的資料。保留容量Volume僅用於管理快照映像。




 a| 
保留容量Volume
 a| 
* 在修改來源磁碟區上的資料區塊之前、要修改的區塊內容會複製到保留容量磁碟區、以供妥善保存。
* 由於保留容量磁碟區會將原始資料的複本儲存在這些資料區塊中、因此對這些資料區塊的進一步變更只會寫入來源磁碟區。
* 線上複製作業所使用的磁碟空間比完整實體複本少、因為保留容量磁碟區中儲存的資料區塊僅限自快照時間起變更的區塊。


|===