---
permalink: sm-storage/volume-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, terms 
summary: 瞭解Volume術語如何適用於您的儲存陣列。 
---
= Volume術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解Volume術語如何適用於您的儲存陣列。



== 所有Volume類型

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
已分配容量
 a| 
您可以使用已分配的容量來建立磁碟區和複製服務作業。

配置的容量和報告的容量對於大型磁碟區而言相同、但對於精簡磁碟區則不同。對於較厚的Volume、實體配置的空間等於報告給主機的空間。對於精簡磁碟區、回報容量是報告給主機的容量、而分配的容量則是目前分配給寫入資料的磁碟機空間量。



 a| 
應用程式
 a| 
應用程式是SQL Server或Exchange等軟體。您可以定義一或多個工作負載來支援每個應用程式。對於某些應用程式、系統會自動建議最佳化儲存設備的Volume組態。磁碟區組態中包含I/O類型、區段大小、控制器擁有權、讀寫快取等特性。



 a| 
容量
 a| 
容量是指您可以儲存在磁碟區中的資料量。



 a| 
控制器擁有權
 a| 
控制器擁有權定義指定為磁碟區擁有或主要控制器的控制器。磁碟區可以有偏好的控制器（A或B）「擁有」該磁碟區。使用「自動負載平衡」功能自動調整Volume擁有權、以修正工作負載在控制器之間移動時的任何負載平衡問題。自動負載平衡可提供自動化的I/O工作負載平衡、確保來自主機的傳入I/O流量能在兩個控制器之間動態管理和平衡。



 a| 
動態快取讀取預先擷取
 a| 
動態快取讀取預先擷取可讓控制器在從磁碟機讀取資料區塊到快取時、將其他循序資料區塊複製到快取。此快取可增加日後從快取中填入資料要求的機會。對於使用連續I/O的多媒體應用程式而言、動態快取讀取預先擷取非常重要預先擷取至快取的資料速率和數量、是根據主機讀取的速率和要求大小而自行調整。隨機存取不會將資料預先擷取至快取。停用讀取快取時、此功能不適用。

對於精簡磁碟區、動態快取讀取預先擷取一律停用、無法變更。



 a| 
可用容量區域
 a| 
可用容量區域是指在建立磁碟區期間、刪除磁碟區或未使用所有可用容量所產生的可用容量。當您在具有一或多個可用容量區域的Volume群組中建立Volume時、該Volume的容量僅限於該Volume群組中最大的可用容量區域。例如、如果某個Volume群組的可用容量總計為15 GiB、而最大的可用容量區域則為10 GiB、則您可以建立的最大磁碟區為10 GiB。

透過整合可用容量、您可以從Volume群組中的可用容量上限建立額外的Volume。



 a| 
主機
 a| 
主機是一種伺服器、可將I/O傳送至儲存陣列上的磁碟區。



 a| 
主機叢集
 a| 
主機叢集是一組主機。您可以建立主機叢集、以便輕鬆將相同的磁碟區指派給多個主機。



 a| 
熱備援磁碟機
 a| 
熱備援磁碟機僅適用於磁碟區群組。熱備援磁碟機不含資料、可在磁碟區群組中的RAID 1、RAID 3、RAID 5或RAID 6磁碟區故障時作為待命。熱備援磁碟機可為儲存陣列新增一層備援。



 a| 
LUN
 a| 
邏輯單元編號（LUN）是指派給主機用來存取磁碟區之位址空間的編號。磁碟區會以LUN的形式、以容量形式呈現給主機。

每個主機都有自己的LUN位址空間。因此、不同主機可以使用相同的LUN來存取不同的磁碟區。



 a| 
媒體掃描
 a| 
媒體掃描提供一種偵測磁碟機媒體錯誤的方法、可在磁碟機正常讀取或寫入資料之前找到這些錯誤。媒體掃描會以背景作業的形式執行、並掃描定義之使用者磁碟區中的所有資料和備援資訊。



 a| 
命名空間
 a| 
命名空間是NVM儲存設備、其格式化為區塊存取。它類似於SCSI中的邏輯單元、與儲存陣列中的磁碟區相關。



 a| 
資源池
 a| 
資源池是邏輯分組的一組磁碟機。您可以使用集區來建立一個或多個可供主機存取的磁碟區。（您可以從集區或磁碟區群組建立磁碟區。）



 a| 
集區或Volume群組容量
 a| 
資源池、Volume或Volume群組容量是儲存陣列中已指派給資源池或Volume群組的容量。此容量可用來建立磁碟區、並滿足複製服務作業和儲存物件的各種容量需求。



 a| 
讀取快取
 a| 
讀取快取是儲存已從磁碟機讀取之資料的緩衝區。讀取作業的資料可能已經在先前作業的快取中、因此不需要存取磁碟機。資料會保留在讀取快取中、直到資料被清除為止。



 a| 
報告容量
 a| 
回報容量是指報告給主機的容量、可由主機存取。

報告的容量和已分配的容量對於大型磁碟區而言相同、但對於精簡磁碟區則不同。對於較厚的Volume、實體配置的空間等於報告給主機的空間。對於精簡磁碟區、回報容量是報告給主機的容量、而分配的容量則是目前分配給寫入資料的磁碟機空間量。



 a| 
區段大小
 a| 
區段是儲存陣列移至等量磁碟區（RAID群組）中的下一個磁碟機之前、儲存在磁碟機上的資料量（千位元組）。區段大小等於或小於Volume群組的容量。區段大小是固定的、無法變更集區的區段大小。



 a| 
分段
 a| 
分拆是在儲存陣列上儲存資料的方法。等量分割會將資料流分割成特定大小的區塊（稱為「區塊大小」）、然後逐一將這些區塊寫入磁碟機。這種資料儲存方式可用於在多個實體磁碟機之間分散及儲存資料。分拆是RAID 0的同義詞、可在RAID群組中的所有磁碟機之間散佈資料、不需同位元檢查。



 a| 
Volume
 a| 
Volume是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機所建立的邏輯元件、可用來存取儲存陣列上的儲存設備。



 a| 
Volume指派
 a| 
Volume指派是將主機LUN指派給磁碟區的方式。



 a| 
Volume名稱
 a| 
Volume名稱是在建立磁碟區時指派給該磁碟區的字元字串。您可以接受預設名稱、或提供更具說明性的名稱、以指示儲存在磁碟區中的資料類型。



 a| 
Volume群組
 a| 
Volume群組是具有共享特性之磁碟區的容器。Volume群組具有已定義的容量和RAID層級。您可以使用Volume群組來建立一個或多個可讓主機存取的磁碟區。（您可以從磁碟區群組或集區建立磁碟區。）



 a| 
工作負載
 a| 
工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。



 a| 
寫入快取
 a| 
寫入快取是一種緩衝區、用於儲存來自主機的資料、但尚未寫入磁碟機。資料會保留在寫入快取中、直到寫入磁碟機為止。寫入快取可提高I/O效能。



 a| 
使用鏡射寫入快取
 a| 
寫入快取搭配鏡射時、寫入某個控制器快取記憶體的資料也會寫入另一個控制器的快取記憶體。因此、如果一個控制器故障、另一個控制器就能完成所有未完成的寫入作業。只有啟用寫入快取且存在兩個控制器時、才能使用寫入快取鏡射。使用鏡射進行寫入快取是建立磁碟區的預設設定。



 a| 
寫入快取、不含電池
 a| 
寫入快取（無電池）設定可讓寫入快取繼續、即使電池遺失、故障、電力完全耗盡或未充滿電也沒問題。通常不建議選擇不含電池的寫入快取、因為如果電力中斷、資料可能會遺失。一般而言、寫入快取會由控制器暫時關閉、直到電池充電或更換故障電池為止。

|===


== 專屬精簡磁碟區

[NOTE]
====
System Manager不提供建立精簡磁碟區的選項。如果要建立精簡磁碟區、請使用命令列介面（CLI）。

====
[NOTE]
====
EF600或EF300儲存系統無法使用精簡磁碟區。

====
[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
已分配容量上限
 a| 
分配的容量上限是指分配給精簡磁碟區的實體容量可以增加多少的上限。



 a| 
寫入容量
 a| 
寫入容量是指從分配給精簡磁碟區的保留容量中寫入的容量量。



 a| 
警告臨界值
 a| 
您可以設定當精簡型磁碟區的分配容量達到已滿百分比（警告臨界值）時、發出警告臨界值警示。

|===