---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 12.00 
summary: 更新功能。SANtricity 
---
= SANtricity OS 12.00 的新特性
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
下表描述了 SANtricity System Manager 12.00 中的新功能。



== 12.00 版的新功能


NOTE: SANtricity OS 12.00 版本僅相容於新型 EF80 和 EF50 全快閃儲存系統。如果您使用的是 SANtricity OS 11.9 或更早版本，請參閱 link:known-issues.html["已知問題"] 以了解先前版本的新功能清單。

[cols="35h,~"]
|===
| 新功能 | 說明 


 a| 
新型儲存系統型號 – EF80 和 EF50 全快閃儲存系統
 a| 
此版本推出了 EF80 和 EF50 全 NVMe 快閃儲存系統。EF80 和 EF50 每個控制器均支援 24 個 NVME SSD 驅動器和一個控制器間鏡像卡。支援的 NVMe over Fabrics 主機介面包括 NVMe over RoCE、NVMe over IB、EF80 的 NVMe over FC 和 EF50 的 NVMe over FC。兩個系統支援的 SCSI 介面均為 Fibre Channel。EF50 每個控制器最多支援兩個主機介面卡，而 EF80 每個控制器最多支援三個主機介面卡。

EF80 和 EF50 也支援 30TB 或 60TB 大小的高容量 NVMe SSD 硬碟。EF80 和 EF50 只有在陣列中配備 30TB 或 60TB 硬碟時才能使用 Dynamic Disk Pool。



 a| 
SANtricity System Manager 的新使用者介面
 a| 
針對新款 EF80 和 EF50 控制器，SANtricity System Manager 使用者介面經過重新設計，外觀更加現代化。新介面採用左側面板導覽，並增強了易用性，從而簡化了管理任務。


NOTE: 新的使用者介面目前僅適用於採用 SANtricity 12.00 版本的 EF80 和 EF50 儲存系統。如果您使用的是 SANtricity 11.9 或更早版本，請參閱link:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html["SANtricity 系統管理員 11.9"]以取得使用舊版使用者介面的說明。



 a| 
伺服器憑證的主體別名 (SAN) 現在僅允許使用字母、數字和連字號字元
 a| 
在 SANtricity System Manager 或 Unified Manager 中建立或編輯伺服器憑證時，Subject Alternative Names（SANs）欄位現在僅允許使用字母、數字和連字號字元。此變更增強了安全性，並確保與 SSL/TLS 憑證的業界標準相容。



 a| 
對於 SSD 和基於 NVMe 的系統、動態磁碟集區區段大小現在預設為 32K
 a| 
對於基於 SSD 和 NVMe 的系統上的動態磁碟池，預設區段大小已變更為 32K。先前，這些系統的動態磁碟池預設區段大小固定為 128K。此項變更最佳化了包含大小 I/O 操作混合的工作負載的效能。



 a| 
SANtricity System Manager 現已提供指令碼編輯器
 a| 
SANtricity System Manager 中現已提供全新的腳本編輯器。腳本編輯器可讓您建立或編輯腳本檔案、將腳本檔案儲存至儲存管理站的本機磁碟，或從磁碟載入腳本檔案。腳本編輯器提供語法檢查和命令執行功能，方便您管理儲存系統。如需更多資訊，請參閱 link:sm-support/use-script-editor.html["使用腳本編輯器"^]。

|===