---
permalink: sm-mirroring/asynchronous-mirror-status.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirror, status, consistency, group, 
summary: 鏡射狀態定義鏡射一致性群組和鏡射Volume配對的狀態。 
---
= 非同步鏡射狀態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
鏡射狀態定義鏡射一致性群組和鏡射Volume配對的狀態。

[NOTE]
====
EF600或EF300儲存系統無法使用此功能。

====


== 鏡射一致性群組的狀態

[cols="25h,~"]
|===
| 狀態 | 說明 


 a| 
同步（初始同步）
 a| 
鏡射Volume配對之間完成的初始資料同步進度。

在初始同步期間、磁碟區可轉換為下列狀態：降級/故障/最佳/未知。



 a| 
同步（時間間隔同步）
 a| 
鏡射Volume配對之間已完成的定期資料同步進度。



 a| 
系統已暫停
 a| 
在鏡射一致性群組層級、所有鏡射配對上的資料儲存系統暫停同步。

鏡射一致性群組中至少有一個鏡射配對處於「已停止」或「失敗」狀態。



 a| 
使用者已暫停
 a| 
在鏡射一致性群組層級、使用者暫停所有鏡射配對上的資料同步。

此狀態有助於降低當本機儲存陣列上的任何變更資料複製到遠端儲存陣列時、可能對主機應用程式造成的任何效能影響。



 a| 
已暫停
 a| 
由於存取遠端儲存陣列時發生錯誤、資料同步程序已暫時暫停。



 a| 
孤立
 a| 
當一致性鏡射群組中的成員磁碟區已移除一致性鏡射群組的一端（主要端或次要端）、但另一端卻未移除時、就會出現孤立的鏡射配對磁碟區。

當陣列間通訊恢復且鏡射組態協調鏡射參數的兩側時、就會偵測到孤立的鏡射配對磁碟區。

您可以移除鏡射配對、以修正孤立的鏡射配對狀態。



 a| 
角色變更待處理/進行中
 a| 
鏡射一致性群組之間的角色變更正在擱置或進行中。

角色反轉變更（為主要角色或次要角色）會影響所選鏡射一致性群組中的所有非同步鏡射配對。

您可以取消擱置中的角色變更、但不能取消進行中的角色變更。



 a| 
角色衝突
 a| 
由於本機儲存陣列與遠端儲存陣列在角色變更作業期間發生通訊問題、因此鏡射一致性群組之間會發生角色衝突。

通訊問題解決後、就會發生角色衝突。使用Recovery Guru從這個錯誤中恢復。

解決角色衝突時、不允許強制升級。

|===


== 鏡射配對的狀態

鏡射配對的狀態會指出主要磁碟區和次要磁碟區上的資料是否同步。

[cols="25h,~"]
|===
| 狀態 | 說明 


 a| 
同步處理
 a| 
鏡射配對之間已完成的初始或週期資料同步處理進度。

同步有兩種類型：初始同步和定期同步。初始同步處理進度也會顯示在「長時間執行作業」對話方塊中。



 a| 
最佳化
 a| 
鏡射配對中的磁碟區會同步、表示儲存陣列之間的連線正常運作、而且每個磁碟區都處於所需的工作狀態。



 a| 
不完整
 a| 
遠端儲存陣列上的非同步鏡射配對並不完整、因為鏡射配對建立順序是在System Manager不支援的儲存陣列上啟動、而鏡射配對尚未在次要儲存陣列上完成。

將磁碟區新增至遠端儲存陣列上的鏡射一致性群組時、鏡射配對建立程序即告完成。此Volume會成為非同步鏡射配對中的次要Volume。

如果遠端儲存陣列是由System Manager管理、則鏡射配對會自動完成。



 a| 
失敗
 a| 
非同步鏡射作業無法正常運作、因為主要磁碟區、次要磁碟區或鏡射保留容量發生故障。



 a| 
孤立
 a| 
當一致性鏡射群組中的成員磁碟區已移除一致性鏡射群組的一端（主要端或次要端）、但另一端卻未移除時、就會出現孤立的鏡射配對磁碟區。

當兩個儲存陣列之間的通訊恢復、以及鏡射組態協調鏡射參數的兩側時、就會偵測到孤立的鏡射配對磁碟區。

您可以移除鏡射配對、以修正孤立的鏡射配對狀態。



 a| 
已停止
 a| 
鏡射配對處於停止狀態、因為鏡射一致性群組處於系統暫停狀態。

|===