---
permalink: sm-mirroring/complete-mirrored-pair-for-primary-volumes-created-on-legacy-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, complete, mirrored, pair, volumes, created, legacy, 
summary: 如果您在SANtricity 無法由支援系統管理程式管理的舊儲存陣列上建立主磁碟區、您可以使用System Manager在此陣列上建立次磁碟區。 
---
= 為舊系統上建立的主要磁碟區建立完整鏡射配對
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您在SANtricity 無法由NetApp系統管理程式管理的舊儲存陣列上建立主磁碟區、您可以使用SANtricity 此Array上的「支援系統管理程式」來建立次磁碟區。

.關於這項工作
您可以在使用不同介面的舊陣列與可由System Manager管理的新陣列之間執行非同步鏡像。

* 如果您是在使用System Manager的兩個儲存陣列之間進行鏡射、您可以跳過此工作、因為您已經在鏡射配對建立順序中完成鏡射配對。
* 在遠端儲存陣列上執行此工作。


.步驟
. 選取功能表：Storage[非同步鏡射]。
. 選取*鏡射配對*索引標籤。
+
鏡射配對表隨即出現、並顯示與儲存陣列相關的所有鏡射配對。

. 找到狀態為「Incompleted（不完整）」的鏡射配對磁碟區、然後按一下「鏡射配對」欄中顯示的*完整鏡射配對*連結。
. 選擇您要自動或手動完成鏡射配對建立順序、方法是選取下列其中一個選項按鈕：
+
** *自動*-建立新的次要Volume。
+
選取要建立次要Volume的現有集區或Volume群組、以接受鏡射配對遠端的預設設定。使用此建議選項、以預設設定分配次要Volume的保留容量。

** *手動*-選取現有的Volume。
+
定義您自己的次要Volume參數。

+
... 單擊* Next*（下一步*）以選擇次要Volume。
... 選取要用作次要磁碟區的現有磁碟區、然後按「*下一步*」來配置保留容量。
... 分配保留容量。執行下列其中一項：
+
**** 接受預設設定。
+
保留容量的預設設定為基礎磁碟區容量的20%、通常此容量已足夠。

**** 配置您自己的保留容量設定、以滿足與非同步鏡射相關的資料儲存需求。
+
所需容量會因主要磁碟區I/O寫入的頻率和大小、以及保留容量所需的時間而有所不同。一般而言、如果存在下列其中一項或兩項條件、請選擇較大的保留容量：

+
***** 您打算長期保留鏡射配對。
***** 由於I/O活動頻繁、一線磁碟區上的資料區塊將會有很大比例改變。使用歷史效能資料或其他作業系統公用程式、協助您判斷主要磁碟區的典型I/O活動。








. 選擇*完整*。


.結果
System Manager會執行下列動作：

* 在遠端儲存陣列上建立次要磁碟區、並為鏡射配對的遠端配置保留容量。
* 開始在本機儲存陣列與遠端儲存陣列之間進行初始同步。
* 如果要鏡射的磁碟區是精簡磁碟區、則在初始同步期間、只有分配的區塊會傳輸到次要磁碟區。此傳輸可減少完成初始同步所需傳輸的資料量。
* 在本機儲存陣列和遠端儲存陣列上建立鏡射配對的保留容量。

