---
permalink: sm-mirroring/faq-sync-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 同步鏡像常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 非同步鏡射與同步鏡射有何不同？

「非同步鏡射」功能與「同步鏡射」功能有一種重要的差異：它會在特定時間點擷取來源Volume的狀態、並只複製自上次映像擷取後變更的資料。

使用同步鏡射時、主要磁碟區的狀態不會在某個時間點擷取、而是反映主要磁碟區對次要磁碟區所做的所有變更。次要磁碟區每次都與主要磁碟區相同、因為有了這種鏡射類型、每次寫入主要磁碟區時、就會寫入次要磁碟區。在次要Volume成功更新為主要Volume所做的變更之前、主機不會收到寫入成功的確認訊息。

透過非同步鏡射、遠端儲存陣列並未與本機儲存陣列完全同步、因此如果應用程式因為本機儲存陣列遺失而需要轉換至遠端儲存陣列、則部分交易可能會遺失。

鏡射功能比較：

[cols="1a,1a"]
|===
| 非同步鏡射 | 同步鏡射 


 a| 
*複寫方法*



 a| 
* *時間點*
+
鏡射是根據需求或根據使用者定義的排程自動完成。排程的定義可精細度（分鐘）。同步之間的最短時間為10分鐘。


 a| 
* *持續*
+
鏡射會持續執行、從每個主機寫入複製資料。





 a| 
*保留容量*



 a| 
* *多重*
+
每個鏡射配對都需要保留容量Volume。


 a| 
* *單一*
+
所有鏡射磁碟區都需要單一保留容量磁碟區。





 a| 
*通訊*



 a| 
* * iSCSI和Fibre Channel*
+
支援儲存陣列之間的iSCSI和Fibre Channel介面。


 a| 
* *光纖通道*
+
僅支援儲存陣列之間的Fibre Channel介面。





 a| 
*距離*



 a| 
* *無限*
+
本機儲存陣列與遠端儲存陣列之間的距離幾乎不受限制、距離通常僅受網路功能與通道擴充技術的限制。


 a| 
* *限制*
+
通常必須距離本機儲存陣列約10公里（6.2英哩）、才能滿足延遲和應用程式效能需求。



|===


== 同步鏡像 - 為什麼我看不到所有磁碟區？

當您選取鏡射配對的主要Volume時、會有一個清單顯示所有符合資格的Volume。

任何不符合使用資格的磁碟區都不會顯示在該清單中。磁碟區可能不符合下列任一原因的資格：

* 此磁碟區為非標準磁碟區、例如快照磁碟區或精簡磁碟區。
* Volume並非最佳。
* Volume已參與鏡射關係。




== 同步鏡像 - 為什麼我看不到遠端儲存陣列上的所有磁碟區？

當您在遠端儲存陣列上選取次要Volume時、清單會顯示該鏡射配對的所有適用磁碟區。

任何不符合使用資格的磁碟區、都不會顯示在該清單中。磁碟區可能不符合下列任一原因的資格：

* 此磁碟區為非標準磁碟區、例如快照磁碟區或精簡磁碟區。
* Volume並非最佳。
* Volume已參與鏡射關係。
* 如果您使用的是Data Assurance（DA）、則主要Volume和次要Volume必須具有相同的DA設定。
+
** 如果主磁碟區已啟用DA、則必須啟用次要磁碟區DA。
** 如果主要Volume未啟用DA、則次要Volume不得啟用DA。






== 同步鏡射-建立鏡射配對之前、我需要知道什麼？

您可以在 SANtricity Unified Manager 介面中設定鏡射配對，然後在 SANtricity 系統管理員中管理這些配對。

建立鏡射配對之前、請遵循下列準則：

* 您必須有兩個儲存陣列。
* 每個儲存陣列都必須有兩個控制器。
* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 您的本機和遠端儲存陣列是透過光纖通道架構來連接。
* 儲存陣列的韌體版本最低為7.84。（每個作業系統都能執行不同的版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您必須在遠端儲存陣列上擁有足夠的可用容量、才能建立等於或大於您要鏡射之主要磁碟區的次要磁碟區。
* 您已安裝Web服務Proxy和Unified Manager。在Unified Manager介面中設定鏡射配對。
* 這兩個儲存陣列都是在Unified Manager中發現的。




== 同步處理優先順序對同步處理速率有何影響？

同步處理優先順序會定義與系統效能相關的同步處理活動所需的處理時間。

主磁碟區的控制器擁有者會在背景執行此作業。同時、控制器擁有者會處理本機I/O寫入主要磁碟區的作業、並將相關的遠端寫入作業處理至次要磁碟區。由於重新同步會將控制器處理資源從I/O活動中轉移、因此重新同步可能會影響主機應用程式的效能。

請記住這些準則、以協助您判斷同步處理優先順序可能需要多久、以及同步處理優先順序如何影響系統效能。

.關於同步優先率
[%collapsible]
====
這些優先率可供選擇：

* 最低
* 低
* 中
* 高
* 最高


最低的優先順序率可支援系統效能、但重新同步需要較長時間。最高優先順序率支援重新同步、但系統效能可能會受損。

====
這些準則大致上與優先順序的差異大致相同。

[cols="35h,~"]
|===
| 完整同步的優先順序率 | 相較於最高同步率、所耗用的時間 


 a| 
最低
 a| 
最高優先率約為八倍。



 a| 
低
 a| 
最高優先率約為六倍。



 a| 
中
 a| 
以最高優先率計算、約為三倍半。



 a| 
高
 a| 
以最高優先率計算、長度約為兩倍。

|===
Volume大小和主機I/O速率負載會影響同步時間比較。



== 為什麼建議使用手動同步原則？

建議手動重新同步、因為它可讓您以最佳的方式來管理重新同步程序、以提供最佳的資料恢復機會。

如果您使用自動重新同步原則、且在重新同步期間發生間歇性通訊問題、則次要磁碟區上的資料可能會暫時毀損。重新同步完成後、資料將會修正。
