---
permalink: sm-mirroring/faq-async-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 非同步鏡像常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 非同步鏡射與同步鏡射有何不同？

「非同步鏡射」功能與「同步鏡射」功能有一種重要的差異：它會在特定時間點擷取來源Volume的狀態、並只複製自上次映像擷取後變更的資料。

使用同步鏡射時、主要磁碟區的狀態不會在某個時間點擷取、而是反映主要磁碟區對次要磁碟區所做的所有變更。次要磁碟區每次都與主要磁碟區相同、因為有了這種鏡射類型、每次寫入主要磁碟區時、就會寫入次要磁碟區。在次要Volume成功更新為主要Volume所做的變更之前、主機不會收到寫入成功的確認訊息。

透過非同步鏡射、遠端儲存陣列並未與本機儲存陣列完全同步、因此如果應用程式因為本機儲存陣列遺失而需要轉換至遠端儲存陣列、則部分交易可能會遺失。

鏡射功能比較：

[cols="1a,1a"]
|===
| 非同步鏡射 | 同步鏡射 


 a| 
*複寫方法*



 a| 
* *時間點*
+
鏡射是根據需求或根據使用者定義的排程自動完成。排程的定義可精細度（分鐘）。同步之間的最短時間為10分鐘。


 a| 
* *持續*
+
鏡射會持續執行、從每個主機寫入複製資料。





 a| 
*保留容量*



 a| 
* *多重*
+
每個鏡射配對都需要保留容量Volume。


 a| 
* *單一*
+
所有鏡射磁碟區都需要單一保留容量磁碟區。





 a| 
*通訊*



 a| 
* * iSCSI和Fibre Channel*
+
支援儲存陣列之間的iSCSI和Fibre Channel介面。


 a| 
* *光纖通道*
+
僅支援儲存陣列之間的Fibre Channel介面。





 a| 
*距離*



 a| 
* *無限*
+
本機儲存陣列與遠端儲存陣列之間的距離幾乎不受限制、距離通常僅受網路功能與通道擴充技術的限制。


 a| 
* *限制*
+
通常必須距離本機儲存陣列約10公里（6.2英哩）、才能滿足延遲和應用程式效能需求。



|===


== 為什麼我無法存取我選擇的鏡像功能？

鏡射是在 SANtricity Unified Manager 介面中設定。

[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存陣列不提供同步鏡射功能。

====
若要啟用及設定兩個陣列之間的鏡射、請確認下列事項：

* Web服務Proxy服務必須正在執行。（Unified Manager與Web服務Proxy一起安裝在主機系統上。）
* Unified Manager必須透過HTTPS連線在本機主機上執行。
* 您要用於鏡射的兩個儲存陣列必須在Unified Manager中探索。
* Unified Manager必須擁有儲存陣列的有效SSL憑證。您可以接受自我簽署的憑證、或從Unified Manager安裝CA簽署的憑證。


如需組態指示、請參閱下列內容：

* link:../um-manage/create-asynchronous-mirrored-pair-um.html["建立非同步鏡射配對（在Unified Manager中）"]
* link:../um-manage/create-synchronous-mirrored-pair-um.html["建立同步鏡射配對（在Unified Manager中）"]




== 在建立鏡射一致性群組之前、我需要知道什麼？

在建立鏡射一致性群組之前、請遵循下列準則。

[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供同步鏡射功能。

====
您可以在「建立鏡射配對」精靈的Unified Manager中建立一致性群組。

符合Unified Manager的下列需求：

* Web服務Proxy服務必須正在執行。
* Unified Manager必須透過HTTPS連線在本機主機上執行。
* Unified Manager必須顯示儲存陣列的有效SSL憑證。您可以接受自我簽署的憑證、或使用Unified Manager安裝自己的安全性憑證、並瀏覽至功能表：「Certificate [ Certificate Management（憑證管理）」。


此外、請務必滿足下列儲存陣列需求：

* 這兩個儲存陣列必須在Unified Manager中探索。
* 每個儲存陣列都必須有兩個控制器。
* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 儲存陣列的韌體版本最低為7.84。（每個作業系統都能執行不同的版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您的本機和遠端儲存陣列是透過光纖通道架構或iSCSI介面來連接。




== 非同步鏡射-建立鏡射配對之前、我需要知道什麼？

您可以在 SANtricity Unified Manager 介面中設定鏡射配對，然後在 SANtricity 系統管理員中管理這些配對。

在建立鏡射配對之前、請遵循下列準則。

* 您必須有兩個儲存陣列。
* 每個儲存陣列都必須有兩個控制器。
* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 您的本機和遠端儲存陣列是透過光纖通道架構或iSCSI介面來連接。
* 儲存陣列的韌體版本最低為7.84。（每個作業系統都能執行不同的版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您必須在遠端儲存陣列上擁有足夠的可用容量、才能建立等於或大於您要鏡射之主要磁碟區的次要磁碟區。
* 您已安裝Web服務Proxy和Unified Manager。在Unified Manager介面中設定鏡射配對。
* 這兩個儲存陣列都是在Unified Manager中發現的。
* 您的儲存陣列必須包含至少一個鏡射一致性群組。您可以在「建立鏡射配對」精靈的Unified Manager中建立一致性群組。




== 在增加鏡射配對磁碟區上的保留容量之前、我需要知道什麼？

一般而言、當您收到鏡射配對的保留容量已滿的警告時、應該增加保留容量。您只能以8 GiB的增量來增加保留容量。

對於非同步鏡射作業、保留容量通常為基礎磁碟區的20%。如果存在下列任一或兩種情況、請選擇較大的容量來保留容量：

* 您打算長期保留鏡射配對。
* 由於I/O活動頻繁、一線磁碟區上的資料區塊將會有很大比例改變。使用歷史效能資料或其他作業系統公用程式、協助您判斷主要磁碟區的典型I/O活動。


您可以執行下列其中一個動作來增加鏡射配對的保留容量：

* 選取功能表：Storage[資源池與磁碟區群組]、然後按一下*保留容量*索引標籤、即可調整鏡射配對磁碟區的容量百分比。
* 使用資源池或磁碟區群組上可用的可用容量來建立新的磁碟區。
+
如果任何資源池或磁碟區群組上不存在可用容量、您可以將未設定的容量、以未使用磁碟機的形式新增至資源池或磁碟區群組。





== 為什麼我無法將預留容量增加到我請求的數量？

您只能以4 GiB的增量來增加保留容量。

請檢閱下列準則：

* 您必須在資源池或磁碟區群組中擁有足夠的可用容量、才能在必要時加以擴充。
+
如果任何集區或Volume群組上不存在可用容量、您可以將未使用磁碟機的未指派容量新增至集區或Volume群組。

* 集區或磁碟區群組中的磁碟區必須處於最佳狀態、且不得處於任何修改狀態。
* 可用容量必須存在於您要用來增加容量的資源池或磁碟區群組中。


對於非同步鏡射作業、保留容量通常為基礎磁碟區的20%。如果您認為基礎磁碟區會經歷許多變更、或儲存物件複製服務作業的預估使用壽命將會很長、請使用較高的百分比。



== 為什麼要變更這個百分比？

保留容量通常是基礎磁碟區的40%、用於快照作業、20%的基礎磁碟區用於非同步鏡射作業。

通常這種容量是足夠的。所需的容量會因寫入基礎磁碟區的頻率和大小、以及您打算使用儲存物件複製服務作業的時間而有所不同。

一般而言、如果存在下列其中一項或兩項條件、請為保留容量選擇較大的百分比：

* 如果特定儲存物件的複製服務作業壽命很長、
* 如果由於I/O活動頻繁、基礎磁碟區上的資料區塊百分比會大幅變動。使用歷史效能資料或其他作業系統公用程式、協助您判斷基礎磁碟區的典型I/O活動。




== 為什麼我會看到多個保留容量的候選對象？

如果集區或Volume群組中有多個磁碟區符合您為儲存物件選取的容量百分比、您將會看到多個候選磁碟區。

您可以變更要保留在基礎磁碟區上進行複製服務作業的實體磁碟機空間百分比、以重新整理建議的候選磁碟機清單。根據您的選擇、將會顯示最佳的候選對象。



== 為什麼我在表格中看到無法使用的值？

當遠端儲存陣列上的資料無法顯示時、表格會列出不可用的值。

若要顯示遠端儲存陣列資料、請從Unified Manager啟動System Manager。



== 為什麼我看不到所有的池和卷組？

當您為非同步鏡射配對建立次要Volume時、系統會顯示該非同步鏡射配對的所有合格資源池和Volume群組清單。任何不符合使用資格的資源池或磁碟區群組、都不會顯示在該清單中。

集區或Volume群組可能不符合下列任何理由的資格。

* 集區或Volume群組的安全功能不相符。
* 集區或磁碟區群組處於非最佳狀態。
* 集區或Volume群組的容量太小。




== 非同步鏡像 - 為什麼我看不到所有磁碟區？

當您選取鏡射配對的主要Volume時、會有一個清單顯示所有符合資格的Volume。

任何不符合使用資格的磁碟區都不會顯示在該清單中。Volume可能不符合下列任何理由：

* Volume並非最佳。
* Volume已參與鏡射關係。
* 對於精簡磁碟區、必須啟用自動擴充。



NOTE: 對於 EF600 和 EF300 控制器、非同步鏡射配對的主要和次要磁碟區必須符合相同的傳輸協定、磁碟匣層級、區段大小、安全類型和 RAID 層級。非合格的非同步鏡射配對不會出現在可用磁碟區清單中。



== 非同步鏡像 - 為什麼我看不到遠端儲存陣列上的所有磁碟區？

當您在遠端儲存陣列上選取次要Volume時、清單會顯示該鏡射配對的所有適用磁碟區。

任何不符合使用資格的磁碟區、都不會顯示在該清單中。磁碟區可能不符合下列任一原因的資格：

* Volume並非最佳。
* Volume已參與鏡射關係。
* 主要Volume與次要Volume之間的精簡Volume屬性不相符。
* 如果您使用的是Data Assurance（DA）、則主要Volume和次要Volume必須具有相同的DA設定。
+
** 如果主磁碟區已啟用DA、則必須啟用次要磁碟區DA。
** 如果主要Volume未啟用DA、則次要Volume不得啟用DA。






== 為什麼要更新遠端儲存陣列的 IP 位址？

當iSCSI連接埠的IP位址變更、且本機儲存陣列無法與遠端儲存陣列通訊時、您可以更新遠端儲存陣列的IP位址。

在與iSCSI連線建立非同步鏡射關係時、本機和遠端儲存陣列都會在非同步鏡射組態中儲存遠端儲存陣列IP位址的記錄。如果iSCSI連接埠的IP位址變更、則嘗試使用該連接埠的遠端儲存陣列會發生通訊錯誤。

具有變更IP位址的儲存陣列會傳送訊息給與鏡射一致性群組相關聯的每個遠端儲存陣列、這些群組已設定為透過iSCSI連線鏡射。接收此訊息的儲存陣列會自動更新遠端目標IP位址。

如果IP位址變更的儲存陣列無法將陣列間訊息傳送至遠端儲存陣列、系統會傳送連線問題警示給您。使用更新遠端IP位址選項、重新建立與本機儲存陣列的連線。
