---
permalink: sm-mirroring/requirements-for-using-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, asynchronous, mirroring, 
summary: 如果您打算使用非同步鏡射、請謹記下列需求。 
---
= 使用非同步鏡射的需求
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您打算使用非同步鏡射、請謹記下列需求。



== Unified Manager

若要在兩個陣列之間啟用及設定鏡射、您必須使用Unified Manager介面。Unified Manager與Web Services Proxy一起安裝在主機系統上。

* Web服務Proxy服務必須正在執行。
* Unified Manager必須透過HTTPS連線在本機主機上執行。
* Unified Manager必須顯示儲存陣列的有效SSL憑證。您可以接受自我簽署的憑證、或使用Unified Manager安裝自己的安全性憑證、並瀏覽至功能表：「Certificate [ Certificate Management（憑證管理）」。




== 儲存陣列

[NOTE]
====
EF600或EF300儲存陣列無法使用鏡射功能。

====
* 您必須有兩個儲存陣列。
* 每個儲存陣列都必須有兩個控制器。
* 這兩個儲存陣列必須在Unified Manager中探索。
* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 儲存陣列的韌體版本最低為7.84。（每個作業系統都能執行不同的版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您必須在遠端儲存陣列上擁有足夠的可用容量、才能建立等於或大於您要鏡射之主要磁碟區的次要磁碟區。
* 您的本機和遠端儲存陣列是透過光纖通道架構或iSCSI介面來連接。




== 支援的連線

非同步鏡射可以使用FC或iSCSI連線、或同時使用兩者來進行本機與遠端儲存系統之間的通訊。在建立鏡射一致性群組時、如果兩個群組都連線至遠端儲存陣列、則系統管理員可以為該群組選取FC或iSCSI。沒有容錯移轉從一種通道類型移轉到另一種通道類型。

非同步鏡射會使用儲存陣列的主機端I/O連接埠、將鏡射資料從主端傳輸到次端。

* *透過光纖通道（FC）介面鏡射*
+
儲存陣列的每個控制器都會將其編號最高的FC主機連接埠專用於鏡射作業。

+
如果控制器同時具有基礎FC連接埠和主機介面卡（HIC）FC連接埠、則編號最高的連接埠位於HIC上。登入專用連接埠的任何主機都會登出、而且不會接受任何主機登入要求。此連接埠上的I/O要求僅接受參與鏡射作業的控制器。

+
專用鏡射連接埠必須連接至支援目錄服務和名稱服務介面的FC架構環境。特別是、參與鏡射關係的控制器之間、不支援使用FC-AL和點對點作為連線選項。

* *透過iSCSI介面鏡像*
+
與FC不同、iSCSI不需要專用連接埠。在iSCSI環境中使用非同步鏡射時、不需要將任何儲存陣列的前端iSCSI連接埠專用於非同步鏡射；這些連接埠會共用以進行非同步鏡射流量和主機對陣列I/O連線。

+
控制器會維護一份遠端儲存系統清單、iSCSI啟動器會嘗試建立工作階段。成功建立iSCSI連線的第一個連接埠、用於與該遠端儲存陣列進行所有後續通訊。如果通訊失敗、則會嘗試使用所有可用的連接埠來建立新的工作階段。

+
iSCSI連接埠是以連接埠為基礎、在陣列層級進行設定。組態訊息和資料傳輸的控制器間通訊使用全域設定、包括下列設定：

+
** VLAN：本機和遠端系統必須具有相同的VLAN設定才能進行通訊
** iSCSI接聽連接埠
** 巨型框架
** 乙太網路優先順序
+
[NOTE]
====
iSCSI互連控制器通訊必須使用主機連線連接埠、而非管理乙太網路連接埠。

====


+
非同步鏡射會使用儲存陣列的主機端I/O連接埠、將鏡射資料從主端傳輸到次端。因為非同步鏡射的目的是為了提供較高的延遲、較低成本的網路、所以iSCSI（因此以TCP/IP為基礎）連線非常適合它。在iSCSI環境中使用非同步鏡射時、不需要將陣列的任何前端iSCSI連接埠專用於非同步鏡射；這些連接埠可用於非同步鏡射流量和主機對陣列I/O連線





== 鏡射Volume候選

* 在非同步鏡射配對的主要和次要磁碟區上、RAID層級、快取參數和區段大小可能會有所不同。
* 次要Volume必須至少與主要Volume一樣大。
* 一個Volume只能參與一個鏡射關係。
* Volume候選對象必須共用相同的資料安全功能。
+
** 如果主要磁碟區支援FIPS、則次要磁碟區必須具備FIPS功能。
** 如果主要Volume支援FDE、則次要Volume必須具備FDE功能。
** 如果主要磁碟區未使用磁碟機安全性、則次要磁碟區不得使用磁碟機安全性。






== 保留容量

* 主磁碟區和鏡射配對中的次要磁碟區需要保留容量磁碟區、以便記錄寫入資訊、以便從控制器重設和其他暫時性中斷中恢復。
* 由於鏡射配對中的主要Volume和次要Volume都需要額外的保留容量、因此您必須確保在鏡射關係中、兩個儲存陣列都有可用的可用容量。




== 磁碟機安全功能

* 如果您使用的是具有安全功能的磁碟機、則主要磁碟區和次要磁碟區必須具有相容的安全性設定。此限制並未強制執行、因此您必須自行驗證。
* 如果您使用的是具有安全功能的磁碟機、則主磁碟區和次要磁碟區應該使用相同的磁碟機類型。此限制並未強制執行、因此您必須自行驗證。
* 如果您使用的是Data Assurance（DA）、則主要Volume和次要Volume必須具有相同的DA設定。

