---
permalink: sm-mirroring/requirements-for-using-synchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, synchronous, mirroring, 
summary: 如果您打算使用同步鏡射、請謹記下列需求。 
---
= 使用同步鏡射的需求
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您打算使用同步鏡射、請謹記下列需求。



== Unified Manager

若要在兩個陣列之間啟用及設定鏡射、您必須使用Unified Manager介面。Unified Manager與Web Services Proxy一起安裝在主機系統上。

* Web服務Proxy服務必須正在執行。
* Unified Manager必須透過HTTPS連線在本機主機上執行。
* Unified Manager必須顯示儲存陣列的有效SSL憑證。您可以接受自我簽署的憑證、或使用Unified Manager安裝自己的安全性憑證、並瀏覽至功能表：「Certificate [ Certificate Management（憑證管理）」。




== 儲存陣列

[NOTE]
====
EF300 或 EF600 儲存陣列不提供同步鏡射功能。

====
* 您必須有兩個儲存陣列。
* 每個儲存陣列都必須有兩個控制器。
* 這兩個儲存陣列必須在Unified Manager中探索。
* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 儲存陣列的韌體版本最低為7.84。（每個作業系統都能執行不同的版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您必須在遠端儲存陣列上擁有足夠的可用容量、才能建立等於或大於您要鏡射之主要磁碟區的次要磁碟區。
* 您的本機和遠端儲存陣列是透過光纖通道架構來連接。




== 支援的連線

同步鏡射的通訊僅支援使用光纖通道（FC）主機連接埠的控制器。

同步鏡射會在本機儲存陣列和遠端儲存陣列上的每個控制器上使用編號最高的主機連接埠。控制器主機匯流排介面卡（HBA）主機連接埠4通常保留用於鏡射資料傳輸。



== 鏡射Volume候選

* 在同步鏡射配對的主要和次要磁碟區上、RAID層級、快取參數和區段大小可能會有所不同。
* 同步鏡射配對中的主要和次要磁碟區必須是標準磁碟區。它們不能是精簡磁碟區或快照磁碟區。
* 次要Volume必須至少與主要Volume一樣大。
* 在Volume複製作業中、只有主要Volume可以有與其相關聯的快照和（或）作為來源或目標Volume。
* 一個Volume只能參與一個鏡射關係。
* 特定儲存陣列支援的磁碟區數量有限制。請確定儲存陣列上已設定的磁碟區數量少於支援的限制。當同步鏡射處於作用中狀態時、所建立的兩個保留容量磁碟區會根據磁碟區限制進行計數。




== 保留容量

* 主要磁碟區和次要磁碟區需要保留容量、以便記錄寫入資訊、以便從控制器重設和其他暫時性中斷中恢復。
* 啟動同步鏡射時、會自動建立保留容量磁碟區。由於鏡射配對中的主要Volume和次要Volume都需要保留容量、因此您必須確保兩個參與同步鏡射關係的儲存陣列都有足夠的可用容量。




== 磁碟機安全功能

* 如果您使用的是具有安全功能的磁碟機、則主要磁碟區和次要磁碟區必須具有相容的安全性設定。此限制並未強制執行、因此您必須自行驗證。
* 如果您使用的是具有安全功能的磁碟機、則主磁碟區和次要磁碟區應該使用相同的磁碟機類型。此限制並未強制執行、因此您必須自行驗證。
+
** 如果主要磁碟區使用完整磁碟加密（FDE）磁碟機、則次要磁碟區應使用FDE磁碟機。
** 如果主要磁碟區使用通過聯邦資訊處理標準140-2（FIPS）驗證的磁碟機、次要磁碟區應使用FIPS 140-2驗證的磁碟機。


* 如果您使用的是Data Assurance（DA）、則主要Volume和次要Volume必須具有相同的DA設定。

