---
permalink: sm-mirroring/role-change-of-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, between, volume, mirrored, pair, 
summary: 您可以變更鏡射配對中磁碟區之間的角色。您可以將主要磁碟區降級為次要角色、或將次要磁碟區提升為主要角色、以達成此目標。 
---
= 鏡射配對中磁碟區之間的角色變更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更鏡射配對中磁碟區之間的角色。您可以將主要磁碟區降級為次要角色、或將次要磁碟區提升為主要角色、以達成此目標。

[NOTE]
====
EF600或EF300儲存系統無法使用此功能。

====
檢閱下列關於角色變更作業的資訊：

* 當主要Volume降級為次要角色時、鏡射配對中的次要Volume會提升為主要角色、反之亦然。
* 當主要磁碟區降級為次要角色時、已指派給該磁碟區的主機將不再擁有該磁碟區的寫入存取權。
* 當次要磁碟區提升為主要角色時、任何正在存取該磁碟區的主機現在都能寫入該磁碟區。
* 如果本機儲存陣列無法與遠端儲存陣列通訊、您可以在本機儲存陣列上強制變更角色。




== 強制角色變更

當本機儲存陣列與遠端儲存陣列之間發生通訊問題、導致次要磁碟區無法升級或主要磁碟區降級時、您可以強制變更鏡射配對中磁碟區的角色。

您可以強制次要端的磁碟區移轉至主要角色。然後、恢復主機就能存取新升級的磁碟區、業務作業也能繼續進行。

[NOTE]
====
當遠端儲存陣列恢復且任何通訊問題均已解決時、會發生同步鏡射-主要Volume衝突情況。恢復步驟包括重新同步磁碟區。使用Recovery Guru從這個錯誤中恢復。

====


== 何時允許或不允許強制促銷？

在下列情況下、不允許強制升級鏡射配對中的磁碟區：

* 鏡射配對中的任何磁碟區都在初始同步處理中。
* 鏡射配對處於「失敗」、「角色變更擱置」或「角色變更進行中」狀態、或是任何相關的保留容量磁碟區發生故障。




== 角色變更進行中狀態

如果鏡射組態中的兩個儲存陣列中斷連線、且鏡射配對的主要Volume被強制降級為次要角色、且鏡射配對的次要Volume被強制提升為主要角色、 然後、當通訊還原時、兩個儲存陣列上的磁碟區都會處於角色變更進行中狀態。

系統將透過傳輸變更記錄、重新同步、將鏡射配對狀態設回正常操作狀態、以及繼續同步等方式來完成角色變更程序。
