---
permalink: sm-mirroring/role-change-of-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, mirror, consistency, group, secondary, mirror, consistency, group, 
summary: 您可以變更鏡射一致性群組中鏡射配對之間的角色。您可以將主要鏡像一致性群組降級為次要角色、或將次要鏡像一致性群組提升為主要角色、以達成此目標。 
---
= 鏡射一致性群組的角色變更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更鏡射一致性群組中鏡射配對之間的角色。您可以將主要鏡像一致性群組降級為次要角色、或將次要鏡像一致性群組提升為主要角色、以達成此目標。

[NOTE]
====
EF600或EF300儲存系統無法使用此功能。

====
檢閱下列關於角色變更作業的資訊：

* 角色變更會影響所選鏡射一致性群組中的所有鏡射配對。
* 當鏡射一致性群組降級為次要角色時、該鏡射一致性群組中的所有鏡射配對也會降級為次要角色、反之亦然。
* 當主要鏡射一致性群組降級為次要角色時、已指派給該群組中成員磁碟區的主機將不再擁有其寫入權限。
* 當鏡射一致性群組提升為主要角色時、任何存取該群組成員磁碟區的主機現在都能寫入這些磁碟區。
* 如果本機儲存陣列無法與遠端儲存陣列通訊、您可以在本機儲存陣列上強制變更角色。




== 強制角色變更

當本機儲存陣列與遠端儲存陣列之間發生通訊問題、導致次要鏡射一致性群組內的成員磁碟區無法升級、或成員磁碟區無法在主要鏡射一致性內降級時、您可以強制變更鏡射一致性群組之間的角色 群組：

您可以強制次要端的鏡射一致性群組移轉至主要角色。然後、恢復主機就能存取該鏡射一致性群組中新升級的成員磁碟區、而且業務營運仍可繼續進行。



== 何時允許或不允許強制促銷？

僅當鏡射一致性群組的所有成員磁碟區都已同步且具有一致的還原點時、才允許強制升級鏡射一致性群組。

在下列情況下、不允許強制升級鏡射一致性群組：

* 鏡射一致性群組的任何成員磁碟區都在初始同步處理中。
* 鏡射一致性群組的任何成員磁碟區都沒有還原點的時間點映像（例如、由於完整保留容量錯誤）。
* 鏡射一致性群組不包含成員磁碟區。
* 鏡射一致性群組處於「失敗」、「角色變更擱置」或「角色變更進行中」狀態、或是任何相關聯的成員磁碟區或保留容量磁碟區發生故障。




== 鏡射群組角色衝突

當本機與遠端儲存陣列之間的通訊問題解決之後、就會發生鏡射群組角色衝突的情況。使用Recovery Guru從這個錯誤中恢復。解決雙重角色衝突時、不允許強制升級。

若要避免鏡射群組角色衝突情況及後續的還原步驟、請等到儲存陣列之間的連線正常運作、以強制變更角色。



== 角色變更進行中狀態

如果鏡射組態中的兩個儲存陣列中斷連線、且鏡射一致性群組的主要端強制降級為次要角色、且鏡射一致性群組的次要端強制提升為主要角色、 然後、當通訊恢復時、兩個儲存陣列上的鏡射一致性群組會置於角色變更進行中狀態。

系統將透過傳輸變更記錄、重新同步、將鏡射一致性群組狀態設回正常作業狀態、以及繼續定期同步等方式、來完成角色變更程序。
