---
permalink: sm-mirroring/test-communication-for-mirror-consistency-groups.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, test, communication, mirror, consistency, groups, 
summary: 您可以測試通訊連結、以診斷本機儲存陣列與與鏡射一致性群組相關的遠端儲存陣列之間可能發生的通訊問題。 
---
= 測試鏡射一致性群組的通訊
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以測試通訊連結、以診斷本機儲存陣列與與鏡射一致性群組相關的遠端儲存陣列之間可能發生的通訊問題。

.開始之前
您要測試的鏡射一致性群組必須存在於本機和遠端儲存陣列上。

.關於這項工作
您可以執行四種不同的測試：

* *連線能力*：驗證兩個控制器是否有通訊路徑。連線測試會在儲存陣列之間傳送陣列間訊息、然後驗證遠端儲存陣列上對應的鏡射一致性群組是否存在。它也會驗證遠端儲存陣列上鏡射一致性群組的成員磁碟區是否符合本機儲存陣列上鏡射一致性群組的成員磁碟區。
* *延遲*：將SCSI測試單元命令傳送至遠端儲存陣列上與鏡射一致性群組相關聯的每個鏡射磁碟區、以測試最小、平均和最大延遲。
* *頻寬*：將兩個陣列間訊息傳送至遠端儲存陣列、以測試執行測試之陣列上連接埠的最小、平均和最大頻寬、以及協調的連結速度。
* *連接埠連線*-顯示本機儲存陣列上用於鏡射的連接埠、以及在遠端儲存陣列上接收鏡射資料的連接埠。


.步驟
. 選取功能表：Storage[非同步鏡射]。
. 選取「*鏡射一致性群組*」索引標籤、然後選取您要測試的鏡射一致性群組。
. 選擇*測試通訊*。
+
「測試通訊」對話方塊隨即出現。

. 選取一或多個通訊測試、以在與所選鏡射一致性群組相關的本機與遠端儲存陣列之間執行、然後按一下* Test*。
. 檢閱「結果」視窗中顯示的資訊。
+
[cols="35h,~"]
|===
| 通訊測試狀態 | 說明 


 a| 
正常、沒有錯誤
 a| 
鏡射一致性群組正在正確通訊。



 a| 
通過狀態（但不正常）
 a| 
請檢查可能的網路或連線問題、然後重試測試。



 a| 
失敗狀態
 a| 
顯示故障原因。請參閱Recovery Guru以修正問題。



 a| 
連接埠連線錯誤
 a| 
原因可能是本機儲存陣列未連線、或無法聯絡遠端儲存陣列。請參閱Recovery Guru以修正問題。

|===


.結果
通訊測試完成後、此對話方塊會顯示「正常」狀態、「通過」狀態或「失敗」狀態。

如果通訊測試傳回「失敗」狀態、則會在您關閉此對話方塊之後繼續執行測試、直到鏡射一致性群組之間的通訊恢復為止。
