---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: 您必須使用系統管理員密碼來設定儲存陣列、以防止其遭到未獲授權的存取。 
---
= 管理密碼保護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須使用密碼來設定儲存陣列、以防止未獲授權的存取。



== 設定及變更密碼

第一次啟動System Manager時、系統會提示您設定管理員密碼。擁有管理員密碼的任何使用者都可以變更儲存陣列的組態、例如新增、變更或移除物件或設定。若要在初始啟動期間設定管理密碼、請參閱 link:../san-getstarted/access-sam.html["存取系統管理員"]。

基於安全考量、您只能在儲存陣列進入「鎖定」狀態之前、嘗試輸入密碼五次。在此狀態下、儲存陣列將拒絕後續的密碼嘗試。您必須等待10分鐘、讓儲存陣列重設為「正常」狀態、才能再次輸入密碼。

除了管理員密碼之外、儲存陣列還包含預先定義的使用者設定檔、其中有一個或多個角色對應到這些設定檔。如需詳細資訊、請參閱 link:../sm-settings/permissions-for-mapped-roles.html["對應角色的權限"]。無法變更使用者設定檔和對應。只能修改密碼。如果您要變更管理密碼或其他使用者密碼、請參閱 link:../sm-settings/change-passwords.html["變更密碼"]。



== 在工作階段逾時後重新輸入密碼

在單一管理工作階段期間、系統只會提示您輸入一次密碼。不過、如果工作階段在閒置30分鐘後逾時、您必須再次輸入密碼。如果在工作階段進行期間、另一位從其他管理用戶端管理相同儲存陣列的使用者變更密碼、則下次嘗試組態作業或檢視作業時、系統會提示您輸入密碼。

您可以調整工作階段逾時時間、也可以一併停用工作階段逾時。請參閱 link:../sm-settings/manage-session-timeouts-sam.html["管理工作階段逾時"]。



== 移除磁碟機或密碼保護

如果您移除受密碼保護的磁碟機、或想要停用密碼保護、請注意下列事項：

* *如果您移除具有密碼保護*的磁碟機、則密碼會儲存在儲存陣列上每個磁碟機的保留區。如果從儲存陣列移除所有磁碟機、其密碼將不再有效。若要修正此狀況、請將其中一個原始磁碟機重新安裝至儲存陣列。
* *如果您想要移除密碼保護*-如果您不想再使用密碼保護命令、請輸入目前的管理員密碼、並將新密碼文字方塊保留空白。


[CAUTION]
====
在儲存陣列上執行組態命令可能會造成嚴重損害、包括資料遺失。因此、您應該永遠為儲存陣列設定管理員密碼。請使用至少15個英數字元的長管理員密碼來提高安全性。

====