---
permalink: sm-interface/faq-storage-system-setup.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 的儲存系統設定常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 如果我沒有看到所有硬體組件怎麼辦？

如果您在「驗證硬體」對話方塊中沒有看到所有的硬體元件、可能表示磁碟機櫃連接不正確、或儲存陣列中安裝了不相容的磁碟櫃。

確認所有磁碟機櫃均已正確連接。如果您不確定哪些磁碟機櫃是否相容、請聯絡技術支援部門。



== 如果我沒有看到所有主機怎麼辦？

如果您沒有看到連線的主機、則表示自動偵測失敗、主機連線不正確、或是目前沒有連線任何主機。

設定完成後、您可以稍後再設定主機。您可以手動建立主機、如下所示：

* 您可以移至功能表：Storage[hosts]、手動建立主機並關聯適當的主機連接埠識別碼。手動建立的主機也會顯示在*初始設定*精靈中。
* 目標和主機必須針對主機連接埠類型（例如iSCSI或NVMe over RoCE）進行設定、並在自動偵測開始運作之前、先建立與儲存設備的工作階段。




== 識別應用程式如何協助我管理儲存陣列？

當您識別應用程式時， SANtricity 系統管理員會根據應用程式類型，自動建議使用可最佳化儲存設備的 Volume 組態。

依應用程式最佳化磁碟區可讓資料儲存作業更有效率。磁碟區組態中包含I/O類型、區段大小、控制器擁有權、讀寫快取等特性。此外、您可以依應用程式和工作負載檢視效能資料、以評估應用程式及其相關工作負載的延遲、IOPS和MIB/s。



== 什麼是工作負載？

對於網路中的某些應用程式（例如SQL Server或Exchange）、您可以定義工作負載來最佳化該應用程式的儲存設備。

工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

在Volume建立期間、系統會提示您回答有關工作負載使用的問題。例如、如果您要為Microsoft Exchange建立磁碟區、系統會詢問您需要多少信箱、平均信箱容量需求為何、以及您想要的資料庫複本數量。系統會使用此資訊為您建立最佳Volume組態、並可視需要加以編輯。



== 我要如何設定AutoSupport 供應方法以利執行？

若要存取AutoSupport 有關供應功能的組態工作、請前往功能表：Support（支援中心）、然後按一下* AutoSupport 《*》索引標籤。

支援下列通訊協定： HTTPS 和 SMTP 。



== 如何知道我是否應該接受建議的集區組態？

是否接受建議的資源池組態取決於幾個因素。

回答下列問題、判斷最符合您需求的儲存設備類型：

* 您是否偏好多個容量較小的資源池、而非最大的資源池？
* 您偏好RAID Volume群組而不偏好集區嗎？
* 您偏好手動配置磁碟機、而不是建議您使用組態嗎？


如果您對上述任何問題回答「是」、請考慮拒絕建議的資源池組態。



== SANtricity 系統管理員未偵測到任何主機。我該怎麼辦？

如果您沒有看到連線的主機、則表示自動偵測失敗、主機連線不正確、或是目前沒有連線任何主機。

設定完成後、您可以稍後再設定主機。您可以手動建立主機、如下所示：

* 您可以移至功能表：Storage[hosts]、手動建立主機並關聯適當的主機連接埠識別碼。手動建立的主機也會顯示在*初始設定*精靈中。
* 目標和主機必須針對主機連接埠類型（例如iSCSI或NVMe over RoCE）進行設定、並在自動偵測開始運作之前、先建立與儲存設備的工作階段。

