---
permalink: sm-interface/faq-management-interface.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 管理介面常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 支援哪些瀏覽器？

SANtricity 系統管理員支援這些瀏覽器版本。

[cols="1a,1a"]
|===
| 瀏覽器 | 最低版本 


 a| 
Google Chrome
 a| 
89



 a| 
Mozilla Firefox
 a| 
80



 a| 
Safari
 a| 
14.



 a| 
Microsoft Edge
 a| 
90

|===


== 什麼是鍵盤快速鍵？

您可以單獨使用鍵盤瀏覽 SANtricity 系統管理員。



=== 整體導覽

[cols="1a,1a"]
|===
| 行動 | 鍵盤快速鍵 


 a| 
移至下一個項目。
 a| 
索引標籤



 a| 
移至上一個項目。
 a| 
Shift + Tab



 a| 
選取項目。
 a| 
輸入



 a| 
下拉式清單-移至下一個或上一個項目。
 a| 
向下鍵或向上鍵



 a| 
核取方塊-選取項目。
 a| 
空格鍵



 a| 
選項按鈕-在項目之間切換。
 a| 
向下鍵或向上鍵



 a| 
可擴充的文字-展開或縮小項目。
 a| 
輸入

|===


=== 表格導覽

[cols="1a,1a"]
|===
| 行動 | 鍵盤快速鍵 


 a| 
選取一列。
 a| 
索引標籤以選取列、然後按Enter



 a| 
向上或向下捲動。
 a| 
向下鍵/向上鍵或向下鍵/向上鍵



 a| 
變更欄的排序順序。
 a| 
索引標籤以選取欄標題、然後按Enter

|===


=== 行事曆導覽

[cols="1a,1a"]
|===
| 行動 | 鍵盤快速鍵 


 a| 
移至上一個月。
 a| 
上一頁



 a| 
移至下個月。
 a| 
下一頁



 a| 
移至上一年。
 a| 
控制+ Page Up



 a| 
邁向下一年。
 a| 
控制+向下翻頁



 a| 
如果關閉、請開啟日期選擇器。
 a| 
控制+主畫面



 a| 
移至本月。
 a| 
控制/命令+首頁



 a| 
移到前一天。
 a| 
控制/命令+左



 a| 
移至隔天。
 a| 
控制/命令+右



 a| 
移至上一週。
 a| 
控制/命令+向上



 a| 
移至下週。
 a| 
控制/命令+向下



 a| 
選取焦點日期。
 a| 
輸入



 a| 
關閉日期選擇器並清除日期。
 a| 
控制/命令+結束



 a| 
關閉日期選擇器而不選取任何項目。
 a| 
逃離

|===


== 個別磁碟區的效能統計資料與總計有何關聯？

集區和磁碟區群組的統計資料是透過彙總所有磁碟區（包括保留容量磁碟區）來計算。

保留容量是由儲存系統內部使用、以支援精簡磁碟區、快照和非同步鏡射、I/O主機無法看到。因此、集區、控制器和儲存陣列的統計資料可能不會加總成可見磁碟區的總和。

不過、對於應用程式和工作負載統計資料、只會彙總可見的磁碟區。



== 為什麼圖表中的資料顯示為零？

如果圖表中的資料點顯示零、表示該時間點的物件沒有I/O活動。發生這種情況的原因可能是主機未對該物件起始I/O、或是物件本身發生問題。

物件的歷史資料仍可供檢視。圖表和表格會在物件的I/O活動開始時顯示非零資料。

下表列出資料點值在任何特定物件中可能為零的最常見原因。

[cols="25h,~"]
|===
| 陣列層級物件類型 | 原因資料顯示為零 


 a| 
Volume
 a| 
* Volume沒有主機指派。




 a| 
Volume群組
 a| 
* 正在匯入Volume群組。
* Volume群組不包含指派給主機的磁碟區、*和_* Volume群組不包含任何保留容量。




 a| 
磁碟機
 a| 
* 磁碟機故障。
* 磁碟機已移除。
* 磁碟機處於未知狀態。




 a| 
控制器
 a| 
* 控制器離線。
* 控制器故障。
* 控制器已移除。
* 控制器處於未知狀態。




 a| 
儲存陣列
 a| 
* 儲存陣列不包含磁碟區。


|===


== 延遲圖表顯示什麼？

延遲圖表以毫秒（毫秒）為單位、針對磁碟區、磁碟區群組、集區、 應用程式與工作負載。此圖表會顯示在「邏輯檢視」、「實體檢視」及「應用程式與工作負載檢視」索引標籤中。

延遲是指在讀取或寫入資料時發生的任何延遲。將游標停留在圖表上的某個點上、即可檢視該時間點的下列值（以毫秒（毫秒）為單位）：

* 讀取時間。
* 寫入時間：
* 平均I/O大小。




== IOPS圖表顯示什麼？

IOPS圖表會顯示每秒輸入/輸出作業的統計資料。在首頁上、此圖表會顯示儲存陣列的統計資料。在「效能」方塊的「邏輯檢視」、「實體檢視」及「應用程式與工作負載檢視」索引標籤中、此圖表會顯示儲存陣列、磁碟區、磁碟區群組、集區、應用程式、 和工作負載。

IOPS是每秒_輸入/輸出（I/O）作業的縮寫。將游標停留在圖表上的某個點上、即可檢視該時間點的下列值：

* 讀取作業數。
* 寫入作業數。
* 合併的讀寫作業總計。




== MIB/s圖顯示什麼？

MIB/s圖以每秒兆位元組的單位顯示傳輸速度統計資料。在首頁上、此圖表會顯示儲存陣列的統計資料。在「效能」方塊的「邏輯檢視」、「實體檢視」及「應用程式與工作負載檢視」索引標籤中、此圖表會顯示儲存陣列、磁碟區、磁碟區群組、集區、應用程式、 和工作負載。

MIB/s是_mibibibytes per second_的縮寫、即每秒1、048、576位元組。將游標停留在圖表上的某個點上、即可檢視該時間點的下列值：

* 讀取的資料量。
* 寫入的資料量。
* 讀取和寫入的總資料量。




== CPU圖表顯示什麼？

CPU圖表會顯示每個控制器（控制器A和控制器B）的處理容量統計資料。CPU是_Central處理器單元_的縮寫。在首頁上、此圖表會顯示儲存陣列的統計資料。在「Performance（效能）」方塊的「Physical View（實體檢視）」索引標籤上、此圖表會顯示儲存陣列和磁碟機的統計資料。

CPU圖表顯示陣列上的作業所使用的CPU處理容量百分比。即使沒有發生外部I/O、CPU使用率百分比也可能非零、因為儲存作業系統可能正在執行背景作業和監控。將游標停留在圖表上的某個點上、即可檢視當時使用的處理能力百分比。



== 保留空間圖表顯示什麼內容？

保留空間圖表與儲存陣列控制器的剩餘效能功能有關。此圖表可在「首頁」和「效能」方塊的「實體檢視」索引標籤上看到。

保留空間圖表顯示儲存系統中實體物件的剩餘效能。將游標停留在圖表上的某個點上、即可檢視控制器A和控制器B的IOPS和MIB/s剩餘容量百分比



== 哪裡可以找到更多有關顯示偏好設定的資訊？

若要尋找可用顯示選項的相關資訊：

* 若要深入瞭解顯示容量值的預設單位、請參閱 link:set-default-units-for-capacity-values.html["設定容量值的預設單位"]。
* 若要深入瞭解顯示效能圖表的預設時間範圍、請參閱 link:set-default-time-frame-for-performance-graphs.html["設定效能圖表的預設時間範圍"]。

