---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: 您可以瀏覽主介面、以存取System Manager的功能和工作。 
---
= SANtricity 系統管理員介面概觀
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity 系統管理員是網路型介面，可讓您在單一檢視中管理儲存陣列。



== 首頁

首頁提供儀表板檢視、可用於儲存陣列的每日管理。登入System Manager時、首頁會顯示第一個畫面。

儀表板檢視包含四個摘要區域、其中包含儲存陣列狀態和健全狀況的重要資訊。您可以在摘要區域中找到更多資訊。

[cols="25h,~"]
|===
| 區域 | 說明 


 a| 
通知
 a| 
通知區域會顯示問題通知、指出儲存陣列及其元件的狀態。此外、此入口小工具會顯示自動警示、協助您疑難排解問題、避免影響儲存環境的其他區域。



 a| 
效能
 a| 
「效能」區域可讓您比較及對照一段時間內的資源使用量。您可以檢視儲存陣列的回應時間（IOPS）、傳輸率（MIB/s）及使用的處理容量（CPU）效能指標。



 a| 
容量
 a| 
容量區域會顯示已分配容量、可用儲存容量及儲存陣列中未指派儲存容量的圖表檢視。



 a| 
儲存階層架構
 a| 
「儲存階層」區域提供由儲存陣列管理之各種硬體元件和儲存物件的組織檢視。按一下下拉式箭頭、對該硬體元件或儲存物件執行特定動作。

|===


== 介面設定

您可以從主介面變更顯示偏好設定和其他設定。

[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
顯示偏好設定
 a| 
從介面右上角的「偏好設定」下拉式清單中變更容量值和時間範圍。



 a| 
工作階段逾時
 a| 
設定逾時、讓使用者的非作用中工作階段在指定時間後中斷連線。



 a| 
說明
 a| 
從介面右上角的下拉式清單存取說明文件和其他資源。

|===


== 使用者登入和密碼

目前登入系統的使用者會顯示在介面右上角。

如需使用者和密碼的詳細資訊、請參閱：

* link:administrator-password-protection.html["設定管理密碼保護"]
* link:../sm-settings/change-passwords.html["變更密碼"]

