---
permalink: sm-interface/setup-wizard-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, setup wizard 
summary: 使用設定精靈來設定儲存陣列、包括硬體、主機、應用程式、工作負載、 資源池、警示和AutoSupport 
---
= 設定精靈總覽
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用設定精靈來設定儲存陣列、包括硬體、主機、應用程式、工作負載、 資源池、警示和AutoSupport



== 首次設定

第一次開啟System Manager時、會啟動設定精靈。安裝精靈會提示您執行基本的組態工作、例如命名儲存陣列、設定主機、選取應用程式、以及建立儲存資源池。


NOTE: 在繼續初始設定之前、請前往升級中心（功能表：Support [Upgrade Center]）、並確定SANtricity 您的作業系統軟體是最新的。如有需要、請升級至最新版本、並重新整理瀏覽器以繼續設定。如需詳細資訊、請參閱 link:../sm-support/overview-upgrade-center.html["升級中心總覽"]。

如果您取消精靈、就無法手動重新啟動精靈。當您開啟System Manager或重新整理瀏覽器時、精靈會自動重新啟動、且至少符合下列條件之一：

* 未偵測到資源池和磁碟區群組。
* 未偵測到工作負載。
* 未設定任何通知。




== 術語

安裝精靈使用下列詞彙。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
應用程式
 a| 
應用程式是軟體程式、例如Microsoft SQL Server或Microsoft Exchange。



 a| 
警示
 a| 
警示會通知系統管理員儲存陣列上發生的重要事件。警示可透過電子郵件、SNMP設陷或系統記錄傳送。



 a| 
AutoSupport
 a| 
此功能可監控儲存陣列的健全狀況、並將自動派單傳送給技術支援部門。AutoSupport



 a| 
硬體
 a| 
儲存系統硬體包括儲存陣列、控制器和磁碟機。



 a| 
主機
 a| 
主機是一種伺服器、可將I/O傳送至儲存陣列上的磁碟區。



 a| 
物件
 a| 
物件是任何邏輯或實體儲存元件。邏輯物件包括磁碟區群組、集區和磁碟區。實體物件包括儲存陣列、陣列控制器、主機和磁碟機。



 a| 
資源池
 a| 
資源池是邏輯分組的一組磁碟機。您可以使用集區來建立一個或多個可供主機存取的磁碟區。（您可以從集區或磁碟區群組建立磁碟區。）



 a| 
Volume
 a| 
Volume是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機所建立的邏輯元件、可用來存取儲存陣列上的儲存設備。

磁碟區是從集區或磁碟區群組中可用的容量所建立。磁碟區具有已定義的容量。雖然磁碟區可能包含多個磁碟機、但磁碟區會顯示為主機的一個邏輯元件。



 a| 
Volume群組
 a| 
Volume群組是具有共享特性之磁碟區的容器。Volume群組具有已定義的容量和RAID層級。您可以使用Volume群組來建立一個或多個可讓主機存取的磁碟區。（您可以從磁碟區群組或集區建立磁碟區。）



 a| 
工作負載
 a| 
工作負載是支援應用程式的儲存物件。您可以針對每個應用程式定義一或多個工作負載或執行個體。對於某些應用程式、系統會將工作負載設定為包含具有類似基礎Volume特性的磁碟區。這些Volume特性是根據工作負載所支援的應用程式類型而最佳化。例如、如果您建立支援Microsoft SQL Server應用程式的工作負載、然後為該工作負載建立磁碟區、則基礎磁碟區特性會最佳化以支援Microsoft SQL Server。

|===