---
permalink: sm-interface/view-storage-hierarchy.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, storage hierarchy 
summary: 主介面上的「儲存階層」可讓您以組織方式檢視儲存陣列所管理的各種硬體元件和儲存物件。 
---
= 檢視儲存階層架構
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
主介面上的「儲存階層」可讓您以組織方式檢視儲存陣列所管理的各種硬體元件和儲存物件。

若要檢視儲存階層架構、請前往首頁、然後按一下儲存陣列元件或儲存物件上的下拉式箭頭。儲存陣列由實體元件和邏輯元件的集合所組成。



== 實體元件

本表說明儲存陣列的實體元件。

[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
控制器
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並實作System Manager功能。



 a| 
機櫃
 a| 
機櫃是安裝在機櫃或機架中的機箱。其中包含儲存陣列的硬體元件。磁碟櫃有兩種類型：控制器磁碟櫃和磁碟機磁碟櫃。控制器機櫃包含控制器和磁碟機。磁碟機櫃包含輸入/輸出模組（IOM）和磁碟機。

[NOTE]
====
如果您的儲存陣列包含不同的媒體類型或不同的介面類型、則會顯示每種磁碟機類型的磁碟機櫃。

====


 a| 
磁碟機
 a| 
磁碟機是一種電磁機械裝置或固態記憶體設備、可提供資料的實體儲存媒體。



 a| 
主機
 a| 
主機是一種伺服器、可將I/O傳送至儲存陣列上的磁碟區。



 a| 
主機匯流排介面卡（HBA）
 a| 
主機匯流排介面卡（HBA）是一種主機板、位於主機中、包含一或多個主機連接埠。



 a| 
主機連接埠
 a| 
主機連接埠是主機匯流排介面卡（HBA）上的連接埠、可提供與控制器的實體連線、並用於I/O作業。



 a| 
管理用戶端
 a| 
管理用戶端是指安裝瀏覽器以存取System Manager的電腦。

|===


== 邏輯元件

儲存陣列中的磁碟機提供資料的實體儲存容量。使用System Manager將實體容量設定為邏輯元件、例如集區、磁碟區群組和磁碟區。這些元件是您用來設定、儲存、維護及保留儲存陣列資料的工具。本表說明儲存陣列的邏輯元件。

[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
資源池
 a| 
資源池是邏輯分組的一組磁碟機。您可以使用集區來建立一個或多個可供主機存取的磁碟區。（您可以從集區或磁碟區群組建立磁碟區。）



 a| 
Volume群組
 a| 
Volume群組是具有共享特性之磁碟區的容器。Volume群組具有已定義的容量和RAID層級。您可以使用Volume群組來建立一個或多個可讓主機存取的磁碟區。（您可以從磁碟區群組或集區建立磁碟區。）



 a| 
Volume
 a| 
Volume是應用程式、資料庫和檔案系統儲存資料的容器。它是為主機所建立的邏輯元件、可用來存取儲存陣列上的儲存設備。



 a| 
邏輯單元編號（LUN）
 a| 
邏輯單元編號（LUN）是指派給主機用來存取磁碟區之位址空間的編號。磁碟區會以LUN的形式、以容量形式呈現給主機。

每個主機都有自己的LUN位址空間。因此、不同主機可以使用相同的LUN來存取不同的磁碟區。

|===