---
permalink: sm-hardware/allow-remote-login.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, login, 
summary: 遠端登入可讓區域網路外部的使用者啟動SSH工作階段、並變更控制器上的設定。 
---
= 設定遠端登入（SSH）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
啟用遠端登入後、即可讓區域網路外部的使用者啟動SSH工作階段、並存取控制器上的設定。

對於版本11.74及更新版本、您也可以要求使用者輸入SSH金鑰及/或SSH密碼、來設定多因素授權（MFA）SANtricity 。對於11.73版及更早版本、此功能不包含使用SSH金鑰和密碼進行多因素授權的選項。SANtricity

[CAUTION]
====
*安全風險*：基於安全考量、只有技術支援人員才應使用遠端登入功能。

====
.步驟
. 選取*硬體*。
. 如果圖形顯示磁碟機、請按一下*顯示磁碟櫃背面*。
+
圖形會變更、以顯示控制器而非磁碟機。

. 按一下您要設定遠端登入的控制器。
+
此時會出現控制器的內容功能表。

. 選擇*設定遠端登入（SSH）*。（SANtricity 對於11.73版及更早版本、此功能表項目為*變更遠端登入*。）
+
隨即開啟對話方塊、以啟用遠端登入。

. 選取「*啟用遠端登入*」核取方塊。
+
此設定提供三種授權選項：

+
** *僅限密碼*。對於此選項、您已完成、並可按一下*「Save（儲存）」*。如果您有雙工系統、您可以依照前述步驟、在第二個控制器上啟用遠端登入。
** * SSH金鑰或密碼*。針對此選項、請繼續下一步。
** *密碼和SSH金鑰*。對於此選項、請選取「*遠端登入需要授權的公開金鑰和密碼*」核取方塊、然後繼續下一步。


. 填寫*授權公開金鑰*欄位。此欄位包含以OpenSSH *授權金鑰*檔案格式的授權公開金鑰清單。
+
填入*授權公開金鑰*欄位時、請注意下列準則：

+
** 「*授權公開金鑰*」欄位適用於這兩個控制器、僅需在第一個控制器上設定。
** 每行*授權金鑰*檔案只能包含一個金鑰。以#開頭的行和空白行將被忽略。如需檔案格式的詳細資訊、請參閱 link:https://www.ssh.com/academy/ssh/authorized-keys-openssh["設定OpenSSH的授權金鑰"^]。
** *授權金鑰*檔案應類似下列範例：
+
[listing]
----
ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQDJlG20rYTk4ok+xFjkPHYp/R0LfJqEYDLXA5AJ49w3DvAWLrUg+1CpNq76WSqmQBmoG9jgbcAB5ABGdswdeMQZHilJcu29iJ3OKKv6SlCulAj1tHymwtbdhPuipd2wIDAQAB
----


. 完成後、請按一下*「Save（儲存）」*。
. 對於雙工系統、您可以依照上述步驟、在第二個控制器上啟用遠端登入。如果您同時設定密碼和SSH金鑰選項、請務必再次選取*要求授權的公開金鑰和密碼以進行遠端登入*核取方塊。
. 技術支援完成疑難排解後、您可以返回「設定遠端登入」對話方塊、取消選取「*啟用遠端登入*」核取方塊、以停用遠端登入。如果在第二個控制器上啟用遠端登入、則會開啟確認對話方塊、並允許您停用第二個控制器上的遠端登入。
+
停用遠端登入會終止任何目前的SSH工作階段、並拒絕任何新的登入要求。


