---
permalink: sm-hardware/configure-ntp-server-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, ntp, server, addresses, network, time, protocol, 
summary: 您可以設定網路時間傳輸協定（NTP）伺服器的連線、以便控制器定期查詢NTP伺服器、以更新其內部時間時鐘。 
---
= 設定NTP伺服器位址
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定網路時間傳輸協定（NTP）伺服器的連線、以便控制器定期查詢NTP伺服器、以更新其內部時間時鐘。

.開始之前
* NTP伺服器必須安裝並設定在您的網路中。
* 您必須知道主要NTP伺服器的位址、以及選用的備份NTP伺服器。這些位址可以是完整網域名稱、IPv4位址或IPv6位址。


[NOTE]
====
如果您為NTP伺服器輸入一或多個網域名稱、也必須設定DNS伺服器來解析NTP伺服器位址。您只需要在設定NTP並提供網域名稱的控制器上設定DNS伺服器。

====
.關於這項工作
NTP可讓儲存陣列使用簡單網路時間傳輸協定（SNTP）、自動將控制器時鐘與外部主機同步。控制器會定期查詢已設定的NTP伺服器、然後使用結果來更新其內部每日時鐘。如果只有一個控制器啟用NTP、則替代控制器會定期與啟用NTP的控制器同步時鐘。如果兩個控制器都未啟用NTP、則控制器會定期同步時鐘。

[NOTE]
====
您不需要在這兩個控制器上設定NTP、但這樣做可改善儲存陣列在硬體或通訊故障期間保持同步的能力。

====
.步驟
. 選取*硬體*。
. 如果圖形顯示磁碟機、請按一下*顯示磁碟櫃背面*。
+
圖形會變更、以顯示控制器而非磁碟機。

. 按一下您要設定的控制器。
+
此時會出現控制器的內容功能表。

. 選擇*設定NTP伺服器*。
+
此時會開啟「設定網路時間傳輸協定（NTP）伺服器」對話方塊。

. 選擇*我要在控制器*上啟用NTP（* A*或* B*）。
+
其他選項會出現在對話方塊中。

. 選取下列其中一個選項：
+
** *自動從DHCP伺服器取得NTP伺服器位址*-顯示偵測到的NTP伺服器位址。
+
[NOTE]
====
如果儲存陣列設定為使用靜態NTP位址、則不會顯示NTP伺服器。

====
** *手動指定NTP伺服器位址*-輸入主要NTP伺服器位址和備份NTP伺服器位址。備份伺服器為選用功能。（這些地址欄位會在您選取選項按鈕之後顯示。） 伺服器位址可以是完整網域名稱、IPv4位址或IPv6位址。


. *選用：*輸入備份NTP伺服器的伺服器資訊和驗證認證資料。
. 按一下「 * 儲存 * 」。


.結果
NTP伺服器組態會顯示在控制器設定* DNS / ntp *索引標籤中。
