---
permalink: sm-hardware/configure-iscsi-ports-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, ports, 
summary: 如果您的控制器包含iSCSI主機連線、您可以從「硬體」頁面設定iSCSI連接埠設定。 
---
= 設定iSCSI連接埠
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的控制器包含iSCSI主機連線、您可以從「硬體」頁面設定iSCSI連接埠設定。

.開始之前
* 您的控制器必須包含iSCSI連接埠、否則iSCSI設定將無法使用。
* 您必須知道網路速度（連接埠與主機之間的資料傳輸率）。


[NOTE]
====
iSCSI設定與功能僅在儲存陣列支援iSCSI時才會顯示。

====
.步驟
. 選取*硬體*。
. 如果圖形顯示磁碟機、請按一下*顯示磁碟櫃背面*。
+
圖形會變更、以顯示控制器而非磁碟機。

. 按一下要設定iSCSI連接埠的控制器。
+
此時會出現控制器的內容功能表。

. 選取*設定iSCSI連接埠*。
+
[NOTE]
====
僅當System Manager偵測到控制器上的iSCSI連接埠時、才會顯示* Configure iSCSI連接埠*選項。

====
+
此時將打開Configure iSCSI Portes（配置iSCSI端口）對話框。

. 在下拉式清單中、選取您要設定的連接埠、然後按一下「*下一步*」。
. 選取組態連接埠設定、然後按一下「*下一步*」。
+
若要查看所有連接埠設定、請按一下對話方塊右側的*顯示更多連接埠設定*連結。

+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 連接埠設定 | 說明 


 a| 
已設定的乙太網路連接埠速度（僅適用於特定類型的主機介面卡）
 a| 
選取與連接埠上SFP速度功能相符的速度。



 a| 
轉送錯誤修正（FEC）模式（僅適用於特定類型的主機介面卡）
 a| 
如有需要、請為指定的主機連接埠選取FEC模式之一。


NOTE: Reed Solomon模式不支援25 Gbps連接埠速度。



 a| 
啟用IPV4 /啟用IPv6
 a| 
選取一個或兩個選項、以啟用對IPv4和IPv6網路的支援。


NOTE: 如果您要停用連接埠存取、請取消選取這兩個核取方塊。



 a| 
TCP接聽連接埠（按一下*顯示更多連接埠設定*即可取得）。
 a| 
如有必要、請輸入新的連接埠號碼。

接聽連接埠是控制器用來接聽來自主機iSCSI啟動器之iSCSI登入的TCP連接埠號碼。預設的接聽連接埠為3260。您必須輸入3260或49152到65535.之間的值。



 a| 
MTU大小（按一下*顯示更多連接埠設定*即可取得）。
 a| 
如有必要、請為最大傳輸單元（MTU）輸入新的位元組大小。

預設的最大傳輸單元（MTU）大小為每個框架1500位元組。您必須輸入介於1500和9000之間的值。



 a| 
啟用ICMP Ping回應
 a| 
選取此選項可啟用網際網路控制訊息傳輸協定（ICMP）。網路電腦的作業系統會使用此傳輸協定來傳送訊息。這些ICMP訊息可判斷主機是否可連線、以及從該主機取得封包所需的時間。

|===
====
+
如果您選取*啟用IPV4、則會在您按一下*下一步*之後、開啟一個對話方塊、供您選取IPV4設定。如果您選取*啟用IPv6 *、則會在您按一下*下一步*之後、開啟一個對話方塊來選取IPv6設定。如果您同時選取這兩個選項、則會先開啟[IPV4設定]對話方塊、然後按一下[* Next*（*下一步*）]之後、隨即開啟[IPv6設定]對話方塊。

. 自動或手動設定IPv6和/或IPv6設定。若要查看所有連接埠設定、請按一下對話方塊右側的*顯示更多設定*連結。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 連接埠設定 | 說明 


 a| 
自動取得組態
 a| 
選取此選項可自動取得組態。



 a| 
手動指定靜態組態
 a| 
選取此選項、然後在欄位中輸入靜態位址。（如有需要、您可以剪下地址並貼到欄位中。） 對於IPV4、請加入網路子網路遮罩和閘道。對於IPv6、請包含可路由的IP位址和路由器IP位址。



 a| 
啟用VLAN支援（按一下*「Show More settings（顯示更多設定）」*即可取得。）
 a| 
選取此選項可啟用VLAN並輸入其ID。VLAN是一種邏輯網路、其運作方式類似於實體獨立於其他實體和虛擬區域網路（LAN）、這些區域網路由相同的交換器、相同的路由器或兩者支援。



 a| 
啟用乙太網路優先順序（按一下*顯示更多設定*即可取得）。
 a| 
選取此選項可啟用決定存取網路優先順序的參數。使用滑桿選取介於1（最低）和7（最高）之間的優先順序。

在共享區域網路（LAN）環境（例如乙太網路）中、許多站台可能會爭用網路存取權。存取權以先到先得的方式提供。兩個站台可能會同時嘗試存取網路、這會導致兩個站台都關機並等待、然後再試一次。交換式乙太網路只有一個站台連接到交換器連接埠、此程序就會最小化。

|===
====
. 單擊*完成*。

