---
permalink: sm-hardware/configure-management-ports.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, management, port, 
summary: 控制器包含用於系統管理的乙太網路連接埠。如有必要、您可以變更其傳輸參數和IP位址。 
---
= 設定管理連接埠
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
控制器包含用於系統管理的乙太網路連接埠。如有必要、您可以變更其傳輸參數和IP位址。

.關於這項工作
在此程序中、您選取連接埠1、然後決定速度和連接埠定址方法。連接埠1會連線至管理用戶端可存取控制器和系統管理程式的網路。

[NOTE]
====
請勿在任一控制器上使用連接埠2。連接埠2保留供技術支援使用。

====
.步驟
. 選取*硬體*。
. 如果圖形顯示磁碟機、請按一下*顯示磁碟櫃背面*。
+
圖形會變更、以顯示控制器而非磁碟機。

. 按一下含有您要設定之管理連接埠的控制器。
+
此時會出現控制器的內容功能表。

. 選取*設定管理連接埠*。
+
此時將打開Configure Management Portes（配置管理端口）對話框。

. 確保顯示端口1，然後單擊*下一步*。
. 選取組態連接埠設定、然後按一下「*下一步*」。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
速度與雙工模式
 a| 
如果您想讓System Manager判斷儲存陣列與網路之間的傳輸參數、請保留「自動協調」設定；如果您知道網路的速度與模式、請從下拉式清單中選取參數。清單中只會顯示有效的速度和雙工組合。



 a| 
啟用IPV4 /啟用IPv6
 a| 
選取一個或兩個選項、以啟用對IPv4和IPv6網路的支援。

|===
====
+
如果您選取*啟用IPV4、則會在您按一下*下一步*之後、開啟一個對話方塊、供您選取IPV4設定。如果您選取*啟用IPv6 *、則會在您按一下*下一步*之後、開啟一個對話方塊來選取IPv6設定。如果您同時選取這兩個選項、則會先開啟[IPV4設定]對話方塊、然後按一下[* Next*（*下一步*）]之後、隨即開啟[IPv6設定]對話方塊。

. 自動或手動設定IPv6和/或IPv6設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
自動從DHCP伺服器取得組態
 a| 
選取此選項可自動取得組態。



 a| 
手動指定靜態組態
 a| 
選取此選項、然後輸入控制器的IP位址。（如有需要、您可以剪下地址並貼到欄位中。） 對於IPV4、請加入網路子網路遮罩和閘道。對於IPv6、請包含可路由的IP位址和路由器IP位址。


NOTE: 如果變更IP位址組態、您將失去儲存陣列的管理路徑。如果您使用SANtricity NetApp統一化管理程式來全域管理網路中的陣列、請開啟使用者介面、然後前往功能表：「Manage（管理）」「Discover（探索）」。如果您使用SANtricity 的是「靜態儲存管理員」、則必須從「企業管理」視窗（EMW）移除該裝置、然後選取功能表：「編輯」（Add Storage Array）、再輸入新的IP位址、將其重新新增至EMW。

|===
====
. 單擊*完成*。


.結果
管理連接埠組態會顯示在「控制器設定」的「管理連接埠」索引標籤中。
