---
permalink: sm-hardware/configure-dns-server-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, dns, server, addresses, 
summary: 網域名稱系統（DNS）用於解析控制器和網路時間傳輸協定（NTP）伺服器的完整網域名稱。儲存陣列上的管理連接埠可同時支援IPV4或IPv6傳輸協定。 
---
= 在 SANtricity System Manager 中設定 DNS 伺服器位址
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
網域名稱系統（DNS）用於解析控制器和網路時間傳輸協定（NTP）伺服器的完整網域名稱。儲存陣列上的管理連接埠可同時支援IPV4或IPv6傳輸協定。

.開始之前
* 必須在網路中安裝和設定DNS伺服器。
* 您知道主要DNS伺服器的位址和選用的備份DNS伺服器。這些位址可以是IPv4位址或IPv6位址。


.關於這項工作
本程序說明如何指定主要和備份DNS伺服器位址。備份DNS伺服器可選擇性地設定為在主要DNS伺服器故障時使用。

[NOTE]
====
如果您已使用動態主機組態傳輸協定（DHCP）設定儲存陣列的管理連接埠、且有一或多個DNS或NTP伺服器與DHCP設定相關聯、則不需要手動設定DNS或NTP。在此情況下、儲存陣列應該已自動取得DNS/NTP伺服器位址。不過、您仍應依照下列指示開啟對話方塊、並確定偵測到正確的位址。

====
.步驟
. 選取*硬體*。
. 如果圖形顯示磁碟機、請按一下 * 控制器與元件 * 索引標籤。
+
圖形會變更、以顯示控制器而非磁碟機。

. 選取要設定的控制器。
+
此時會出現控制器的內容功能表。

. 選取*設定DNS伺服器*。
+
此時會開啟「設定網域名稱系統（DNS）伺服器」對話方塊。

. 選取下列其中一個選項：
+
** *自動從DHCP伺服器取得DNS伺服器位址*-顯示偵測到的DNS伺服器位址。
+
[NOTE]
====
如果儲存陣列設定為使用靜態DNS位址、則不會顯示DNS伺服器。

====
** *手動指定DNS伺服器位址*-輸入主要DNS伺服器位址和備份DNS伺服器位址。備份伺服器為選用功能。（這些地址欄位會在您選取選項按鈕之後顯示。） 這些位址可以是IPv4位址或IPv6位址。


. 按一下「 * 儲存 * 」。
. 對另一個控制器重複這些步驟。


.結果
DNS組態會顯示在控制器設定* DNS / ntp *索引標籤中。
