---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, erase, drives, removal, 
summary: 您可以使用「Erase（清除）」選項、準備從系統中移除未指派的磁碟機。此程序會永久移除資料、確保無法再次讀取資料。 
---
= 在 SANtricity System Manager 中擦除磁碟機
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「Erase（清除）」選項、準備從系統中移除未指派的磁碟機。此程序會永久移除資料、確保無法再次讀取資料。

.開始之前
磁碟機必須處於「未指派」狀態。

.關於這項工作
只有當您要永久移除磁碟機上的所有資料時、才可使用「清除」選項。如果磁碟機已啟用安全功能、「清除」選項會執行密碼編譯清除、並將磁碟機的安全屬性重設回具有安全功能的屬性。

[NOTE]
====
「清除」功能不支援某些較舊的磁碟機機型。如果您嘗試清除其中一種舊機型、會出現錯誤訊息。

====
.步驟
. 選取*硬體*。
. 如果圖形顯示控制器、請按一下 * 磁碟機 * 索引標籤。
+
圖形會變更、以顯示磁碟機而非控制器。

. 或者、您可以使用篩選欄位來檢視機櫃中所有未指派的磁碟機。從*顯示磁碟機為...*下拉式清單中、選取*未指派*。
+
機櫃檢視僅顯示未指派的磁碟機、其他所有磁碟機則呈現灰色。

. 若要開啟磁碟機的內容功能表、請按一下您要清除的磁碟機。（如果您要選取多個磁碟機、可以在「清除磁碟機」對話方塊中選取。）
+
[CAUTION]
====
*可能的資料遺失*-「清除」作業無法復原。請務必在程序期間選取正確的磁碟機。

====
. 從內容功能表中選取*清除*。
+
「清除磁碟機」對話方塊隨即開啟、顯示所有符合清除作業資格的磁碟機。

. 如有需要、請從表中選取其他磁碟機。您無法選取_all_磁碟機；請確定一個磁碟機仍未選取。
. 輸入「erase」（清除）、然後按一下「* Eraser*」、確認作業。
+
[CAUTION]
====
請確定您要繼續執行此作業。在下一個對話方塊中按一下「是」之後、就無法中止作業。

====
. 在「預估完成時間」對話方塊中、按一下*是*以繼續清除作業。


.結果
「清除」作業可能需要數分鐘或數小時的時間。您可以在功能表中檢視狀態：首頁[檢視進行中的作業]。當「清除」作業完成時、磁碟機可用於其他磁碟區群組或磁碟集區、或其他儲存陣列。

.完成後
如果您想要再次使用磁碟機、必須先初始化磁碟機。若要執行此操作、請從磁碟機的內容功能表中選取*初始化*。
