---
permalink: sm-hardware/faq-storage-controller.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 的儲存控制器常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 什麼是自動交涉？

「自動協調」是指網路介面能夠自動協調自己的連線參數（速度和雙工）與其他網路介面。

自動交涉通常是設定管理連接埠的慣用設定、但是如果交涉失敗、不相符的網路介面設定可能會嚴重影響網路效能。在無法接受此情況的情況下、您應該手動將網路介面設定設為正確的組態。自動交涉是由控制器的乙太網路管理連接埠執行。iSCSI主機匯流排介面卡不會執行自動交涉。

[NOTE]
====
如果自動交涉失敗、控制器會嘗試以10BASE-T、半雙工、這是最低的共同點來建立連線。

====


== 什麼是IPv6無狀態位址自動組態？

在無狀態自動組態的情況下、主機不會從伺服器取得位址和其他組態資訊。

IPv6中的無狀態自動組態具有連結本機位址、多點傳送和鄰近探索（ND）傳輸協定。IPv6可從基礎資料連結層位址產生位址的介面ID。

無狀態自動組態和狀態自動組態可相輔相成。例如、主機可以使用無狀態自動組態來設定自己的位址、但可使用狀態自動組態來取得其他資訊。狀態自動組態可讓主機從伺服器取得位址和其他組態資訊。網際網路傳輸協定第6版（IPv6）也定義了一種方法、可讓網路上的所有IP位址一次重新編號。IPv6定義了一種方法、可讓網路上的裝置自動設定其IP位址和其他參數、而不需要伺服器。

使用無狀態自動組態時、裝置會執行下列步驟：

. *產生連結本機位址*：裝置會產生連結本機位址、其位址為10位元、後面接著54個零、後面接著64位元介面ID。
. *測試鏈路本機位址*的獨特性：節點會測試以確定其產生的連結本機位址尚未在本機網路上使用。節點使用ND-傳輸協定傳送鄰近請求訊息。因此、本機網路會接聽鄰近通告訊息、指出另一個裝置已使用連結本機位址。如果是、則必須產生新的連結本機位址或自動組態失敗、而且必須使用其他方法。
. *指派連結本機位址*-如果裝置通過唯一性測試、則裝置會將連結本機位址指派給其IP介面。連結本機位址可用於在本機網路上進行通訊、但不能用於透過網際網路進行通訊。
. *聯絡路由器*：節點會嘗試聯絡本機路由器、以取得有關繼續設定的詳細資訊。此聯絡活動的執行方式為：聆聽路由器定期傳送的路由器通告訊息、或傳送特定的路由器請求訊息、詢問路由器有關後續行動的資訊。
. *提供節點的方向*：路由器會向節點提供如何繼續自動組態的指示。或者、路由器會告訴主機如何判斷全域網際網路位址。
. *設定全域位址*：主機使用其全域唯一的網際網路位址自行設定。此位址通常是由路由器提供給主機的網路前置碼所形成。




== 我該選擇哪一個——DHCP 還是手動設定？

網路組態的預設方法是動態主機組態傳輸協定（DHCP）。除非您的網路沒有DHCP伺服器、否則請務必使用此選項。



== 什麼是DHCP伺服器？

動態主機組態傳輸協定（DHCP）是一種傳輸協定、可自動指派網際網路傳輸協定（IP）位址。

每個連線至TCP/IP網路的裝置都必須指派唯一的IP位址。這些設備包括儲存陣列中的控制器。

如果沒有DHCP、網路管理員會手動輸入這些IP位址。使用DHCP時、當用戶端需要啟動TCP/IP作業時、用戶端會廣播位址資訊要求。DHCP伺服器會接收要求、指派新位址一段指定時間（稱為租用期間）、然後將位址傳送給用戶端。有了DHCP、每次裝置連線到網路時、都可以有不同的IP位址。在某些系統中、即使裝置仍在連線中、裝置的IP位址仍可能變更。



== 如何設定我的DHCP伺服器？

您必須設定動態主機組態傳輸協定（DHCP）伺服器、以使用儲存陣列中控制器的靜態網際網路傳輸協定（IP）位址。

您的DHCP伺服器指派的IP位址通常是動態的、而且可能會因為租用期間已過期而變更。有些裝置（例如伺服器和路由器）需要使用靜態位址。儲存陣列中的控制器也需要靜態IP位址。

如需如何指派靜態位址的相關資訊、請參閱DHCP伺服器的文件。



== 為何需要變更控制器網路組態？

使用頻外管理時、您必須為每個控制器設定網路組態、包括其網際網路傳輸協定（IP）位址、子網路遮罩（子網路遮罩）和閘道。

您可以使用動態主機組態傳輸協定（DHCP）伺服器來設定網路組態。如果您不使用DHCP伺服器、則必須手動輸入網路組態。



== 網路組態在哪裡？

您可以從網路管理員取得網際網路傳輸協定（IP）位址、子網路遮罩（子網路遮罩）和閘道資訊。

在控制器上設定連接埠時、您需要此資訊。



== 什麼是ICMP ping回應？

網際網路控制訊息傳輸協定（ICMP）是TCP/IP套件的其中一種傳輸協定。

「ICMP回應要求」和「ICMP回應回覆」訊息通常稱為「ping」訊息。「Ping」是系統管理員用來手動測試網路裝置之間連線、以及測試網路延遲和封包遺失的疑難排解工具。ping命令會將一個「ICMP回應要求」傳送到網路上的裝置、然後裝置會立即以「ICMP回應回覆」回應。有時候、公司的網路安全原則要求在所有裝置上停用「ping」（「ICMP回應回覆」）、讓未經授權的人員更難發現這些裝置。



== 何時應重新整理連接埠組態？

每當修改或升級伺服器時、請重新整理DHCP伺服器、而且與目前儲存陣列和您要使用的儲存陣列相關的DHCP資訊已變更。

具體而言、當您知道DHCP伺服器將指派不同的位址時、請重新整理DHCP伺服器的連接埠組態或iSNS伺服器。

[NOTE]
====
重新整理連接埠組態會破壞該連接埠上的所有iSCSI連線。

====


== 設定管理連接埠之後該怎麼辦？

如果您變更了儲存陣列的IP位址、您可能會想要更新SANtricity 《統一化管理程式（Cisco Unified Manager）」中的全域陣列檢視。

若要在Unified Manager中更新全域陣列檢視、請開啟介面、然後前往功能表：「Manage（管理）」[Discover（探索）。

如果您仍在使用SANtricity 此功能、請前往「企業管理」視窗（EMW）、您必須在其中移除並重新新增新的IP位址。



== 為什麼儲存系統處於非最佳模式？

處於非最佳模式的儲存系統是因為系統組態狀態無效。儘管如此，仍完全支援對現有磁碟區的正常 I/O 存取，但 SANtricity 系統管理員將禁止某些作業。

儲存系統可能因為下列其中一項原因而轉換為「無效的系統組態」：

* 控制器不符合法規要求、可能是因為它的子機型ID（SMID）代碼不正確、或是已超過優質功能的限制。
* 正在進行內部服務作業、例如磁碟機韌體下載。
* 控制器超過同位元檢查錯誤臨界值、並進入鎖定狀態。
* 發生一般鎖定狀況。

