---
permalink: sm-hardware/faq-storage-shelf.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 儲存架常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 什麼是機櫃損失保護和藥櫃損失保護？

機櫃遺失保護和藥櫃遺失保護是資源池和磁碟區群組的屬性、可讓您在單一機櫃或藥櫃故障時維持資料存取。



=== 機櫃損失保護

機櫃是包含磁碟機或磁碟機與控制器的機箱。機櫃遺失保護可確保在單一磁碟機櫃發生通訊完全中斷時、能夠存取資源池或磁碟區群組中磁碟區上的資料。通訊中斷的範例可能是磁碟機櫃電力中斷、或兩個I/O模組（IOM）故障。

[NOTE]
====
如果磁碟機已在集區或磁碟區群組中故障、則無法保證磁碟櫃遺失保護。在這種情況下、失去磁碟機櫃的存取權、進而導致集區或磁碟區群組中的另一個磁碟機遺失資料。

====
機櫃損失保護的準則取決於保護方法、如下表所述：

[cols="1a,1a,1a"]
|===
| 層級 | 機櫃損失保護準則 | 所需的磁碟櫃數量下限 


 a| 
資源池
 a| 
集區必須包含至少五個磁碟櫃的磁碟機、而且每個磁碟櫃中必須有相同數量的磁碟機。機櫃遺失保護不適用於大容量機櫃；如果您的系統含有大容量機櫃、請參閱「藥櫃遺失保護」。
 a| 
5.



 a| 
RAID 6
 a| 
Volume群組在單一磁碟櫃中不包含兩個以上的磁碟機。
 a| 
3.



 a| 
RAID 3或RAID 5
 a| 
Volume群組中的每個磁碟機都位於不同的磁碟櫃中。
 a| 
3.



 a| 
RAID 1
 a| 
RAID 1配對中的每個磁碟機都必須位於不同的磁碟櫃中。
 a| 
2.



 a| 
RAID 0
 a| 
無法達到機架遺失保護。
 a| 
不適用

|===


=== 藥櫃遺失保護

抽屜是您拉出以存取磁碟機的磁碟櫃之一。只有大容量的機櫃才有抽屜。藥櫃遺失保護可確保在單一藥櫃發生通訊中斷時、能夠存取資源池或磁碟區群組中磁碟區上的資料。通訊中斷的範例可能是藥櫃電力中斷、或藥櫃內的內部元件故障。

[NOTE]
====
如果磁碟機已在集區或磁碟區群組中故障、則無法保證藥櫃遺失保護。在這種情況下、無法存取藥櫃（以及池或Volume群組中的另一個磁碟機）會導致資料遺失。

====
藥櫃遺失保護的條件取決於保護方法、如下表所述：

[cols="1a,1a,1a"]
|===
| 層級 | 藥櫃損失保護條件 | 所需的藥櫃數量下限 


 a| 
資源池
 a| 
資源池候選裝置必須包含所有藥櫃的磁碟機、而且每個藥櫃中的磁碟機數量必須相等。

集區必須包含至少五個抽屜的磁碟機、而且每個抽屜中的磁碟機數量必須相等。

當集區包含15、20、25、30、35、 40、45、50、55或60個磁碟機。初始建立之後、可以將5的倍數遞增量新增至資源池。
 a| 
5.



 a| 
RAID 6
 a| 
磁碟區群組在單一藥櫃中不包含兩個以上的磁碟機。
 a| 
3.



 a| 
RAID 3或RAID 5
 a| 
磁碟區群組中的每個磁碟機都位於獨立的磁碟櫃中。
 a| 
3.



 a| 
RAID 1
 a| 
鏡射配對中的每個磁碟機都必須位於獨立的抽屜中。
 a| 
2.



 a| 
RAID 0
 a| 
無法達到藥櫃損失保護。
 a| 
不適用

|===


== 什麼是電池學習週期？

學習週期是自動校準智慧型電池電量表的週期。

學習週期包含下列階段：

* 控制的電池電力耗盡
* 休息期間
* 充電


電池會排空至預先決定的臨界值。在此階段、電池電量表會經過校準。

學習週期需要下列參數：

* 充飽電的電池
* 無過熱的電池


雙工控制器系統的學習週期會同時發生。對於使用多個電池或一組電池供電的控制器、記憶週期會依序進行。

學習週期會排定在一週中的同一天、以固定的時間間隔自動開始。週期之間的時間間隔以週為單位。

[NOTE]
====
學習週期可能需要數小時才能完成。

====