---
permalink: sm-hardware/hardware-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, terms 
summary: 瞭解硬體條款如何適用於您的儲存陣列。 
---
= 硬體術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下列硬體條款適用於儲存陣列。

.一般硬體術語：
[%collapsible]
====
[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
Bay
 a| 
機櫃是機櫃中安裝磁碟機或其他元件的插槽。



 a| 
控制器
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並實作System Manager功能。



 a| 
控制器機櫃
 a| 
控制器機櫃包含一組磁碟機和一或多個控制器容器。控制器容器可容納控制器、主機介面卡（HIC）和電池。



 a| 
磁碟機
 a| 
磁碟機是一種電磁機械裝置或固態記憶體設備、可提供資料的實體儲存媒體。



 a| 
磁碟機櫃
 a| 
磁碟機櫃也稱為擴充櫃、包含一組磁碟機和兩個輸入/輸出模組（IOM）。IOM包含SAS連接埠、可將磁碟機櫃連接至控制器機櫃或其他磁碟機櫃。



 a| 
IOM（ESm）
 a| 
IOM是一種輸入/輸出模組、包含SAS連接埠、可將磁碟機櫃連接至控制器機櫃。在先前的控制器機型中、IOM稱為環境服務模組（ESm）。



 a| 
電力/風扇容器
 a| 
電力/風扇容器是滑入機櫃的組件。其中包括電源供應器和整合式風扇。



 a| 
SFP
 a| 
SFP是小型可插拔（SFP）收發器。



 a| 
機櫃
 a| 
機櫃是安裝在機櫃或機架中的機箱。其中包含儲存陣列的硬體元件。磁碟櫃有兩種類型：控制器磁碟櫃和磁碟機磁碟櫃。控制器機櫃包含控制器和磁碟機。磁碟機櫃包含輸入/輸出模組（IOM）和磁碟機。



 a| 
儲存陣列
 a| 
儲存陣列包括磁碟櫃、控制器、磁碟機、軟體和韌體。

|===
====
.控制器術語：
[%collapsible]
====
[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
控制器
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並實作System Manager功能。



 a| 
控制器機櫃
 a| 
控制器機櫃包含一組磁碟機和一或多個控制器容器。控制器容器可容納控制器、主機介面卡（HIC）和電池。



 a| 
DHCP
 a| 
動態主機組態傳輸協定（DHCP）是一種用於網際網路傳輸協定（IP）網路的傳輸協定、可用來動態分配網路組態參數、例如IP位址。



 a| 
DNS
 a| 
網域名稱系統（DNS）是連線至網際網路或私有網路之裝置的命名系統。DNS伺服器會維護網域名稱目錄、並將其轉譯為網際網路傳輸協定（IP）位址。



 a| 
雙工組態
 a| 
雙工是儲存陣列內的雙控制器模組組組態。雙工系統在控制器、邏輯磁碟區路徑和磁碟路徑方面具有完全備援的功能。如果一個控制器故障、另一個控制器就會接管其I/O、以維持可用度。雙工系統也有備援風扇和電源供應器。



 a| 
全雙工/半雙工連線
 a| 
全雙工和半雙工是指連線模式。在全雙工模式中、兩個裝置可以同時雙向通訊。在半雙工模式中、裝置一次可以單向通訊（一部裝置會傳送訊息、另一部裝置則會接收訊息）。



 a| 
HIC
 a| 
主機介面卡（HIC）可選擇性安裝在控制器容器內。控制器內建的主機連接埠稱為基板主機連接埠。HIC內建的主機連接埠稱為HIC連接埠。



 a| 
ICMP Ping回應
 a| 
網際網路控制訊息傳輸協定（ICMP）是網路電腦的作業系統用來傳送訊息的傳輸協定。ICMP訊息會判斷主機是否可連線、以及從該主機取得封包所需的時間。



 a| 
MAC位址
 a| 
乙太網路使用媒體存取控制識別碼（MAC位址）來區分連接同一個實體傳輸網路介面上兩個連接埠的獨立邏輯通道。



 a| 
管理用戶端
 a| 
管理用戶端是指安裝瀏覽器以存取System Manager的電腦。



 a| 
MTU
 a| 
最大傳輸單元（MTU）是可在網路中傳送的最大封包或框架。



 a| 
NTP
 a| 
網路時間傳輸協定（NTP）是一種網路傳輸協定、可在資料網路中的電腦系統之間進行時鐘同步。



 a| 
單工組態
 a| 
單工是儲存陣列內的單一控制器模組組組態。單工系統不提供控制器或磁碟路徑備援、但有備援風扇和電源供應器。



 a| 
VLAN
 a| 
虛擬區域網路（VLAN）是一種邏輯網路、其運作方式類似於實體獨立於其他受相同裝置（交換器、路由器等）支援的網路。

|===
====
.磁碟機術語：
[%collapsible]
====
[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
大
 a| 
資料保證（DA）是一項功能、可檢查及修正資料經由控制器向下傳輸至磁碟機時可能發生的錯誤。資料保證功能可在集區或磁碟區群組層級啟用、主機可使用具有DA功能的I/O介面、例如Fibre Channel。



 a| 
磁碟機安全功能
 a| 
磁碟機安全性是一項儲存陣列功能、可透過全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機提供額外的安全層級。當這些磁碟機搭配磁碟機安全功能使用時、它們需要安全金鑰才能存取其資料。當磁碟機從陣列中實際移除時、除非安裝在另一個陣列中、否則無法運作、此時磁碟機將處於「安全性鎖定」狀態、直到提供正確的安全金鑰為止。



 a| 
磁碟機櫃
 a| 
磁碟機櫃也稱為擴充櫃、包含一組磁碟機和兩個輸入/輸出模組（IOM）。IOM包含SAS連接埠、可將磁碟機櫃連接至控制器機櫃或其他磁碟機櫃。



 a| 
DULBE
 a| 
在NVMe磁碟機上、取消分配或未寫入的邏輯區塊錯誤（DULBE）是一個選項、可讓EF300或EF600儲存陣列支援資源配置的磁碟區。



 a| 
FDE磁碟機
 a| 
全磁碟加密（FDE）磁碟機在硬體層級對磁碟機執行加密。硬碟內含ASIC晶片、可在寫入期間加密資料、然後在讀取期間解密資料。



 a| 
FIPS磁碟機
 a| 
FIPS磁碟機使用聯邦資訊處理標準（FIPS）140-2第2級。它們基本上是FDE磁碟機、符合美國政府的標準、以確保強大的加密演算法和方法。FIPS磁碟機的安全性標準高於FDE磁碟機。



 a| 
HDD
 a| 
硬碟機（HDD）是資料儲存設備、使用具有磁性塗層的旋轉式金屬盤片。



 a| 
熱備援磁碟機
 a| 
熱備援磁碟機在RAID 1、RAID 5或RAID 6磁碟區群組中扮演待命磁碟機的角色。它們是功能完整的磁碟機、不含任何資料。如果磁碟機在Volume群組中故障、控制器會自動將故障磁碟機的資料重新建構至熱備援磁碟機。



 a| 
NVMe
 a| 
非揮發性記憶體Express（NVMe）是專為Flash型儲存裝置（例如SSD磁碟機）所設計的介面。NVMe可降低I/O負荷、並與先前的邏輯裝置介面相比、提升效能。



 a| 
SAS
 a| 
序列附加SCSI（SAS）是一種點對點序列傳輸協定、可將控制器直接連結至磁碟機。



 a| 
具備安全功能的磁碟機
 a| 
可安全使用的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機、在讀取期間加密資料並解密資料。這些磁碟機被視為安全的磁碟機、因為它們可以使用磁碟機安全功能來提高安全性。如果已針對這些磁碟機所使用的磁碟區群組和集區啟用「磁碟機安全性」功能、磁碟機就會變成安全的-_enabled_.



 a| 
啟用安全功能的磁碟機
 a| 
啟用安全功能的磁碟機可搭配磁碟機安全功能使用。當您啟用「磁碟機安全性」功能、然後將「磁碟機安全性」套用至安全的磁碟機上的集區或磁碟區群組時、磁碟機就會變成安全的__已啟用__。讀寫存取只能透過設定正確安全金鑰的控制器來使用。這項新增的安全功能可防止未獲授權存取從儲存陣列實體移除之磁碟機上的資料。



 a| 
SSD
 a| 
固態磁碟（SSD）是使用固態記憶體（Flash）持續儲存資料的資料儲存裝置。SSD可模擬傳統硬碟機、並與硬碟機使用的介面相同。

|===
====
.iSCSI術語：
[%collapsible]
====
[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
CHAP
 a| 
Challenge Handshake驗證傳輸協定（CHAP）方法會在初始連結期間驗證目標和啟動器的身分識別。驗證是以稱為CHAP _secret _的共用安全金鑰為基礎。



 a| 
控制器
 a| 
控制器由主機板、韌體和軟體組成。它控制磁碟機並實作System Manager功能。



 a| 
DHCP
 a| 
動態主機組態傳輸協定（DHCP）是一種用於網際網路傳輸協定（IP）網路的傳輸協定、可用來動態分配網路組態參數、例如IP位址。



 a| 
IB
 a| 
InfiniBand（IB）是高效能伺服器與儲存系統之間資料傳輸的通訊標準。



 a| 
ICMP Ping回應
 a| 
網際網路控制訊息傳輸協定（ICMP）是網路電腦的作業系統用來傳送訊息的傳輸協定。ICMP訊息會判斷主機是否可連線、以及從該主機取得封包所需的時間。



 a| 
IQN
 a| 
iSCSI合格名稱（IQN）識別碼是iSCSI啟動器或iSCSI目標的唯一名稱。



 a| 
商用
 a| 
RDMA的iSCSI擴充（iSER）是一種傳輸協定、可延伸iSCSI傳輸協定、以透過RDMA傳輸（例如InfiniBand或乙太網路）進行操作。



 a| 
iSNS
 a| 
網際網路儲存名稱服務（iSNS）是一種傳輸協定、可在TCP/IP網路上自動探索、管理及設定iSCSI和光纖通道裝置。



 a| 
MAC位址
 a| 
乙太網路使用媒體存取控制識別碼（MAC位址）來區分連接同一個實體傳輸網路介面上兩個連接埠的獨立邏輯通道。



 a| 
管理用戶端
 a| 
管理用戶端是指安裝瀏覽器以存取System Manager的電腦。



 a| 
MTU
 a| 
最大傳輸單元（MTU）是可在網路中傳送的最大封包或框架。



 a| 
RDMA
 a| 
遠端直接記憶體存取（RDMA）是一項技術、可讓網路電腦在主記憶體中交換資料、而不需涉及任一部電腦的作業系統。



 a| 
未命名的探索工作階段
 a| 
啟用未命名探索工作階段選項時、iSCSI啟動器不需要指定目標IQN來擷取控制器資訊。

|===
====
.NVMe術語：
[%collapsible]
====
[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
InfiniBand
 a| 
InfiniBand（IB）是高效能伺服器與儲存系統之間資料傳輸的通訊標準。



 a| 
命名空間
 a| 
命名空間是NVM儲存設備、其格式化為區塊存取。它類似於SCSI中的邏輯單元、與儲存陣列中的磁碟區相關。



 a| 
命名空間ID
 a| 
命名空間ID是NVMe控制器的命名空間唯一識別碼、可設定為1到255之間的值。它類似於SCSI中的邏輯單元號碼（LUN）。



 a| 
NQN
 a| 
NVMe合格名稱（NQN）用於識別遠端儲存目標（儲存陣列）。



 a| 
NVM
 a| 
非揮發性記憶體（NVM）是許多儲存設備類型所使用的持續記憶體。



 a| 
NVMe
 a| 
非揮發性記憶體Express（NVMe）是專為Flash型儲存裝置（例如SSD磁碟機）所設計的介面。NVMe可降低I/O負荷、並與先前的邏輯裝置介面相比、提升效能。



 a| 
NVMe
 a| 
非揮發性記憶體Express over Fabrics（NVMe）是一種規格、可讓NVMe命令和資料在主機與儲存設備之間透過網路傳輸。



 a| 
NVMe控制器
 a| 
NVMe控制器是在主機連線程序期間建立的。它提供主機與儲存陣列中命名空間之間的存取路徑。



 a| 
NVMe佇列
 a| 
佇列用於透過NVMe介面傳遞命令和訊息。



 a| 
NVMe子系統
 a| 
採用NVMe主機連線的儲存陣列。



 a| 
RDMA
 a| 
遠端直接記憶體存取（RDMA）可在網路介面卡（NIC）硬體中實作傳輸傳輸協定、讓資料更直接地進出伺服器。



 a| 
RoCE
 a| 
RDMA over Converged Ethernet（RoCE）是一種網路傳輸協定、可透過乙太網路進行遠端直接記憶體存取（RDMA）。



 a| 
SSD
 a| 
固態磁碟（SSD）是使用固態記憶體（Flash）持續儲存資料的資料儲存裝置。SSD可模擬傳統硬碟機、並與硬碟機使用的介面相同。

|===
====