---
permalink: sm-hardware/hardware-page-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, page, components, 
summary: 「硬體」頁面以圖形方式呈現儲存陣列的實體元件。您可以從這裡檢查元件狀態、並執行與這些元件相關的部分功能。 
---
= 硬體頁面與元件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hardware（硬體）頁面提供儲存陣列實體元件的圖形化描述。您可以從這裡檢查元件狀態、並執行與這些元件相關的部分功能。



== 磁碟櫃

機櫃是一個元件、其中包含儲存陣列（控制器、電源/風扇容器和磁碟機）的硬體。磁碟櫃有兩種類型：

* *控制器機櫃*：包含磁碟機、電源/風扇機櫃和控制器。
* *磁碟機櫃*（或*擴充櫃*）-包含磁碟機、電源/風扇迴路、以及兩個輸入/輸出模組（IOM）。IOM也稱為環境服務模組（ESM）、包括將磁碟機櫃連接至控制器機櫃的SAS連接埠。


磁碟櫃有三種尺寸可供選擇、最多容納12、24或60個磁碟機。每個機櫃都有一個ID編號、由控制器韌體指派。ID會顯示在機櫃檢視的左上角。

「硬體」頁面上的機櫃檢視會顯示前端或後端元件。您可以從機櫃檢視的右上角選取*顯示機櫃背面*或*顯示機櫃正面*、在兩個檢視之間切換。您也可以從頁面底部選取*顯示全部正面*或*顯示全部背面*。正面和背面檢視顯示下列項目：

* *前端元件*：磁碟機和閒置磁碟機支架。
* *後端元件*-控制器和電源/風扇迴路（用於控制器磁碟櫃）或IOM和電源/風扇迴路（用於磁碟機磁碟櫃）。


您可以執行下列與磁碟櫃相關的功能：

* 開啟機櫃的定位燈、以便在機櫃或機架中找到機櫃的實體位置。
* 變更機櫃檢視左上角顯示的ID編號。
* 檢視機櫃設定、例如安裝的磁碟機類型和序號。
* 將機櫃檢視向上或向下移動、以符合儲存陣列中的實體配置。




== 控制器

控制器是實作儲存陣列與管理功能的硬體與韌體組合。它包括快取記憶體、磁碟機支援和主機介面支援。

您可以執行下列與控制器相關的功能：

* 設定IP位址和速度的管理連接埠。
* 設定iSCSI主機連線（如果您有iSCSI主機）。
* 設定網路時間傳輸協定（NTP）伺服器和網域名稱系統（DNS）伺服器。
* 檢視控制器狀態和設定。
* 允許區域網路以外的使用者啟動SSH工作階段、並變更控制器上的設定。
* 將控制器置於離線、線上或服務模式。




== 磁碟機

儲存陣列可包含硬碟（HDD）或固態硬碟（SSD）。根據磁碟櫃大小、磁碟櫃最多可安裝12、24或60個磁碟機。

您可以執行下列與磁碟機相關的功能：

* 開啟磁碟機的定位指示燈、即可在磁碟櫃中找到磁碟機的實體位置。
* 檢視磁碟機狀態和設定。
* 重新指派磁碟機（邏輯上以未指派的磁碟機取代故障磁碟機）、並視需要手動重建磁碟機。
* 手動將磁碟機故障、以便更換。（如果磁碟機故障、您可以在更換磁碟機之前複製磁碟機內容。）
* 指派或取消指派熱備援磁碟。
* 清除磁碟機。

