---
permalink: sm-hardware/hot-spare-drives.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hot, spare, drives, raid1, raid6, raid5 
summary: 熱備援磁碟機在System Manager的RAID 1、RAID 5或RAID 6磁碟區群組中扮演待命磁碟機的角色。 
---
= 熱備援磁碟機總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
熱備援磁碟機在System Manager的RAID 1、RAID 5或RAID 6磁碟區群組中扮演待命磁碟機的角色。

它們是功能完整的磁碟機、不含任何資料。如果磁碟機在Volume群組中故障、控制器會自動將故障磁碟機的資料重新建構至指派為熱備援磁碟機的磁碟機。

熱備援磁碟機並非專供特定磁碟區群組使用。只要熱備援磁碟機與磁碟機共用下列屬性、就能將它們用於儲存陣列中的任何故障磁碟機：

* 容量相等（或熱備援的容量更大）
* 相同的媒體類型（例如HDD或SSD）
* 相同的介面類型（例如SAS）




== 如何識別熱備援磁碟機

您可以透過「初始設定精靈」或「硬體」頁面指派熱備援磁碟機。若要判斷是否已指派熱備援磁碟機、請前往「硬體」頁面、尋找任何以粉色顯示的磁碟機支架。



== 熱備援保固範圍的運作方式

熱備援涵蓋範圍如下：

* 您將未指派的磁碟機保留為RAID 1、RAID 5或RAID 6 Volume群組的熱備援磁碟機。
+
[NOTE]
====
熱備援磁碟區無法用於具有不同資料保護方法的集區。集區不會保留額外的磁碟機、而是在集區的每個磁碟機內保留備用容量（稱為_RESEervation capeity_）。如果集區中的磁碟機故障、控制器會重新建構該備用容量中的資料。

====
* 如果RAID 1、RAID 5或RAID 6 Volume群組內的磁碟機故障、控制器會自動使用備援資料來重建故障磁碟機中的資料。熱備援磁碟機會自動取代故障磁碟機、而不需要實體交換。
* 當您實際更換故障磁碟機時、會從熱備援磁碟機到更換的磁碟機執行反向複製作業。如果您已將熱備援磁碟指定為磁碟區群組的永久成員、則不需要複製作業。
* 磁碟區群組的磁碟匣遺失保護和藥櫃遺失保護的可用度取決於磁碟區群組所在磁碟機的位置。由於磁碟機故障和熱備援磁碟機的位置、因此可能會遺失紙匣遺失保護和藥櫃遺失保護。為了確保紙匣遺失保護和藥櫃遺失保護不受影響、您必須更換故障的磁碟機、以啟動回寫程序。
* 在更換故障磁碟機時、儲存陣列磁碟區仍會保持線上狀態、並可供存取、因為熱備援磁碟機會自動取代故障磁碟機。




== 熱備援磁碟機容量的考量

選取容量等於或大於您要保護之磁碟機總容量的磁碟機。例如、如果您的18GiB磁碟機已設定容量為8 GiB、則可使用9-GiB或更大的磁碟機作為熱備援磁碟機。一般而言、除非磁碟機的容量等於或大於儲存陣列中最大磁碟機的容量、否則請勿將其指派為熱備援磁碟機。

[NOTE]
====
如果無法使用具有相同實體容量的熱備援磁碟機、則如果磁碟機的「已用容量」與熱備援磁碟機的容量相同或小於該磁碟機的容量、則容量較低的磁碟機可能會用作熱備援磁碟機。

====


== 媒體和介面類型的考量

作為熱備援磁碟機的磁碟機必須與要保護的磁碟機共用相同的媒體類型和介面類型。例如、HDD磁碟機無法做為SSD磁碟機的熱備援磁碟機。



== 安全型磁碟機的考量

具有安全功能的磁碟機（例如FDE或FIPS）可做為具有或不具有安全功能的磁碟機的熱備援磁碟機。但是、不具備安全功能的磁碟機、無法作為具有安全功能的磁碟機的熱備援磁碟機。

當您選取要用於熱備援的安全磁碟機時、System Manager會提示您執行安全清除、然後才能繼續。「安全清除」會將磁碟機的安全屬性重設為具有安全功能、但不會啟用安全功能。

[NOTE]
====
當您啟用「磁碟機安全性」功能、然後從具有安全功能的磁碟機建立集區或磁碟區群組時、磁碟機就會變成_安全啟用_。讀寫存取只能透過設定正確安全金鑰的控制器來使用。這項新增的安全功能可防止未獲授權存取從儲存陣列實體移除之磁碟機上的資料。

====


== 建議的熱備援磁碟機數量

如果您使用初始設定精靈自動建立熱備援磁碟機、系統管理員會針對每30個特定媒體類型和介面類型的磁碟機、建立一個熱備援磁碟機。否則、您可以在儲存陣列的磁碟區群組之間手動建立熱備援磁碟機。
