---
permalink: sm-hardware/limit-the-drive-view.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, limit, drive, view, 
summary: 如果儲存陣列包含具有不同類型實體和邏輯屬性的磁碟機、「硬體」頁面會提供篩選欄位、協助您限制磁碟機檢視並找出特定的磁碟機。 
---
= 在 SANtricity System Manager 中篩選磁碟機視圖
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果儲存陣列包含具有不同類型實體和邏輯屬性的磁碟機、「硬體」頁面會提供篩選欄位、協助您限制磁碟機檢視並找出特定的磁碟機。

.關於這項工作
磁碟機篩選器可將檢視範圍限制在特定邏輯位置（例如Volume Group 1）的特定類型實體磁碟機（例如、All SAS）、並具有特定的安全屬性（例如、安全功能）。您可以一起或單獨使用這些篩選器。

[NOTE]
====
如果所有磁碟機共用相同的實體屬性、則不會顯示*顯示磁碟機為...*篩選欄位。如果所有磁碟機都共用相同的邏輯屬性、則不會出現「* Anywhere in the storage array* filter」（*儲存陣列*篩選器的任何位置）欄位。

====
.步驟
. 選取*硬體*。
. 在第一個篩選欄位（在*顯示磁碟機為...*下）中、按一下下拉式箭頭以顯示可用的磁碟機類型和安全性屬性。
+
磁碟機類型可能包括：

+
** 磁碟機媒體類型（SSD、HDD）
** 磁碟機介面類型
** 磁碟機容量（最高至最低）
** 磁碟機速度（最高至最低）安全性屬性可能包括：
** 安全功能
** 安全功能
** DA（資料保證）功能
** 符合FIPS標準
** FIPS相容（FIPS 140-2）
** FIPS相容（FIPS 140-2）
+
如果所有磁碟機的這些屬性都相同、則不會顯示在下拉式清單中。例如、如果儲存陣列包含所有具有SAS介面和15000 RPM速度的SSD磁碟機、但部分SSD的容量不同、則下拉式清單只會顯示容量作為篩選選項。

+
當您從欄位中選取選項時、不符合篩選條件的磁碟機會在圖形檢視中呈現灰色。



. 在第二個篩選器方塊中、按一下下拉式箭頭以顯示磁碟機的可用邏輯位置。
+
[NOTE]
====
如果您需要清除篩選條件、請選取篩選方塊最右側的*清除*。

====
+
邏輯位置可能包括：

+
** 資源池
** Volume群組
** 熱備援
** SSD快取
** 未指派
+
當您從欄位中選取選項時、不符合篩選條件的磁碟機會在圖形檢視中呈現灰色。



. 您也可以選擇篩選欄位最右側的*開啟定位燈*、開啟所顯示磁碟機的定位燈。
+
此動作可協助您在儲存陣列中實際找到磁碟機。


