---
permalink: sm-hardware/unlock-or-reset-a-locked-nvme-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, reset, locked, fips, nvme, drives, 
summary: 如果您將一個或多個鎖定的NVMe或FIPS磁碟機插入儲存陣列、您可以新增與磁碟機相關的安全金鑰檔案、以解除鎖定磁碟機資料。如果您沒有安全金鑰、可以輸入實體安全ID（PSID）來重設每個鎖定的磁碟機、以重設其安全屬性並清除磁碟機資料。 
---
= 解除鎖定或重設鎖定的NVMe或FIPS磁碟機
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您將一個或多個鎖定的NVMe或FIPS磁碟機插入儲存陣列、您可以新增與磁碟機相關的安全金鑰檔案、以解除鎖定磁碟機資料。如果您沒有安全金鑰、可以輸入實體安全ID（PSID）來重設每個鎖定的磁碟機、以重設其安全屬性並清除磁碟機資料。

.開始之前
* 對於Unlock（解除鎖定）選項、請確定管理用戶端（使用瀏覽器存取System Manager的系統）上有可用的安全金鑰檔案（副檔名為「.slk」）。您也必須知道與金鑰相關的密碼。
* 針對「重設」選項、您必須在每個要重設的磁碟機上找到PSID。若要找出PSID、請實際移除磁碟機、並在磁碟機標籤上找到PSID字串（最多32個字元）、然後重新安裝磁碟機。


本工作說明如何將安全金鑰檔案匯入儲存陣列、以解除NVMe或FIPS磁碟機中的資料鎖定。如果無法使用安全金鑰、此工作也會說明如何在鎖定的磁碟機上執行重設。

[NOTE]
====
如果磁碟機是使用外部金鑰管理伺服器鎖定、請在System Manager中選取功能表：設定[系統>安全金鑰管理]、以設定外部金鑰管理並解除鎖定磁碟機。

====
您可以從硬體頁面或功能表：設定[系統>安全金鑰管理]存取解除鎖定功能。以下工作提供「硬體」頁面的指示。

.步驟
. 選取*硬體*。
. 如果圖形顯示控制器、請按一下*顯示機櫃正面*。
+
圖形會變更、以顯示磁碟機而非控制器。

. 選取您要解除鎖定或重設的NVMe或FIPS磁碟機。
+
隨即開啟磁碟機的內容功能表。

. 選取*解除鎖定*以套用安全性金鑰檔案；如果沒有安全性金鑰檔案、請選取*重設*。
+
這些選項僅在您選取鎖定的NVMe或FIPS磁碟機時才會出現。

+
[CAUTION]
====
在重設作業期間、所有資料都會被清除。只有在您沒有安全金鑰時才執行「重設」。重設鎖定的磁碟機會永久移除磁碟機上的所有資料、並將其安全屬性重設為「安全功能」、但不會啟用。*此操作不可回復。*

====
. 執行下列其中一項：
+
.. *解除鎖定*：在*解除鎖定安全磁碟機*對話方塊中、按一下*瀏覽*、然後選取與您要解除鎖定磁碟機對應的安全金鑰檔案。接著輸入密碼、然後按一下*解除鎖定*。
.. *重設*：在*重設鎖定磁碟機*對話方塊中、在欄位中輸入PSID字串、然後輸入「重設」以確認。按一下*重設*。
+
若要解除鎖定作業、您只需執行一次此作業、即可解除鎖定所有NVMe或FIPS磁碟機。若要執行重設作業、您必須個別選取要重設的每個磁碟機。





磁碟機現在可用於其他磁碟區群組或磁碟集區、或其他儲存陣列。
