---
permalink: sm-hardware/view-drive-status-and-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, drive, status, settings, media, 
summary: 您可以檢視磁碟機的狀態和設定、例如媒體類型、介面類型和容量。 
---
= 在 SANtricity System Manager 中查看磁碟機狀態和設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視磁碟機的狀態和設定、例如媒體類型、介面類型和容量。

.步驟
. 選取*硬體*。
. 如果圖形顯示控制器、請按一下 * 磁碟機 * 索引標籤。
+
圖形會變更、以顯示磁碟機而非控制器。

. 選取您要檢視其狀態和設定的磁碟機。
+
隨即開啟磁碟機的內容功能表。

. 選取*檢視設定*。
+
「磁碟機設定」對話方塊隨即開啟。

. 若要查看所有設定、請按一下對話方塊右上角的*顯示更多設定*。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
狀態
 a| 
顯示最佳、離線、非關鍵故障和故障。最佳狀態表示所需的工作條件。



 a| 
模式
 a| 
顯示「已指派」、「未指派」、「熱備援待命」或「使用中的熱備援」。



 a| 
位置
 a| 
顯示磁碟機所在的磁碟櫃和磁碟櫃編號。



 a| 
指派給/可以保護/保護
 a| 
如果磁碟機已指派給資源池、磁碟區群組或SSD快取、此欄位會顯示「已指派給」。 此值可以是集區名稱、磁碟區群組名稱或SSD快取名稱。如果磁碟機已指派至熱備援、且其模式為待命、則此欄位會顯示「可以保護」。 如果熱備援磁碟可以保護一或多個Volume群組、則會顯示Volume群組名稱。如果無法保護磁碟區群組、則會顯示0個磁碟區群組。

如果磁碟機已指派至熱備援磁碟機、且其模式正在使用中、則此欄位會顯示「正在保護」。 此值為受影響Volume群組的名稱。

如果未指派磁碟機、則不會顯示此欄位。



 a| 
媒體類型
 a| 
顯示磁碟機使用的錄製媒體類型、可以是硬碟機（HDD）或固態磁碟（SSD）。



 a| 
使用的持久度百分比（僅在SSD磁碟機存在時顯示）
 a| 
迄今寫入磁碟機的資料量、除以總理論寫入限制。



 a| 
介面類型
 a| 
顯示磁碟機使用的介面類型、例如SAS。



 a| 
磁碟機路徑備援
 a| 
顯示磁碟機與控制器之間的連線是否為備援（是）或非（否）。



 a| 
容量（GiB）
 a| 
顯示磁碟機的可用容量（總組態容量）。



 a| 
速度（RPM）
 a| 
以RPM顯示速度（SSD不會顯示）。



 a| 
目前資料傳輸率
 a| 
顯示磁碟機與儲存陣列之間的資料傳輸率。



 a| 
邏輯區段大小（位元組）
 a| 
顯示磁碟機使用的邏輯磁碟區大小。



 a| 
實體區段大小（位元組）
 a| 
顯示磁碟機使用的實體磁碟區大小。硬碟機的實體磁碟區大小通常為4096位元組。



 a| 
磁碟機韌體版本
 a| 
顯示磁碟機韌體的修訂層級。



 a| 
全球識別碼
 a| 
顯示磁碟機的唯一十六進位識別碼。



 a| 
產品ID
 a| 
顯示製造商指派的產品識別碼。



 a| 
序號
 a| 
顯示磁碟機的序號。



 a| 
製造商
 a| 
顯示磁碟機的廠商。



 a| 
製造日期
 a| 
顯示磁碟機的建置日期。


NOTE: 不適用於NVMe磁碟機。



 a| 
安全功能
 a| 
顯示磁碟機是否具備安全功能（是）（否）。可安全使用的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機（層級140-2或140-2）、在讀取期間加密資料。這些磁碟機被視為安全的磁碟機、因為它們可以使用磁碟機安全功能來提高安全性。如果已針對這些磁碟機所使用的磁碟區群組和集區啟用「磁碟機安全性」功能、磁碟機就會變成安全的-_enabled_.



 a| 
安全功能
 a| 
顯示磁碟機是否已啟用安全功能（是）（否）。啟用安全功能的磁碟機可搭配磁碟機安全功能使用。當您啟用「磁碟機安全性」功能、然後將「磁碟機安全性」套用至安全的-_Capable磁碟機上的集區或磁碟區群組時、磁碟機就會變成安全的-_enabled_.讀寫存取只能透過設定正確安全金鑰的控制器來使用。這項新增的安全功能可防止未獲授權存取從儲存陣列實體移除之磁碟機上的資料。



 a| 
可存取讀寫
 a| 
顯示磁碟機是可讀寫的（是）、還是不可讀（否）。



 a| 
磁碟機安全金鑰識別碼
 a| 
顯示啟用安全功能之磁碟機的安全金鑰。磁碟機安全性是一項儲存陣列功能、可透過全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機提供額外的安全層級。當這些磁碟機搭配磁碟機安全功能使用時、它們需要安全金鑰才能存取其資料。當磁碟機從陣列中實際移除時、除非安裝在另一個陣列中、否則無法運作、此時磁碟機將處於「安全性鎖定」狀態、直到提供正確的安全金鑰為止。



 a| 
具備資料保證（DA）功能
 a| 
顯示資料保證（DA）功能是否已啟用（是）（否）。資料保證（DA）是一項功能、可檢查及修正資料經由控制器向下傳輸至磁碟機時可能發生的錯誤。資料保證功能可在集區或磁碟區群組層級啟用、主機可使用具有DA功能的I/O介面、例如Fibre Channel。



 a| 
具備DUBE功能
 a| 
指出是否已啟用取消分配或未寫入的邏輯區塊錯誤（DULBE）選項（是）（否）。DULBE是NVMe磁碟機的選項、可讓EF300或EF600儲存陣列支援資源配置的磁碟區。

|===
====
. 按一下 * 關閉 * 。

