---
permalink: sm-hardware/view-controller-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, controller, settings 
summary: 您可以檢視控制器的相關資訊、例如主機介面、磁碟機介面和管理連接埠的狀態。 
---
= 檢視控制器設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視控制器的相關資訊、例如主機介面、磁碟機介面和管理連接埠的狀態。

.步驟
. 選取*硬體*。
. 如果圖形顯示磁碟機、請按一下*顯示磁碟櫃背面*。
+
圖形會變更、以顯示控制器而非磁碟機。

. 執行下列其中一項動作以顯示控制器設定：
+
** 按一下控制器以顯示內容功能表、然後選取*檢視設定*。
** 選取控制器圖示（*機櫃*下拉式清單旁）。對於雙工組態、請從對話方塊中選取*控制器A*或*控制器B*、然後按一下*下一步*。
+
控制器設定對話方塊隨即開啟。



. 選取索引標籤以在內容設定之間移動。
+
部分索引標籤的右上角有*顯示更多設定*的連結。

+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 索引標籤 | 說明 


 a| 
基礎
 a| 
顯示控制器狀態、機型名稱、更換零件編號、目前韌體版本、以及非揮發性靜態隨機存取記憶體（NVSRAM）版本。



 a| 
快取
 a| 
顯示控制器的快取設定、包括資料快取、處理器快取和快取備份裝置。快取備份設備可在控制器斷電時、用於備份快取中的資料。狀態可以是「最佳」、「失敗」、「移除」、「未知」、「寫入保護」、 或不相容。



 a| 
主機介面
 a| 
顯示主機介面資訊及每個連接埠的連結狀態。主機介面是控制器與主機（例如Fibre Channel或iSCSI）之間的連線。


NOTE: 主機介面卡（HIC）位置是在基板或插槽（Bay）中。「基礎板」表示HIC連接埠內建於控制器中。「插槽」連接埠位於選購的HIC上。



 a| 
磁碟機介面
 a| 
顯示每個連接埠的磁碟機介面資訊和連結狀態。磁碟機介面是控制器與磁碟機（例如SAS）之間的連線。



 a| 
管理連接埠
 a| 
顯示管理連接埠詳細資料、例如用於存取控制器的主機名稱、以及是否已啟用遠端登入。管理連接埠會連接控制器和管理用戶端、這是安裝瀏覽器以存取System Manager的位置。



 a| 
DNS / NTP
 a| 
顯示DNS伺服器和NTP伺服器的定址方法和IP位址（如果這些伺服器已在System Manager中設定）。

網域名稱系統（DNS）是連線至網際網路或私有網路之裝置的命名系統。DNS伺服器會維護網域名稱目錄、並將其轉譯為網際網路傳輸協定（IP）位址。

網路時間傳輸協定（NTP）是一種網路傳輸協定、可在資料網路中的電腦系統之間進行時鐘同步。

|===
====
. 按一下 * 關閉 * 。

