---
permalink: sm-hardware/view-hardware-components.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, hardware, components, filtering, 
summary: 「硬體」頁面提供排序和篩選功能、讓您更容易找到元件。 
---
= 檢視硬體元件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「硬體」頁面提供排序和篩選功能、讓您更容易找到元件。

.步驟
. 選取*硬體*。
. 請使用下表所述的功能來檢視硬體元件。


[cols="25h,~"]
|===
| 功能 | 說明 


 a| 
磁碟機、控制器和元件檢視
 a| 
若要在前置和後置視圖之間切換、請從最右側選擇 * 磁碟機 * 或 * 控制器與元件 * （顯示的連結取決於目前視圖）。「 * 磁碟機 * 」檢視會顯示磁碟機和任何空磁碟機支架。"* 控制器與元件 * " 檢視會顯示控制器、任何 IOM （ ESM ）模組、電源 / 風扇迴廊或空的控制器托架。在頁面底部、您也可以選取 * 顯示所有磁碟機 * 。



 a| 
磁碟機檢視篩選器
 a| 
如果儲存陣列包含具有不同類型實體和邏輯屬性的磁碟機、則「*硬體*」頁面會包含磁碟機檢視篩選器。這些篩選欄位可限制頁面上顯示的磁碟機類型、協助您快速找到特定的磁碟機。在*顯示磁碟機為...*下、按一下左側的篩選欄位（預設顯示*任何磁碟機類型*）、即可查看實體屬性的下拉式清單（例如容量和速度）。按一下右側的篩選欄位（依預設、會在儲存陣列*的任何位置顯示*）、以查看邏輯屬性的下拉式清單（例如、磁碟區群組指派）。您可以一起或單獨使用這些篩選器。

[NOTE]
====
如果儲存陣列包含所有磁碟機共用相同的實體屬性、則左側的* any磁碟機類型*欄位不會出現。如果磁碟機都位於相同的邏輯位置、則右側的「* Anywhere in the storage array*（*儲存陣列*的任何位置）」欄位不會出現。

====


 a| 
圖例
 a| 
元件會以特定色彩顯示、以描述其角色狀態。若要展開及摺疊這些狀態的說明、請按一下*圖例*。



 a| 
顯示狀態圖示詳細資料
 a| 
狀態指標可包含可用度狀態的文字說明。按一下*顯示狀態圖示詳細資料*以顯示或隱藏此狀態文字。



 a| 
機櫃/機櫃圖示
 a| 
每個機櫃檢視都會提供相關命令的清單、以及內容和狀態。按一下*機櫃*以查看命令的下拉式清單。您也可以選取頂端的其中一個圖示、查看個別元件的狀態和內容：控制器、IOM（ESM）、電源供應器、風扇、溫度、 電池和SFP。



 a| 
機櫃訂單
 a| 
磁碟櫃可在「硬體」頁面重新排列。使用每個機櫃檢視右上角的向上和向下箭頭、變更機櫃的上/下順序。

|===