---
permalink: sm-hardware/what-is-ipv6-stateless-address-auto-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ipv6, stateless, address, auto, configuration, 
summary: 在無狀態自動組態的情況下、主機不會從伺服器取得位址和其他組態資訊。 
---
= 什麼是IPv6無狀態位址自動組態？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在無狀態自動組態的情況下、主機不會從伺服器取得位址和其他組態資訊。

IPv6中的無狀態自動組態具有連結本機位址、多點傳送和鄰近探索（ND）傳輸協定。IPv6可從基礎資料連結層位址產生位址的介面ID。

無狀態自動組態和狀態自動組態可相輔相成。例如、主機可以使用無狀態自動組態來設定自己的位址、但可使用狀態自動組態來取得其他資訊。狀態自動組態可讓主機從伺服器取得位址和其他組態資訊。網際網路傳輸協定第6版（IPv6）也定義了一種方法、可讓網路上的所有IP位址一次重新編號。IPv6定義了一種方法、可讓網路上的裝置自動設定其IP位址和其他參數、而不需要伺服器。

使用無狀態自動組態時、裝置會執行下列步驟：

. *產生連結本機位址*：裝置會產生連結本機位址、其位址為10位元、後面接著54個零、後面接著64位元介面ID。
. *測試鏈路本機位址*的獨特性：節點會測試以確定其產生的連結本機位址尚未在本機網路上使用。節點使用ND-傳輸協定傳送鄰近請求訊息。因此、本機網路會接聽鄰近通告訊息、指出另一個裝置已使用連結本機位址。如果是、則必須產生新的連結本機位址或自動組態失敗、而且必須使用其他方法。
. *指派連結本機位址*-如果裝置通過唯一性測試、則裝置會將連結本機位址指派給其IP介面。連結本機位址可用於在本機網路上進行通訊、但不能用於透過網際網路進行通訊。
. *聯絡路由器*：節點會嘗試聯絡本機路由器、以取得有關繼續設定的詳細資訊。此聯絡活動的執行方式為：聆聽路由器定期傳送的路由器通告訊息、或傳送特定的路由器請求訊息、詢問路由器有關後續行動的資訊。
. *提供節點的方向*：路由器會向節點提供如何繼續自動組態的指示。或者、路由器會告訴主機如何判斷全域網際網路位址。
. *設定全域位址*：主機使用其全域唯一的網際網路位址自行設定。此位址通常是由路由器提供給主機的網路前置碼所形成。

