---
permalink: um-manage/activate-pending-firmware.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, activate, staged, os, software 
summary: 您可以選擇立即啟動軟體檔案、或等到更方便的時間再啟動。此程序假設您選擇稍後啟動軟體檔案。 
---
= 在 SANtricity Unified Manager 中啟動暫存作業系統軟體
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以選擇立即啟動軟體檔案、或等到更方便的時間再啟動。此程序假設您選擇稍後啟動軟體檔案。

.關於這項工作
您可以在不啟動韌體檔案的情況下傳輸韌體檔案。您可以選擇稍後啟動、原因如下：

* *每天的時間*-啟動軟體可能需要很長時間、因此您可能需要等待I/O負載變輕。控制器會在啟動期間重新開機並容錯移轉、因此在升級完成之前、效能可能會比平常低。
* *套件類型*：在升級其他儲存陣列上的檔案之前、您可能需要在一個儲存陣列上測試新的軟體和韌體。


[NOTE]
====
啟動程序之後、您無法停止啟動程序。

====
.步驟
. 從主檢視畫面選取*管理*。如有必要、請按一下「Status（狀態）」欄、在頁面頂端排序所有狀態為「OS Upgrade（waiting activation）（OS升級（等待啟動））」的儲存陣列。
. 選取您要啟動軟體的一或多個儲存陣列、然後選取功能表：升級中心[啟動分段作業系統軟體]。
+
升級作業期間會執行下列動作：

+
** 升級前的狀況檢查會在啟動程序中執行。預先升級的健全狀況檢查會評估所有儲存陣列元件、以確保啟動作業能夠繼續進行。
** 如果儲存陣列的任何健全狀況檢查失敗、啟動就會停止。您可以按一下省略符號（...）、然後選取*「Save Log*」（儲存記錄*）以檢閱錯誤。您也可以選擇置換健全狀況檢查錯誤、然後按一下*繼續*繼續啟動。
** 您可以在升級前狀況檢查之後取消啟動作業。成功完成升級前的健全狀況檢查後、就會啟動。啟動所需的時間取決於儲存陣列組態和您要啟動的元件。


. *選用：*啟動完成後、您可以按一下省略符號（...）、然後選取*「Save Log*」（儲存記錄*）、查看特定儲存陣列的啟動項目清單。
+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「actaction_log-<date>.json」。


