---
permalink: um-manage/considerations-for-discovering-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, considerations, discovering, arrays 
summary: 在Unified Manager能夠顯示及管理儲存資源之前、它必須先探索您要在組織網路中管理的儲存陣列。您可以探索多個陣列、也可以探索單一陣列。 
---
= 探索陣列的考量事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在支援顯示及管理儲存資源之前、必須先探索您要在組織網路中管理的儲存陣列。SANtricity您可以探索多個陣列、也可以探索單一陣列。



== 探索多個儲存陣列

如果您選擇探索多個陣列、請輸入網路IP位址範圍、然後Unified Manager會嘗試個別連線至該範圍內的每個IP位址。任何已成功連線的儲存陣列都會顯示在「Discover（探索）」頁面上、並可新增至您的管理網域。



== 探索單一儲存陣列

如果您選擇探索單一陣列、請在儲存陣列中輸入其中一個控制器的單一IP位址、然後新增個別的儲存陣列。

[NOTE]
====
Unified Manager只會探索並顯示指派給控制器之範圍內的單一IP位址或IP位址。如果指派給這些控制器的替代控制器或IP位址超出此單一IP位址或IP位址範圍、Unified Manager將不會發現或顯示這些控制器。不過、新增儲存陣列之後、所有相關的IP位址都會被探索並顯示在「管理」檢視中。

====


== 使用者認證

在探索過程中、您必須為每個要新增的儲存陣列提供管理員密碼。



== Web服務憑證

在探索過程中、Unified Manager會驗證探索到的儲存陣列是否使用受信任來源的憑證。Unified Manager使用兩種類型的憑證型驗證來驗證其與瀏覽器建立的所有連線：

* *信任的憑證*
+
對於Unified Manager探索到的陣列、您可能需要安裝其他由憑證授權單位提供的信任憑證。

+
使用*匯入*按鈕匯入這些憑證。如果您之前已連線至此陣列、則其中一個或兩個控制器憑證會在其憑證鏈結中過期、撤銷或遺失根憑證或中繼憑證。在管理儲存陣列之前、您必須先更換過期或撤銷的憑證、或是新增遺失的根憑證或中繼憑證。

* *自我簽署的憑證*
+
也可以使用自我簽署的憑證。如果系統管理員嘗試探索陣列而不匯入簽署的憑證、Unified Manager會顯示錯誤對話方塊、讓系統管理員接受自我簽署的憑證。儲存陣列的自我簽署憑證會標示為信任、儲存陣列也會新增至Unified Manager。

+
如果您不信任儲存陣列的連線、請選取*取消*、然後在將儲存陣列新增至Unified Manager之前驗證儲存陣列的安全性憑證策略。


