---
permalink: um-manage/create-asynchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, asynchronous, mirrored, pair 
summary: 若要設定非同步鏡射、您可以建立鏡射配對、其中包含本機陣列上的主要磁碟區、以及遠端陣列上的次要磁碟區。 
---
= 建立非同步鏡射配對
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要設定非同步鏡射、您可以建立鏡射配對、其中包含本機陣列上的主要磁碟區、以及遠端陣列上的次要磁碟區。

[NOTE]
====
EF600或EF300儲存系統無法使用此功能。

====
建立鏡射配對之前、請先滿足Unified Manager的下列需求：

* Web服務Proxy服務必須正在執行。
* Unified Manager必須透過HTTPS連線在本機主機上執行。
* Unified Manager必須顯示儲存陣列的有效SSL憑證。您可以接受自我簽署的憑證、或使用Unified Manager安裝自己的安全性憑證、並瀏覽至功能表：「Certificate [ Certificate Management（憑證管理）」。


此外、請務必滿足下列儲存陣列與磁碟區的需求：

* 每個儲存陣列都必須有兩個控制器。
* 這兩個儲存陣列必須在Unified Manager中探索。
* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 儲存陣列的韌體版本最低為7.84。（每個作業系統都能執行不同的版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您必須在遠端儲存陣列上擁有足夠的可用容量、才能建立等於或大於您要鏡射之主要磁碟區的次要磁碟區。
* 您的本機和遠端儲存陣列是透過光纖通道架構或iSCSI介面來連接。
* 您已建立要用於非同步鏡射關係的主要和次要磁碟區。
* 次要Volume必須至少與主要Volume一樣大。


建立非同步鏡射配對的程序是多步驟程序。



== 步驟1：建立或選取鏡射一致性群組

在此步驟中、您可以建立新的鏡射一致性群組、或選取現有的群組。鏡射一致性群組是主要和次要磁碟區（鏡射配對）的容器、並為群組中的所有配對指定所需的重新同步方法（手動或自動）。

.步驟
. 從「*管理*」頁面中、選取您要用於來源的本機儲存陣列。
. 選取功能表：「Actions（動作）」[建立非同步鏡射配對]。
+
「建立非同步鏡射配對」精靈隨即開啟。

. 選取現有的鏡射一致性群組或建立新的群組。
+
若要選取現有的群組、請確定已選取*現有的鏡射一致性群組*、然後從表格中選取群組。一致性群組可包含多個鏡射配對。

+
若要建立新群組、請執行下列步驟：

+
.. 選取*新的鏡射一致性群組*、然後按一下*下一步*。
.. 輸入最能描述兩個儲存陣列之間鏡射磁碟區資料的唯一名稱。名稱只能由字母、數字和特殊字元組成：底線（_）、破折號（-）和雜湊符號（#）。名稱不得超過30個字元、且不得包含空格。
.. 選取您要與本機儲存陣列建立鏡射關係的遠端儲存陣列。
+
[NOTE]
====
如果您的遠端儲存陣列受到密碼保護、系統會提示您輸入密碼。

====
.. 選擇要手動或自動同步鏡射配對：
+
*** *手動*-選取此選項可手動啟動此群組中所有鏡射配對的同步。請注意、稍後若要執行重新同步、您必須啟動主儲存陣列的System Manager、然後移至功能表：Storage[非同步鏡射鏡射]、從*鏡射一致性群組*索引標籤中選取群組、然後選取功能表：More（更多）[手動重新同步]。
*** *自動*-從上一次更新開始到下一次更新開始、選取所需的時間間隔（*分鐘*、*小時*或*天*）。例如、如果同步時間間隔設為30分鐘、而同步處理程序則從下午4：00開始、則下一個程序將從下午4：30開始


.. 選取所需的警示設定：
+
*** 針對手動同步、請指定接收警示的臨界值（以剩餘容量百分比定義）。
*** 對於自動同步、您可以設定三種警示方法： 當同步尚未在特定時間長度內完成、遠端陣列上的恢復點資料早於特定時間限制、以及保留容量接近特定臨界值（由剩餘容量百分比定義）時。




. 選擇* Next*並前往  2: Select the primary volume。
+
如果您定義了新的鏡射一致性群組、Unified Manager會先在本機儲存陣列上建立鏡射一致性群組、然後在遠端儲存陣列上建立鏡射一致性群組。您可以針對每個陣列啟動System Manager、以檢視及管理鏡射一致性群組。

+
[NOTE]
====
如果Unified Manager成功在本機儲存陣列上建立鏡射一致性群組、但無法在遠端儲存陣列上建立、則會自動從本機儲存陣列刪除鏡射一致性群組。如果Unified Manager嘗試刪除鏡射一致性群組時發生錯誤、您必須手動刪除該群組。

====




== 步驟2：選取主要Volume

在此步驟中、您可以選取要用於鏡射關係的主要磁碟區、然後分配其保留容量。當您在本機儲存陣列上選取主要磁碟區時、系統會顯示該鏡射配對的所有合格磁碟區清單。任何不符合使用資格的磁碟區都不會顯示在該清單中。

您在本機儲存陣列上新增至鏡射一致性群組的任何磁碟區、都將在鏡射關係中扮演主要角色。

.步驟
. 從合格磁碟區清單中、選取您要用作主要磁碟區的磁碟區、然後按一下*「下一步*」來配置保留容量。
. 從符合資格的候選名單中、選取主要Volume的保留容量。
+
請謹記下列準則：

+
** 保留容量的預設設定為基礎磁碟區容量的20%、通常此容量已足夠。如果您變更百分比、請按一下*重新整理候選項目*。
** 所需容量會因主要磁碟區I/O寫入的頻率和大小、以及保留容量所需的時間而有所不同。
** 一般而言、如果存在下列其中一項或兩項條件、請選擇較大的保留容量：
+
*** 您打算長期保留鏡射配對。
*** 由於I/O活動頻繁、一線磁碟區上的資料區塊將會有很大比例改變。使用歷史效能資料或其他作業系統公用程式、協助您判斷主要磁碟區的典型I/O活動。




. 選擇* Next*並前往  3: Select the secondary volume。




== 步驟3：選取次要Volume

在此步驟中、您可以選取要用於鏡射關係的次要Volume、然後分配其保留容量。當您在遠端儲存陣列上選取次要磁碟區時、系統會顯示該鏡射配對的所有合格磁碟區清單。任何不符合使用資格的磁碟區都不會顯示在該清單中。

您在遠端儲存陣列上新增至鏡射一致性群組的任何磁碟區、都會在鏡射關係中擔任次要角色。

.步驟
. 從合格磁碟區清單中、選取您要在鏡射配對中作為次要磁碟區的磁碟區、然後按一下*「下一步*」來配置保留容量。
. 從符合資格的候選名單中、選取次要Volume的保留容量。
+
請謹記下列準則：

+
** 保留容量的預設設定為基礎磁碟區容量的20%、通常此容量已足夠。如果您變更百分比、請按一下*重新整理候選項目*。
** 所需容量會因主要磁碟區I/O寫入的頻率和大小、以及保留容量所需的時間而有所不同。
** 一般而言、如果存在下列其中一項或兩項條件、請選擇較大的保留容量：
+
*** 您打算長期保留鏡射配對。
*** 由於I/O活動頻繁、一線磁碟區上的資料區塊將會有很大比例改變。使用歷史效能資料或其他作業系統公用程式、協助您判斷主要磁碟區的典型I/O活動。




. 選取*完成*以完成非同步鏡射順序。


Unified Manager會執行下列動作：

* 開始在本機儲存陣列與遠端儲存陣列之間進行初始同步。
* 在本機儲存陣列和遠端儲存陣列上建立鏡射配對的保留容量。



NOTE: 如果要鏡射的磁碟區是精簡磁碟區、則在初始同步期間、只會將已配置的區塊（已配置的容量而非報告的容量）傳輸至次要磁碟區。如此可減少完成初始同步所需傳輸的資料量。
