---
permalink: um-manage/create-synchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, synchronous, mirrored, pair 
summary: 若要設定同步鏡射、您可以建立鏡射配對、其中包含本機陣列上的主要磁碟區、以及遠端陣列上的次要磁碟區。 
---
= 建立同步鏡射配對
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要設定同步鏡射、您可以建立鏡射配對、其中包含本機陣列上的主要磁碟區、以及遠端陣列上的次要磁碟區。

[NOTE]
====
EF600或EF300儲存系統無法使用此功能。

====
.開始之前
建立鏡射配對之前、請先滿足Unified Manager的下列需求：

* Web服務Proxy服務必須正在執行。
* Unified Manager必須透過HTTPS連線在本機主機上執行。
* Unified Manager必須顯示儲存陣列的有效SSL憑證。您可以接受自我簽署的憑證、或使用Unified Manager安裝自己的安全性憑證、並瀏覽至功能表：「Certificate [ Certificate Management（憑證管理）」。


此外、請務必滿足下列儲存陣列與磁碟區的需求：

* 您計畫用於鏡射的兩個儲存陣列都會在Unified Manager中找到。
* 每個儲存陣列都必須有兩個控制器。
* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 儲存陣列的韌體版本最低為7.84。（每個作業系統都能執行不同的版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您的本機和遠端儲存陣列是透過光纖通道架構來連接。
* 您已建立要用於同步鏡射關係的主要和次要磁碟區。
* 主Volume必須是標準Volume。它不能是精簡磁碟區或快照磁碟區。
* 次要Volume必須是標準Volume。它不能是精簡磁碟區或快照磁碟區。
* 次要Volume應至少與主要Volume一樣大。


.關於這項工作
建立同步鏡射配對的程序是多步驟程序。



== 步驟1：選取主要Volume

在此步驟中、您可以選取要用於同步鏡射關係的主要Volume。當您在本機儲存陣列上選取主要磁碟區時、系統會顯示該鏡射配對的所有合格磁碟區清單。任何不符合使用資格的磁碟區都不會顯示在該清單中。您選取的磁碟區在鏡射關係中具有主要角色。

.步驟
. 從「*管理*」頁面中、選取您要用於來源的本機儲存陣列。
. 選取功能表：「Actions（動作）」[建立同步鏡射配對]。
+
「建立同步鏡射配對」精靈隨即開啟。

. 從符合資格的Volume清單中、選取您要做為鏡射中主要Volume的Volume。
. 選擇* Next*並前往 <<步驟2：選取次要Volume>>。




== 步驟2：選取次要Volume

在此步驟中、您可以選取要用於鏡射關係的次要Volume。當您在遠端儲存陣列上選取次要磁碟區時、系統會顯示該鏡射配對的所有合格磁碟區清單。任何不符合使用資格的磁碟區都不會顯示在該清單中。您選取的磁碟區將在鏡射關係中擔任次要角色。

.步驟
. 選取您要與本機儲存陣列建立鏡射關係的遠端儲存陣列。
+
[NOTE]
====
如果您的遠端儲存陣列受到密碼保護、系統會提示您輸入密碼。

====
+
** 儲存陣列會依其儲存陣列名稱列出。如果您尚未命名儲存陣列、則會將其列為「unnamed（未命名）」。
** 如果您要使用的儲存陣列不在清單中、請確定已在Unified Manager中找到該陣列。


. 從符合資格的Volume清單中、選取您要在鏡射中作為次要Volume的Volume。
+
[NOTE]
====
如果選擇的次要Volume容量大於主要Volume、則可用容量僅限於主要Volume的大小。

====
. 單擊* Next*（下一步*）並轉至 <<步驟3：選取同步處理設定>>。




== 步驟3：選取同步處理設定

在此步驟中、您可以選取設定、決定在通訊中斷後如何同步處理資料。您可以設定主要磁碟區的控制器擁有者在通訊中斷後、將資料與次要磁碟區重新同步的優先順序。您也必須選取手動或自動重新同步原則。

.步驟
. 使用滑桿列設定同步處理優先順序。
+
同步處理優先順序會決定在通訊中斷之後、與服務I/O要求相比、系統資源有多少用於完成初始同步處理和重新同步作業。

+
此對話方塊上設定的優先順序同時適用於主要Volume和次要Volume。您可以稍後前往System Manager並選取功能表：Storage（同步鏡射）> More（更多）> Edit Settings（編輯設定）、以修改主磁碟區的速率。

+
同步優先順序有五種：

+
** 最低
** 低
** 中
** 高
** 最高
+
如果同步優先順序設定為最低速率、則會優先處理I/O活動、而且重新同步作業需要較長時間。如果同步優先順序設定為最高速率、則重新同步作業會優先處理、但儲存陣列的I/O活動可能會受到影響。



. 選擇是手動或自動重新同步遠端儲存陣列上的鏡射配對。
+
** *手動*（建議選項）-選取此選項、即可在將通訊還原至鏡射配對後、要求手動恢復同步。此選項提供最佳的資料恢復機會。
** *自動*-選取此選項可在將通訊還原至鏡射配對後自動開始重新同步。
+
若要手動恢復同步、請移至System Manager並選取功能表：Storage[同步鏡射]、在表格中反白顯示鏡射配對、然後在* More *（更多*）下選取* Resumed*（恢復*）。



. 按一下「*完成*」以完成同步鏡射順序。


.結果
啟動鏡射後、系統會執行下列動作：

* 開始在本機儲存陣列與遠端儲存陣列之間進行初始同步。
* 設定同步優先順序和重新同步原則。
* 保留控制器HIC編號最高的連接埠、以進行鏡射資料傳輸。
+
只有鏡射配對中次要Volume的遠端慣用控制器擁有者、才會接受在此連接埠上接收的I/O要求。（允許保留主磁碟區。）

* 建立兩個保留容量磁碟區、每個控制器各一個磁碟區、用於記錄寫入資訊、以便從控制器重設和其他暫時性中斷中恢復。
+
每個磁碟區的容量為128個mib。不過、如果將磁碟區放在資源池中、則每個磁碟區將保留4 GiB。



.完成後
移至System Manager並選取功能表：首頁[檢視進行中的作業]以檢視同步鏡射作業的進度。這項作業可能會耗費大量時間、並可能影響系統效能。
