---
permalink: um-manage/discover-multiple-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, multiple, storage, arrays 
summary: 您會發現多個陣列、偵測管理伺服器所在子網路上的所有儲存陣列、並自動將探索到的陣列新增至管理網域。 
---
= 在 SANtricity Unified Manager 中發現多個儲存陣列
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您會發現多個陣列、偵測管理伺服器所在子網路上的所有儲存陣列、並自動將探索到的陣列新增至管理網域。

.開始之前
* 您必須以包含「安全性管理」權限的使用者設定檔登入。
* 儲存陣列必須正確設定和設定。
* 儲存陣列密碼必須使用System Manager的「存取管理」方塊來設定。
* 若要解析不受信任的憑證、您必須擁有來自憑證授權單位（CA）的信任憑證檔案、而且憑證檔案可在本機系統上使用。


探索陣列是一個多步驟程序。



== 步驟1：輸入網路位址

您可以輸入網路位址範圍、以便在本機子網路中搜尋。任何已成功連線的儲存陣列都會顯示在「Discover（探索）」頁面上、而且可能會新增至您的管理網域。

如果您因任何原因而需要停止探索作業、請按一下*停止探索*。

.步驟
. 從「管理」頁面選取*「新增/探索」*。
+
此時會出現「新增/探索」對話方塊。

. 選取*「Discover all storage Array within a network range（探索網路範圍內的所有儲存陣列）」選項按鈕。
. 輸入起始網路位址和結束網路位址、以在本機子網路中搜尋、然後按一下*「Start Discovery」（開始探索）*。
+
探索程序隨即開始。此探索程序可能需要數分鐘的時間才能完成。探索頁面上的表格會隨著儲存陣列的探索而填入。

+
[NOTE]
====
如果未找到可管理的陣列、請確認儲存陣列已正確連線至您的網路、且其指派的位址在範圍內。按一下「*新增探索參數*」以返回「新增/探索」頁面。

====
. 檢閱探索到的儲存陣列清單。
. 選取您要新增至管理網域之任何儲存陣列旁的核取方塊、然後按一下*下一步*。
+
Unified Manager會對您要新增至管理網域的每個陣列執行認證檢查。您可能需要解析任何與該陣列相關的自我簽署憑證和不受信任的憑證。

. 單擊*下一步*繼續執行精靈中的下一步。




== 步驟2：在探索期間解決自我簽署的憑證

在探索過程中、系統會驗證儲存陣列是否使用受信任來源的憑證。

.步驟
. 執行下列其中一項：
+
** 如果您信任已探索儲存陣列的連線、請繼續執行精靈中的下一個卡片。自我簽署的憑證會標示為信任、儲存陣列也會新增至Unified Manager。
** 如果您不信任儲存陣列的連線、請選取*「取消」*、然後在將每個儲存陣列的安全性憑證策略新增至Unified Manager之前驗證。


. 單擊*下一步*繼續執行精靈中的下一步。




== 步驟3：在探索期間解析不受信任的憑證

當儲存陣列嘗試建立與Unified Manager的安全連線、但連線無法確認為安全時、就會發生不受信任的憑證。在陣列探索程序期間、您可以匯入由信任的第三方所發行的憑證授權單位（CA）憑證（或CA簽署的憑證）、以解決不受信任的憑證。

如果符合下列任一項條件、您可能需要安裝其他信任的CA憑證：

* 您最近新增了儲存陣列。
* 一個或兩個憑證都已過期。
* 一個或兩個憑證均已撤銷。
* 一或兩個憑證都遺失根或中繼憑證。


.步驟
. 選取您要解析不受信任憑證之任何儲存陣列旁的核取方塊、然後選取「**匯入」按鈕。
+
隨即開啟一個對話方塊、用於匯入信任的憑證檔案。

. 按一下*瀏覽*以選取儲存陣列的憑證檔案。
+
檔案名稱會顯示在對話方塊中。

. 按一下*匯入*。
+
檔案會上傳並驗證。

+
[NOTE]
====
任何未解決的不受信任憑證問題儲存陣列、都不會新增至Unified Manager。

====
. 單擊*下一步*繼續執行精靈中的下一步。




== 步驟4：提供密碼

您必須輸入要新增至管理網域之儲存陣列的密碼。

.步驟
. 輸入您要新增至Unified Manager的每個儲存陣列密碼。
. *選用：*將儲存陣列與群組建立關聯：從下拉式清單中、選取要與所選儲存陣列建立關聯的群組。
. 單擊*完成*。


.完成後
儲存陣列會新增至您的管理網域、並與選取的群組相關聯（若有指定）。

[NOTE]
====
Unified Manager連線至指定的儲存陣列可能需要數分鐘的時間。

====