---
permalink: um-manage/discover-single-array.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, single, array 
summary: 使用「新增/探索單一儲存陣列」選項、手動探索及新增單一儲存陣列至組織的網路。 
---
= 探索單一陣列
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「新增/探索單一儲存陣列」選項、手動探索及新增單一儲存陣列至組織的網路。

.開始之前
* 儲存陣列必須正確設定和設定。
* 儲存陣列密碼必須使用System Manager的「存取管理」方塊來設定。


.步驟
. 從「管理」頁面選取*「新增/探索」*。
+
此時會出現「新增/探索」對話方塊。

. 選取*「Discover a son那個 儲存陣列*」選項按鈕。
. 輸入儲存陣列中其中一個控制器的IP位址、然後按一下*「Start Discovery」（開始探索）*。
+
Unified Manager連線至指定的儲存陣列可能需要數分鐘的時間。

+
[NOTE]
====
當連線至指定控制器的IP位址失敗時、會出現「Storage Array Not平易近人（儲存陣列無法存取）」訊息。

====
. 如果出現提示、請解決任何自我簽署的憑證。
+
在探索過程中、系統會驗證探索到的儲存陣列是否使用受信任來源的憑證。如果無法找到儲存陣列的數位憑證、系統會提示您新增安全性例外狀況、以解決未由認可的憑證授權單位（CA）簽署的憑證。

. 如果出現提示、請解析任何不受信任的憑證。
+
當儲存陣列嘗試建立與Unified Manager的安全連線、但連線無法確認為安全時、就會發生不受信任的憑證。匯入由信任的第三方所發行的憑證授權單位（CA）憑證、以解決不受信任的憑證。

. 單擊 * 下一步 * 。
. *選用：*將探索到的儲存陣列與群組建立關聯：從下拉式清單中、選取要與儲存陣列建立關聯的群組。
+
預設會選取「All（全部）」群組。

. 輸入要新增至管理網域之儲存陣列的管理員密碼、然後按一下*確定*。


.完成後
儲存陣列會新增至Unified Manager、如果指定、也會新增至您所選的群組。

如果啟用自動支援資料收集功能、系統會自動為您新增的儲存陣列收集支援資料。
