---
permalink: um-manage/faq-storage-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity Unified Manager 的儲存映像常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 在建立鏡射一致性群組之前、我需要知道什麼？

在建立鏡射一致性群組之前、請遵循下列準則。

符合Unified Manager的下列需求：

* Web服務Proxy服務必須正在執行。
* Unified Manager必須透過HTTPS連線在本機主機上執行。
* Unified Manager必須顯示儲存陣列的有效SSL憑證。您可以接受自我簽署的憑證、或使用Unified Manager安裝自己的安全性憑證、並瀏覽至功能表：「Certificate [ Certificate Management（憑證管理）」。


此外、請務必滿足下列儲存陣列需求：

* 這兩個儲存陣列必須在Unified Manager中探索。
* 每個儲存陣列都必須有兩個控制器。
* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 儲存陣列的韌體版本最低為7.84。（每個作業系統都能執行不同的版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您的本機和遠端儲存陣列是透過光纖通道架構或iSCSI介面來連接。


[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供同步鏡射功能。

====


== 建立鏡射配對之前、我需要知道什麼？

在建立鏡射配對之前、請遵循下列準則。

* 您必須有兩個儲存陣列。
* 每個儲存陣列都必須有兩個控制器。
* 這兩個儲存陣列必須在Unified Manager中探索。
* 主陣列和次陣列中的每個控制器都必須設定乙太網路管理連接埠、而且必須連線至您的網路。
* 儲存陣列的韌體版本最低為7.84。（每個作業系統都能執行不同的版本。）
* 您必須知道本機和遠端儲存陣列的密碼。
* 您必須在遠端儲存陣列上擁有足夠的可用容量、才能建立等於或大於您要鏡射之主要磁碟區的次要磁碟區。
* 具有光纖通道（FC）或iSCSI主機連接埠的控制器支援非同步鏡射、而同步鏡射僅支援具有FC主機連接埠的控制器。


[NOTE]
====
EF600/EF600C 或 EF300/EF300C 儲存系統不提供同步鏡射功能。

====


== 為什麼要變更這個百分比？

保留容量通常是基礎磁碟區的20%、用於非同步鏡射作業。通常這種容量是足夠的。

所需的容量會因寫入基礎磁碟區的頻率和大小、以及您打算使用儲存物件複製服務作業的時間而有所不同。一般而言、如果存在下列其中一項或兩項條件、請為保留容量選擇較大的百分比：

* 如果特定儲存物件的複製服務作業壽命很長、
* 如果由於I/O活動頻繁、基礎磁碟區上的資料區塊百分比會大幅變動。使用歷史效能資料或其他作業系統公用程式、協助您判斷基礎磁碟區的典型I/O活動。




== 為什麼我會看到多個保留容量的候選對象？

如果某個集區或Volume群組中有多個Volume符合您為儲存物件選取的容量百分比量、您就會看到多個候選磁碟區。

您可以變更要保留在基礎磁碟區上進行複製服務作業的實體磁碟機空間百分比、以重新整理建議的候選磁碟機清單。根據您的選擇、將會顯示最佳的候選對象。



== 為什麼我看不到我的所有捲？

當您選取鏡射配對的主要Volume時、會有一個清單顯示所有符合資格的Volume。

任何不符合使用資格的磁碟區都不會顯示在該清單中。磁碟區可能不符合下列任一原因的資格：

* Volume並非最佳。
* Volume已參與鏡射關係。
* 對於同步鏡射、鏡射配對中的主要和次要磁碟區必須是標準磁碟區。它們不能是精簡磁碟區或快照磁碟區。
* 對於非同步鏡射、精簡磁碟區必須啟用自動擴充。



NOTE: 對於 EF600 和 EF300 控制器、非同步鏡射配對的主要和次要磁碟區必須符合相同的傳輸協定、磁碟匣層級、區段大小、安全類型和 RAID 層級。非合格的非同步鏡射配對不會出現在可用磁碟區清單中。



== 為什麼我看不到遠端儲存陣列上的所有磁碟區？

當您在遠端儲存陣列上選取次要Volume時、清單會顯示該鏡射配對的所有適用磁碟區。

任何不符合使用資格的磁碟區、都不會顯示在該清單中。Volume可能不符合下列任何理由：

* 此磁碟區為非標準磁碟區、例如快照磁碟區。
* Volume並非最佳。
* Volume已參與鏡射關係。
* 對於非同步鏡射、主要磁碟區與次要磁碟區之間的精簡磁碟區屬性不相符。
* 如果您使用的是Data Assurance（DA）、則主要Volume和次要Volume必須具有相同的DA設定。
+
** 如果主磁碟區已啟用DA、則必須啟用次要磁碟區DA。
** 如果主要Volume未啟用DA、則次要Volume不得啟用DA。


* 對於非同步鏡射、主要磁碟區和次要磁碟區必須具有相同的磁碟機安全功能。
+
** 如果主要磁碟區支援FIPS、則次要磁碟區必須具備FIPS功能。
** 如果主要Volume支援FDE、則次要Volume必須具備FDE功能。
** 如果主要磁碟區未使用磁碟機安全性、則次要磁碟區不得使用磁碟機安全性。






== 同步處理優先順序對同步處理速率有何影響？

同步處理優先順序會定義與系統效能相關的同步處理活動所需的處理時間。

主磁碟區的控制器擁有者會在背景執行此作業。同時、控制器擁有者會處理本機I/O寫入主要磁碟區的作業、並將相關的遠端寫入作業處理至次要磁碟區。由於重新同步會將控制器處理資源從I/O活動中轉移、因此重新同步可能會影響主機應用程式的效能。

請記住這些準則、以協助您判斷同步處理優先順序可能需要多久、以及同步處理優先順序如何影響系統效能。

這些優先率可供選擇：

* 最低
* 低
* 中
* 高
* 最高


最低的優先順序率可支援系統效能、但重新同步需要較長時間。最高優先順序率支援重新同步、但系統效能可能會受損。

這些準則大致上與優先順序的差異大致相同。

[cols="45h,~"]
|===
| 完整同步的優先順序率 | 相較於最高同步率、所耗用的時間 


 a| 
最低
 a| 
最高優先率約為八倍。



 a| 
低
 a| 
最高優先率約為六倍。



 a| 
中
 a| 
以最高優先率計算、約為三倍半。



 a| 
高
 a| 
以最高優先率計算、長度約為兩倍。

|===
Volume大小和主機I/O速率負載會影響同步時間比較。



== 為什麼建議使用手動同步原則？

建議手動重新同步、因為它可讓您以最佳的方式來管理重新同步程序、以提供最佳的資料恢復機會。

如果您使用自動重新同步原則、且在重新同步期間發生間歇性通訊問題、則次要磁碟區上的資料可能會暫時毀損。重新同步完成後、資料將會修正。
