---
permalink: um-manage/how-upgrades-work.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrades, 
summary: 您可以使用Unified Manager將SANtricity 同類型的多個儲存陣列上的支援升級為較新版本。 
---
= 升級的運作方式
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用SANtricity 支援支援功能的支援功能、將SANtricity 同類型的多個儲存陣列上的支援功能升級至新版本。



== 升級工作流程

下列步驟提供執行軟體升級的高層級工作流程：

. 您可從SANtricity Support網站下載最新的支援作業系統軟體檔案（如需連結、請參閱* Support*頁面上的Unified Manager）。將檔案儲存在管理主機系統（您在瀏覽器中存取Unified Manager的主機）上、然後解壓縮檔案。
. 在Unified Manager中、您可以將SANtricity Sesome作業系統軟體檔案和NVSRAM/檔案載入儲存庫（儲存檔案的Web Services Proxy伺服器區域）。您可以從功能表：Upgrade Center[升級SANtricity 支援中心軟體或從Upgrade Center > Manage Software儲存庫]新增檔案。
. 在檔案載入儲存庫之後、您可以選取要用於升級的檔案。從「Upgrade SANtricity EOSOS」（升級版作業系統）軟體頁面（功能表：Upgrade Center[升級SANtricity 版作業系統軟體]）中、選取SANtricity 「EOSR」軟體檔案和「NVSRAM/」檔案。選取軟體檔案後、相容儲存陣列的清單就會出現在此頁面上。然後選擇要使用新軟體升級的儲存陣列。（您無法選取不相容的陣列。）
. 接著您可以立即開始軟體傳輸和啟動、也可以選擇稍後將檔案登入以進行啟動。在升級過程中、Unified Manager會執行下列工作：
+
.. 對儲存陣列執行健全狀況檢查、以判斷是否存在任何可能妨礙升級完成的情況。如果有任何陣列未通過健全狀況檢查、您可以跳過該特定陣列並繼續升級其他陣列、或是停止整個程序、並疑難排解未通過的陣列。
.. 將升級檔案傳輸至每個控制器。
.. 重新啟動控制器、並啟動新SANtricity 的作業系統軟體、一次一個控制器。在啟動期間、現有SANtricity 的作業系統檔案會被新檔案取代。
+
[NOTE]
====
您也可以指定日後啟動軟體。

====






== 立即或分段升級

您可以立即啟動升級、或稍後再進行登入。您可以選擇稍後啟動、原因如下：

* *每天的時間*-啟動軟體可能需要很長時間、因此您可能需要等待I/O負載變輕。控制器升級通常需要15到25分鐘才能完成、視I/O負載和快取大小而定。控制器會在啟動期間重新開機並容錯移轉、因此在升級完成之前、效能可能會比平常低。
* *套件類型*：在升級其他儲存陣列上的檔案之前、您可能需要在一個儲存陣列上測試新的軟體和韌體。


若要啟動階段式軟體、請前往功能表：Support（升級中心）、然後按一下標示SANtricity 為「停止作業系統控制器軟體升級」的區域中的* Activate*。



== 健全狀況檢查

健全狀況檢查會在升級程序中執行、但您也可以在開始之前分別執行健全狀況檢查（前往功能表：Upgrade Center[預先升級健全狀況檢查]）。

健全狀況檢查會評估所有儲存系統元件、以確保升級能夠繼續進行。下列情況可能會導致升級無法進行：

* 指派的磁碟機故障
* 使用中的熱備援磁碟機
* 不完整的Volume群組
* 執行專屬作業
* 遺失磁碟區
* 控制器處於非最佳狀態
* 事件記錄事件過多
* 組態資料庫驗證失敗
* 使用舊版的DACStore磁碟機

