---
permalink: um-manage/mirroring-configuration-workflow.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, configuration, workflow 
summary: 您可以在Unified Manager中設定非同步或同步鏡射、然後使用System Manager來管理同步作業。 
---
= 鏡射組態工作流程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在Unified Manager中設定非同步或同步鏡射、然後使用System Manager來管理同步作業。



== 非同步鏡射工作流程

非同步鏡射涉及下列工作流程：

. 在Unified Manager中執行初始組態：
+
.. 選取本機儲存陣列作為資料傳輸來源。
.. 建立或選取現有的鏡射一致性群組、此群組是本機陣列上主要磁碟區的容器、也是遠端陣列上次要磁碟區的容器。主要和次要磁碟區稱為「鏡射配對」。 如果您是第一次建立鏡射一致性群組、請指定要執行手動或排程的同步。
.. 從本機儲存陣列選取主要磁碟區、然後決定其保留容量。保留容量是指用於複製作業的實體配置容量。
.. 選取遠端儲存陣列做為傳輸的目的地、次要磁碟區、然後決定其保留容量。
.. 開始從主要磁碟區傳輸初始資料至次要磁碟區。視磁碟區大小而定、此初始傳輸可能需要數小時的時間。


. 檢查初始同步的進度：
+
.. 在Unified Manager中、啟動本機陣列的System Manager。
.. 在System Manager中、檢視鏡射作業的狀態。鏡射完成後、鏡射配對的狀態為「最佳」。


. 您也可以在System Manager中重新排程或手動執行後續資料傳輸。只有新的和變更的區塊會從主要Volume傳輸到次要Volume。
+
[NOTE]
====
由於非同步複寫是定期的、因此系統可以整合變更的區塊並節省網路頻寬。寫入處理量和寫入延遲的影響最小。

====




== 同步鏡射工作流程

同步鏡射涉及下列工作流程：

. 在Unified Manager中執行初始組態：
+
.. 選取本機儲存陣列作為資料傳輸來源。
.. 從本機儲存陣列選取主要磁碟區。
.. 選取遠端儲存陣列做為資料傳輸的目的地、然後選取次要Volume。
.. 選取同步與重新同步優先順序。
.. 開始從主要磁碟區傳輸初始資料至次要磁碟區。視磁碟區大小而定、此初始傳輸可能需要數小時的時間。


. 檢查初始同步的進度：
+
.. 在Unified Manager中、啟動本機陣列的System Manager。
.. 在System Manager中、檢視鏡射作業的狀態。鏡射完成後、鏡射配對的狀態為「最佳」。 這兩個陣列嘗試透過正常作業保持同步。只有新的和變更的區塊會從主要Volume傳輸到次要Volume。


. 您也可以在System Manager中變更同步處理設定。
+
[NOTE]
====
由於同步複寫是持續的、因此這兩個站台之間的複寫連結必須提供足夠的頻寬功能。

====

