---
permalink: um-manage/mirroring-overview.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, 
summary: Unified Manager提供SANtricity 支援鏡射功能的組態選項、可讓系統管理員在兩個儲存陣列之間複寫資料、以保護資料。 
---
= 鏡射的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager提供SANtricity 支援鏡射功能的組態選項、可讓系統管理員在兩個儲存陣列之間複寫資料、以保護資料。

[NOTE]
====
EF600或EF300儲存系統無法使用此功能。

====


== 鏡射類型

支援非同步和同步的兩種鏡射類型。SANtricity

非同步鏡射會根據需求或排程複製資料磁碟區、如此可將資料毀損或遺失所造成的停機時間減至最少或避免。非同步鏡射會在特定時間點擷取主要磁碟區的狀態、並只複製自上次擷取映像以來所變更的資料。主站台可立即更新、而次要站台可在頻寬允許的情況下更新。這些資訊會在網路資源可用時快取並於稍後傳送。這類鏡射最適合用於定期程序、例如備份與歸檔。

同步鏡射可即時複寫資料磁碟區、確保持續可用。其目的是在兩個儲存陣列之一發生災難時、提供重要資料的複本、藉此達到零遺失資料的還原點目標（RPO）。複本會在每一刻與正式作業資料完全相同、因為每次寫入主要磁碟區時、都會寫入次要磁碟區。在將次要Volume更新為主要Volume所做的變更之前、主機不會收到寫入成功的確認訊息。這類鏡射是業務持續運作（例如災難恢復）的理想選擇。



== 鏡射類型之間的差異

下表說明兩種鏡射類型之間的主要差異。

[cols="1a,1a,1a"]
|===
| 屬性 | 非同步 | 同步 


 a| 
複寫方法
 a| 
時間點-鏡像是隨需執行、或是根據使用者定義的排程自動執行。
 a| 
Continuous（持續）-鏡像會持續執行、從每個主機寫入複製資料。



 a| 
距離
 a| 
支援陣列之間的長距離傳輸。一般而言、距離僅受限於網路功能和通道擴充技術。
 a| 
限制在陣列之間的較短距離。一般而言、距離本機儲存陣列必須在10公里（6.2英哩）內、才能滿足延遲和應用程式效能需求。



 a| 
通訊方法
 a| 
標準IP或光纖通道網路。
 a| 
僅限Fibre Channel網路。



 a| 
Volume類型
 a| 
標準或精簡。
 a| 
僅限標準。

|===