---
permalink: um-manage/overview-upgrade-center-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, center 
summary: 從升級中心、您可以管理SANtricity 多個儲存陣列的支援功能、包括作業系統的功能和NVSRAM升級。 
---
= 升級中心總覽
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從升級中心、您可以管理SANtricity 多個儲存陣列的支援功能、包括作業系統的功能和NVSRAM升級。



== 升級如何運作？

您可以下載最新的作業系統軟體、然後升級一或多個陣列。



=== 升級工作流程

下列步驟提供執行軟體升級的高層級工作流程。

. 您可從SANtricity Support網站下載最新的支援作業系統軟體檔案（如需支援頁面中的Unified Manager連結、請參閱）。將檔案儲存在管理主機系統（您在瀏覽器中存取Unified Manager的主機）上、然後解壓縮檔案。
. 在Unified Manager中、您可以將SANtricity Sesome作業系統軟體檔案和NVSRAM/檔案載入儲存庫（儲存檔案的Web Services Proxy伺服器區域）。您可以從功能表：Upgrade Center[升級SANtricity 支援中心軟體或從Upgrade Center > Manage Software儲存庫]新增檔案。
. 在檔案載入儲存庫之後、您可以選取要用於升級的檔案。從「Upgrade SANtricity EOSOS」（升級版作業系統）軟體頁面（功能表：Upgrade Center[升級SANtricity 版作業系統軟體]）中、選取SANtricity 「EOSR」軟體檔案和「NVSRAM/」檔案。選取軟體檔案後、相容儲存陣列的清單就會出現在此頁面上。然後選擇要使用新軟體升級的儲存陣列。（您無法選取不相容的陣列。）
. 接著您可以立即開始軟體傳輸和啟動、也可以選擇稍後將檔案登入以進行啟動。在升級過程中、Unified Manager會執行下列工作：
+
.. 對儲存陣列執行健全狀況檢查、以判斷是否存在任何可能妨礙升級完成的情況。如果有任何陣列未通過健全狀況檢查、您可以跳過該特定陣列並繼續升級其他陣列、或是停止整個程序、並疑難排解未通過的陣列。
.. 將升級檔案傳輸至每個控制器。
.. 重新啟動控制器、並啟動新SANtricity 的作業系統軟體、一次一個控制器。在啟動期間、現有SANtricity 的作業系統檔案會被新檔案取代。
+
[NOTE]
====
您也可以指定日後啟動軟體。

====






=== 立即或分段升級

您可以立即啟動升級、或稍後再進行登入。您可以選擇稍後啟動、原因如下：

* *每天的時間*-啟動軟體可能需要很長時間、因此您可能需要等待I/O負載變輕。控制器升級通常需要15到25分鐘才能完成、視I/O負載和快取大小而定。控制器會在啟動期間重新開機並容錯移轉、因此在升級完成之前、效能可能會比平常低。
* *套件類型*：在升級其他儲存陣列上的檔案之前、您可能需要在一個儲存陣列上測試新的軟體和韌體。


若要啟動階段式軟體、請前往功能表：Support（升級中心）、然後按一下標示SANtricity 為「停止作業系統控制器軟體升級」的區域中的* Activate*。



=== 健全狀況檢查

健全狀況檢查會在升級程序中執行、但您也可以在開始之前分別執行健全狀況檢查（前往功能表：Upgrade Center[預先升級健全狀況檢查]）。

健全狀況檢查會評估所有儲存系統元件、以確保升級能夠繼續進行。下列情況可能會導致升級無法進行：

* 指派的磁碟機故障
* 使用中的熱備援磁碟機
* 不完整的Volume群組
* 執行專屬作業
* 遺失磁碟區
* 控制器處於非最佳狀態
* 事件記錄事件過多
* 組態資料庫驗證失敗
* 使用舊版的DACStore磁碟機




== 升級前需要知道哪些資訊？

在升級多個儲存陣列之前、請先檢閱規劃中的重要考量事項。



=== 目前版本

您可以SANtricity 從Unified Manager的「管理」頁面、針對每個探索到的儲存陣列、檢視目前的版本。版本會顯示在SANtricity 「更新OS軟體」欄位中。當您按一SANtricity 下每列的「還原OS版本」時、控制器韌體和NVSRAM資訊 會出現在快顯對話方塊中。



=== 其他需要升級的元件

在升級過程中、您可能還需要升級主機的多重路徑/容錯移轉驅動程式或HBA驅動程式、以便主機能夠正確與控制器互動。

如需相容性資訊、請參閱 https://imt.netapp.com/matrix/#welcome["NetApp 互通性對照表"^]。此外、請參閱適用於您作業系統的快速指南中的程序。如需快速指南、請參閱 https://docs.netapp.com/us-en/e-series/index.html["E系列與SANtricity 支援技術文件"^]。



=== 雙控制器

如果儲存陣列包含兩個控制器、而且您已安裝多重路徑驅動程式、則儲存陣列可在升級時繼續處理I/O。在升級期間、會發生下列程序：

. 控制器A將其所有LUN容錯移轉至控制器B
. 在控制器A上進行升級
. 控制器A會恢復其LUN及控制器B的所有LUN。
. 在控制器B上進行升級


升級完成後、您可能需要在控制器之間手動重新分配磁碟區、以確保磁碟區回到正確的擁有控制器。
