---
permalink: sm-settings/access-management-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, terms 
summary: 瞭解存取管理條款如何適用於您的儲存陣列。 
---
= 存取管理術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解存取管理條款如何適用於您的儲存陣列。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
存取權杖
 a| 
存取權杖可用來以REST API或命令列介面（CLI）來驗證、取代使用者名稱和密碼。權杖與特定使用者（包括LDAP使用者）相關聯、並包含一組權限和到期日。



 a| 
Active Directory
 a| 
Active Directory（AD）是一項Microsoft目錄服務、用於Windows網域網路的LDAP。



 a| 
連結
 a| 
連結作業用於驗證目錄伺服器的用戶端。綁定通常需要帳戶和密碼認證、但有些伺服器允許匿名連結作業。



 a| 
CA
 a| 
憑證授權單位（CA）是信任的實體、可發行稱為數位憑證的電子文件、以確保網際網路安全。這些憑證可識別網站擁有者、以便在用戶端與伺服器之間進行安全連線。



 a| 
憑證
 a| 
憑證可識別站台的擁有者、以確保安全性、防止攻擊者模擬站台。憑證包含網站擁有者的相關資訊、以及認證（簽署）此資訊的信任實體身分。



 a| 
IDP
 a| 
身分識別提供者（IDP）是外部系統、用於向使用者要求認證、以及判斷該使用者是否已成功驗證。IDP可設定為提供多因素驗證、並使用任何使用者資料庫、例如Active Directory。您的安全團隊負責維護IDP。



 a| 
LDAP
 a| 
輕量型目錄存取傳輸協定（LDAP）是用於存取及維護分散式目錄資訊服務的應用程式傳輸協定。此傳輸協定可讓許多不同的應用程式和服務連線至LDAP伺服器、以驗證使用者。



 a| 
RBAC
 a| 
角色型存取控制（RBAC）是一種根據個別使用者角色來管理電腦或網路資源存取的方法。RBAC控制會在儲存陣列上強制執行、並包含預先定義的角色。



 a| 
SAML
 a| 
安全聲明標記語言（SAML）是兩個實體之間驗證與授權的XML型標準。SAML允許多因素驗證、使用者必須提供兩個或多個項目來證明身分（例如密碼和指紋）。儲存陣列的內嵌SAML功能符合SAML2.0標準、可用於身分識別聲明、驗證及授權。



 a| 
SP
 a| 
服務供應商（SP）是控制使用者驗證與存取的系統。使用SAML設定存取管理時、儲存陣列會做為服務供應商、以要求身分識別供應商進行驗證。



 a| 
SSO
 a| 
單一登入（SSO）是一種驗證服務、可讓一組登入認證資料存取多個應用程式。

|===