---
permalink: sm-settings/add-trap-destinations-for-snmp-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, trap, destinations, SNMP, alerts, 
summary: 您最多可以新增10部伺服器來傳送SNMP設陷。 
---
= 新增SNMP警示的設陷目的地
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您最多可以新增10部伺服器來傳送SNMP設陷。

.開始之前
* 您要新增的網路伺服器必須使用SNMP服務應用程式進行設定。您需要此伺服器的網路位址（無論是IPv4或IPv6位址）、事件監控器才能將陷阱訊息傳送到該位址。您可以使用多部伺服器（最多允許10部伺服器）。
* 管理資訊庫（mib）檔案已複製並使用SNMP服務應用程式在伺服器上編譯。此mib檔案定義要監控和管理的資料。
+
如果您沒有mib檔案、可以從NetApp支援網站取得：

+
** 前往 https://mysupport.netapp.com/site/global/dashboard["NetApp支援"^]。
** 單擊* Downloads *（下載*），然後選擇* Downloads（*下載*）。
** 按一下「* E系列SANtricity 」「作業系統控制器軟體*」。
** 選擇*下載最新版本*。
** 登入。
** 接受「注意」聲明和授權合約。
** 向下捲動、直到您看到控制器類型的mib檔案、然後按一下連結下載檔案。




.步驟
. 選取功能表：設定[警示]。
. 選取「* SNMP *」索引標籤。
+
目前定義的設陷目的地會出現在表格中。

. 選取*新增設陷的設計*。
+
「新增設陷目的地」對話方塊隨即開啟。

. 輸入一個或多個陷阱目的地、選取其相關的社群名稱或使用者名稱、然後按一下*「Add*（新增*）」。
+
** *陷阱目的地*-輸入執行SNMP服務之伺服器的IPV4或IPv6位址。
** *社群名稱或使用者名稱*-從下拉式清單中、選取此設陷目的地的社群名稱（SNMPv2c）或使用者名稱（v3）。（如果您只定義了一個名稱、則該名稱已出現在此欄位中。）
** *傳送驗證失敗Trap *-如果您想要在SNMP要求因無法辨識的社群名稱或使用者名稱而遭拒時、發出警示陷阱目的地、請選取此選項（核取方塊）。按一下「*新增*」之後、陷阱目的地和相關的社群名稱或使用者名稱會出現在表格中。


. 若要確定設陷有效、請從表格中選取設陷目的地、然後按一下*測試設陷目的地*、將測試設陷傳送到設定的位址。


.結果
每當發生警示事件時、事件監視器會將SNMP設陷傳送至伺服器。
