---
permalink: sm-settings/alerts-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, alerts, terms, 
summary: 瞭解警示條款如何適用於您的儲存陣列。 
---
= 警示術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解警示條款如何適用於您的儲存陣列。

[cols="25h,~"]
|===
| 元件 | 說明 


 a| 
事件監控
 a| 
事件監視器位於儲存陣列上、並作為背景工作執行。當事件監控器偵測到儲存陣列上的異常狀況時、會將有關問題的資訊寫入事件記錄。問題可能包括電池故障、從最佳狀態移至離線狀態的元件、或是控制器中的備援錯誤等事件。如果事件監控器判定事件為「alertable」（警示表）、則會使用設定的警示方法（電子郵件、SNMP及/或系統記錄）傳送通知。所有重大事件都會被視為「警示」、以及一些警告和資訊事件。



 a| 
郵件伺服器
 a| 
郵件伺服器用於傳送和接收電子郵件警示。伺服器使用簡易郵件傳輸傳輸傳輸協定（Simple Mail Transfer Protocol、簡稱SMTP）。



 a| 
SNMP
 a| 
簡易網路管理傳輸協定（SNMP）是一種網際網路標準傳輸協定、用於管理和共用IP網路上裝置之間的資訊。



 a| 
SNMP設陷
 a| 
SNMP設陷是傳送至SNMP伺服器的通知。陷阱包含儲存陣列重大問題的相關資訊。



 a| 
SNMP設陷目的地
 a| 
SNMP設陷目的地是執行SNMP服務之伺服器的IPv4或IPv6位址。



 a| 
社群名稱
 a| 
社群名稱是類似SNMP環境中網路伺服器密碼的字串。



 a| 
mib檔案
 a| 
管理資訊庫（mib）檔案定義儲存陣列中所監控及管理的資料。必須使用SNMP服務應用程式在伺服器上複製及編譯。支援網站上的System Manager軟體可提供此mib檔案。



 a| 
mib變數
 a| 
管理資訊庫（MIB）變數可傳回儲存陣列名稱、陣列位置、以及回應SNMP GetRequest的聯絡人等值。



 a| 
系統記錄
 a| 
syslog是網路裝置用來傳送事件訊息至記錄伺服器的傳輸協定。



 a| 
UDP
 a| 
使用者資料包傳輸協定（UDP）是傳輸層傳輸協定、可在其封包標頭中指定來源連接埠和目的地連接埠號碼。

|===