---
permalink: sm-settings/automatic-load-balancing-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, load, balancing, 
summary: 自動負載平衡功能可動態回應一段時間內的負載變更、並自動調整Volume控制器擁有權、以修正工作負載在控制器之間移動時發生的任何負載不平衡問題、進而改善I/O資源管理。 
---
= 了解 SANtricity 軟體中的自動負載平衡
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動負載平衡功能可動態回應一段時間內的負載變更、並自動調整Volume控制器擁有權、以修正工作負載在控制器之間移動時發生的任何負載不平衡問題、進而改善I/O資源管理。

每個控制器的工作負載都會持續受到監控、並可在主機上安裝多重路徑驅動程式的協助下、在必要時自動取得平衡。當工作負載在各個控制器之間自動重新平衡時、儲存管理員可免除手動調整Volume控制器所有權以因應儲存陣列負載變更的負擔。

啟用「自動負載平衡」時、會執行下列功能：

* 自動監控及平衡控制器資源使用率。
* 視需要自動調整Volume控制器擁有權、藉此最佳化主機與儲存陣列之間的I/O頻寬。




== 啟用和停用自動負載平衡

所有儲存陣列預設會啟用自動負載平衡。

基於下列原因、您可能想要停用儲存陣列上的自動負載平衡：

* 您不想自動變更特定磁碟區的控制器擁有權、以平衡工作負載。
* 您所在的環境經過高度調校、有針對性地設定負載分配、以便在控制器之間達成特定的分配。




== 支援自動負載平衡功能的主機類型

即使已在儲存陣列層級啟用自動負載平衡、您為主機或主機叢集所選取的主機類型仍會直接影響該功能的運作方式。

在控制器之間平衡儲存陣列的工作負載時、「自動負載平衡」功能會嘗試移動兩個控制器都能存取、且只對應到能夠支援「自動負載平衡」功能的主機或主機叢集的磁碟區。

這種行為可防止主機因為負載平衡程序而失去對磁碟區的存取權；不過、對應到不支援自動負載平衡之主機的磁碟區存在、會影響儲存陣列平衡工作負載的能力。為了讓自動負載平衡能夠平衡工作負載、多重路徑驅動程式必須支援TPGS、且主機類型必須包含在下表中。

[NOTE]
====
若要將主機叢集視為能夠自動負載平衡、該群組中的所有主機都必須能夠支援自動負載平衡。

====
[cols="1a,1a"]
|===
| 支援自動負載平衡的主機類型 | 使用此多重路徑驅動程式 


 a| 
Windows或Windows叢集
 a| 
採用NetApp E系列DSM的MPIO



 a| 
Linux DM-MP（核心3.10或更新版本）
 a| 
DM-MP搭配「scsi _dh _alua」裝置處理常式



 a| 
VMware
 a| 
原生多路徑外掛程式（NMP）、含「VMW_SATP_ALUA Storage Array Type」外掛程式

|===
[NOTE]
====
除了次要例外、不支援自動負載平衡的主機類型、無論是否啟用此功能、都會繼續正常運作。一個例外是、如果系統有容錯移轉、儲存陣列會在資料路徑傳回時、將未對應或未指派的磁碟區移回擁有控制器。不會移動任何對應或指派給非自動負載平衡主機的磁碟區。

====
請參閱 https://mysupport.netapp.com/matrix["互通性對照表工具"^] 以取得特定多重路徑驅動程式、作業系統層級和控制器磁碟機匣支援的相容性資訊。



== 驗證作業系統與自動負載平衡功能的相容性

在設定新（或移轉現有）系統之前、請先確認作業系統與自動負載平衡功能的相容性。

. 前往 https://mysupport.netapp.com/matrix["互通性對照表工具"^] 尋找您的解決方案並驗證支援。
+
如果您的系統執行的是Red Hat Enterprise Linux 6或SUSE Linux Enterprise Server 11、請聯絡技術支援部門。

. 更新並設定「/etc/multipath.conf檔案」。
. 請確認適用廠商和產品的「目錄附加裝置處理常式」和「目錄優先」都設為「是」、或使用預設設定。

