---
permalink: sm-settings/cache-settings-and-performance.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, settings, performance, 
summary: 快取記憶體是控制器上暫用揮發性儲存設備的區域、存取時間比磁碟機媒體快。 
---
= 快取設定與效能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
快取記憶體是控制器上暫用揮發性儲存設備的區域、存取時間比磁碟機媒體快。

透過快取、整體I/O效能可提升如下：

* 從主機要求讀取的資料可能已經在先前作業的快取中、因此不需要存取磁碟機。
* 寫入資料一開始會寫入快取、如此可釋出應用程式以繼續執行、而不需等待資料寫入磁碟機。


預設的快取設定符合大多數環境的需求、但您可以視需要加以變更。



== 儲存陣列快取設定

對於儲存陣列中的所有磁碟區、您可以從「System（系統）」頁面指定下列值：

* *清空的開始值*：快取中觸發快取清空（寫入磁碟）的未寫入資料百分比。當快取保留指定的未寫入資料開始百分比時、就會觸發排清。依預設、當快取達到80%的完整容量時、控制器會開始排清快取。
* *快取區塊大小*：每個快取區塊的最大大小、這是快取管理的組織單位。快取區塊大小預設為8 KiB、但可以設定為4、8、16或32 KiB。理想情況下、快取區塊大小應設定為應用程式的主要I/O大小。檔案系統或資料庫應用程式通常使用較小的大小、而較大的大小則適合需要大量資料傳輸或連續I/O的應用程式




== Volume快取設定

對於儲存陣列中的個別磁碟區、您可以從「Volumes（磁碟區）」頁面（功能表：Storage[Volumes]）指定下列值：

* *讀取快取*-讀取快取是儲存已從磁碟機讀取之資料的緩衝區。讀取作業的資料可能已經在先前作業的快取中、因此不需要存取磁碟機。資料會保留在讀取快取中、直到資料被清除為止。
+
** *動態讀取快取預先擷取*-動態快取讀取預先擷取可讓控制器在讀取磁碟機至快取的資料區塊時、將其他循序資料區塊複製到快取中。此快取可增加日後從快取中填入資料要求的機會。對於使用連續I/O的多媒體應用程式而言、動態快取讀取預先擷取非常重要預先擷取至快取的資料速率和數量、是根據主機讀取的速率和要求大小而自行調整。隨機存取不會將資料預先擷取至快取。停用讀取快取時、此功能不適用。


* *寫入快取*：寫入快取是一種緩衝區、用於儲存來自主機的資料、但尚未寫入磁碟機。資料會保留在寫入快取中、直到寫入磁碟機為止。寫入快取可提高I/O效能。
+
[CAUTION]
====
*可能的資料遺失*-如果您啟用*無電池寫入快取*選項、而且沒有通用電源供應器來保護資料、您可能會遺失資料。此外、如果您沒有控制器電池、並且啟用*無電池寫入快取*選項、則可能會遺失資料。

====
+
** *無電池寫入快取*-無電池寫入快取設定可讓寫入快取繼續、即使電池遺失、故障、電力完全耗盡或未充滿電也沒問題。通常不建議選擇不含電池的寫入快取、因為如果電力中斷、資料可能會遺失。一般而言、寫入快取會由控制器暫時關閉、直到電池充電或更換故障電池為止。
** *使用鏡射寫入快取*-寫入快取搭配鏡射會在寫入某個控制器快取記憶體的資料同時寫入另一個控制器的快取記憶體時發生。因此、如果一個控制器故障、另一個控制器就能完成所有未完成的寫入作業。只有啟用寫入快取且存在兩個控制器時、才能使用寫入快取鏡射。使用鏡射進行寫入快取是建立磁碟區的預設設定。



