---
permalink: sm-settings/change-saml-role-mappings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, saml, role, mappings, 
summary: 如果您先前已針對存取管理設定SAML、則可以變更IDP群組與儲存陣列預先定義角色之間的角色對應。 
---
= 變更SAML角色對應
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您先前已針對存取管理設定SAML、則可以變更IDP群組與儲存陣列預先定義角色之間的角色對應。

.開始之前
* 您必須以包含安全管理員權限的使用者設定檔登入。否則、就不會顯示存取管理功能。
* IDP管理員已在IDP系統中設定使用者屬性和群組成員資格。
* 已設定並啟用SAML。


.步驟
. 選取功能表：設定[Access Management（存取管理）]。
. 選取* SAML *索引標籤。
. 選擇*角色對應*。
+
此時會開啟「角色對應」對話方塊。

. 將IDP使用者屬性和群組指派給預先定義的角色。一個群組可以有多個指派的角色。
+
[CAUTION]
====
請注意、在啟用SAML時、您不會移除權限、否則您將無法存取System Manager。

====
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*對應*



 a| 
使用者屬性
 a| 
指定要對應之SAML群組的屬性（例如「memberof」）。



 a| 
屬性值
 a| 
指定要對應群組的屬性值。



 a| 
角色
 a| 
按一下欄位、然後選取要對應至屬性的其中一個儲存陣列角色。您必須個別選取要納入此群組的每個角色。必須搭配其他角色才能登入系統管理員、才能使用監控角色。必須將安全管理員角色指派給至少一個群組。對應的角色包括下列權限：

** *儲存設備管理*-對儲存物件（例如磁碟區和磁碟集區）的完整讀寫存取權、但無法存取安全性組態。
** *安全管理*：存取存取管理、憑證管理、稽核記錄管理中的安全組態、以及開啟或關閉舊版管理介面（符號）的功能。
** *支援admin*：存取儲存陣列上的所有硬體資源、故障資料、MEL事件及控制器韌體升級。無法存取儲存物件或安全性組態。
** *監控*-對所有儲存物件的唯讀存取、但無法存取安全性組態。


|===
====
+

NOTE: 所有使用者（包括系統管理員）都必須具備「監控」角色。沒有監控角色的任何使用者、System Manager將無法正常運作。

. （可選）單擊* Add another mapping（添加另一個映射）*以輸入更多的組對角色映射。
. 按一下「 * 儲存 * 」。


.結果
完成此工作之後、任何作用中的使用者工作階段都會終止。只會保留目前的使用者工作階段。
