---
permalink: sm-settings/configure-mail-server-and-recipients-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, mail, server, recipients, alerts, 
summary: 若要設定電子郵件警示、您必須指定警示收件者的郵件伺服器位址和電子郵件位址。最多允許20個電子郵件地址。 
---
= 設定郵件伺服器和收件者的警示
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要設定電子郵件警示、您必須指定警示收件者的郵件伺服器位址和電子郵件位址。最多允許20個電子郵件地址。

.開始之前
* 郵件伺服器的位址必須是可用的。位址可以是IPV4或IPV6位址、也可以是完整網域名稱。
+
[NOTE]
====
若要使用完整網域名稱、您必須在兩個控制器上設定DNS伺服器。您可以從「硬體」頁面設定DNS伺服器。

====
* 必須提供電子郵件地址、才能作為警示傳送者使用。這是警示訊息「寄件者」欄位中顯示的位址。在SMTP傳輸協定中需要寄件者位址、否則會產生錯誤。
* 警示收件者的電子郵件地址必須可供使用。收件者通常是網路管理員或儲存管理員的位址。您最多可以輸入20個電子郵件地址。


.關於這項工作
此工作說明如何設定郵件伺服器、輸入寄件者和收件者的電子郵件地址、以及測試從「警示」頁面輸入的所有電子郵件地址。

[NOTE]
====
您也可以從初始設定精靈設定電子郵件警示。

====
.步驟
. 選取功能表：設定[警示]。
. 選取*電子郵件*索引標籤。
+
如果尚未設定電子郵件伺服器、「電子郵件」標籤會顯示「設定郵件伺服器」。

. 選擇*設定郵件伺服器*。
+
此時將打開Configure Mail Server（配置郵件服務器）對話框。

. 輸入郵件伺服器資訊、然後按一下「*儲存*」。
+
** *郵件伺服器位址*-輸入郵件伺服器的完整網域名稱、IPv4位址或IPv6位址。
+
[NOTE]
====
若要使用完整網域名稱、您必須在兩個控制器上設定DNS伺服器。您可以從「硬體」頁面設定DNS伺服器。

====
** *電子郵件寄件者地址*-輸入有效的電子郵件地址、作為電子郵件寄件者。此地址會出現在電子郵件訊息的「寄件者」欄位中。
** *加密*-如果您要加密訊息、請選取* SMTP*或* STARTTLS*作為加密類型、然後選取加密訊息的連接埠號碼。否則、請選取*無*。
** *使用者名稱與密碼*-如有需要、請輸入使用者名稱與密碼、以便與傳出傳送者和郵件伺服器進行驗證。
** *在電子郵件中加入聯絡資訊*-若要在警示訊息中包含寄件者的聯絡資訊、請選取此選項、然後輸入姓名和電話號碼。
+
按一下「*儲存*」之後、電子郵件地址會出現在「警示」頁面的「電子郵件」索引標籤中。



. 選取*新增電子郵件*。
+
「新增電子郵件」對話方塊隨即開啟。

. 輸入警示收件者的一或多個電子郵件地址、然後按一下*「Add*（新增*）」。
+
電子郵件地址會顯示在「警示」頁面上。

. 如果您想確定電子郵件地址有效、請按一下*測試所有電子郵件*、將測試訊息傳送給收件者。


.結果
設定電子郵件警示之後、每當發生警示事件時、事件監視器都會將電子郵件訊息傳送給指定的收件者。
