---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, snmp, alerts, 
summary: 若要設定簡單網路管理傳輸協定（SNMP）警示、您必須至少識別一部伺服器、讓儲存陣列的事件監視器能夠傳送SNMP設陷。此組態需要社群名稱或使用者名稱、以及伺服器的IP位址。 
---
= 設定SNMP警示
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要設定簡單網路管理傳輸協定（SNMP）警示、您必須至少識別一部伺服器、讓儲存陣列的事件監控器能夠傳送SNMP設陷。此組態需要社群名稱或使用者名稱、以及伺服器的IP位址。

.開始之前
* 網路伺服器必須設定SNMP服務應用程式。您需要此伺服器的網路位址（無論是IPv4或IPv6位址）、事件監控器才能將陷阱訊息傳送到該位址。您可以使用多部伺服器（最多允許10部伺服器）。
* 管理資訊庫（mib）檔案已複製並使用SNMP服務應用程式在伺服器上編譯。此mib檔案定義要監控和管理的資料。
+
如果您沒有mib檔案、可以從NetApp支援網站取得：

+
** 前往 https://mysupport.netapp.com/site/global/dashboard["NetApp支援"^]。
** 單擊* Downloads（下載）*選項卡，然後選擇* Downloads（*下載）*。
** 按一下「* E系列SANtricity 」「作業系統控制器軟體*」。
** 選擇*下載最新版本*。
** 登入。
** 接受「注意」聲明和授權合約。
** 向下捲動、直到您看到控制器類型的mib檔案、然後按一下連結下載檔案。




本工作說明如何識別SNMP伺服器的設陷目的地、然後測試您的組態。

.步驟
. 選取功能表：設定[警示]。
. 選取「* SNMP *」索引標籤。
+
初次設定時、SNMP索引標籤會顯示「Configure Communities / Users」（設定社群/使用者）。

. 選擇*設定社群/使用者*。
+
「選取SNMP版本」對話方塊隨即開啟。

. 選取警示的SNMP版本：* SNMPv2c*或* SNMPv3 *。
+
視您的選擇而定、「設定社群」對話方塊或「設定v3使用者」對話方塊會開啟。

. 請遵循適當的SNMP v2c（社群）或v3（使用者）指示：
+
** * SNMP v2c（社群）*-在「設定社群」對話方塊中、輸入網路伺服器的一或多個社群字串。社群名稱是用來識別已知管理站組的字串、通常是由網路管理員所建立。它僅包含可列印的Ascii字元。您最多可以新增256個社群。完成後、請按一下*「Save（儲存）」*。
** * v3（使用者）*-在「設定v3使用者」對話方塊中、按一下「*新增*」、然後輸入下列資訊：
+
*** *使用者名稱*-輸入名稱以識別使用者、最多31個字元。
*** *引擎ID*-選取用來產生訊息驗證和加密金鑰的引擎ID、而且必須在管理網域上是唯一的。在大多數情況下、您應該選取*本機*。如果您使用的是非標準組態、請選取* Custom*；此時會出現另一個欄位、您必須輸入驗證引擎ID做為一個十六進位字串、其中的偶數字元長度介於10到32個字元之間。
*** *驗證認證資料*-選取驗證傳輸協定、以確保使用者的身分識別。接著、輸入驗證密碼、這是設定或變更驗證傳輸協定時所需的密碼。密碼長度必須介於8到128個字元之間。
*** *隱私權認證*-選取用於加密訊息內容的隱私權傳輸協定。接著、輸入隱私權密碼、這是設定或變更隱私權傳輸協定時所需的密碼。密碼長度必須介於8到128個字元之間。完成後、按一下*「Add*（新增*）」、然後按一下「* Close（*關閉*）」。




. 在「警示」頁面中選取「SNMP」索引標籤、按一下「*新增設陷目的地*」。
+
「新增設陷目的地」對話方塊隨即開啟。

. 輸入一個或多個陷阱目的地、選取其相關的社群名稱或使用者名稱、然後按一下*「Add*（新增*）」。
+
** *陷阱目的地*-輸入執行SNMP服務之伺服器的IPV4或IPv6位址。
** *社群名稱或使用者名稱*-從下拉式清單中、選取此設陷目的地的社群名稱（SNMPv2c）或使用者名稱（v3）。（如果您只定義了一個名稱、則該名稱已出現在此欄位中。）
** *傳送驗證失敗Trap *-如果您想要在SNMP要求因無法辨識的社群名稱或使用者名稱而遭拒時、發出警示陷阱目的地、請選取此選項（核取方塊）。單擊* Add（添加）*後，陷阱目標和相關名稱將顯示在* alert*（警告）頁面的* SNMP*（SNMP）選項卡中。


. 若要確定設陷有效、請從表格中選取設陷目的地、然後按一下*測試設陷目的地*、將測試設陷傳送到設定的位址。


每當發生警示事件時、事件監視器會將SNMP設陷傳送至伺服器。
