---
permalink: sm-settings/configure-iscsi-authentication.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, authentication, 
summary: 為了加強iSCSI網路的安全性、您可以在控制器（目標）和主機（啟動器）之間設定驗證。 
---
= 設定iSCSI驗證
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了加強iSCSI網路的安全性、您可以在控制器（目標）和主機（啟動器）之間設定驗證。

System Manager使用Challenge Handshake驗證傳輸協定（CHAP）方法、在初始連結期間驗證目標和啟動器的身分。驗證是以稱為_CHAP secret的共用安全金鑰為基礎。

.開始之前
您可以在設定目標（控制器）的CHAP機密之前或之後、設定啟動器（iSCSI主機）的CHAP機密。在遵循此工作的指示之前、您應該等到主機先建立iSCSI連線、然後在個別主機上設定CHAP機密。建立連線之後、主機的IQN名稱及其CHAP機密會列在iSCSI驗證的對話方塊中（如本工作所述）、您不需要手動輸入這些名稱。

.關於這項工作
您可以選取下列其中一種驗證方法：

* *單向驗證*-使用此設定可讓控制器驗證iSCSI主機的身分識別（單向驗證）。
* *雙向驗證*-使用此設定可允許控制器和iSCSI主機執行驗證（雙向驗證）。此設定可讓控制器驗證iSCSI主機的身分識別、進而驗證控制器的身分識別、進而提供第二層安全性。


[NOTE]
====
如果您的儲存陣列支援iSCSI、則iSCSI設定與功能僅會顯示在「設定」頁面上。

====
.步驟
. 選取功能表：設定[系統]。
. 在iSCSI設定下、按一下*設定驗證*。
+
此時會出現「設定驗證」對話方塊、顯示目前設定的方法。也會顯示是否有任何主機已設定CHAP機密。

. 選取下列其中一項：
+
** *無驗證*-如果您不希望控制器驗證iSCSI主機的身分識別、請選取此選項、然後按一下「*完成*」。對話方塊隨即關閉、您將完成組態設定。
** *單向驗證*-若要允許控制器驗證iSCSI主機的身分識別、請選取此選項、然後按*「下一步*」以顯示「設定目標CHAP」對話方塊。
** *雙向驗證*-若要允許控制器和iSCSI主機執行驗證、請選取此選項、然後按「*下一步*」以顯示「設定目標CHAP」對話方塊。


. 對於單向或雙向驗證、請輸入或確認控制器（目標）的CHAP機密。CHAP密碼必須介於12到57個可列印的Ascii字元之間。
+
[NOTE]
====
如果先前已設定控制器的CHAP密碼、則會遮罩欄位中的字元。如有必要、您可以取代現有的字元（新字元不會遮罩）。

====
. 執行下列其中一項：
+
** 如果您要設定_單向 驗證、請按一下*完成*。對話方塊隨即關閉、您將完成組態設定。
** 如果您要設定_雙向_驗證、請按一下*下一步*以顯示「設定啟動器CHAP」對話方塊。


. 對於雙向驗證、請輸入或確認任何iSCSI主機（啟動器）的CHAP密碼、此密碼可介於12到57個可列印的Ascii字元之間。如果您不想為特定主機設定雙向驗證、請將「啟動器CHAP機密」欄位保留空白。
+
[NOTE]
====
如果先前已設定主機的CHAP密碼、則會遮罩欄位中的字元。如有必要、您可以取代現有的字元（新字元不會遮罩）。

====
. 單擊*完成*。


.結果
除非您未指定驗證、否則驗證會在控制器與iSCSI主機之間的iSCSI登入順序期間進行。
