---
permalink: sm-settings/create-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, internal, security, key, 
summary: 若要使用「磁碟機安全性」功能、您可以建立內部安全金鑰、由儲存陣列中的控制器和具有安全功能的磁碟機共用。內部金鑰會保留在控制器的持續記憶體上。 
---
= 建立內部安全金鑰
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要使用「磁碟機安全性」功能、您可以建立內部安全金鑰、由儲存陣列中的控制器和具有安全功能的磁碟機共用。內部金鑰會保留在控制器的持續記憶體上。

.開始之前
* 必須在儲存陣列中安裝具有安全功能的磁碟機。這些磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。
* 必須啟用磁碟機安全功能。否則、在此工作期間會開啟「無法建立安全金鑰」對話方塊。如有必要、請聯絡您的儲存設備廠商、以取得啟用磁碟機安全功能的指示。


[NOTE]
====
如果儲存陣列中同時安裝FDE和FIPS磁碟機、則它們都會共用相同的安全金鑰。

====
.關於這項工作
在此工作中、您可以定義要與內部安全金鑰建立關聯的識別碼和密碼。

[NOTE]
====
磁碟機安全性密碼與儲存陣列的管理員密碼無關。

====
.步驟
. 選取功能表：設定[系統]。
. 在*安全金鑰管理*下、選取*建立內部金鑰*。
+
如果您尚未產生安全性金鑰、則會開啟「建立安全性金鑰」對話方塊。

. 在下列欄位中輸入資訊：
+
** *定義安全金鑰識別碼*-您可以接受預設值（儲存陣列名稱和時間戳記、由控制器韌體產生）、或輸入您自己的值。最多可輸入189個英數字元、不含空格、符號或符號。
+
[NOTE]
====
系統會自動產生其他字元、並附加到您輸入字串的兩端。產生的字元可確保識別碼是唯一的。

====
** *定義密碼/重新輸入密碼*-輸入並確認密碼。此值可包含8到32個字元、且必須包含下列各項：
+
*** 大寫字母（一個或多個）。請記住、密碼區分大小寫。
*** 數字（一或多個）。
*** 非英數字元、例如！、*、@（一或多個）。




+
[CAUTION]
====
*請務必記錄您的輸入項目以供日後使用*。如果您需要從儲存陣列移除啟用安全功能的磁碟機、則必須知道識別碼和密碼、才能解除鎖定磁碟機資料。

====
. 按一下「 * 建立 * 」。
+
安全金鑰儲存在無法存取的控制器位置。除了實際的金鑰、還有一個加密的金鑰檔案、可從瀏覽器下載。

+
[NOTE]
====
下載檔案的路徑可能取決於瀏覽器的預設下載位置。

====
. 記錄您的金鑰識別碼、密碼和下載金鑰檔的位置、然後按一下*關閉*。


.結果
您現在可以建立啟用安全功能的Volume群組或集區、也可以在現有的Volume群組和集區上啟用安全功能。

[NOTE]
====
只要關閉磁碟機的電源、然後再次開啟、所有啟用安全功能的磁碟機都會變更為「安全性鎖定」狀態。在此狀態下、資料將無法存取、直到控制器在磁碟機初始化期間套用正確的安全金鑰為止。如果有人實際移除鎖定的磁碟機並將其安裝在其他系統中、安全鎖定狀態會防止未獲授權存取其資料。

====
.完成後
您應該驗證安全金鑰、以確保金鑰檔案未毀損。
