---
permalink: sm-settings/drive-security-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drive, security, terms, 
summary: 瞭解磁碟機安全性條款如何適用於您的儲存陣列。 
---
= 推動安全性術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解磁碟機安全性條款如何適用於您的儲存陣列。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
磁碟機安全功能
 a| 
磁碟機安全性是一項儲存陣列功能、可透過全磁碟加密（FDE）磁碟機或聯邦資訊處理標準（FIPS）磁碟機提供額外的安全層級。當這些磁碟機搭配磁碟機安全功能使用時、它們需要安全金鑰才能存取其資料。當磁碟機從陣列中實際移除時、除非安裝在另一個陣列中、否則無法運作、此時磁碟機將處於「安全性鎖定」狀態、直到提供正確的安全金鑰為止。



 a| 
FDE磁碟機
 a| 
全磁碟加密（FDE）磁碟機在硬體層級對磁碟機執行加密。硬碟內含ASIC晶片、可在寫入期間加密資料、然後在讀取期間解密資料。



 a| 
FIPS磁碟機
 a| 
FIPS磁碟機使用聯邦資訊處理標準（FIPS）140-2第2級。它們基本上是FDE磁碟機、符合美國政府的標準、以確保強大的加密演算法和方法。FIPS磁碟機的安全性標準高於FDE磁碟機。



 a| 
管理用戶端
 a| 
本機系統（電腦、平板電腦等）、內含瀏覽器、可供存取System Manager。



 a| 
密碼
 a| 
密碼用於加密安全金鑰以供備份之用。在磁碟機移轉或頭端切換後匯入備份安全金鑰時、必須提供用於加密安全金鑰的相同密碼。通關詞可以介於8到32個字元之間。

[NOTE]
====
磁碟機安全性密碼與儲存陣列的管理員密碼無關。

====


 a| 
具備安全功能的磁碟機
 a| 
可安全使用的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機、在讀取期間加密資料並解密資料。這些磁碟機被視為安全的磁碟機、因為它們可以使用磁碟機安全功能來提高安全性。如果已針對這些磁碟機所使用的磁碟區群組和集區啟用「磁碟機安全性」功能、磁碟機就會變成安全的-_enabled_.



 a| 
啟用安全功能的磁碟機
 a| 
啟用安全功能的磁碟機可搭配磁碟機安全功能使用。當您啟用「磁碟機安全性」功能、然後將「磁碟機安全性」套用至安全的磁碟機上的集區或磁碟區群組時、磁碟機就會變成安全的__已啟用__。讀寫存取只能透過設定正確安全金鑰的控制器來使用。這項新增的安全功能可防止未獲授權存取從儲存陣列實體移除之磁碟機上的資料。



 a| 
安全金鑰
 a| 
安全金鑰是儲存陣列中啟用安全功能的磁碟機與控制器之間共用的字元字串。只要關閉和開啟磁碟機的電源、安全啟用的磁碟機就會變更為安全鎖定狀態、直到控制器套用安全金鑰為止。如果從儲存陣列中移除啟用安全功能的磁碟機、則磁碟機的資料會被鎖定。當磁碟機重新安裝在不同的儲存陣列中時、它會先尋找安全金鑰、然後再讓資料再次存取。若要解除資料鎖定、您必須套用原始的安全金鑰。您可以使用下列其中一種方法來建立及管理安全性金鑰：

* 內部金鑰管理：在控制器的持續記憶體上建立及維護安全金鑰。
* 外部金鑰管理：在外部金鑰管理伺服器上建立及維護安全金鑰。




 a| 
安全金鑰識別碼
 a| 
安全性金鑰識別碼是在金鑰建立期間與安全性金鑰相關聯的字串。識別碼儲存在控制器和所有與安全金鑰相關聯的磁碟機上。

|===