---
permalink: sm-settings/edit-directory-server-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, directory, server, settings, role, mappings, 
summary: 如果您先前在Access Management中設定了目錄伺服器、則可以隨時變更其設定。設定包括伺服器連線資訊和群組對角色對應。 
---
= 編輯目錄伺服器設定和角色對應
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您先前在Access Management中設定了目錄伺服器、則可以隨時變更其設定。設定包括伺服器連線資訊和群組對角色對應。

.開始之前
* 您必須以包含安全管理員權限的使用者設定檔登入。否則、就不會顯示存取管理功能。
* 必須定義目錄伺服器。


.步驟
. 選取功能表：設定[Access Management（存取管理）]。
. 選取*目錄服務*索引標籤。
. 如果定義了多個伺服器、請從表格中選取您要編輯的伺服器。
. 選取*檢視/編輯設定*。
+
此時將打開Directory Server Settings（目錄服務器設置）對話框。

. 在伺服器設定索引標籤中、變更所需的設定。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*組態設定*



 a| 
網域
 a| 
LDAP伺服器的網域名稱。若為多個網域、請在以逗號分隔的清單中輸入網域。網域名稱用於登入（_username_@_domain_）、以指定要驗證的目錄伺服器。



 a| 
伺服器URL
 a| 
以_LDAP[s]//host:port_格式存取LDAP伺服器的URL。



 a| 
連結帳戶（選用）
 a| 
用於針對LDAP伺服器進行搜尋查詢及在群組內搜尋的唯讀使用者帳戶。



 a| 
連結密碼（選用）
 a| 
綁定帳戶的密碼。（輸入連結帳戶時、會顯示此欄位。）



 a| 
儲存前先測試伺服器連線
 a| 
檢查儲存陣列是否能與LDAP伺服器組態通訊。在您按一下對話方塊底部的*「Save"（儲存）*之後、就會進行測試。如果選取此核取方塊且測試失敗、則不會變更組態。您必須解決錯誤或取消選取核取方塊、才能跳過測試並重新編輯組態。



 a| 
*權限設定*



 a| 
搜尋基礎DN
 a| 
要搜尋使用者的LDAP內容、通常格式為「CN=Users、DC=cOPC、DC=local」。



 a| 
使用者名稱屬性
 a| 
繫結至使用者ID以進行驗證的屬性。例如：「AMAccountName」。



 a| 
群組屬性
 a| 
使用者上的群組屬性清單、用於群組對角色對應。例如：「memberof、managedObjects'。

|===
====
. 在「角色對應」索引標籤中、變更所需的對應。
+
.欄位詳細資料
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*對應*



 a| 
群組DN
 a| 
要對應之LDAP使用者群組的網域名稱。支援規則運算式。如果這些特殊的規則運算式字元不是一般運算式模式的一部分、則必須以反斜槓（'\）轉義：\.[]{}()<>*+-=!?^$|



 a| 
角色
 a| 
要對應至群組DN的儲存陣列角色。您必須個別選取要納入此群組的每個角色。必須搭配其他角色來登入SANtricity 「監控」角色才能登入「系統管理程式」。儲存陣列的角色包括：

** *儲存設備管理*-對儲存物件（例如磁碟區和磁碟集區）的完整讀寫存取權、但無法存取安全性組態。
** *安全管理*：存取存取管理、憑證管理、稽核記錄管理中的安全組態、以及開啟或關閉舊版管理介面（符號）的功能。
** *支援admin*：存取儲存陣列上的所有硬體資源、故障資料、MEL事件及控制器韌體升級。無法存取儲存物件或安全性組態。
** *監控*-對所有儲存物件的唯讀存取、但無法存取安全性組態。


|===
====
+
[NOTE]
====
所有使用者（包括系統管理員）都必須具備「監控」角色。沒有監控角色的任何使用者、System Manager將無法正常運作。

====
. 如有需要、請按一下*新增其他對應*、以輸入更多群組對角色對應。
. 按一下「 * 儲存 * 」。


完成此工作之後、任何作用中的使用者工作階段都會終止。只會保留目前的使用者工作階段。
