---
permalink: sm-settings/enable-iscsi-discovery-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, iscsi, discovery, settings, 
summary: 您可以在iSCSI網路中啟用與探索儲存裝置相關的設定。 
---
= 在 SANtricity System Manager 中啟用 iSCSI 發現設置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在iSCSI網路中啟用與探索儲存裝置相關的設定。

「目標探索設定」可讓您使用網際網路儲存名稱服務（iSNS）傳輸協定來登錄儲存陣列的iSCSI資訊、並決定是否允許未命名的探索工作階段。

.開始之前
如果iSNS伺服器使用靜態IP位址、則該位址必須可用於iSNS登錄。同時支援IPV4和IPV6。

.關於這項工作
您可以啟用下列與iSCSI探索相關的設定：

* *讓iSNS伺服器登錄目標*-啟用後、儲存陣列會從iSNS伺服器登錄其iSCSI合格名稱（IQN）和連接埠資訊。此設定可允許進行iSNS探索、以便啟動器從iSNS伺服器擷取IQN和連接埠資訊。
* *啟用未命名探索工作階段*-啟用未命名探索工作階段時、啟動器（iSCSI主機）不需要在探索型連線的登入順序期間提供目標（控制器）的IQN。停用時、主機確實需要提供IQN、才能建立與控制器的探索工作階段。然而、一般（I/O承載）工作階段一律需要目標IQN。停用此設定可防止未獲授權的iSCSI主機僅使用其IP位址連線至控制器。


[NOTE]
====
如果您的儲存陣列支援iSCSI、則iSCSI設定與功能僅會顯示在「設定」頁面上。

====
.步驟
. 選取功能表：設定[系統]。
. 在「* iSCSI設定*」下、按一下「*檢視/編輯目標探索設定*」。
+
此時會出現「目標探索設定」對話方塊。在「*啟用iSNS伺服器*...」欄位下方、對話方塊會指出控制器是否已登錄。

. 若要登錄控制器、請選取*啟用iSNS伺服器以登錄我的目標*、然後選取下列其中一項：
+
** *自動從DHCP伺服器取得組態*-如果您要使用動態主機組態傳輸協定（DHCP）伺服器來設定iSNS伺服器、請選取此選項。請注意、如果您使用此選項、則控制器上的所有iSCSI連接埠也必須設定為使用DHCP。如有必要、請更新控制器iSCSI連接埠設定以啟用此選項。
+
[NOTE]
====
若要讓DHCP伺服器提供iSNS伺服器位址、您必須將DHCP伺服器設定為使用選項43 -「廠商專屬資訊」。 此選項必須包含以資料位元組為單位的iSNS伺服器IPv4位址：0xA-xd（10-13）。

====
** *手動指定靜態組態*-如果您要輸入iSNS伺服器的靜態IP位址、請選取此選項。（如有需要、您可以剪下地址並貼到欄位中。） 在欄位中、輸入一個IPv4位址或IPv6位址。如果您同時設定這兩者、則預設為使用IPV4。同時輸入TCP聆聽連接埠（使用預設值3205或輸入介於49152和6555之間的值）。


. 若要允許儲存陣列參與未命名的探索工作階段、請選取*啟用未命名的探索工作階段*。
+
** 啟用時、iSCSI啟動器不需要指定目標IQN來擷取控制器資訊。
** 停用時、除非啟動器提供目標IQN、否則會禁止探索工作階段。停用未命名的探索工作階段可提供更高的安全性。


. 按一下「 * 儲存 * 」。


.結果
當System Manager嘗試將控制器登錄到iSNS伺服器時、會出現進度列。此程序可能需要五分鐘的時間。
