---
permalink: sm-settings/faq-certificates.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 的 CA 簽章憑證和自簽章憑證常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 為什麼會出現「無法存取其他控制器」對話方塊？

當您執行某些與CA憑證相關的作業（例如匯入憑證）時、可能會看到一個對話方塊、提示您接受第二個控制器的自我簽署憑證。

在具有兩個控制器（雙工組態）的儲存陣列中、SANtricity 如果無法與第二個控制器通訊、或是瀏覽器在作業的某個時間點無法接受憑證、有時會出現此對話方塊。

如果此對話方塊開啟、請按一下*「接受自我簽署的憑證*」繼續。如果另一個對話方塊提示您輸入密碼、請輸入您用於存取System Manager的管理員密碼。

如果此對話方塊再次出現、且您無法完成憑證工作、請嘗試下列其中一個程序：

* 使用不同的瀏覽器類型來存取此控制器、接受憑證並繼續。
* 使用System Manager存取第二個控制器、接受自我簽署的憑證、然後返回第一個控制器並繼續。




== 如何知道需要上傳哪些憑證到 SANtricity 系統管理員才能進行外部金鑰管理？

對於外部金鑰管理、您可以匯入兩種類型的憑證、以便在儲存陣列和金鑰管理伺服器之間進行驗證、讓兩個實體彼此信任。

用戶端憑證會驗證儲存陣列的控制器、因此金鑰管理伺服器可以信任其金鑰管理互通性傳輸協定（KMIP）要求。

若要取得用戶端憑證、請使用System Manager為儲存陣列完成CSR。您也可以使用私密和公開金鑰配對從外部產生 CSR 。

然後、您可以將CSR上傳至金鑰管理伺服器、然後從該伺服器產生用戶端憑證。取得用戶端憑證後、請將該檔案複製到您要存取System Manager的主機。

金鑰管理伺服器憑證會驗證金鑰管理伺服器、因此儲存陣列可以信任其IP位址。從金鑰管理伺服器擷取伺服器憑證檔案、然後將該檔案複製到您正在存取System Manager的主機。



== 關於憑證撤銷檢查、我需要知道什麼？

SANtricity 系統管理員可讓您使用線上憑證狀態通訊協定 (OCSP) 伺服器來檢查撤銷的憑證，而非上傳憑證撤銷清單 (CRL) 。

撤銷的憑證不應再受到信任。憑證可能會因數種原因而遭撤銷；例如、如果憑證授權單位（CA）未適當核發憑證、私密金鑰遭洩漏、或是識別的實體未遵守原則要求。

在System Manager中建立OCSP伺服器的連線之後、儲存陣列會在連線至AutoSupport 某個伺服器、外部金鑰管理伺服器（EKMS）、SSL上的輕量型目錄存取傳輸協定（LDAPS）伺服器或Syslog伺服器時、執行撤銷檢查。儲存陣列會嘗試驗證這些伺服器的憑證、以確保這些憑證尚未撤銷。然後伺服器會傳回該憑證的「好」、「已撤銷」或「未知」值。如果憑證已撤銷、或陣列無法聯絡OCSP伺服器、則連線會遭到拒絕。

[NOTE]
====
在System Manager或命令列介面（CLI）中指定OCSP回應程式位址、會覆寫在憑證檔案中找到的OCSP位址。

====


== 哪些類型的伺服器會啟用撤銷檢查？

儲存陣列會在連線AutoSupport 至某個伺服器、外部金鑰管理伺服器（EKMS）、輕量型SSL目錄存取傳輸協定（LDAPS）伺服器或Syslog伺服器時、執行撤銷檢查。
