---
permalink: sm-settings/how-access-management-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, authentication, users, roles, access, Management, 
summary: 存取管理是SANtricity 一種在《Sytricity System Manager》中建立使用者驗證的方法。 
---
= 存取管理的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
存取管理是在System Manager中建立使用者驗證的方法。

組態和使用者驗證的運作方式如下：

. 系統管理員使用包含「安全性管理」權限的使用者設定檔登入System Manager。
+
[NOTE]
====
首次登入時、使用者名稱「admin」會自動顯示、無法變更。「admin」使用者可完整存取系統中的所有功能。

====
. 系統管理員會在使用者介面中導覽至「存取管理」。儲存陣列已預先設定為使用本機使用者角色、這是RBAC（角色型存取控制）功能的實作。
. 系統管理員可設定下列一或多種驗證方法：
+
** *本機使用者角色*-驗證是透過儲存陣列中強制執行的RBAC功能來管理。本機使用者角色包括預先定義的使用者設定檔和具有特定存取權限的角色。系統管理員可以使用這些本機使用者角色做為單一驗證方法、或搭配目錄服務使用。除了為使用者設定密碼之外、不需要進行任何組態。
** *目錄服務*-驗證是透過LDAP（輕量型目錄存取傳輸協定）伺服器和目錄服務（例如Microsoft的Active Directory）來管理。系統管理員會連線至LDAP伺服器、然後將LDAP使用者對應至儲存陣列內嵌的本機使用者角色。
** * SAML *-驗證是透過身分識別供應商（IDP）、使用安全聲明標記語言（SAML）2.0來管理。系統管理員會在IDP系統與儲存陣列之間建立通訊、然後將IDP使用者對應至儲存陣列內嵌的本機使用者角色。


. 系統管理員會為使用者提供System Manager的登入認證。
. 使用者輸入認證資料以登入系統。
+
[NOTE]
====
如果使用SAML和SSO（單一登入）來管理驗證、系統可能會略過System Manager登入對話方塊。

====
+
登入期間、系統會執行下列背景工作：

+
** 根據使用者帳戶驗證使用者名稱和密碼。
** 根據指派的角色來決定使用者的權限。
** 讓使用者存取使用者介面中的工作。
** 在介面右上角顯示使用者名稱。






== System Manager中可用的工作

存取工作取決於使用者指派的角色、包括下列項目：

* *儲存設備管理*-對儲存物件（例如磁碟區和磁碟集區）的完整讀寫存取權、但無法存取安全性組態。
* *安全管理*：存取存取管理、憑證管理、稽核記錄管理中的安全組態、以及開啟或關閉舊版管理介面（符號）的功能。
* *支援admin*：存取儲存陣列上的所有硬體資源、故障資料、MEL事件及控制器韌體升級。無法存取儲存物件或安全性組態。
* *監控*-對所有儲存物件的唯讀存取、但無法存取安全性組態。


無法使用的工作會呈現灰色、或不會顯示在使用者介面中。例如、擁有「監控」角色的使用者可以檢視所有關於磁碟區的資訊、但無法存取修改該磁碟區的功能。諸如*複製服務*和*新增至工作負載*等功能的索引標籤將會呈現灰色、僅提供*檢視/編輯設定*。



== Unified Manager和Storage Manager的限制

如果已針對儲存陣列設定SAML、使用者將無法從Unified Manager或舊版Storage Manager介面探索或管理該陣列的儲存設備。

設定本機使用者角色和目錄服務時、使用者必須先輸入認證資料、才能執行下列任一功能：

* 重新命名儲存陣列
* 升級控制器韌體
* 正在載入儲存陣列組態
* 執行指令碼
* 嘗試在未使用的工作階段逾時時時執行作用中作業

