---
permalink: sm-settings/save-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, save, storage array, configuration, 
summary: 您可以將儲存陣列的組態資訊儲存在指令碼檔案中、以節省設定相同組態的其他儲存陣列所需的時間。 
---
= 儲存儲存陣列組態
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將儲存陣列的組態資訊儲存在指令碼檔案中、以節省使用相同組態設定其他儲存陣列的時間。

儲存陣列不得執行任何變更其邏輯組態設定的作業。這些作業的範例包括建立或刪除磁碟區、下載控制器韌體、指派或修改熱備援磁碟機、或將容量（磁碟機）新增至磁碟區群組。

儲存儲存陣列組態會產生命令列介面（CLI）指令碼、其中包含儲存陣列的儲存陣列設定、磁碟區組態、主機組態或主機對磁碟區指派。您可以使用此產生的CLI指令碼、將組態複寫到具有完全相同硬體組態的另一個儲存陣列。

但是、您不應該使用此產生的CLI指令碼來進行災難恢復。若要進行系統還原、請改用手動建立的組態資料庫備份檔案、或聯絡技術支援部門、從最新的「自動支援」資料取得此資料。

此作業_不會儲存下列設定：

* 電池壽命
* 控制器每日時間
* 非揮發性靜態隨機存取記憶體（NVSRAM）設定
* 任何優質功能
* 儲存陣列密碼
* 硬體元件的作業狀態和狀態
* Volume群組的作業狀態（最佳）和狀態除外
* 複製服務、例如鏡射和Volume複製


[CAUTION]
====
*應用程式錯誤的風險*-如果儲存陣列正在執行會變更任何邏輯組態設定的作業、請勿使用此選項。這些作業的範例包括建立或刪除磁碟區、下載控制器韌體、指派或修改熱備援磁碟機、或將容量（磁碟機）新增至磁碟區群組。

====
.步驟
. 選取功能表：設定[系統]。
. 選擇*儲存儲存陣列組態*。
. 選取您要儲存的組態項目：
+
** 儲存陣列設定
** Volume組態
** 主機組態
** 主機對磁碟區指派


+
[NOTE]
====
如果選擇*主機到磁碟區指派*項目、則預設也會選取*磁碟區組態*項目和*主機組態*項目。您必須儲存「Volume組態」和「主機組態」、才能儲存「主機對Volume指派」。

====
. 按一下「 * 儲存 * 」。
+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「shorage-array-configuration．cfg」。



若要將儲存的儲存陣列組態載入其他儲存陣列、請使用SANtricity 含有「-f」選項的指令行介面（SMcli）來套用「.cfg」檔案。

[NOTE]
====
您也可以使用Unified Manager介面將儲存陣列組態載入其他儲存陣列（選取功能表：「Manage（匯入設定）」）。

====