---
permalink: sm-settings/unlock-drives-using-an-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, drives, internal, key, management, 
summary: 如果您已設定內部金鑰管理、之後再將啟用安全功能的磁碟機從一個儲存陣列移至另一個儲存陣列、則必須重新指派安全金鑰給新的儲存陣列、才能存取磁碟機上的加密資料。 
---
= 使用內部金鑰管理時解除磁碟機鎖定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您已設定內部金鑰管理、之後再將啟用安全功能的磁碟機從一個儲存陣列移至另一個儲存陣列、則必須重新指派安全金鑰給新的儲存陣列、才能存取磁碟機上的加密資料。

.開始之前
* 在來源陣列（您要移除磁碟機的陣列）上、您已匯出磁碟區群組並移除磁碟機。在目標陣列上、您已重新安裝磁碟機。
+

NOTE: System Manager使用者介面不支援匯出/匯入功能；您必須使用命令列介面（CLI）將磁碟區群組匯出/匯入至不同的儲存陣列。

+
如需移轉Volume群組的詳細指示、請參閱 https://kb.netapp.com/["NetApp知識庫"^]。請務必遵循適當的指示、以處理由System Manager管理的較新陣列或舊系統。

* 必須啟用磁碟機安全功能。否則、在此工作期間會開啟「無法建立安全金鑰」對話方塊。如有必要、請聯絡您的儲存設備廠商、以取得啟用磁碟機安全功能的指示。
* 您必須知道要解除鎖定之磁碟機的相關安全性金鑰。
* 安全金鑰檔案可在管理用戶端上使用（使用瀏覽器存取System Manager的系統）。如果您要將磁碟機移至由不同系統管理的儲存陣列、則必須將安全金鑰檔案移至該管理用戶端。


.關於這項工作
使用內部金鑰管理時、安全金鑰會儲存在本機儲存陣列上。安全金鑰是控制器和磁碟機共用的字元字串、用於讀取/寫入存取。當磁碟機從陣列中實際移除並安裝在另一個陣列中時、除非您提供正確的安全金鑰、否則這些磁碟機將無法運作。

[NOTE]
====
您可以從控制器的持續記憶體建立內部金鑰、或從金鑰管理伺服器建立外部金鑰。本主題說明使用_internal金鑰管理時的資料解除鎖定。如果您使用_extERE_金鑰管理、請參閱 link:unlock-drives-using-an-external-security-key.html["使用外部金鑰管理時解除鎖定磁碟機"]。如果您正在執行控制器升級、並要將所有控制器交換為最新硬體、則必須依照SANtricity 中的E系列與更新文件中心所述的不同步驟進行 link:https://docs.netapp.com/us-en/e-series/upgrade-controllers/upgrade-unlock-drives-task.html["解除磁碟機鎖定"]。

====
在另一個陣列中重新安裝啟用安全功能的磁碟機後、該陣列會探索磁碟機、並顯示「Needs Attention（需要注意）」狀態、以及「Security Key Needs（需要安全金鑰）」狀態。 若要解除鎖定磁碟機資料、請選取安全金鑰檔案、然後輸入金鑰的密碼。（此密碼與儲存陣列的管理員密碼不同。）

如果新儲存陣列中安裝了其他已啟用安全功能的磁碟機、它們可能會使用與您匯入磁碟機不同的安全金鑰。在匯入程序期間、舊的安全金鑰僅用於解除鎖定您要安裝之磁碟機的資料。當解除鎖定程序成功時、新安裝的磁碟機會重新鎖定至目標儲存陣列的安全金鑰。

.步驟
. 選取功能表：設定[系統]。
. 在*安全金鑰管理*下、選取*解除鎖定安全磁碟機*。
+
「解除鎖定安全磁碟機」對話方塊隨即開啟。任何需要安全金鑰的磁碟機都會顯示在表格中。

. *選用：*將滑鼠游標移到磁碟機編號上、即可查看磁碟機的位置（機櫃編號和機櫃編號）。
. 按一下*瀏覽*、然後選取與您要解除鎖定磁碟機對應的安全金鑰檔案。
+
您選取的金鑰檔會出現在對話方塊中。

. 輸入與此金鑰檔相關的密碼。
+
您輸入的字元會被遮罩。

. 按一下*解除鎖定*。
+
如果解除鎖定作業成功、對話方塊會顯示：「相關的安全磁碟機已解除鎖定。」



.結果
當所有磁碟機都已鎖定、然後解除鎖定時、儲存陣列中的每個控制器都會重新開機。但是、如果目標儲存陣列中已有未鎖定的磁碟機、則控制器將不會重新開機。

.完成後
在目的地陣列（新安裝磁碟機的陣列）上、您現在可以匯入磁碟區群組。


NOTE: System Manager使用者介面不支援匯出/匯入功能；您必須使用命令列介面（CLI）將磁碟區群組匯出/匯入至不同的儲存陣列。

如需移轉Volume群組的詳細指示、請參閱 https://kb.netapp.com/["NetApp知識庫"^]。
