---
permalink: sm-settings/view-iscsi-sessions-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iscsi, sessions, 
summary: 您可以檢視iSCSI與儲存陣列連線的詳細資訊。在非同步鏡射關係中、主機或遠端儲存陣列可能會發生iSCSI工作階段。 
---
= 在 SANtricity System Manager 中查看 iSCSI 會話
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視iSCSI與儲存陣列連線的詳細資訊。在非同步鏡射關係中、主機或遠端儲存陣列可能會發生iSCSI工作階段。

.步驟
. 選取功能表：設定[系統]。
. 選取*檢視/結束iSCSI工作階段*。
+
此時會顯示目前iSCSI工作階段的清單。

. *選用：*若要查看特定iSCSI工作階段的其他資訊、請選取工作階段、然後按一下*檢視詳細資料*。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 項目 | 說明 


 a| 
工作階段識別碼（SSID）
 a| 
用於識別iSCSI啟動器與iSCSI目標之間工作階段的十六進位字串。SSID由ISID和TPGT組成。



 a| 
啟動器工作階段ID（ISID）
 a| 
工作階段識別碼的啟動器部分。啟動器會在登入期間指定ISID。



 a| 
目標入口網站群組
 a| 
iSCSI目標。



 a| 
目標入口網站群組標籤（TPGT）
 a| 
工作階段識別碼的目標部分。iSCSI目標入口網站群組的16位元數字識別碼。



 a| 
啟動器iSCSI名稱
 a| 
啟動器的全球唯一名稱。



 a| 
啟動器iSCSI標籤
 a| 
在System Manager中設定的使用者標籤。



 a| 
啟動器iSCSI別名
 a| 
也可與iSCSI節點相關聯的名稱。別名可讓組織將使用者友好字串與iSCSI名稱建立關聯。不過、別名並不能取代iSCSI名稱。啟動器iSCSI別名只能在主機上設定、不能在系統管理員中設定



 a| 
主機
 a| 
將輸入和輸出傳送至儲存陣列的伺服器。



 a| 
連線ID（CID）
 a| 
啟動器與目標之間工作階段內連線的唯一名稱。啟動器會產生此ID、並在登入要求期間將其呈現給目標。連線ID也會在登出時顯示、以關閉連線。



 a| 
連接埠識別碼
 a| 
與連線相關聯的控制器連接埠。



 a| 
啟動器IP位址
 a| 
啟動器的IP位址。



 a| 
協調登入參數
 a| 
在iSCSI工作階段登入期間所處理的參數。



 a| 
驗證方法
 a| 
驗證想要存取iSCSI網路之使用者的技術。有效值為* CHAP*和*無*。



 a| 
標頭摘要方法
 a| 
顯示iSCSI工作階段可能標頭值的技術。「標題摘要」和「資料摘要」可以是*「無」*或*「CRC32C*」。兩者的預設值為*無*。



 a| 
資料摘要方法
 a| 
顯示iSCSI工作階段可能資料值的技術。「標題摘要」和「資料摘要」可以是*「無」*或*「CRC32C*」。兩者的預設值為*無*。



 a| 
最大連線數
 a| 
iSCSI工作階段所允許的最大連線數。最多可有1到4個連線。預設值為* 1*。



 a| 
目標別名
 a| 
與目標相關的標籤。



 a| 
啟動器別名
 a| 
與啟動器相關的標籤。



 a| 
目標IP位址
 a| 
iSCSI工作階段目標的IP位址。不支援DNS名稱。



 a| 
初始R2T
 a| 
初始「準備傳輸」狀態。狀態可以是*是*或*否*。



 a| 
最大突發長度
 a| 
此iSCSI工作階段的最大SCSI有效負載（以位元組為單位）。最大突發長度可介於512至262,144（256 KB）之間。預設值為* 262,144（256 KB）*。



 a| 
第一次爆發長度
 a| 
此iSCSI工作階段的非主動式資料SCSI有效負載（以位元組為單位）。第一個脈衝長度可介於512至131,072（128 KB）之間。預設值為* 65536（64 KB）*。



 a| 
預設等待時間
 a| 
在連線終止或連線重設後、嘗試連線之前所需等待的最小秒數。預設的等待時間值可介於0到3、600之間。預設值為* 2 *。



 a| 
預設保留時間
 a| 
連線終止或連線重設後仍可進行連線的最大秒數。保留的預設時間可介於0到3、600之間。預設值為* 20*。



 a| 
最大未處理R2T
 a| 
此iSCSI工作階段未處理的「準備傳輸」上限。最大未處理準備傳輸值可為1至16。預設值為* 1*。



 a| 
錯誤恢復層級
 a| 
此iSCSI工作階段的錯誤恢復層級。錯誤恢復層級值永遠設定為* 0*。



 a| 
最大接收資料區段長度
 a| 
啟動器或目標可在任何iSCSI有效負載資料單元（PDU）中接收的資料量上限。



 a| 
目標名稱
 a| 
目標的正式名稱（非別名）。以_iqn_格式的目標名稱。



 a| 
啟動器名稱
 a| 
啟動器的正式名稱（非別名）。使用_iqn_或_EUI_格式的啟動器名稱。

|===
====
. *選用：*若要將報告儲存至檔案、請按一下*儲存*。
+
檔案會以「iscso-site-connections．txt」檔案名稱儲存在瀏覽器的「Downloads（下載）」資料夾中。


