---
permalink: sm-settings/what-is-cache-flushing.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, flushing, 
summary: 當快取中的未寫入資料量達到特定層級時、控制器會定期將快取資料寫入磁碟機。此寫入程序稱為「排清」。 
---
= 什麼是快取排清？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當快取中的未寫入資料量達到特定層級時、控制器會定期將快取資料寫入磁碟機。此寫入程序稱為「排清」。

控制器使用兩種演算法來排清快取：需求型與年齡型。控制器使用需求型演算法、直到快取資料量降至快取清除臨界值以下為止。根據預設、當80%的快取正在使用時、就會開始排清。

在System Manager中、您可以設定「開始需求快取排清」臨界值、以最佳方式支援環境中使用的I/O類型。在主要是寫入作業的環境中、您應該將「開始需求快取排清」百分比設定為高、以增加快取處理任何新寫入要求的可能性、而不需要移至磁碟。高百分比的設定會限制快取的清除次數、使快取中保留更多資料、進而增加快取命中次數的機率。

在I/O不穩定的環境中（使用資料突發）、您可以使用低快取排清功能、讓系統在資料突發之間頻繁排清快取。在處理各種負載的多元I/O環境中、或是當負載類型不明時、將臨界值設為良好的中間接地、設定為50%。請注意、如果您選擇低於80%的開始百分比、可能會看到效能降低、因為讀取主機所需的資料可能無法使用。選擇較低的百分比也會增加維護快取層級所需的磁碟寫入次數、進而增加系統負荷。

根據年齡的演算法會指定寫入資料在符合排清至磁碟資格之前、保留在快取中的時間段。控制器會使用根據年齡的演算法、直到快取齊面臨界值達到為止。預設值為10秒、但此時間段僅會在閒置期間計算。您無法在System Manager中修改排清時間、而是必須在命令列介面（CLI）中使用*設定儲存陣列*命令。

[CAUTION]
====
*可能的資料遺失*-如果您啟用*無電池寫入快取*選項、而且沒有通用電源供應器來保護資料、您可能會遺失資料。此外、如果您沒有控制器電池、並且啟用*無電池寫入快取*選項、則可能會遺失資料。

====