---
permalink: sm-support/activate-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, activate, controller, software, firmware 
summary: 您可以選擇立即啟動升級檔案、或等到更方便的時間再啟動。 
---
= 在 SANtricity System Manager 中啟動控制器軟體和韌體
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以選擇立即啟動升級檔案、或等到更方便的時間再啟動。

.關於這項工作
您可以下載及傳輸檔案、而不需啟動檔案。您可以選擇稍後啟動、原因如下：

* *每天的時間*-啟動軟體和韌體可能需要很長的時間、因此您可能需要等待I/O負載變輕。控制器會在啟動期間容錯移轉、因此在升級完成之前、效能可能會比平常低。
* *套件類型*：在升級其他儲存陣列上的檔案之前、您可能需要在一個儲存陣列上測試新的軟體和韌體。


如果您的軟體或韌體已傳輸但尚未啟動、您會在System Manager首頁的「通知」區域和「升級中心」頁面上看到通知。

[CAUTION]
====
啟動程序之後、您無法停止啟動程序。

====
.步驟
. 選取功能表：Support[升級中心]。
. 在標示SANtricity 為「SweXOS控制器軟體升級」的區域中、按一下「*啟動*」、然後確認您要執行此作業。
+
您可以在升級前狀況檢查期間取消作業、但在啟動期間無法取消。

+
升級前的健全狀況檢查隨即開始。如果升級前的健全狀況檢查通過、升級程序會繼續啟動檔案。如果升級前的狀況檢查失敗、請使用Recovery Guru或聯絡技術支援部門來解決問題。對於某些類型的情況、「技術支援」可能會建議您選取「*允許升級*」核取方塊、儘管有錯誤、仍繼續升級。

+
成功完成升級前的健全狀況檢查後、就會啟動。啟動所需的時間取決於儲存陣列組態和您要啟動的元件。

. *選用：*若要查看已升級項目的清單、請按一下*儲存記錄*。
+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「drive_升級_log-timestamp.txt"。



.完成後
* 確認所有元件都顯示在「硬體」頁面上。
* 核取「軟體與韌體庫存」對話方塊（前往功能表：「Support[升級中心]」、然後按一下「*軟體與韌體庫存*」連結）、以驗證新的軟體與韌體版本。
* 如果您升級控制器的NVSRAM,則在啟動程序期間會遺失任何已套用至現有的NVSRAM/R的自訂設定。啟動程序完成後、您需要再次將自訂設定套用至NVSRAM.

