---
permalink: sm-support/faq-autosupport.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= SANtricity System Manager 的 AutoSupport 常見問題解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 我要收集哪些資料？

「支援資料收集」功能和手冊可讓您在客戶支援套裝組合中收集資料、以便技術支援人員進行遠端疑難排解和問題分析。AutoSupport

客戶支援服務組合會將儲存陣列的所有類型資訊收集到單一壓縮檔案中。收集的資訊包括實體組態、邏輯組態、版本資訊、事件、記錄檔、 和效能資料。此資訊僅供技術支援人員用來解決儲存陣列的問題。



== 無法讀取的區段資料會顯示什麼？

您可以顯示儲存陣列磁碟機上偵測到無法讀取磁區的詳細資料。

不可讀取的磁區記錄會先顯示最近無法讀取的磁區。記錄包含下列有關含有不可讀取磁區的磁碟區資訊。欄位可排序。

[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
受影響的Volume
 a| 
顯示Volume的標籤。如果遺失的磁碟區包含無法讀取的磁碟區、則會顯示遺失磁碟區的全球識別碼。



 a| 
邏輯單元編號（LUN）
 a| 
顯示磁碟區的LUN。如果磁碟區沒有LUN、對話方塊會顯示NA。



 a| 
指派給
 a| 
顯示可存取磁碟區的主機或主機叢集。如果主機、主機叢集、甚至是預設叢集無法存取磁碟區、則對話方塊會顯示NA。

|===
若要查看有關不可讀取磁區的其他資訊、請按一下磁碟區旁的加號（+）。

[cols="25h,~"]
|===
| 欄位 | 說明 


 a| 
日期/時間
 a| 
顯示偵測到無法讀取的磁區的日期和時間。



 a| 
Volume邏輯區塊位址
 a| 
顯示磁碟區的邏輯區塊位址（LBA）。



 a| 
磁碟機位置
 a| 
顯示磁碟機櫃、抽屜（如果磁碟機櫃有抽屜）和機櫃位置。



 a| 
磁碟機邏輯區塊位址
 a| 
顯示磁碟機的LBA。



 a| 
故障類型
 a| 
顯示下列其中一種故障類型：

* *實體*-實體媒體錯誤。
* *邏輯*：等量磁碟區中其他位置的讀取錯誤、導致無法讀取的資料。例如、由於磁碟區中其他位置的媒體錯誤而導致無法讀取的磁碟區。
* *不一致*：不一致的備援資料。
* *資料保證*-資料保證錯誤。


|===


== 什麼是健全狀況映像？

健全狀況映像是控制器處理器記憶體的原始資料傾印、技術支援可用來診斷控制器的問題。

韌體偵測到特定錯誤時、會自動產生健全狀況映像。在某些疑難排解案例中、技術支援人員可能會要求您擷取健全狀況映像檔並將其傳送給他們。



== 這個功能有什麼AutoSupport 作用？

此功能由三項個別功能組成、AutoSupport 您可以分別啟用。

* *基本AutoSupport 版S還原*：可讓儲存陣列自動收集資料、並將資料傳送給技術支援部門。
* * AutoSupport 《支援需求*》-可讓技術支援部門在AutoSupport 需要時要求重新傳輸先前的故障排除資訊。所有傳輸都是從儲存陣列啟動、而非AutoSupport 從伺服器啟動。儲存陣列會定期與AutoSupport VMware伺服器一起檢查、以判斷是否有任何擱置中的重新傳輸要求、並據此做出回應。
* *遠端診斷*-可讓技術支援部門在AutoSupport 疑難排解問題時、要求提供最新的更新版的支援。所有傳輸都是從儲存陣列啟動、而非AutoSupport 從伺服器啟動。儲存陣列會定期與AutoSupport VMware伺服器一起檢查、以判斷是否有任何擱置中的新要求、並據此做出回應。




== 透過此功能收集哪種類型的資料AutoSupport ？

此功能包含三種標準派單類型：事件派單、排程派單、隨選及遠端診斷派單。AutoSupport

不含任何使用者資料。AutoSupport

* *事件派單*
+
當系統發生事件、需要主動通知技術支援人員時AutoSupport 、此功能會自動傳送事件觸發的派遣。

+
** 受管理儲存陣列發生支援事件時傳送。
** 包括事件發生時儲存陣列的完整現況快照。


* *定期派單*
+
此功能會定期自動傳送多份分派文件。AutoSupport

+
** *每日派單*-在使用者可設定的時間間隔內、每天傳送一次。包括目前的系統事件記錄和效能資料。
** *每週派單*-在使用者可自行設定的時間間隔和日期內、每週傳送一次。包括組態和系統狀態資訊。


* * AutoSupport 《隨需與遠端診斷》派單*
+
** * AutoSupport 《支援需求*》-可讓技術支援部門在AutoSupport 需要時要求重新傳輸先前的故障排除資訊。所有傳輸都是從儲存陣列啟動、而非AutoSupport 從伺服器啟動。儲存陣列會定期與AutoSupport VMware伺服器一起檢查、以判斷是否有任何擱置中的重新傳輸要求、並據此做出回應。
** *遠端診斷*-可讓技術支援部門在AutoSupport 疑難排解問題時、要求提供最新的更新版的支援。所有傳輸都是從儲存陣列啟動、而非AutoSupport 從伺服器啟動。儲存陣列會定期與AutoSupport VMware伺服器一起檢查、以判斷是否有任何擱置中的新要求、並據此做出回應。






== 我要如何設定AutoSupport 供應方法以使用「不知道」功能？

AutoSupport 功能支援 HTTPS 和 SMTP 通訊協定，可將 AutoSupport 派遣單傳送給技術支援。

.開始之前
* 必須啟用此功能。AutoSupport您可以在AutoSupport 「介紹」頁面上查看是否已啟用此功能。
* 必須在網路中安裝和設定DNS伺服器。DNS伺服器位址必須在系統管理員中設定（此工作可從「硬體」頁面取得）。


.關於這項工作
檢閱不同的傳輸協定：

* * HTTPS *：可讓您使用HTTPS直接連線至目的地技術支援伺服器。如果您要啟用AutoSupport 「僅供支援的更新」或「遠端診斷」、AutoSupport 則必須將「提供支援的方法」設為HTTPS。
* *電子郵件*：可讓您使用電子郵件伺服器作為傳送AutoSupport 功能來傳送非功能性派單。


[NOTE]
====
HTTPS 和電子郵件方法之間的差異 * 。使用 SMTP 的電子郵件傳送方法與 HTTPS 傳送方法有一些重要差異。首先、「電子郵件」方法的派單大小限制為5MB、這表示部分ASUP資料收集將不會派送。其次， AutoSupport 隨選功能僅適用於 HTTPS 交付方法。

====
.步驟
. 選取功能表：Support（支援）[Support Center（支援中心）> AutoSupport SESS]索引標籤。
. 選擇*設定AutoSupport 「供應方法」*。
+
此時會出現一個對話方塊、列出分派交付方法。

. 選取所需的交付方法、然後選取該交付方法的參數。執行下列其中一項：
+
** 如果您選取 HTTPS ，請選取下列其中一個傳送參數：
+
*** *直接*-此交付參數為預設選項。選擇此選項可讓您使用 HTTPS 通訊協定直接連線到目的地技術支援系統。
*** *透過Proxy伺服器*-選擇此選項可讓您指定與目的地技術支援系統建立連線所需的HTTP Proxy伺服器詳細資料。您必須指定主機位址和連接埠號碼。不過、您只需在必要時輸入主機驗證詳細資料（使用者名稱和密碼）。
*** *透過Proxy自動組態指令碼（PAC）*-指定Proxy自動組態（PAC）指令碼檔案的位置。PAC檔案可讓系統自動選擇適當的Proxy伺服器、以建立與目的地技術支援系統的連線。


** 如果您選取電子郵件、請輸入下列資訊：
+
*** 郵件伺服器位址是完整網域名稱、IPv4位址或IPv6位址。
*** 出現在AutoSupport 「來源」欄位的電子郵件地址。
*** *選用；如果您要執行組態測試。* AutoSupport 當系統收到測試派單時、會傳送確認訊息的電子郵件地址。
*** 如果您要加密訊息、請選取* SMTP*或* STARTTLS*作為加密類型、然後選取加密訊息的連接埠號碼。否則、請選取*無*。
*** 如有需要、請輸入使用者名稱和密碼、以便與傳出寄件者和郵件伺服器進行驗證。




. 按一下*測試組態*、使用指定的交付參數測試技術支援伺服器的連線。如果您啟用AutoSupport 「根據需求提供支援」功能、系統也會測試連線AutoSupport 功能、以利提供「根據需求提供支援」。
+
如果組態測試失敗、請檢查組態設定、然後再次執行測試。如果測試持續失敗、請聯絡技術支援部門。

. 按一下「 * 儲存 * 」。




== 什麼是組態資料？

選取「收集組態資料」時、系統會儲存RAID組態資料庫的目前狀態。

RAID組態資料庫包含控制器上磁碟區群組和磁碟集區的所有資料。「收集組態資料」功能會將與CLI命令相同的資訊儲存在「儲存陣列dbmDatabase」中。



== 升級SANtricity 完《不知如何」的《不知如何？

在升級控制器的軟體和韌體之前、請注意以下事項。

* 您已閱讀文件和「readme.txt"檔案、並決定要進行升級。
* 您知道是否要升級IOM韌體。
+
一般而言、您應該同時升級所有元件。不過、如果您不想將IOM韌體升級為SANtricity 更新版的一部分、或是技術支援部門指示您降級IOM韌體（您只能使用命令列介面來降級韌體）、您可能會決定不升級IOM韌體。

* 您知道是否要升級控制器的NVSRAM.
+
一般而言、您應該同時升級所有元件。不過、如果您的檔案已修補或是自訂版本、而且您不想覆寫、您可能會決定不升級控制器的NVSRAM/檔案。

* 您知道現在或之後要啟動。
+
日後啟用的理由可能包括：

+
** *每天的時間*-啟動軟體和韌體可能需要很長的時間、因此您可能需要等待I/O負載變輕。控制器會在啟動期間容錯移轉、因此在升級完成之前、效能可能會比平常低。
** *套件類型*：在升級其他儲存陣列上的檔案之前、您可能需要在一個儲存陣列上測試新的軟體和韌體。




這些元件是SANtricity 更新版作業系統控制器軟體的一部分：

* *管理軟體*- System Manager是管理儲存陣列的軟體。
* *控制器韌體*-控制器韌體可管理主機與磁碟區之間的I/O。
* *控制器NVSRAM*-控制器NVSRAM-是控制器檔案、可指定控制器的預設設定。
* * IOM韌體*- I/O模組（IOM）韌體可管理控制器與磁碟機櫃之間的連線。它也會監控元件的狀態。
* *監控軟體*-監控軟體是軟體執行所在控制器上的虛擬機器。


在升級過程中、主機的多重路徑/容錯移轉驅動程式和（或）HBA驅動程式可能也需要升級、以便主機能夠正確與控制器互動。

[NOTE]
====
若要判斷是否為這種情況、請參閱 https://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^]。

====
如果您的儲存陣列只包含一個控制器、或您沒有安裝多重路徑驅動程式、請停止儲存陣列的I/O活動、以避免應用程式錯誤。如果您的儲存陣列有兩個控制器、而且安裝了多重路徑驅動程式、則不需要停止I/O活動。


CAUTION: 升級時請勿變更儲存陣列。



== 在暫停IOM自動同步之前、我需要知道什麼？

暫停IOM自動同步可防止IOM韌體在下次SANtricity 進行更新時升級、

控制器軟體和IOM韌體通常會以套裝組合形式升級。如果您有想保留在機箱上的特殊IOM韌體版本、可以暫停IOM自動同步。否則、下次進行控制器軟體升級時、您將會回復到控制器軟體隨附的IOM韌體。



== 我的韌體升級為什麼進展緩慢？

韌體升級進度取決於系統的整體負載。

在線上升級磁碟機韌體期間、如果在快速重建程序期間進行磁碟區傳輸、系統會對傳輸的磁碟區進行完整重建。這項作業可能需要相當長的時間。實際的完整重建時間取決於多個因素、包括重建作業期間發生的I/O活動量、磁碟區群組中的磁碟機數量、重建優先順序設定、以及磁碟機效能。



== 升級磁碟機韌體之前、我需要知道什麼？

在升級磁碟機韌體之前、請注意以下事項。

* 為了預防、請使用磁碟對磁碟備份、磁碟區複製（至不受規劃韌體升級影響的磁碟區群組）或遠端鏡像來備份資料。
* 您可能只想升級幾個磁碟機、以測試新韌體的行為、確保其正常運作。如果新韌體正常運作、請升級其餘磁碟機。
* 如果您有任何故障磁碟機、請在開始韌體升級之前予以修正。
* 如果磁碟機可以進行離線升級、請停止與磁碟機相關聯的所有磁碟區的I/O活動。當I/O活動停止時、就不會發生與這些磁碟區相關的組態作業。
* 升級磁碟機韌體時、請勿移除任何磁碟機。
* 升級磁碟機韌體時、請勿對儲存陣列進行任何組態變更。




== 如何選擇要執行的升級類型？

您可以根據集區或Volume群組的狀態、選擇要在磁碟機上執行的升級類型。

* *線上*
+
如果集區或磁碟區群組支援備援且為最佳、您可以使用「線上」方法來升級磁碟機韌體。當儲存陣列使用這些磁碟機處理I/O時、線上方法會下載韌體_到相關的磁碟區。您不需要使用這些磁碟機來停止相關磁碟區的I/O。這些磁碟機一次升級為與磁碟機相關的磁碟區。如果磁碟機未指派給資源池或磁碟區群組、則可透過「線上」或「離線」方法來更新其韌體。使用線上方法升級磁碟機韌體時、系統效能可能會受到影響。

* *離線*
+
如果集區或磁碟區群組不支援備援（RAID 0）或降級、則您必須使用離線方法來升級磁碟機韌體。只有當所有I/O活動都停止時、「離線」方法才會將韌體升級至使用這些磁碟機的相關磁碟區。您必須使用這些磁碟機來停止所有與任何相關磁碟區的I/O。如果磁碟機未指派給資源池或磁碟區群組、則其韌體可透過「線上」或「離線」方法進行更新。


