---
permalink: sm-support/review-the-possible-software-and-firmware-upgrade-errors.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, software, firmware, upgrade, errors 
summary: 控制器軟體升級或磁碟機韌體升級期間可能發生錯誤。 
---
= 檢閱可能的軟體和韌體升級錯誤
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
控制器軟體升級或磁碟機韌體升級期間可能發生錯誤。

[cols="25h,~,~"]
|===
| 韌體下載錯誤 | 說明 | 建議採取的行動 


 a| 
指派的磁碟機故障
 a| 
無法升級儲存陣列中指派的磁碟機。
 a| 
故障的原因之一可能是磁碟機沒有適當的簽名。確定受影響的磁碟機是授權的磁碟機。如需詳細資訊、請聯絡技術支援部門。

更換磁碟機時、請確定更換磁碟機的容量等於或大於您要更換的故障磁碟機。

您可以在儲存陣列接收I/O時更換故障磁碟機



 a| 
整合式熱備援磁碟機
 a| 
如果磁碟機標示為熱備援磁碟機、且正在用於磁碟區群組、則韌體升級程序將會失敗。
 a| 
您必須先修正此錯誤狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
不完整的Volume群組
 a| 
如果某個磁碟區群組中的任何磁碟機被略過、移除或無回應、則該磁碟機視為不完整的磁碟區群組。不完整的Volume群組會阻止韌體升級。
 a| 
如果一個或多個Volume群組或磁碟集區不完整、您必須先修正此錯誤狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
目前在任何Volume群組上執行的排他性作業（背景媒體/同位元檢查除外）
 a| 
如果磁碟區上正在進行任何獨家作業、則無法升級韌體。
 a| 
如果正在進行一或多個專屬作業、則必須先完成作業、才能升級韌體。使用System Manager來監控作業進度。



 a| 
遺失磁碟區
 a| 
如果有任何磁碟區遺失、則無法升級韌體。
 a| 
您必須先修正遺失的磁碟區狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
任一控制器處於非最佳狀態
 a| 
如果任一控制器處於非最佳狀態、則無法升級韌體。
 a| 
其中一個儲存陣列控制器需要注意。必須先修正此狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
SPM驗證資料庫控制器檢查失敗
 a| 
無法升級韌體、因為儲存分割對應資料庫毀損。
 a| 
控制器上發生儲存分割區對應資料庫錯誤。請聯絡技術支援部門以解決此問題。



 a| 
組態資料庫驗證（如果儲存陣列的控制器版本支援）
 a| 
無法升級韌體、因為組態資料庫毀損。
 a| 
控制器上發生組態資料庫錯誤。請聯絡技術支援部門以解決此問題。



 a| 
MEL相關檢查
 a| 
無法升級韌體、因為事件記錄包含錯誤。
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內報告了超過10個「DDE資訊」或「重大MEL」事件
 a| 
無法升級韌體、因為過去七天內報告的DDE資訊或重要MEL事件超過10個。
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內報告超過2頁2C重大MEL事件
 a| 
無法升級韌體、因為過去七天報告超過兩頁2C重大MEL事件。
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內報告超過2個降級的磁碟機通道嚴重MEL事件
 a| 
無法升級韌體、因為過去七天報告超過兩個降級磁碟機通道關鍵MEL事件。
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內有4個以上的重要MEL項目
 a| 
無法升級韌體、因為過去七天報告的重大事件記錄項目超過四個。
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
需要有效的管理IP位址。
 a| 
執行此作業需要有效的控制器IP位址。
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
此命令需要提供每個控制器的作用中管理IP位址。
 a| 
此作業需要每個與儲存陣列相關的控制器IP位址。
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
傳回未處理的下載檔案類型。
 a| 
不支援指定的下載檔案。
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
韌體下載上傳程序期間發生錯誤。
 a| 
韌體下載失敗、因為控制器無法處理要求。確認儲存陣列處於最佳狀態、然後重試此作業。
 a| 
如果在驗證儲存陣列是否為最佳狀態之後再次發生此錯誤、請聯絡技術支援部門以解決此問題。



 a| 
韌體啟動程序期間發生錯誤。
 a| 
韌體啟動失敗、因為控制器無法處理要求。確認儲存陣列處於最佳狀態、然後重試此作業。
 a| 
如果在驗證儲存陣列是否為最佳狀態之後再次發生此錯誤、請聯絡技術支援部門以解決此問題。



 a| 
等待控制器\｛0｝重新開機時已達逾時時間。
 a| 
重新開機後、管理軟體無法重新連線至控制器\｛0｝。驗證儲存陣列是否有運作中的連線路徑、如果作業未成功完成、請重試該作業。
 a| 
如果在驗證儲存陣列是否為最佳狀態之後再次發生此錯誤、請聯絡技術支援部門以解決此問題。

|===
您可以使用System Manager中的Recovery Guru來修正這些狀況。不過、在某些情況下、您可能需要聯絡技術支援部門。您可從儲存陣列取得最新的控制器韌體下載資訊。此資訊可協助技術支援人員瞭解妨礙韌體升級與下載的錯誤情況。
