---
permalink: sm-support/upgrade-drive-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, drive, firmware 
summary: 您可以升級磁碟機的韌體、以確保擁有所有最新的功能和錯誤修復。 
---
= 在 SANtricity System Manager 中升級磁碟機韌體
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升級磁碟機韌體、以確保擁有所有最新的功能和錯誤修復。

.開始之前
* 您已使用磁碟對磁碟備份、磁碟區複製（至不受規劃韌體升級影響的磁碟區群組）或遠端鏡像來備份資料。
* 儲存陣列的狀態為「最佳」。
* 所有磁碟機均處於最佳狀態。
* 儲存陣列上未執行任何組態變更。
* 如果磁碟機只能進行離線升級、則會停止與磁碟機相關聯之所有磁碟區的I/O活動。


.步驟
. 選取功能表：Support[升級中心]。
. 將新檔案從Support網站下載到您的管理用戶端。
. 在「磁碟機韌體升級」下、按一下「*開始升級*」。
+
此時會出現一個對話方塊、列出目前使用中的磁碟機韌體檔案。

. 從Support網站擷取（解壓縮）您下載的檔案。
. 按一下*瀏覽*、然後選取您從Support網站下載的新磁碟機韌體檔案。
+
磁碟機韌體檔案的檔名類似於「D_HUC101212CSS600_3060291_MS01_2800_0002」、副檔名為「.edp」。

+
您最多可以選取四個磁碟機韌體檔案、一次一個。如果多個磁碟機韌體檔案與同一個磁碟機相容、您會收到檔案衝突錯誤。決定要用於升級的磁碟機韌體檔案、然後移除另一個。

. 單擊 * 下一步 * 。
+
此時將出現* Select Drives*（選擇驅動器*）對話框，其中列出了您可以使用選定文件進行升級的驅動器。

+
僅顯示相容的磁碟機。

+
所選的磁碟機韌體會顯示在「提議的韌體資訊」區域中。如果您必須變更韌體、請按一下*上一頁*以返回上一對話方塊。

. 選取您要執行的升級類型：
+
** *線上（預設）*-顯示儲存陣列正在處理I/O時、可支援韌體下載的磁碟機。選取此升級方法時、您不需要使用這些磁碟機來停止相關磁碟區的I/O。這些磁碟機會在儲存陣列處理這些磁碟機的I/O時、一次升級一個。
** *離線（平行）*-顯示在使用磁碟機的任何磁碟區上、只有當所有I/O活動都停止時、才能支援韌體下載的磁碟機。選取此升級方法時、您必須停止使用要升級磁碟機的任何磁碟區上的所有I/O活動。沒有備援的磁碟機必須以離線作業的形式處理。此需求包括與SSD快取、RAID 0磁碟區群組或任何降級的資源池或磁碟區群組相關的任何磁碟機。離線（平行）升級通常比線上（預設）方法更快。


. 在表格的第一欄中、選取您要升級的磁碟機。
. 按一下* Start*（開始*）、然後確認您要執行此作業。
+
如果您需要停止升級、請按一下*停止*。目前正在進行的任何韌體下載均已完成。任何尚未開始的韌體下載都會取消。

+
[CAUTION]
====
停止磁碟機韌體升級可能會導致資料遺失或磁碟機無法使用。

====
. *選用：*若要查看已升級項目的清單、請按一下*儲存記錄*。
+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「drive_升級_log-timestamp.txt"。

. 如果在升級程序期間發生下列任何錯誤、請採取適當的建議行動。


.錯誤和建議的行動
[%collapsible]
====
[cols="40h,~"]
|===
| 如果您遇到此韌體下載錯誤... | 然後執行下列動作... 


 a| 
指派的磁碟機故障
 a| 
故障的原因之一可能是磁碟機沒有適當的簽名。確定受影響的磁碟機是授權的磁碟機。如需詳細資訊、請聯絡技術支援部門。

更換磁碟機時、請確定更換磁碟機的容量等於或大於您要更換的故障磁碟機。

您可以在儲存陣列接收I/O時更換故障磁碟機



 a| 
檢查儲存陣列
 a| 
* 確定已將IP位址指派給每個控制器。
* 確保連接至控制器的所有纜線均未損壞。
* 確定所有纜線都已緊密連接。




 a| 
整合式熱備援磁碟機
 a| 
您必須先修正此錯誤狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
不完整的Volume群組
 a| 
如果一個或多個Volume群組或磁碟集區不完整、您必須先修正此錯誤狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
目前在任何Volume群組上執行的排他性作業（背景媒體/同位元檢查除外）
 a| 
如果正在進行一或多個專屬作業、則必須先完成作業、才能升級韌體。使用System Manager來監控作業進度。



 a| 
遺失磁碟區
 a| 
您必須先修正遺失的磁碟區狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
任一控制器處於非最佳狀態
 a| 
其中一個儲存陣列控制器需要注意。必須先修正此狀況、才能升級韌體。啟動System Manager並使用Recovery Guru解決問題。



 a| 
控制器物件圖表之間的儲存分割資訊不相符
 a| 
驗證控制器上的資料時發生錯誤。請聯絡技術支援部門以解決此問題。



 a| 
SPM驗證資料庫控制器檢查失敗
 a| 
控制器上發生儲存分割區對應資料庫錯誤。請聯絡技術支援部門以解決此問題。



 a| 
組態資料庫驗證（如果儲存陣列的控制器版本支援）
 a| 
控制器上發生組態資料庫錯誤。請聯絡技術支援部門以解決此問題。



 a| 
MEL相關檢查
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內報告了超過10個「DDE資訊」或「重大MEL」事件
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內報告超過2頁2C重大MEL事件
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內報告超過2個降級的磁碟機通道嚴重MEL事件
 a| 
請聯絡技術支援部門以解決此問題。



 a| 
過去7天內有4個以上的重要MEL項目
 a| 
請聯絡技術支援部門以解決此問題。

|===
====
.完成後
您的磁碟機韌體升級已完成。您可以恢復正常作業。
