---
permalink: sm-support/upgrade-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, software, firmware 
summary: 您可以升級儲存陣列的軟體、也可以選擇性地升級IOM韌體和非揮發性靜態隨機存取記憶體（NVSRAM）、以確保您擁有所有最新的功能和錯誤修復。 
---
= 在 SANtricity System Manager 中升級控制器軟體和韌體
:allow-uri-read: 


[role="lead"]
您可以升級儲存陣列的軟體、也可以選擇性地升級IOM韌體和非揮發性靜態隨機存取記憶體（NVSRAM）、以確保您擁有所有最新的功能和錯誤修復。

.開始之前
* 您知道是否要升級IOM韌體。
+
一般而言、您應該同時升級所有元件。不過、如果您不想將IOM韌體升級為SANtricity 更新版的一部分、或是技術支援部門指示您降級IOM韌體（您只能使用命令列介面降級韌體）、則可能會決定不升級IOM韌體。

* 您知道是否要升級控制器的NVSRAM.
+
一般而言、您應該同時升級所有元件。不過、如果您的檔案已修補或是自訂版本、而且您不想覆寫、您可能會決定不升級控制器的NVSRAM/檔案。

* 您知道現在或之後是否要啟動作業系統升級。
+
日後啟用的理由可能包括：

+
** *每天的時間*-啟動軟體和韌體可能需要很長的時間、因此您可能需要等待I/O負載變輕。控制器會在啟動期間容錯移轉、因此在升級完成之前、效能可能會比平常低。
** *套件類型*：在升級其他儲存陣列上的檔案之前、您可能需要在一個儲存陣列上測試新的軟體和韌體。


* 您知道要從不安全的磁碟機或內部安全的磁碟機切換、以使用外部金鑰管理伺服器（KMS）來保護磁碟機安全。
* 您知道是否要在儲存陣列中使用角色型存取控制。


.關於這項工作
您可以選擇僅升級OS軟體檔案、或只升級控制器的NVSRAM/檔案、也可以選擇升級這兩個檔案。

只有在技術支援人員的指示下、才執行此作業。

[CAUTION]
====
*資料遺失的風險或儲存陣列受損的風險*-升級期間請勿變更儲存陣列。維持儲存陣列的電力。

====
.步驟
. 如果您的儲存陣列只包含一個控制器、或您沒有安裝多重路徑驅動程式、請停止儲存陣列的I/O活動、以避免應用程式錯誤。如果您的儲存陣列有兩個控制器、而且安裝了多重路徑驅動程式、則不需要停止I/O活動。
. 選取功能表：Support[升級中心]。
. 從Support網站下載新檔案至您的管理用戶端。
+
.. 按一下「* NetApp支援*」以啟動「支援」網站。
.. 在Support（支援）網站上、按一下* Downloads（下載）*索引標籤、然後選取* Downloads（下載）*。
.. 選擇* E系列SANtricity 《支援OS控制器軟體*》。
.. 請遵循其餘指示。


+
[NOTE]
====
8.42版及更新版本需要數位簽署的韌體。如果您嘗試下載未簽署的韌體、將會顯示錯誤、且下載會中止。

====
. 如果您目前不想升級IOM韌體、請按一下*暫停IOM自動同步*。
+
如果您有單一控制器的儲存陣列、則不會升級IOM韌體。

. 在「支援作業系統軟體升級」下SANtricity 、按一下「*開始升級*」。
+
此時SANtricity 會出現「Upgrade VMware OS軟體」對話方塊。

. 選取一或多個檔案以開始升級程序：
+
.. 按一下*瀏覽*並SANtricity 瀏覽至從Support網站下載的OS軟體檔案、以選取「支援OS軟體」檔案。
.. 單擊*瀏覽*並瀏覽至從Support（支持）站點下載的NVSRAM/文件，以選擇Controller NVSRAM/文件。控制器的NVSRAM,檔案名稱類似於「N2800-830000-000.dlp」。


+
這些動作會發生：

+
** 根據預設、只會顯示與目前儲存陣列組態相容的檔案。
** 當您選取要升級的檔案時、會顯示檔案名稱和大小。


. *選用：*如果您選擇SANtricity 要升級的支援功能作業系統軟體檔案、您可以選擇*立即傳輸檔案、但不要升級（稍後啟動升級）*核取方塊、將檔案傳輸至控制器、而不啟動檔案。
. 按一下* Start*（開始*）、然後確認您要執行此作業。
+
您可以在升級前的狀況檢查期間取消作業、但在傳輸或啟動期間無法取消。

. *選用：*若要查看已升級項目的清單、請按一下*儲存記錄*。
+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「drive_升級_log-timestamp.txt"。



.完成後
* 確認所有元件都顯示在「硬體」頁面上。
* 核取「軟體與韌體庫存」對話方塊（前往功能表：「Support[升級中心]」、然後按一下「*軟體與韌體庫存*」連結）、以驗證新的軟體與韌體版本。
* 如果您升級控制器的NVSRAM,則在啟動程序期間會遺失任何已套用至現有的NVSRAM/R的自訂設定。啟動程序完成後、您需要再次將自訂設定套用至NVSRAM.

