---
permalink: sm-support/view-storage-array-profile.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, storage, array, profile 
summary: 儲存陣列設定檔提供儲存陣列所有元件和內容的說明。 
---
= 在 SANtricity System Manager 中查看儲存陣列的設定檔
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存陣列設定檔提供儲存陣列所有元件和內容的說明。

.關於這項工作
您可以在恢復期間使用儲存陣列設定檔作為輔助工具、也可以作為儲存陣列目前組態的總覽。您可能想要在管理用戶端上儲存儲存儲存陣列設定檔的複本、並保留儲存陣列設定檔的硬備份。如果組態變更、請建立新的儲存陣列設定檔複本。

.步驟
. 選取功能表：Support（支援）[Support Center（支援中心）> Support Resources（支援資源）]索引標籤。
. 向下捲動至*啟動詳細的儲存陣列資訊*、然後選取*儲存陣列設定檔*。
+
報告會出現在您的螢幕上。

+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 區段 | 說明 


 a| 
儲存陣列
 a| 
顯示您可以設定的所有選項、以及儲存陣列的系統靜態選項。這些選項包括控制器、磁碟機櫃、磁碟機、磁碟集區、磁碟區群組、 磁碟區和熱備援磁碟機；允許的磁碟機櫃、磁碟機、固態磁碟（SSD）和磁碟區數量上限；快照群組、快照映像、快照磁碟區和一致性群組的數量；功能相關資訊；韌體版本資訊；機箱序號資訊；AutoSupport Intel®固態磁碟機（英文）AutoSupport 排程資訊； 自動支援資料收集與排程支援資料收集的設定、儲存陣列全球識別碼（WWID）、以及媒體掃描與快取設定。



 a| 
儲存設備
 a| 
顯示儲存陣列中所有儲存裝置的清單。根據儲存陣列組態的不同、「儲存」區段可能會顯示這些子區段。

** *磁碟集區*-顯示儲存陣列中所有磁碟集區的清單。
** * Volume Groups *（磁碟區群組）-顯示儲存陣列中所有磁碟區群組的清單。磁碟區和可用容量會依照建立順序列出。
** * Volumes（磁碟區）*-顯示儲存陣列中所有磁碟區的清單。列出的資訊包括磁碟區名稱、磁碟區狀態、容量、RAID層級、磁碟區群組或磁碟集區、磁碟機類型、以及其他詳細資料。
** *遺失磁碟區*-顯示儲存陣列中目前遺失狀態的所有磁碟區清單。列出的資訊包括每個遺失磁碟區的全球識別碼（WWID）。




 a| 
複製服務
 a| 
顯示用於儲存陣列的所有複本服務清單。複製服務區段可能會顯示以下子區段、視儲存陣列組態而定：

** * Volume Copies（磁碟區複本）*-顯示儲存陣列中所有複本配對的清單。列出的資訊包括複本數量、複本配對名稱、狀態、開始時間戳記及其他詳細資料。
** * Snapshot Groups *（快照組*）-顯示儲存陣列中所有快照組的列表。
** * Snapshot映像*-顯示儲存陣列中所有快照的清單。
** * Snapshot Volumes（快照磁碟區）*-顯示儲存陣列中所有快照磁碟區的清單。
** *一致性群組*-顯示儲存陣列中所有一致性群組的清單。
** *成員磁碟區*-顯示儲存陣列中所有一致性群組成員磁碟區的清單。
** *鏡射群組*-顯示所有鏡射磁碟區的清單。
** *保留容量*-顯示儲存陣列中所有保留容量磁碟區的清單。




 a| 
主機指派
 a| 
顯示儲存陣列中的主機指派清單。列出的資訊包括磁碟區名稱、邏輯單元編號（LUN）、控制器ID、主機名稱或主機叢集名稱、以及磁碟區狀態。所列的其他資訊包括拓撲定義和主機類型定義。



 a| 
硬體
 a| 
顯示儲存陣列中所有硬體的清單。視儲存陣列組態而定、「硬體」區段可能會顯示這些子區段。

** *控制器*-顯示儲存陣列中所有控制器的清單、其中包括控制器位置、狀態和組態。此外、還包括磁碟機通道資訊、主機通道資訊和乙太網路連接埠資訊。
** * Drives *（磁碟機）-顯示儲存陣列中所有磁碟機的清單。磁碟機列在機櫃ID、藥櫃ID、插槽ID順序中。列出的資訊包括機櫃ID、藥櫃ID、插槽ID、狀態、原始容量、 每個磁碟機的媒體類型、介面類型、目前資料速率、產品ID和韌體版本。「磁碟機」區段也包含磁碟機通道資訊、熱備援保固範圍資訊、以及耗損壽命資訊（僅適用於SSD磁碟機）。耗損壽命資訊包括使用的持久度百分比、亦即迄今寫入SSD磁碟機的資料量、除以磁碟機的理論寫入總限制。
** *磁碟機通道*-顯示儲存陣列中所有磁碟機通道的資訊。列出的資訊包括通道狀態、連結狀態（若適用）、磁碟機數及累計錯誤數。
** * Shelves *-顯示儲存陣列中所有磁碟櫃的資訊。列出的資訊包括磁碟機類型、以及磁碟櫃每個元件的狀態資訊。機櫃元件可能包括電池套件、小型可插拔（SFP）收發器、電源風扇迴路、或輸入/輸出模組（IOM）迴路。如果儲存陣列使用安全金鑰、「硬體」區段也會顯示安全金鑰識別碼。




 a| 
功能
 a| 
顯示已安裝的功能套件清單、以及每個主機或主機叢集允許的快照群組、快照（舊版）和磁碟區數量上限。「功能」區段中的資訊也包括「磁碟機安全性」、也就是儲存陣列是否已啟用安全性或已停用安全性。

|===
====
. 若要搜尋儲存陣列設定檔、請在*尋找*文字方塊中輸入搜尋詞彙、然後按一下*尋找*。
+
所有相符的詞彙都會反白顯示。若要逐一捲動所有結果、請繼續按一下「*尋找*」。

. 若要儲存儲存陣列設定檔、請按一下「*儲存*」。
+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「shorage-array-profile（儲存陣列設定檔）」。


