---
permalink: sm-support/view-events-using-the-event-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, events, 
summary: 您可以檢視事件記錄、其中提供儲存陣列上發生事件的歷史記錄。 
---
= 使用 SANtricity System Manager 中的事件日誌檢視事件
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視事件記錄、其中提供儲存陣列上發生事件的歷史記錄。

.步驟
. 選取功能表：Support[事件記錄]。
+
此時會出現「事件記錄」頁面。

+
.頁面詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 項目 | 說明 


 a| 
檢視全部欄位
 a| 
在所有事件之間切換、以及僅切換關鍵和警告事件。



 a| 
篩選欄位
 a| 
篩選事件。僅用於顯示與特定元件、特定事件等相關的事件



 a| 
選取欄圖示。
 a| 
可讓您選取要檢視的其他欄。其他欄位則提供事件的其他相關資訊。



 a| 
核取方塊
 a| 
可讓您選取要儲存的事件。表格標頭中的核取方塊會選取所有事件。



 a| 
日期/時間欄
 a| 
事件的日期和時間戳記（根據控制器時鐘）。


NOTE: 事件日誌最初會根據順序編號來排序事件。此順序通常與日期和時間相對應。不過、儲存陣列中的兩個控制器時鐘可能會不同步。在這種情況下、事件記錄中可能會出現一些已知的不一致之處、這些不一致之處與事件及顯示的日期和時間有關。



 a| 
優先順序欄
 a| 
這些優先順序值存在：

** *嚴重*：儲存陣列有問題。不過、如果您立即採取行動、可能會避免資料遺失存取權。重要事件用於警示通知。所有重大事件都會傳送至任何網路管理用戶端（透過SNMP設陷）或您設定的電子郵件收件者。
** *警告*：發生錯誤、導致儲存陣列效能和從另一個錯誤中恢復的能力降低。
** *資訊性*：與儲存陣列相關的非關鍵資訊。




 a| 
零組件類型欄
 a| 
受事件影響的元件。元件可以是硬體、例如磁碟機或控制器、也可以是軟體、例如控制器韌體。



 a| 
零組件位置欄
 a| 
儲存陣列中元件的實體位置。



 a| 
說明欄
 a| 
事件說明。

*範例*-「磁碟寫入失敗-重試次數耗盡」



 a| 
序號欄
 a| 
可唯一識別儲存陣列特定記錄項目的64位元號碼。此數字會隨著每個新的事件記錄項目而遞增一次。若要顯示此資訊、請按一下*選取欄*圖示。



 a| 
事件類型欄
 a| 
識別每種記錄事件類型的4位數號碼。若要顯示此資訊、請按一下*選取欄*圖示。



 a| 
事件特定代碼欄
 a| 
技術支援人員會使用此資訊。若要顯示此資訊、請按一下*選取欄*圖示。



 a| 
事件類別欄
 a| 
** *故障*：儲存陣列中的元件故障、例如磁碟機故障或電池故障。
** 「狀態變更」*：儲存陣列的一項元素、其狀態已變更；例如、磁碟區已轉換為最佳狀態、或控制器已轉換為「離線」狀態。
** **內部*：不需要使用者動作的內部控制器作業；例如、控制器已完成一天的開始作業。
** **命令*：已發出給儲存陣列的命令；例如、已指派熱備援磁碟機。
** **錯誤*：在儲存陣列上偵測到錯誤狀況；例如、控制器無法同步及清除快取、或在儲存陣列上偵測到備援錯誤。
** *一般*：任何不適合任何其他類別的活動。若要顯示此資訊、請按一下「**選取欄*」圖示。




 a| 
記錄者欄
 a| 
記錄事件的控制器名稱。若要顯示此資訊、請按一下「**選取欄*」圖示。

|===
====
. 若要從儲存陣列擷取新事件、請按一下「**Refresh*」。
+
記錄事件可能需要幾分鐘的時間、並在「事件記錄」頁面中顯示。

. 若要將事件記錄儲存至檔案：
+
.. 選取您要儲存的每個事件旁的核取方塊。
.. 按一下「 * 儲存 * 」。
+
檔案會以「major -EVEN-log-timestamp.log」的名稱儲存在瀏覽器的「下載」資料夾中。



. 若要清除事件記錄中的事件：
+
事件記錄會儲存約8、000個事件、然後以新事件取代事件。如果您想要保留事件、可以儲存這些事件、並從事件記錄中清除這些事件。

+
.. 首先、儲存事件記錄。
.. 按一下「*全部清除*」、然後確認您要執行此作業。



