---
permalink: sm-support/view-unreadable-sectors-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, unreadable, sectors, log 
summary: 您可以儲存無法讀取的磁區記錄、並將檔案傳送給技術支援部門進行分析。 
---
= 檢視無法讀取的磁區記錄
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以儲存無法讀取的磁區記錄、並將檔案傳送給技術支援部門進行分析。

.關於這項工作
無法讀取的磁碟區記錄包含報告不可恢復媒體錯誤之磁碟機所造成無法讀取磁碟區的詳細記錄。在正常I/O和修改作業（例如重建）期間偵測到無法讀取的磁區。在儲存陣列上偵測到無法讀取的磁區時、會出現儲存陣列的Needs Attention警示。Recovery Guru可區分哪些無法讀取的區段狀況需要注意。無法讀取的磁區中所含的任何資料都無法恢復、因此應視為遺失。

不可讀取的磁區記錄最多可儲存1、000個無法讀取的磁區。當無法讀取的磁區記錄達到1、000個項目時、適用下列條件：

* 如果在重建期間偵測到新的無法讀取的磁區、重建就會失敗、而且不會記錄任何項目。
* 對於在I/O期間偵測到的新無法讀取磁區、I/O會失敗、而且不會記錄任何項目。
+
[NOTE]
====
這些動作包括RAID 5寫入和RAID 6寫入、這些寫入作業在溢位前就會成功完成。

====


[CAUTION]
====
*可能的資料遺失*-從無法讀取的磁區恢復是一項複雜的程序、可能涉及數種不同的方法。只有在技術支援人員的指示下、才執行此作業。

====
.步驟
. 選取功能表：Support（支援）[Support Center（支援中心）> Diagnostics（診斷）]索引標籤。
. 選取*檢視/清除無法讀取的磁區*。
. 若要儲存無法讀取的磁區記錄：
+
.. 在表格的第一欄中、您可以選取您要儲存「Unreadable Sectors」（無法讀取的磁碟區）記錄的個別磁碟區（按一下每個磁碟區旁的核取方塊）、或選取所有磁碟區（選取表格標題中的核取方塊）。
+
若要尋找特定的磁碟區、您可以在*篩選*方塊中排序任何欄或輸入字元。

.. 按一下「 * 儲存 * 」。


+
檔案會儲存在瀏覽器的「Downloads（下載）」資料夾中、名稱為「Unread-sectors.txt」。

. 如果技術支援部門指示您清除無法讀取的磁區記錄、請執行下列步驟：
+
.. 在表格的第一欄中、您可以選取要清除「Unreadable Sectores（無法讀取的磁區）」記錄的個別磁碟區（按一下每個磁碟區旁的核取方塊）、或選取所有磁碟區（選取表格標題中的核取方塊）。
.. 按一下*清除*、然後確認您要執行此作業。



