---
permalink: sm-support/what-do-i-need-to-know-before-upgrading-the-santricity-os-software.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrading, santricity, os, software 
summary: 在升級控制器的軟體和韌體之前、請注意以下事項。 
---
= 升級SANtricity 完《不知如何」的《不知如何？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在升級控制器的軟體和韌體之前、請注意以下事項。

* 您已閱讀文件和「readme.txt"檔案、並決定要進行升級。
* 您知道是否要升級IOM韌體。
+
一般而言、您應該同時升級所有元件。不過、如果您不想將IOM韌體升級為SANtricity 更新版的一部分、或是技術支援部門指示您降級IOM韌體（您只能使用命令列介面來降級韌體）、您可能會決定不升級IOM韌體。

* 您知道是否要升級控制器的NVSRAM.
+
一般而言、您應該同時升級所有元件。不過、如果您的檔案已修補或是自訂版本、而且您不想覆寫、您可能會決定不升級控制器的NVSRAM/檔案。

* 您知道現在或之後要啟動。
+
日後啟用的理由可能包括：

+
** *每天的時間*-啟動軟體和韌體可能需要很長的時間、因此您可能需要等待I/O負載變輕。控制器會在啟動期間容錯移轉、因此在升級完成之前、效能可能會比平常低。
** *套件類型*：在升級其他儲存陣列上的檔案之前、您可能需要在一個儲存陣列上測試新的軟體和韌體。




這些元件是SANtricity 更新版作業系統控制器軟體的一部分：

* *管理軟體*- System Manager是管理儲存陣列的軟體。
* *控制器韌體*-控制器韌體可管理主機與磁碟區之間的I/O。
* *控制器NVSRAM*-控制器NVSRAM-是控制器檔案、可指定控制器的預設設定。
* * IOM韌體*- I/O模組（IOM）韌體可管理控制器與磁碟機櫃之間的連線。它也會監控元件的狀態。
* *監控軟體*-監控軟體是軟體執行所在控制器上的虛擬機器。


在升級過程中、主機的多重路徑/容錯移轉驅動程式和（或）HBA驅動程式可能也需要升級、以便主機能夠正確與控制器互動。

[NOTE]
====
若要判斷是否為這種情況、請參閱 https://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^]。

====
如果您的儲存陣列只包含一個控制器、或您沒有安裝多重路徑驅動程式、請停止儲存陣列的I/O活動、以避免應用程式錯誤。如果您的儲存陣列有兩個控制器、而且安裝了多重路徑驅動程式、則不需要停止I/O活動。


CAUTION: 升級時請勿變更儲存陣列。
