---
permalink: um-certificates/certificate-terminology-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, certificate, terminology 
summary: 下列條款適用於憑證管理。 
---
= 憑證術語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下列條款適用於憑證管理。

[cols="25h,~"]
|===
| 期限 | 說明 


 a| 
CA
 a| 
憑證授權單位（CA）是信任的實體、可發行稱為數位憑證的電子文件、以確保網際網路安全。這些憑證可識別網站擁有者、以便在用戶端與伺服器之間進行安全連線。



 a| 
CSR
 a| 
憑證簽署要求（CSR）是一則訊息、會從申請者傳送至憑證授權單位（CA）。CSR會驗證CA核發憑證所需的資訊。



 a| 
憑證
 a| 
憑證可識別站台的擁有者、以確保安全性、防止攻擊者模擬站台。憑證包含網站擁有者的相關資訊、以及認證（簽署）此資訊的信任實體身分。



 a| 
憑證鏈結
 a| 
將安全層新增至憑證的檔案階層。一般而言、此鏈包括階層頂端的一個根憑證、一個或多個中繼憑證、以及識別實體的伺服器憑證。



 a| 
中介憑證
 a| 
一個或多個中繼憑證會從憑證鏈結的根目錄下分支。CA會發出一或多個中繼憑證、做為受保護根憑證與伺服器憑證之間的中間人。



 a| 
Keystore
 a| 
Keystore是主機管理系統上的儲存庫、內含私密金鑰及其對應的公開金鑰和憑證。這些金鑰和憑證可識別您自己的實體、例如控制器。



 a| 
根憑證
 a| 
根憑證位於憑證鏈結階層的頂端、其中包含用於簽署其他憑證的私密金鑰。根可識別特定的CA組織。如果您的所有網路裝置都使用相同的CA、則只需要一個根憑證。



 a| 
簽署的憑證
 a| 
由憑證授權單位（CA）驗證的憑證。此資料檔案包含私密金鑰、可確保資料以加密形式透過HTTPS連線在伺服器與用戶端之間傳送。此外、已簽署的憑證還包含實體擁有者（通常是伺服器或網站）的詳細資料、以及由字母和數字組成的數位簽章。簽署的憑證使用信任鏈、因此最常用於正式作業環境。也稱為「CA簽署的憑證」或「管理憑證」。



 a| 
自我簽署的憑證
 a| 
自行簽署的憑證由實體擁有者驗證。此資料檔案包含私密金鑰、可確保資料以加密形式透過HTTPS連線在伺服器與用戶端之間傳送。其中也包含由字母和數字組成的數位簽名。自我簽署的憑證不會使用與CA簽署憑證相同的信任鏈結、因此最常用於測試環境。也稱為「預先安裝」憑證。



 a| 
伺服器憑證
 a| 
伺服器憑證位於憑證鏈結的底部。它會識別您的特定實體、例如網站或其他裝置。儲存系統中的每個控制器都需要個別的伺服器憑證。



 a| 
信任存放區
 a| 
信任存放區是一個儲存庫、其中包含來自信任的第三方（例如CA）的憑證。

|===