---
permalink: um-certificates/edit-directory-server-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, edit, directory, server, settings, role, mappings 
summary: 如果您先前在Access Management中設定了目錄伺服器、則可以隨時變更其設定。設定包括伺服器連線資訊和群組對角色對應。 
---
= 在 SANtricity Unified Manager 中編輯目錄伺服器設定和角色映射
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您先前在Access Management中設定了目錄伺服器、則可以隨時變更其設定。設定包括伺服器連線資訊和群組對角色對應。

.開始之前
* 您必須以包含安全管理員權限的使用者設定檔登入。否則、就不會顯示存取管理功能。
* 必須定義目錄伺服器。


.步驟
. 選擇*存取管理*。
. 選取*目錄服務*索引標籤。
. 如果定義了多個伺服器、請從表格中選取您要編輯的伺服器。
. 選取*檢視/編輯設定*。
+
此時將打開Directory Server Settings（目錄服務器設置）對話框。

. 在*伺服器設定*索引標籤中、變更所需的設定。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*組態設定*



 a| 
網域
 a| 
LDAP伺服器的網域名稱。若為多個網域、請在以逗號分隔的清單中輸入網域。網域名稱用於登入（_username_@_domain_）、以指定要驗證的目錄伺服器。



 a| 
伺服器URL
 a| 
以下列形式存取LDAP伺服器的URL `ldap[s]://host:port`。



 a| 
連結帳戶（選用）
 a| 
用於針對LDAP伺服器進行搜尋查詢及在群組內搜尋的唯讀使用者帳戶。



 a| 
連結密碼（選用）
 a| 
綁定帳戶的密碼。（輸入連結帳戶時、會顯示此欄位。）



 a| 
儲存前先測試伺服器連線
 a| 
檢查系統是否能與LDAP伺服器組態通訊。按一下「*儲存*」之後、就會進行測試。如果選取此核取方塊且測試失敗、則不會變更組態。您必須解決錯誤或清除核取方塊、才能跳過測試並重新編輯組態。



 a| 
*權限設定*



 a| 
搜尋基礎DN
 a| 
要搜尋使用者的LDAP內容、通常採用的形式 `CN=Users, DC=cpoc, DC=local`。



 a| 
使用者名稱屬性
 a| 
繫結至使用者ID以進行驗證的屬性。例如：「AMAccountName」。



 a| 
群組屬性
 a| 
使用者上的群組屬性清單、用於群組對角色對應。例如：「memberof、managedObjects'。

|===
====
. 在*角色對應*索引標籤中、變更所需的對應。
+
.欄位詳細資料
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 說明 


 a| 
*對應*



 a| 
群組DN
 a| 
要對應之LDAP使用者群組的網域名稱。支援規則運算式。如果這些特殊的規則運算式字元不是規則運算式模式的一部分、則必須以反斜槓（\）轉義：

\.[]{}()<>*+-=!?^$|



 a| 
角色
 a| 
要對應至群組DN的角色。您必須個別選取要納入此群組的每個角色。監控角色必須與其他角色搭配使用、才能登入SANtricity 到NetApp Unified Manager。這些角色包括：

** *儲存設備管理*-完整讀寫陣列上的儲存物件存取權、但無法存取安全性組態。
** *安全管理*：存取存取管理與憑證管理中的安全性組態。
** *支援admin*：存取儲存陣列、故障資料及MEL事件上的所有硬體資源。無法存取儲存物件或安全性組態。
** *監控*-對所有儲存物件的唯讀存取、但無法存取安全性組態。


|===
====
+

NOTE: 所有使用者（包括系統管理員）都必須具備「監控」角色。

. 如有需要、請按一下*新增其他對應*、以輸入更多群組對角色對應。
. 按一下「 * 儲存 * 」。


.結果
完成此工作之後、任何作用中的使用者工作階段都會終止。只會保留目前的使用者工作階段。
