---
permalink: um-certificates/how-access-management-works-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, authentication, users, roles, access management 
summary: 使用存取管理功能、在SANtricity 《統一化管理程式》中建立使用者驗證。 
---
= 存取管理的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用存取管理功能、在SANtricity 《統一化管理程式》中建立使用者驗證。



== 組態工作流程

存取管理組態的運作方式如下：

. 系統管理員使用包含安全管理員權限的使用者設定檔登入Unified Manager。
+
[NOTE]
====
首次登入時、使用者名稱「admin」會自動顯示、無法變更。「admin」使用者可完整存取系統中的所有功能。首次登入時必須設定密碼。

====
. 系統管理員會在使用者介面中導覽至「存取管理」、其中包含預先設定的本機使用者角色。這些角色是RBAC（角色型存取控制）功能的實作。
. 系統管理員可設定下列一或多種驗證方法：
+
** *本機使用者角色*-驗證是透過RBAC功能來管理。本機使用者角色包括具有特定存取權限的預先定義使用者和角色。系統管理員可以使用這些本機使用者角色做為單一驗證方法、或搭配目錄服務使用。除了為使用者設定密碼之外、不需要進行任何組態。
** *目錄服務*-驗證是透過LDAP（輕量型目錄存取傳輸協定）伺服器和目錄服務（例如Microsoft的Active Directory）來管理。系統管理員會連線至LDAP伺服器、然後將LDAP使用者對應至本機使用者角色。
** * SAML *-驗證是透過身分識別供應商（IDP）、使用安全聲明標記語言（SAML）2.0來管理。系統管理員會在IDP系統與儲存陣列之間建立通訊、然後將IDP使用者對應至儲存陣列內嵌的本機使用者角色。


. 系統管理員可為使用者提供Unified Manager的登入認證。
. 使用者輸入認證資料以登入系統。登入期間、系統會執行下列背景工作：
+
** 根據使用者帳戶驗證使用者名稱和密碼。
** 根據指派的角色來決定使用者的權限。
** 讓使用者能夠存取使用者介面中的功能。
** 在上方橫幅中顯示使用者名稱。






== Unified Manager提供的功能

存取功能取決於使用者指派的角色、包括下列項目：

* *儲存設備管理*-完整讀寫陣列上的儲存物件存取權、但無法存取安全性組態。
* *安全管理*：存取存取管理與憑證管理中的安全性組態。
* *支援admin*：存取儲存陣列、故障資料及MEL事件上的所有硬體資源。無法存取儲存物件或安全性組態。
* *監控*-對所有儲存物件的唯讀存取、但無法存取安全性組態。


無法使用的功能會呈現灰色、或不會顯示在使用者介面中。
