---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: 您必須設定SANtricity 管理員密碼才能防止他人未經授權存取。 
---
= 設定管理密碼保護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須設定SANtricity 管理員密碼才能防止他人未經授權存取。



== 管理密碼和使用者設定檔

首次啟動Unified Manager時、系統會提示您設定管理員密碼。擁有管理員密碼的任何使用者都可以變更儲存陣列的組態。

除了管理員密碼之外、Unified Manager介面還包含預先設定的使用者設定檔、其中有一個或多個角色對應到這些設定檔。如需詳細資訊、請參閱 link:../um-certificates/how-access-management-works-unified.html["存取管理的運作方式"]。

無法變更使用者和對應。只能修改密碼。若要變更密碼、請參閱：

* link:change-admin-password-unified.html["變更管理密碼"]
* link:../um-certificates/change-passwords-unified.html["變更本機使用者設定檔的密碼"]




== 工作階段逾時

在單一管理工作階段期間、軟體只會提示您輸入一次密碼。工作階段預設在閒置30分鐘後逾時、此時您必須再次輸入密碼。如果其他使用者從其他管理用戶端存取軟體、並在工作階段進行期間變更密碼、則下次嘗試組態作業或檢視作業時、系統會提示您輸入密碼。

基於安全考量、您只能在軟體進入「鎖定」狀態之前、嘗試輸入密碼五次。在此狀態下、軟體會拒絕後續的密碼嘗試。您必須等待10分鐘、才能重設為「正常」狀態、才能再次嘗試輸入密碼。

您可以調整工作階段逾時、也可以一併停用工作階段逾時。如需詳細資訊、請參閱 link:manage-session-timeouts-unified.html["管理工作階段逾時"]。
